- CHANGELOG.md
- packages/eas-cli/src/commands/update/configure.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/projectUtils.ts
- packages/eas-cli/src/update/__tests__/utils-test.ts
- packages/eas-cli/src/update/configure.ts
- packages/eas-cli/src/utils/statuspageService.ts
- Add tests for `src/updates/configure.ts` -> comming in follow up PR
- Continuation of PR https://github.com/expo/eas-cli/pull/1473 and [ENG-5926](https://linear.app/expo/issue/ENG-5926)
- Fixes ENG-6748, ENG-5806
- Part of ENG-6002
This moves most of the (auto) configuration from both `eas update:configure` and `eas update` into `src/updates/configure.ts` and reuses it on both commands.
> This also includes the change from PR #1467, just for completeness and being able to test the final result with `npx @bycedric/some-cli-test update` - a published version of these stacked PRs.
<details><summary>Project without any EAS service/config setup</summary>
</details>
<details><summary>Project with EAS Update fully configured</summary>
</details>
<details><summary>Project with EAS Update fully …
> [eas-cli] Improve configuration setup for EAS update

- CHANGELOG.md
- packages/eas-cli/graphql-codegen.yml
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/branch/queries.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/graphql/generated.ts
We'd like for users to be able to associate an Update with a Git commit.
I added `gitCommitHash` to the input we send to our GraphQL API for creating Update records. I also had to fix a few GraphQL codegen issues because we did a refactor which changed where some GraphQL mutations were defined.
I use the same method that we use to get the git commit hash for builds: `await vcsClient.getCommitHashAsync()`
Using a local version of the CLI and website, I published a new update on Staging and used the website to render the new commit data (and GitHub link 👀 )
Updated log:
> [eas-cli][update] Attach Git Commit to EAS Update

- packages/eas-json/schema/eas.schema.json
In the vscode extension, the intellisense for the `distribution` property of a build profile is incorrect. The `store` value gets the markdown description for the `internal` value, and vice versa:
I reordered the enum values to corresponding with the ordering in the markdown descriptions. (In the descriptions, `internal` appears first, but it was second in the array of values).
This is a trivial change, so I have not tested it.
> [eas-json] fix ordering of distribution enum values

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
Hotfix because `eas build` should work out of the box with a new `@react-native-community/cli` initialized project
See code
```
npx react-native init my-project
cd my-project
eas init # or eas build
```
Without this patch, you will see an error like this:
```
eas init
✔ Which account should own this project? › brents
✔ Existing project found: @brents/trybuildsizeios (ID: 37e39e45-a33e-4541-bee5-625109b2b10c). Link this project? … yes
ConfigError: Cannot determine which native SDK version your project uses because
the module `expo` is not installed. Please install it with `yarn add expo` and try
again.
Code: MODULE_NOT_FOUND
```
Works with this patch
> [eas-cli] Remove dependency on expo package from eas init

- CHANGELOG.md
- packages/eas-cli/src/commands/credentials.ts
- packages/eas-cli/src/credentials/manager/HelperActions.ts
- packages/eas-cli/src/credentials/manager/ManageAndroid.ts
- packages/eas-cli/src/credentials/manager/ManageIos.ts
- packages/eas-cli/src/credentials/manager/SelectPlatform.ts
When you have a logic that is changing slug or bundle identifier based on some envs that are specified in eas.json, the credentials manager does not take that into account when resolving values in app.json.
https://exponent-internal.slack.com/archives/C017N0N99RA/p1668430103460189?thread_ts=1668006887.615549&cid=C017N0N99RA
Resolve `exp` dynamically after profile is selected.
TODO Not tested yet.
> [eas-cli] Pass env variables when resolving config in credentials manager.

- CHANGELOG.md
- packages/eas-cli/src/prompts.ts
If cli tries to display prompt on CI it's hard to identify in some cases what was the problem, because it's not clear which prompt failed.
https://github.com/expo/eas-cli/issues/1521
Print prompt message.
> [eas-cli] Show what prompt failed when running in non interactive shell.

- CHANGELOG.md
- packages/eas-json/package.json
- packages/eas-json/src/accessor.ts
- packages/eas-json/src/log.ts
https://linear.app/expo/issue/ENG-6941/add-error-message-for-when-image-validation-fails-in-the-cli
Add a custom error message handler when the `image` field is invalid.
Test locally.
> [ENG-6941][eas-json] add better error message for when invalid image is set in the `eas.json`

- CHANGELOG.md
- packages/eas-cli/src/devices/utils/formatDevice.ts
- Remove expo ID from `formatDevice` method. The ID is not needed for anything.
- Move UDID to the top.
> [ENG-6491] remove internal expo id from device:list

- CHANGELOG.md
- packages/eas-cli/src/project/applicationIdentifier.ts
> The command will ask for the Android package name, but will bail on the missing ios.bundleIdentifier.
This happens only on managed, for bare projects we would just fail, but it's hard to create native project where those values are not defined, so it should not be a big issue.
remove package name and bundle identifier from app.json and run `eas bulid:version:sync`
> [ENG-6866][eas-cli] Consistent prompt for application identifier for both platorms

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/graphql/generated.ts
Builds track if the git working tree was dirty, but updates do not:
https://github.com/expo/eas-cli/pull/1499#pullrequestreview-1165131094
I added `isGitWorkingTreeDirty` to the `PublishUpdateGroupInput` payload and also showed the asterisk at the end of the commit in the publish command summary if the working tree was dirty.
I tested with a local build of the CLI and the website to render the dirty state asterisks:
> [eas-cli] add isGitWorkingTreeDirty to EAS Update publish command

- CHANGELOG.md
- packages/eas-cli/src/commands/build/run.ts
https://linear.app/expo/issue/ENG-7006/indicate-in-eas-buildrun-when-build-artifacts-have-expired
Disable choosing the build which finished over 30 days ago.
Test manually
> [ENG-7006][eas-cli] Indicate in `eas build:run` when build artifacts has expired

- CHANGELOG.md
- packages/eas-cli/src/run/android/emulator.ts
https://linear.app/expo/issue/ENG-7007/deep-link-received-when-launching-dev-client-with-eas-buildrun
I discussed this with @lukmccall and we decided that `MAIN` intent is a better option than `RUN`.
It solves the issue with the dev client and also works fine for other builds.
Change Android start intent from `android.intent.action.RUN` to `android.intent.action.MAIN` in the `eas build:run` command.
Run command for a dev client build and for other types of builds as well.
> [ENG-7007][eas-cli] change Android start intent to `MAIN` instead of `RUN` in `eas build:run`

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/run.ts
- packages/eas-cli/src/run/ios/simulator.ts
- packages/eas-cli/src/run/utils.ts
- packages/eas-cli/src/utils/download.ts
The last addition to the `eas build:run` feature
If `eas build` is run in interactive mode and any of the builds is successfully finished simulator build prompt the user to install it on the emulator/simulator.
https://user-images.githubusercontent.com/55145344/205007745-62ca3f09-a671-436c-aadb-6393837e710a.mov
https://user-images.githubusercontent.com/55145344/205007773-c5d40293-cac4-47f6-8790-c217d7979fd5.mov
https://user-images.githubusercontent.com/55145344/205007792-f7b926d9-ed8f-4791-a583-ba5cc88eed25.mov
Test manually.
> [ENG-6238][eas-cli] prompt developer to download the simulator app after build is finished when in interactive mode

- CHANGELOG.md
- packages/eas-json/src/accessor.ts
https://github.com/expo/eas-cli/issues/1562
Before this fix, the handler would show the error message if anything is invalid about the `image` field in the `eas-json`. We want it only to show the custom error when `image` is placed in the correct spot but has an invalid value.
Run the handler only if `image` is placed under the proper key.
Test manually.
> [eas-json] Make not recognized image error handler run only if image is present under valid key with invalid value

- CHANGELOG.md
- packages/eas-cli/src/commands/build/run.ts
- packages/eas-cli/src/run/android/emulator.ts
https://github.com/expo/eas-cli/issues/1566
I downgraded to node `14.17.5` and was able to replicate the issue. Once I updated all wrong imports to use the `assert` module (as we did in other places), instead of the `node:assert` module everything started to work. I also checked for higher node version `18.12.1` and everything seems fine as well.
Test manually.
> [eas-cli] Fix eas cli `node:assert` import error by using imports from `assert` instead of `node:assert`

- CHANGELOG.md
- packages/eas-cli/src/commands/update/configure.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/update/configure.ts
To make EAS Update easier to set up, we are adding `channel` properties to build profiles when running `eas update:configure`.
The logic is:
- If eas.json is present:
- if there is not pre-existing channel or release channel, set a channel named after the profile name
- else do nothing (leave as is)
- else warn that the developer may need to run `eas build:configure`, then re-run `eas update:configure` to set everything up.
In addition, I updated the "Next steps" text, so there's actionable items after running `eas update:configure`.
Run `easd update:configure` in a project. Check:
- that projects with channels in build profiles are not overwritten
- that projects with release channels in build profiles are not overwritten
- that projects get a channel when none is specified after running …
> [eas-cli] Adds channels to build profiles on eas update:configure

- CHANGELOG.md
- packages/eas-cli/graphql-codegen.yml
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/branch/queries.ts
- packages/eas-cli/src/build/ios/credentials.ts
- packages/eas-cli/src/build/ios/graphql.ts
- packages/eas-cli/src/build/ios/prepareJob.ts
- packages/eas-cli/src/build/queries.ts
- packages/eas-cli/src/channel/queries.ts
- packages/eas-cli/src/commands/branch/delete.ts
- packages/eas-cli/src/commands/branch/view.ts
- packages/eas-cli/src/commands/build/index.ts
- packages/eas-cli/src/commands/build/resign.ts
- packages/eas-cli/src/commands/channel/edit.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/list.ts
- packages/eas-cli/src/devices/queries.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/mutations/BuildMutation.ts
- packages/eas-cli/src/update/queries.ts
- packages/eas-cli/src/utils/__tests__/queries-test.ts
- packages/eas-cli/src/utils/queries.ts
This is not finished yet, I'm waiting for some server-side changes before i can finish the implementation.
Add `build:resign` command.
In the first iteration command only supports iOS archives that were created by EAS Build for internal distribution. After the user selects a build, we are running the same code as normally when resolving credentials for the build. The only difference is that we are forcing apple authentication.
- if buildId is specified platform option is not needed.
- If buildId is not specified we are showing a paginated select prompt of finished internal distribution builds for that platform.
- Add helper to query builds with paginated select. I modified what `createDisplayTextForSelectionPromptListItem` is returning, so we can specify both title and description for …
> [ENG-7058][eas-cli] Add `build:resign` command

- CHANGELOG.md
- packages/eas-cli/src/channel/errors.ts
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/graphql/queries/ChannelQuery.ts
- packages/eas-cli/src/update/__tests__/getBranchNameFromChannelNameAsync-test.ts
- packages/eas-cli/src/update/getBranchNameFromChannelNameAsync.ts
To make EAS Update easier for people to use, we are adding a `--channel` flag to `eas update`. This flag allows developers to run a command like `eas update --channel channel-name`.
The command looks for the specified channel, then:
- if it exists, it finds the branch mapped to the channel and publishes to that branch
- if there are multiple branches, it errors
- if there are no branches, it errors (should not be possible, but I still handled it)
- If the channel does not exist, it creates it, then:
- if a branch exists of the same name, then map it to the newly made channel
- if a branch noes not exist, create one, then map it to the channel
Run `easd update --channel test-channel-name` to test out the feature.
Also, run the unit tests.
> [eas-cli] Add --channel flag to eas update command

- CHANGELOG.md
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/__tests__/republish.test.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/publish.ts
A partner reported an issue when using the following command combination:
```bash
$ eas update --branch "..." --message "..." --non-interactive
> Error: --auto or both --channel or --branch and --message are required
> when updating in non-interactive mode
```
It seems that PR #1570 introduced an incorrect validation combination, where it requires users to provide all flags (`--branch`, `--channel`, _and_ `--message`) when not using `--auto`.
This changes:
- The validation to allow combinations like:
- `--branch` + `--message`
- `--channel` + `--message`
- `--branch` + `--channel` + `--message` (this is caught after flag validation as incorrect combination)
- Change the error message in attempt to improve communicating the allowed combinations
> ```bash
> Error: --branch and --message, or …
```
> [eas-cli] Fix update --channel and --branch flag validation

- packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts
> This is an internal change and does not face the user.
I'm running into this timeout quite a lot, see:
- https://github.com/expo/eas-cli/actions/runs/3734346601/jobs/6336291927#step:6:154
- https://github.com/expo/eas-cli/actions/runs/3734012233/jobs/6336146018#step:6:154
- https://github.com/expo/eas-cli/actions/runs/3732872371/jobs/6332899405#step:6:154
Increased the allowed timeout from 15s to 30s.
- Rerun the CI a couple of times, and see if they fail on errors like: https://github.com/expo/eas-cli/actions/runs/3734012233/jobs/6336146018#step:6:151
> [eas-cli] Increase the timeout for loading the command config

- CHANGELOG.md
- packages/eas-cli/src/commands/update/__tests__/republish.test.ts
- packages/eas-cli/src/commands/update/republish.ts
- packages/eas-cli/src/update/__tests__/getBranchNameFromChannelNameAsync-test.ts
- packages/eas-cli/src/update/getBranchNameFromChannelNameAsync.ts
Keep the usage of `update` and `update:republish` similar, by adding `--channel` to republish.
This only works for channels that are pointing to a single branch. When that branch is fetched, it reuses the code from the `--branch` flag.
- See tests
- `eas update:republish --channel <channelName>`
→ should prompt you to select an update from the branch that is connected to the channel
→ should fail with `--non-interactive`, `--group`, or `--branch`
- `eas update:republish --branch <branchName>`
→ should prompt you to select an update from the branch
→ should fail with `--non-interactive`, `--group`, or `--channel`
- `eas update:republish --group <updateGroupId>`
→ should work with `--non-interactive`
→ should fail with `--branch` or `--channel`
> [eas-cli] Add --channel to update republish

- packages/eas-cli/src/build/build.ts
Why
---
Builds under the Free tier use spare capacity amongst the builders and have shorter timeouts. To communicate the priority of these builds more clearly and that they are not given the same level of service that customer builds receive, write out "Free-tier queue" instead of just "queue". Note: I capitalized "Free" since that is how "Free tier" is written in other contexts.
How
---
Searched the entire code base for "normal" and "standard" (case-insensitive). Found the one place where the search results affected human-facing text about the queues.
Test Plan
---
Just made sure the code built
> [ui] Rename "queue" to "Free tier queue"

- CHANGELOG.md
- packages/eas-cli/src/update/configure.ts
The `appVersion` runtime version policy is easier to understand and read than `sdkVersion`, and now that android correctly parses values like `1.10`, we can make this the default policy.
In addition, the `appVersion` policy will work better with upcoming EAS website dashboards.
Run `eas update:configure` and make sure the runtime version policy is `appVersion`.
> [eas-cli] use appVersion instead of sdkVersion

- CHANGELOG.md
- packages/eas-cli/src/build/queries.ts
https://linear.app/expo/issue/ENG-7070/unable-to-see-details-of-disabled-builds-when-selecting-the-build-to
Don't use the dim effect. Use bold effect for all undimmed fragments.
Test locally
> [ENG-7070][eas-cli] Fix issues with invisible build info in some terminals in `build:run` and `build:resign` commands

- CHANGELOG.md
- packages/eas-cli/src/commands/update/configure.ts
- packages/eas-cli/src/update/configure.ts
This PR is a bug fix. I landed a PR where when running `eas update:configure`, we set the `channel` property in build profiles. However, I placed that logic in a place that is also called when running `eas update ...`. (We want to set up expo-updates and configure app.json if needed when running `eas update`)
This is not the desired behavior for this configuration however. We _only_ want to set up channels in build profiles when a developer is running `eas update:configure`. By removing this from the `eas update` command, it allows developers to set a channel in their native code, then use EAS Build, and not have their native channel overwritten.
- Takes the `ensureEASUpdateIsConfiguredInEasJsonAsync()` function out of the shared configuration and call it in the `update:configure` …
> [eas-cli] Makes eas.json configuration to only run on update:configure

- CHANGELOG.md
- packages/eas-cli/src/submit/ArchiveSource.ts
While working on https://github.com/expo/eas-cli/pull/1602 I forgot to apply the same changes for submit command.
https://linear.app/expo/issue/ENG-7070/unable-to-see-details-of-disabled-builds-when-selecting-the-build-to
Don't use the dim effect. Use bold effect for all undimmed fragments.
Test locally
> [ENG-7070][eas-cli] fix issues with invisible build info in some terminals while using submit command

- CHANGELOG.md
- packages/eas-cli/src/branch/queries.ts
- packages/eas-cli/src/build/queries.ts
- packages/eas-cli/src/channel/queries.ts
- packages/eas-cli/src/commands/build/run.ts
- packages/eas-cli/src/devices/queries.ts
- packages/eas-cli/src/prompts.ts
- packages/eas-cli/src/update/queries.ts
- packages/eas-cli/src/utils/__tests__/queries-test.ts
- packages/eas-cli/src/utils/queries.ts
https://linear.app/expo/issue/ENG-7069/add-pagination-to-eas-buildrun-command
Use the paginated list and select function created by @wkozyra95 for the `build:resign` command https://github.com/expo/eas-cli/pull/1575
Test `build:run` locally
> [ENG-7069][eas-cli] Use pagianted select prompt for eas build:run command

- CHANGELOG.md
- packages/eas-cli/src/commands/webhook/list.ts
This updates adds the option of outputting the result of the webhook list command in JSON to allow for easier parsing.
This was discussed in the forum thread here https://forums.expo.dev/t/how-to-programmatically-delete-a-webhook/68354 and this PR was used as a guide: https://github.com/expo/eas-cli/pull/567
Tested locally using an existing Expo project to confirm that the output can now be formatted in JSON.
> Add json output option to listing webhooks

- CHANGELOG.md
- packages/eas-cli/src/build/queries.ts
- packages/eas-cli/src/commands/build/run.ts
When adding a paginated select prompt to the `eas build:run` I introduced a new bug.
When you have no emulator/simulator builds in your project you will get this strange assertion error message.
EDIT: I noticed that I wasn't sanitizing builds selected by id or as latest. This is also fixed now.
Now I sanitize every selected build to make sure it is valid in the context of the `eas build:run` command.
Throw a custom error if there are no simulator/emulator builds for a given platform.
Manual tests.
> [eas-cli] validate chosen build in `eas build:run` command

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/__tests__/republish.test.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/view.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/mutations/PublishMutation.ts
- packages/eas-cli/src/graphql/types/Update.ts
- packages/eas-cli/src/update/utils.ts
Fixes ENG-7180
This information isn't necessarily useful when using `eas update ...` or `eas update:view ...`. However, it's useful if you use it programmatically with `--json`.
`eas update:view <group>` | `eas update:view <group> --json`
--- | ---
With this information, we can generate things like QR codes, branch links to expo.dev, and more. It also allows us to add support for EAS Update in [expo-github-action ](https://github.com/expo/expo-github-action) without implementing anything other than calling `expo config --json` and `eas update ... --json`.
- Added `getUpdateGroupJson` next to helper functions we use to generate the non-json output
- Replaced custom partial mutation response with `UpdateFragment` when creating an update
- Implemented `getUpdateGroupJson` in `eas update …
> [eas-cli] Add missing key information about updates in json outputs

- packages/eas-cli/src/commands/build/index.ts
https://linear.app/expo/issue/ENG-7198/deprecate-resource-class-flag
Deprecate the `--resource-class` flag.
> [ENG-7198][build] deprecate --resource-class flag

- CHANGELOG.md
- packages/eas-cli/src/vcs/local.ts
Remove workaround for some git ignore files. Issue was fixed upstream in https://github.com/kaelzhang/node-ignore/issues/81
Remove workaround, package was updated in https://github.com/expo/eas-cli/pull/1617
run build with a .gitignore including `test\` entry.
> [eas-cli] Remove workaround for gitignore parsing (fixed upstream)

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/local.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/index.ts
- packages/eas-cli/src/commands/build/inspect.ts
- packages/eas-cli/src/commands/build/internal.ts
- packages/eas-cli/src/commands/config.ts
Part of the effort to run EAS Build directly from GitHub. 
Adds new local build mode that runs the same, code as a local build, but:
- Instead of spawning local-build-plugin it prints job and metadata to stdout
- It always runs in non-interactive mode
- It can only be triggered from a hidden command
Add `--json`/`--non-interactive`/`--eas-json-only` flags to the `expo config` command. We need that command to read eas.json at the beginning of the process before pre install hook is called. It needs to be part of the `eas-cli` to make it possible to users to force their own version of the `eas-cli`. `--eas-json-only` is needed because we can't evaluate app config before `yarn install` and we need to have that value before pre-install hook is called.
- Add `eas build:internal` command and …
> [eas-cli] Base implementation for running builds directly from GitHub

- .github/workflows/release.yml
- RELEASING.md
For builds from GitHub we will need to run cli on the workers.
- Automatically promote the new release to staging, and print instructions on how to promote it to production.
- Replace deprecated set-output syntax.
Run code-promoting packages as part of the test suite.
> [eas-cli] Automatically promote new cli release to staging on EAS Build

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
iOS resource classes (M1, Intel) can be disabled independently. 
When a particular resource class is disabled, mention which one.
Tested with changes in https://github.com/expo/universe/pull/11239
> print disabled resource class labels

- CHANGELOG.md
- packages/eas-cli/src/build/configure.ts
For new apps adopting EAS Build, they should be using M1, and this should be explicit until we change the default across the board.
Add M1 resource class configuration to **eas.json**. We should remove this as M1 adoption increases, likely around the SDK 48 release where we hope to make it default.
I ran `easd build:configure` on a new project
> [eas-cli] Switch to using M1 by default when running build:configure

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/commands/build/index.ts
Often when reacting to a new situation, we do not have a way to send good error messages to users without an EAS CLI update. This change is making all error messages defined server side.
- Print error returned from www
- Print entire raw error in debug mode
enable kill switch and try to run build on staging
> [eas-cli] Print error message sent from server

- CHANGELOG.md
- packages/eas-cli/src/vcs/index.ts
Closes #1636
Always print warning about EAS_NO_VCS to stderr to avoid issues when command is run in json only mode
`EAS_NO_VCS=1 eas_dev build:list --json --non-interactive | jq .`
> [eas-cli] Print warning about EAS_NO_VCS option to stderr

- CHANGELOG.md
- packages/eas-cli/src/build/local.ts
Fixes https://github.com/expo/eas-cli/issues/1648
https://github.com/expo/eas-cli/pull/1568/files#diff-4d125a745cc089a165745b3ab71732146c1bd1ac146f531cae4ea4824a27c6b0L224 introduced a bug with local builds. By default, enum values are 0, 1, 2, and so on. `0` is falsy.
Use non-default values for the LocalBuildMode enum.
> fix local builds

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/build/build.ts
- packages/eas-json/src/build/schema.ts
- yarn.lock
https://linear.app/expo/issue/ENG-7094/better-error-handling-when-image-is-valid-but-doesnt-exist-on
We recently moved `image` validation to the server side from the `eas-build-job` package https://github.com/expo/eas-build/pull/182. We need to move validating `image` in `eas-json` to the server side. To achieve this we also need to improve handling validation errors from WWW in `eas-cli`
Improve handling of `VALIDATION_ERROR` errors and don't validate `image` in `eas-json`.
Test locally with https://github.com/expo/turtle-v2/pull/1179 and https://github.com/expo/universe/pull/11284
> [ENG-7094][eas-cli] move image validation to server side

- CHANGELOG.md
- packages/eas-cli/src/channel/utils.ts
When someone has a channel that doesn't point to a branch, the branch mapping is `{version: 0, data []}`. While this is valid, the cli assumes there is always some mapped branch . This PR fixes this assumption. 
Optionally chain `branchMapping.data[0]` because it can be undefined
> [ENG-7328][eas-cli] fix undefined branchMappingLogic

- CHANGELOG.md
- packages/eas-cli/src/build/createContext.ts
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/build/utils/resourceClass.ts
https://linear.app/expo/issue/ENG-7351/switch-the-default-resourceclass-to-m1-for-sdk-48-projects
If the resource class is unspecified, and the project is using SDK 48 / React Native 0.71, use the `m1-medium` resource class for the build.
Test locally.
> [ENG-7351][eas-cli] set `m1-medium` resource class for builds which don't specify resource class for SDK 48 and RN 0.71

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts
- packages/eas-cli/src/credentials/ios/utils/provisioningProfile.ts
Closes #1656 
Check if the provisioning profile is using universal provisioning for enterprise accounts when using local credentials.
Additionally, check more strictly if enterpriseProvisioning is specified in eas.json.
Don't have access to the enterprise account at the moment(some policies need to be accepted), so I didn't test it, but I verfied with EAS Build sources that this is the way we validate on builider type of the Provisioning profile
> [ENG-7367][eas-cli] Fix using local credentials with enterprise provisioning

- CHANGELOG.md
- packages/eas-cli/src/build/createContext.ts
- packages/eas-cli/src/commandUtils/context/DynamicProjectConfigContextField.ts
- packages/eas-cli/src/commands/update/index.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1675204277962559?thread_ts=1675197740.345569&cid=C017N0N99RA
Revert change which caused this bug https://github.com/expo/eas-cli/commit/7fc3e3fcdbfaf8678f74a381ae29906d363ff33a#diff-c63107e3aba5b4b07dc44257b5a0d13751a25aa74279e996419d1e35a5955acf
Tested locally
> [eas-cli] fix issue with the `eas.json` envs being not available when resolving local config

- CHANGELOG.md
- packages/eas-cli/src/update/configure.ts
This reverts commit 9ef848388277d641419814bb99ecf69143cdced7.
This PR makes the default `runtimeVersion` after running `eas update:configure` to be `sdkVersion`.
We fixed a bug that allows `appVersion` to run correctly on Android. I thought that Expo Go no longer had a runtime version constraint, so I made the change to default to `appVersion`. However, Expo Go still only supports SDK based runtime versions, and it’s causing issues for developers using Expo Go. We also decided we never want to let Expo Go handle non-SDK runtime versions.
- Change back to `sdkVersion` as the default
Run `eas update:configure` in a project and make sure it outputs `sdkVersion` as the `runtimeVersion`
> Revert "[eas-cli] use appVersion instead of sdkVersion (#1588)"

- CHANGELOG.md
- packages/eas-cli/src/build/android/build.ts
- packages/eas-cli/src/build/ios/build.ts
- packages/eas-cli/src/commands/build/version/set.ts
- packages/eas-cli/src/commands/build/version/sync.ts
- packages/eas-cli/src/project/android/__tests__/applicationId-test.ts
- packages/eas-cli/src/project/android/applicationId.ts
- packages/eas-cli/src/project/applicationIdentifier.ts
- packages/eas-cli/src/project/ios/__tests__/bundleIdentifier-test.ts
- packages/eas-cli/src/project/ios/bundleIdentifier.ts
Noticed that when I have an application that belongs to an org it still suggests my logged-in username as the application identifier part. This changes it to use the owner account name.
Closes ENG-7475.
Update logic.
Before:
```
$ eas build -p android
✔ Generated eas.json
📝  Android application id Learn more
✖ What would you like your Android application id to be? … com.wschurman.pouidapoidaw
```
After:
```
$ ~/expo/eas-cli/packages/eas-cli/bin/run build -p android
📝  Android application id Learn more
✖ What would you like your Android application id to be? … com.myneworg.pouidapoidaw
```
> [eas-cli] Fix suggested identifiers to match owning account name

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/contextUtils/__tests__/getProjectIdAsync-test.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
- packages/eas-cli/src/commands/project/__tests__/init.test.ts
- packages/eas-cli/src/commands/project/init.ts
- packages/eas-cli/src/user/User.ts
A user reported an issue where they were operating on a organization project as another account. While this works for 99% of things, some legacy code still requires an owner field to work properly.
It is unlikely that many users end up in this state though since:
a) `eas init` sets owner and project ID
b) the instructions tell people to set owner when collaborating
But it might be missed sometimes. Therefore, this PR validates that when there is a project ID and no owner set, it will throw an error when the implicit owner for legacy tools (the currently-logged-in user) does not match the actual owner of the project identified by the ID.
Closes ENG-7474.
Add check and test.
This commit also now verifies the project setup idempotently when `eas init` is re-run so that the command error …
> [eas-cli] Warn when project ID but no owner specified and mismatch logged in user

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/build/utils/formatBuild.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/types/Build.ts
Support returning the message in the build list, found this feature very useful in the dashboard to tell builds apart. But it was missing in the CLI
Expanded the query to include the message, unsure if I should include the generated file (it has unnecessary amount of changes)
> Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.
Following the CONTRIBUTING guide, I setup a local version of the cli and ran both the list and json outputs.
| List  | JSON |
| ------------- | ------------- |
| <img width="610" alt="Screenshot 2023-02-12 at 4 45 01 PM" …
> feat: return the build message when one is available

- CHANGELOG.md
- packages/eas-cli/src/analytics/AnalyticsManager.ts
Closes #1684 
The analytics library does not respect proxy configuration, and it is causing cli to hang before exiting.
Disable analytics if CLI is running behind a proxy.
> [eas-cli] Disable analytics for environments behind proxy

- CHANGELOG.md
- packages/eas-cli/src/commands/build/index.ts
https://github.com/expo/eas-cli/issues/1685
Sometimes running local builds on windows fails before we even validate the platform, so to users it looks like a bug.
In the above case validation was never reached because spawning a process for local buld plugin failed.
Validate platform in eas-cli before local plugin is executed.
Not tested, copied the check from the local build plugin
> [eas-cli] Validate platform for local builds earlier

- .github/workflows/release.yml
In https://github.com/expo/eas-cli/pull/1640/files changed PR changelog workflow behavior, it commits changelog changes using Expo Bot's PAT. I forgot to do the same for the release changelog update workflow committing to `main`.
We also can see that after the merge queue was enabled main commits from this workflow failed with branch protected error. Maybe adding PAT will fix it as well.
Do the same as in https://github.com/expo/eas-cli/pull/1640/files. It shouldn't break anything.
Test on prod 😈 I will observe if the next release workflow succeeds or if we see branch protected error again.
> [ci] commit release changelog update using Expo Bot PAT

- CHANGELOG.md
- packages/eas-cli/src/build/queries.ts
- packages/eas-cli/src/submit/ArchiveSource.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1676462063098759
Display `build.message` data
> [eas-cli] display build message data when picking build in `submit`, `build:run` and `build:resign` commands

- package.json
- packages/eas-cli/package.json
- packages/eas-json/package.json
The old release script wasn't cleaning `build` folders and therefore releases from my device were publishing `README` containing nonexisting commands `eas run`, and `eas run:run`.
https://github.com/expo/eas-cli/commit/bfa63f95fed5741f44009e8506143d38ce9fbc6b
I modified it to delete the `build` folder contents before running the script
I tested that it deletes the `build` folder and runs `yarn build`
> [ci] fix release script

- CHANGELOG.md
- packages/eas-cli/src/build/utils/printBuildInfo.ts
- packages/eas-cli/src/build/utils/url.ts
- packages/eas-cli/src/log.ts
https://linear.app/expo/issue/ENG-7376/add-link-directly-to-log-build-phase-in-eas-cli-build-error-message
Add overrides for certain error messages. Use changes from https://github.com/expo/universe/pull/11440 to link users directly to the error phase mentioned in the error message.
Test locally.
https://user-images.githubusercontent.com/55145344/219015836-3d0db562-febc-40cd-93fe-1264f54d1580.mov
> [ENG-7376][eas-cli] link to build phase in error message

- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/__tests__/publish-test.ts
- packages/eas-cli/src/project/publish.ts
Fixes ENG-6081
This change renders the "original path" (from `assetmap.json`), or the "asset name" (from `manifest.json`, if `assetmap.json` isn't there or not containing the asset hash).
This also changes the logging text. Idea is that while app bundles are "assets" for EAS Update, users might not associate bundles as assets. Instead of "assets", I split the story into:
- "app bundles" (technically `launchAssets`)
- "normal assets" (just `assets`)
Not sure if that's correct, but I think that this helps communicate what was uploaded and what not.
- Added `launchAssetCount` and `uniqueUploadedAssetPaths` outputs to `uploadAssetsAsync`
- Added optional `assetmap.json` loading to resolve the original filenames of the assets
- _When there is no `assetmap.json`, e.g. when using …
> [eas-cli] Provide more context about uploaded assets when publishing

- CHANGELOG.md
- packages/eas-cli/src/project/android/gradleUtils.ts
`package*UniversalApk` is a well-known (though undocumented) Gradle task to build just the universal APK. This is especially useful if `enableSeparateBuildPerCPUArchitecture` is set to true, but you just want to output the universal APK file without needing to specify `buildArtifactPaths`.
Added `package` in addition to the other prefixes for Gradle commands.
I have a config in my `eas.json` containing `"gradleCommand": ":app:packageDebugUniversalApk"`.
Running `eas-cli` resulted in the message:
```
Unable to read gradle project config: Failed to parse gradle command: :app:packageDebugUniversalApk.
Values from app/build.gradle might be resolved incorrectly.
```
I then made the changes in this PR to `eas-cli` in my local dev environment, and ensured that the message no longer shows up.
> Support variant detection for package*UniversalApk Gradle Commands

- packages/eas-cli/graphql.schema.json
- packages/eas-cli/package.json
- packages/eas-cli/src/build/android/build.ts
- packages/eas-cli/src/build/android/graphql.ts
- packages/eas-cli/src/build/android/prepareJob.ts
- packages/eas-cli/src/build/graphql.ts
- packages/eas-cli/src/build/ios/credentials.ts
- packages/eas-cli/src/build/ios/graphql.ts
- packages/eas-cli/src/build/ios/prepareJob.ts
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/build/utils/printBuildInfo.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/project/customBuildConfig.ts
- packages/eas-json/package.json
- packages/eas-json/src/__tests__/buildProfiles-test.ts
- packages/eas-json/src/build/schema.ts
- packages/eas-json/src/build/types.ts
- yarn.lock
This PR adds very basic support for custom builds.
- Add `config` field to build profile that points at a .yml file in the **.eas/build** directory. 
- Validate if the custom build config file exists.
- If `config` is set, consider build custom.
- Don't configure credentials for custom builds (this is temporary until there is a way to read credentials from custom builds).
- Custom builds don't support uploading artifacts yet. Don't print application archive URL if it doesn't exist for a build.
- Set `buildMode` in metadata - build / custom.
Configuration file does not exist in `.eas/build` directory:
Failed build:
Successful build:
> [ENG-7565] add basic support for custom builds

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
- fix https://github.com/expo/eas-cli/issues/1714 🤞 
- implements Apple's proprietary implementation of hashcash for signing authentication requests.
- Tested on all my accounts at a rate that would surely trigger rate limit issues otherwise. Didn't get a single failure.
> [eas-cli] bump apple-utils to support hashcash for authentication

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/configure.ts
- packages/eas-cli/src/build/utils/resourceClass.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-json/schema/eas.schema.json
- packages/eas-json/src/build/schema.ts
- packages/eas-json/src/build/types.ts
https://linear.app/expo/issue/ENG-7709/create-m-large-and-m-medium-resource-classes
Add new `m-medium` and `m-large` resource classes.
Make `m1-medium` and `m1-experimental` point to `m-medium` on the server side.
Don't suggest `m1-medium` in the `eas.json` schema to users. Suggest `m-medium` instead.
I'm not adding `m-large` to `eas.schema.json`, because it's hidden behind the feature gate and it isn't publicly available.
Run builds locally
> [ENG-7709][eas-cli][eas-json] add `m-medium` and `m-large` resource classes

- CHANGELOG.md
- packages/eas-cli/src/build/__tests__/handleBuildRequestError-test.ts
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/errors.ts
- packages/eas-cli/src/build/queries.ts
- packages/eas-cli/src/commandUtils/EasCommand.ts
- packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts
- packages/eas-cli/src/commandUtils/errors.ts
- packages/eas-cli/src/commands/build/index.ts
Overriden the `Command`'s `catch` method to catch all the errors thrown by the commands, log the error message there the same way as it was previously handled in `src/build/build.ts` and re-throw generic `Error` instance with predefined base error message. To avoid duplication, old `Log.error()` calls have been removed from `src/build/build.ts`. Also added tests to see if the `catch()` method works as intended.
There used to be a difference between how the expected/handled errors had been displayed by `eas-cli` when compared to these that were not expected. This change is meant to unify this behaviour
Expected:
Unexpected:
See: https://linear.app/expo/issue/ENG-6945/improve-eas-cli-error-logging
Utilised the `catch()` method of `oclif`'s `Command` class, which is extended by custom base …
> [eas-cli] [ENG-6945] Unify error display method

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/EasCommand.ts
- packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts
- packages/eas-cli/src/commands/build/index.ts
Removed the option to provide custom base error message, so that it always be lower case for command failures
See: https://linear.app/expo/issue/ENG-6945/improve-eas-cli-error-logging
To unify the behaviour the base error message is no longer customisable and always has lower case command id for command failures
Lower case command id is always used for command failures
Updated the automatic tests
> [eas-cli] [ENG-6945] Don't use capitalised base error messages

- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/index.ts
Make sure we are only using the public config when creating updates.
Added test case.
- See tests
- `$ yarn create expo-app ./test-update && cd ./test-update`
- `$ eas update --auto`
- _Make sure this works as expected_
- Modify the `app.json` to create code-signed updates
- `$ eas update --auto`
- _Make sure code signing works as expected_
> [eas-cli] Add test case to ensure public config is used as update

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/__tests__/republish.test.ts
- packages/eas-cli/src/commands/update/__tests__/roll-back-to-embedded.test.ts
- packages/eas-cli/src/commands/update/republish.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/types/Update.ts
- packages/eas-cli/src/project/__tests__/publish-test.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/update/__tests__/getBranchNameFromChannelNameAsync-test.ts
- packages/eas-cli/src/utils/code-signing.ts
- packages/eas-cli/src/utils/expodash/__tests__/areSetsEqual-test.ts
- packages/eas-cli/src/utils/expodash/areSetsEqual.ts
This adds a new command, `eas update:roll-back-to-embedded` (name up for discussion), that creates a "roll back to embedded" update.
Server implementation: https://github.com/expo/universe/pull/11720
Client implementations: https://github.com/expo/expo/pull/21652, https://github.com/expo/expo/pull/21256
Protocol spec: https://www.notion.so/expo/Expo-Updates-directives-in-multipart-manifests-2dee4deac86241a4873ee2fdb3d83d9c
I considered making this a flag, but it seems the trend is to have these be a separate command (see `update:republish`).
1. Create command
2. Factor out common code from index
3. Add test
Run test.
Run:
```
~/expo/eas-cli/packages/eas-cli/bin/run update:roll-back-to-embedded --private-key-path keys/private-key.pem
```
(to check that a republish is created in staging and …
> [eas-cli] Add support for roll back to embedded updates

- CHANGELOG.md
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/update/utils.ts
This adds more info about updates into the table. We (do or will soon) show these in the website.
Add info.
```
$ ~/expo/eas-cli/packages/eas-cli/bin/run update:list
✔ Which branch would you like to view? › main
Branch:
Name  main
ID    eb778b09-83b4-4b45-9c82-c9e4332e424b
Recent update groups:
Platforms                 android, ios
Runtime Version           exposdk:48.0.0
Message                   "Initial commit
Generated by create-expo-app 1.3.2." (14 minutes ago by wschurman)
Code Signing Key          main
Is Roll Back to Embedded  Yes
Group ID                  4c3d99e4-40cf-49eb-9c75-eeee7652e309
———
Platforms                 android, ios
Runtime Version           exposdk:48.0.0
Message                   "Initial commit
Generated by create-expo-app 1.3.2." (16 minutes ago by …
```
> [eas-cli] Add info about code signing and roll back to embedded in update info

- CHANGELOG.md
- scripts/src/updateLocalPlugin.sh
Streamlines eas-cli / eas-build releases.
Use the `eas-cli` tag for checking for `eas-cli-local-build-plugin`.
I tagged the 0.0.128 version with `eas-cli` so this PR doesn't change anything yet.
None.
> [ENG-7981] use the eas-cli npm tag for eas-cli-local-build-plugin updates

- CHANGELOG.md
- packages/eas-cli/src/utils/expoCli.ts
Since https://github.com/expo/expo/pull/21388 was merged we've been experiencing failures in the `Publish Native Component List Website & Update` workflow on [expo/expo](https://github.com/expo/expo) due to the `eas update` command failing to find the module 'expo/bin/cli.js'
E.g. https://github.com/expo/expo/actions/runs/4620498308/jobs/8170689606
This PR updates the `expoCommandAsync` function to resolve the CLI path from the new path, `expo/bin/cli`, using `expo/bin/cli.js` as a fallback
Run the cli locally
> [eas-cli] Fix expoCommandAsync to support the new cli bin path

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
This updates our apple utilities to work around the `maintenance` error users encounter when logging in.
- Updated to `@expo/apple-utils@1.2.0`
- `eas credentials` and try to log in
> [eas-cli] Update apple utilities to avoid the maintenance error

- CHANGELOG.md
- packages/eas-cli/src/utils/__tests__/profiles-test.ts
- packages/eas-cli/src/utils/profiles.ts
- packages/eas-json/src/__tests__/buildProfiles-test.ts
- packages/eas-json/src/utils.ts
https://linear.app/expo/issue/ENG-7968/do-not-cache-podfilelock-by-default
Companion to https://github.com/expo/turtle-v2/pull/1256.
Add a method in `eas.json` which returns deprecation warnings. Print them in the EAS CLI.
Test manually
> [ENG-7968][eas-cli][eas-json] print deprecation warnings for deprecated `eas.json` fields

- CHANGELOG.md
- packages/eas-cli/src/update/configure.ts
When reproducing unrelated issues I noticed that if global expo-cli is not installed then running `eas update` will trigger installing `expo-update` package but it will hang on a prompt that is never displayed because the output is not printed to a terminal.
The result of the above is that command hangs indefinitely unless users hits enter(but no prompt is displayed). It happens for SDK 45 and lower)
Always show output install command
before
after
> [eas-cli] always show logs from expo install

- packages/eas-cli/src/commandUtils/context/contextUtils/__tests__/getProjectIdAsync-test.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
@kbrandwijk reported that people are getting a cryptic error around the `appId`. I repro'd the issue by setting `extra.eas.projectId` to a non-string value.
- Validate whether `extra.eas.projectId` is a string before sending a server request.
- Print an error message with the potential solution (removing the value from app config).
- Test case
- Manual test:
> print meaningful error message if extra.eas.projectId is not a string

- .github/PULL_REQUEST_TEMPLATE
- .github/workflows/changelog-bot.yml
- .github/workflows/changelog.yml
- .github/workflows/test.yml
This PR implements my idea on how to make skipping adding the changelog entry less likely.
- Add a workflow that fails if the PR didn't modify CHANGELOG.md.
- The check is skipped if "no changelog" label is added to the PR.
- Comment PR with the check status.
> [gha] add PR changelog check

- CHANGELOG.md
- packages/eas-cli/src/build/utils/resourceClass.ts
https://exponent-internal.slack.com/archives/CHZKBDRN1/p1681788787056429
Throw an error if somebody tries to run an iOS build using the `large` resource class specified using experimental and deprecated `--resource-class` flag.
> [eas-cli] throw error if somebody tries to run iOS with `large` resource class selected using deprecated `--resource-class` flag

- packages/eas-cli/src/ora.ts
Some users trigger `eas build` from their CI. I'm not sure if `isTTY` is intended to always trigger in this case, but a user recently reported EAS build CI output that looked like the output below, and we've added CI flag checks elsewhere to do the same thing.
```
Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
⠋ Compressing project files⠙ Compressing project files⠹ Compressing project files⠸ Compressing project files⠼ Compressing project files⠴ Compressing project files⠦ Compressing project files⠧ Compressing project files⠇ Compressing project files⠏ Compressing project files⠋ Compressing project files⠙ Compressing project files⠹ Compressing project files⠸ Compressing project files⠼ Compressing project files⠴ Compressing project files⠦ …
```
> [eas-cli] make ora recognize CI env variable

- CHANGELOG.md
- packages/eas-cli/src/commands/device/delete.ts
- packages/eas-cli/src/devices/actions/create/inputMethod.ts
For https://github.com/expo/eas-cli/pull/1787, I copied the Expo-to-Apple device cross-reference from `eas device:delete`. During testing, I discovered that it never found the device on Apple, and then when I went back to try out delete, it turned out that delete wasn't finding the device either, and thus never disabling it on the Apple Developer Portal.
The previous `find` was comparing Expo GUID to an Apple 9-character alphanumeric ID. Updated to compare `udid` to `udid`.
Here's what the objects look like:
`AppleDevice` (Expo entity):
```
{
id: 'f8108da4-d62b-4325-8f0d-b646133c2d16',
identifier: '00008110-ABCDEFD12345678',
name: 'keiths ipad',
deviceClass: 'IPAD',
enabled: true,
model: null,
}
```
`Device` (from `@expo/apple-utils`):
```
{
context: { providerId: 12345678, teamId: …
```
> [eas-cli] Device delete not disabling on Apple side

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/configure.ts
- packages/eas-cli/src/build/createContext.ts
- packages/eas-cli/src/build/utils/resourceClass.ts
- packages/eas-cli/src/graphql/generated.ts
https://linear.app/expo/issue/ENG-7676/default-resource-class-m1-rollout
Companion to https://github.com/expo/universe/pull/11639
We want to move resolving the default iOS resource class to the server side so we can have more control over users.
Don't resolve the iOS default resource class in CLI
Don't set `m1-medium` as default when running the `eas build:configure` command. 
Send `sdkVersion` and `reactNativeVersion` as build params to our server
Should be merged after https://github.com/expo/universe/pull/11639
Test manually.
> [ENG-7676][eas-cli] don't resolve default resource class for iOS based on metadata in CLI

- CHANGELOG.md
- packages/eas-cli/src/build/utils/resourceClass.ts
- packages/eas-json/schema/eas.schema.json
- packages/eas-json/src/__tests__/buildProfiles-test.ts
- packages/eas-json/src/build/schema.ts
- packages/eas-json/src/build/types.ts
We want to make `large` iOS available for the users
Add `large` as a valid option for the `resourceClass` field in `eas.json` (both for iOS-specific options and in build profile root). 
After this PR is merged users should be able to use the `large` resource class in the following ways:
Request `large` both for iOS and Android
```json
{
"build": {
"production": {
"resourceClass": "large",
...
},
...
},
...
}
```
Request `large` for iOS only
```json
{
"build": {
"production": {
"ios": {
"resourceClass": "large",
...
},
...
},
...
},
...
}
```
Request `large` for Android only
```json
{
"build": {
"production": {
"android": {
"resourceClass": "large",
...
},
...
},
...
},
...
}
```
Deprecate experimental `m-large` resource class.
Add tests.
Test manually
Deprecated `m-large` resource class: …
> [eas-cli][eas-json] add `large` resource class for iOS as allowed value in `eas.json`

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
I added support for the `import` statement in the custom builds config.
Upgrade `@expo/steps` to the latest so `import` passes validation.
> [ENG-7740][eas-cli] upgrade @expo/steps

- CHANGELOG.md
- packages/eas-cli/src/build/metadata.ts
Builds from GitHub should never be in a dirty state, even if there are some local changes cause by e.g. pre-install hook.
override isGitWorkingTreeDirty when localBuildMode is INTERNAL
simple change, not tested
> [eas-cli] builds from GitHub are never in a dirty state

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/project/ios/target.ts
- packages/eas-cli/src/update/ios/UpdatesModule.ts
- yarn.lock
Companion to https://github.com/expo/expo/pull/22454
Fixes https://github.com/expo/eas-cli/issues/1812
Don't generate credentials for non-signable targets. 
Tested against the project from https://github.com/expo/eas-cli/issues/1812#issuecomment-1540282795
Upgrade `config-plugins` here when it's published
> don't generate ios credentials for non-signable targets

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/actions/DeviceUtils.ts
- packages/eas-cli/src/easMultiselect.ts
- packages/eas-cli/src/prompts.ts
- packages/eas-cli/tsconfig.json
- ts-declarations/prompts/index.d.ts
Select devices prompt is a bit messy when there are many selected devices. Instead of printing all of their names and identifiers, simply the number of selected devices should be displayed.
Since `prompts` library does not make it easy to customize default prompts, default multiselect is overriden by new `EasMultiselect`. New prompt can customize output message via `selectionFormat` option.
It can be tested by issuing new/editing existing adhoc provisioning profile with `eas credentials` command.
> [eas-cli][ENG-8528] Don't print all selected devices.

- CHANGELOG.md
- packages/eas-cli/src/__tests__/commands/utils.ts
- packages/eas-cli/src/build/__tests__/handleBuildRequestError-test.ts
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/errors.ts
- packages/eas-json/schema/eas.schema.json
Companion to https://github.com/expo/universe/pull/12375
Handle newly defined error thrown when a free tier user tries to use a `large` resource class as other server-side defined errors in EAS CLI.
Add tests
> [eas-cli] make `large` resource class only available for paid tier users

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/build/types.ts
- packages/eas-cli/src/build/utils/formatBuild.ts
- packages/eas-cli/src/build/utils/printBuildInfo.ts
- packages/eas-cli/src/commands/build/cancel.ts
- packages/eas-cli/src/commands/build/list.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/update/__tests__/getBranchNameFromChannelNameAsync-test.ts
Adding new build status `PENDING_CANCEL` which is supposed to give workers time to perform cleanup and upload logs when the build is canceled before the worker gets terminated by the launcher. This status is only relevant to EAS and from the user's perspective builds in this status should be treated the same as the ones that are already canceled. This PRs adds support for that
In all the places where the behaviour is dictated by the build status a change is introduced to mirror the behaviour for canceled builds.
Manually tested with modified response from `www` returning a build in `PENDING_CANCEL` status ⬇️ 
Build `9ae0d32f-9ed5-4eb8-a396-bfbbd4ca95e7` is actually `PENDING_CANCEL` but is displayed as `CANCELED`
Testing with the version of CLI from main shows the build as in `unknown` …
> [eas-cli] [ENG-8506] Handle pending cancel build status in cli

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/__tests__/publish-test.ts
- packages/eas-cli/src/project/publish.ts
Closes ENG-8515.
We recently had a customer ask why their assets were struggling to upload. It happened to be that it was a 30MB compressible asset and our system wasn't tuned to support that. We fixed it by increasing the memory of our processing cloud function. But, it would have made debugging faster if we knew which assets had stalled.
This PR adds logging to indicate which assets have stalled.
Add race.
In project with new unique assets, run `neas update --branch preview` after manually making the upload function time out.
See
```
✖ Failed to upload
Upload processing timed out for assets:
- /Users/wschurman/temp/lots-o-assets/dist/bundles/android-2031cfb5df244b2172589371d5afeaed.js,
- /assets/images/1590.jpg,
- /assets/images/1591.jpg,
- /assets/images/1592.jpg,
- …
```
> [eas-cli] Print assets that timed out during upload or processing

- CHANGELOG.md
- packages/eas-cli/src/update/android/UpdatesModule.ts
https://github.com/expo/expo/commit/166385e28b75d11684bacdcace0c4abb92434adb added this to the config plugin.
This code in eas-cli is supposed to emulate the config plugin, but for bare projects.
Make the config plugin emulation also do the new synchronization of strings.xml.
- npx create expo-app
- npx expo prebuild
- add runtime version to app.json
- install expo-updates
- commit everything 
- eas build (current prod version)
- it added `<meta-data android:name="expo.modules.updates.EXPO_RUNTIME_VERSION" android:value="@string/expo_runtime_version"`
- but there were no changes in strings.xml
- neas build (with this PR)
- it added `<meta-data android:name="expo.modules.updates.EXPO_RUNTIME_VERSION" android:value="@string/expo_runtime_version"`
- it added `<string …
> [ENG-8790][eas-cli] Fix updates synchronization of native files to include strings.xml

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts
- yarn.lock
- WWDC 23 update.
- Add the new bundle identifier capabilities from WWDC 23. Only the values there show up on the [dashboard](https://developer.apple.com/account/resources/identifiers/bundleId) are added.
- Updated apple-utils with new version that contains new capabilities.
- Got the entitlement IDs from the new Xcode: Version 15.0 beta (15A5160n)
- Tested API directly with apple utils.
> feat(eas-cli): add new public entitlements from wwdc23

- packages/eas-cli/package.json
- yarn.lock
Cleanup after https://github.com/expo/eas-build/pull/233.
Upgraded `@expo/steps` package. It is the only `eas-build` package in here.
It's a type-only change so CI success will be enough.
> Remove direct `@types/bunyan` dependency

- CHANGELOG.md
- packages/eas-cli/src/build/configure.ts
This came up when talking to @brentvatne about improving user experience when they are running `eas build:configure` by linking to the [eas.json schema doc](https://docs.expo.dev/build-reference/eas-json/).
By updating the message when it outputs "Generated eas.json" to use `learnMore()` to display a "(learn more)" 
message with a link to eas.json schema doc.
- In one terminal window, Inside `eas-cli` directory, run `yarn start`.
- In another terminal window,  create a new project with `npx create-expo` and navigate to the project directory.
- Inside the project directory, run `easd build:configure` and follow the prompts.
One success, you will get the following result with "(learn more)" link:
> [eas-cli] Update eas build:configure command to show link of eas.json when generated

- CHANGELOG.md
- packages/eas-cli/src/utils/expoCli.ts
Fail gracefully on commands that call `npx expo install` if the expo package is not installed
Before:
```
quins-MacBook-Pro:AwesomeProject2 quin$ ~/Documents/eas-cli/packages/eas-cli/bin/run update:configure
💡 The following process will configure your project to run EAS Update. These changes only apply to your local project files and you can safely revert them at any time.
> npx expo install expo-updates
Error: Cannot find module 'expo/bin/cli.js'
Require stack:
- /Users/quin/AwesomeProject2/noop.js
```
After:
```
quins-MacBook-Pro:AwesomeProject2 quin$ ~/Documents/eas-cli/packages/eas-cli/bin/run update:configure
💡 The following process will configure your project to run EAS Update. These changes only apply to your local project files and you can safely revert them at any time.
> npx …
```
> [eas-cli] error gracefully if expo pkg not installed

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/EasCommand.ts
Without this diff, all stack traces that you can see with `DEBUG=* eas [cmd]` will point to where we catch and sanitize the error `EasCommand.ts`, and not give you any indication of the original source of the error.
Point the `stack` on the new error object to the original error stack.
- Add an error somewhere inside a command
- Run `DEBUG=* easd [command]`
- You should see the appropriate stack
> [eas-cli] Ensure that re-thrown error includes original stack

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
- packages/eas-cli/src/commands/project/__tests__/init.test.ts
- packages/eas-cli/src/commands/project/init.ts
- packages/eas-cli/src/project/__tests__/expoConfig.test.ts
- packages/eas-cli/src/project/expoConfig.ts
- packages/eas-cli/src/update/configure.ts
It's unfortunate to have to tell people to manually create this file, we should do it automatically with `eas init` or `eas update:configure` or `eas build:configure`. Additionally, the current error is.. not very helpful: 
```
easd build:configure
EAS project not configured.
✔ Existing EAS project found for @brents/quin (id = 0f084c7f-d209-491d-97ac-c8c5c4c2c122). Configure this project? … yes
✖ Linking local project to EAS project 0f084c7f-d209-491d-97ac-c8c5c4c2c122
No config exists
Error: build:configure command failed.
```
"No config exists"
Wrap `modifyConfigAsync` and add some ensure calls where we read the app config.
I tried this in a project without app.json, and with an app.json that does not have an `expo` key. Need to write actual unit tests to cover this behavior still
> [eas-cli] Initialize app.json if it does not exist, add expo key if missing

- CHANGELOG.md
- packages/eas-cli/README.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/package.json
- packages/eas-cli/src/api.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
- packages/eas-cli/src/commands/account/login.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/queries/UserQuery.ts
- packages/eas-cli/src/project/projectUtils.ts
- packages/eas-cli/src/update/__tests__/getBranchNameFromChannelNameAsync-test.ts
- packages/eas-cli/src/user/SessionManager.ts
- packages/eas-cli/src/user/User.ts
- packages/eas-cli/src/user/__tests__/SessionManager-test.ts
- packages/eas-cli/src/user/__tests__/User-test.ts
- packages/eas-cli/src/user/actions.ts
- packages/eas-cli/src/user/expoSsoLauncher.ts
- packages/eas-cli/src/user/fetchSessionSecretAndSsoUser.ts
- packages/eas-cli/src/user/fetchSessionSecretAndUser.ts
- packages/eas-cli/src/user/fetchUser.ts
- packages/eas-cli/src/utils/port.ts
- ts-declarations/freeport-async/index.d.ts
- yarn.lock
These changes are to enable  an SSO user to log in with eas cli via the Expo website.
Added a -sso, -s flag to the login command for a user to select logging in with SSO. The CLI then opens a browser window and redirects the user to the Expo website to log in. The website takes them through the auth flow with their Auth Provider and logs them in to Expo before returning.
This CLI SSO user login follows Expo Go login behavior (which also logs in via the Expo website):
- if no user is logged into the website, the user gets logged in and the session is returned to the CLI
- if a user is already logged into the website then that user session is returned
- once a user is logged into the website, in order to change the logged-in user in the CLI, the current user has to be manually logged out in …
> [eas-cli] Changes for SSO user type and SSO login.

- CHANGELOG.md
- packages/eas-cli/src/credentials/__tests__/fixtures-android.ts
- packages/eas-cli/src/credentials/android/api/GraphqlClient.ts
- packages/eas-cli/src/credentials/android/api/graphql/mutations/AndroidAppBuildCredentialsMutation.ts
- packages/eas-cli/src/credentials/manager/Actions.ts
- packages/eas-cli/src/credentials/manager/AndroidActions.ts
- packages/eas-cli/src/credentials/manager/CreateAndroidBuildCredentials.ts
- packages/eas-cli/src/credentials/manager/ManageAndroid.ts
- packages/eas-cli/src/credentials/manager/SetDefaultAndroidKeystore.ts
Current workflow can lead to users unintentionally overwriting their Android keystore. We should make this mistake less likely.
Change current flow to the following:
- Keystore: Manage everything needed to build your project
- Set up a new keystore
- Generate a new Android Keystore
- Assign a name to your build credentials
- Set this as your default build credentials (y/N)
Also, user can also change his default keystore via CLI.
1. Run `eas credentials -p android`
2. Select any profile
3. Select `Keystore: Manage everything needed to build your project`
Creating new keystore
4. Select `Set up a new keystore`
5. Follow the workflow
Selecting default keystore
4. Select `Change default keystore`
5. Select new default keystore
6. Check (via CLI or web) whether default keystore changed.
> [eas-cli][ENG-8763] Select default android keystore

- CHANGELOG.md
- packages/eas-cli/src/build/configure.ts
- packages/eas-cli/src/commands/update/configure.ts
Make `eas update:configure` output less verbose and similar to `eas build:configure`
Before:
```
🎉 Your app is configured with EAS Update!
Next steps:
Update a production build:
1. Create a new build. Example: eas build --profile production.
2. Make changes in your project.
3. Publish an update. Example: eas update --channel production.
4. Force close and reopen the app at least twice to view the update.
Preview an update:
1. Publish an update to a branch. Example: eas update --branch new-feature.
2. In Expo Go or a development build, navigate to Projects > [project name] > Branch > Open.
```
After:
```
quins-MacBook-Pro:AwesomeProject2 quin$ ~/Documents/eas-cli/packages/eas-cli/bin/run update:configure
🎉 Your app is configured with EAS Update!
- Run eas build:configure to complete your …
```
> [eas-cli] update:configure less verbose output

- CHANGELOG.md
- packages/eas-cli/README.md
- packages/eas-cli/src/commands/account/login.ts
This makes 2 minor changes which are not to display the login -sso flag in the help text and not to list it in the README, as SSO is in beta stage.
Added 'hidden' to the sso flag definition, and deleted the remaining mention of it in the README.
Manually tested that easd login --help does not list the sso flag.
> [eas-cli] Change sso flag display

- CHANGELOG.md
- packages/eas-cli/src/build/createContext.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/project/projectUtils.ts
- packages/eas-cli/src/update/configure.ts
https://linear.app/expo/issue/ENG-7183/improve-detection-of-expo-updates-in-devdependencies
Currently, we don't perform any check in the `eas build` command to verify if a user has `expo-updates` installed when `channel` is set for the build profile.
If a user has a `channel` set for their build profile warn if they don't have `expo-updates` installed. Detect when `expo-updates` are installed as a dev dependency and print a warning suggesting them moving it to dependencies.
Print a warning if `expo-updates` are installed as a dev dependency in `update` commands.
> [ENG-7183][eas-cli] validate that `expo-updates` are in project dependencies when somebody tries to run a build with channel set

- CHANGELOG.md
- packages/eas-cli/src/update/configure.ts
In `eas update:configure`, we are double quoting the `runtimeVersion` and printing it for each platform even if they are the same. Example:
```
✔ Configured runtimeVersion for Android with ""1.0.0""
✔ Configured runtimeVersion for iOS with ""1.0.0""
```
This PR fixes the double quote, and prints the platform runtimeVersion together if they are the same. Example:
if they are same:
```
✔ Configured runtimeVersion for Android and iOS with "1.0.0"
```
if they are different:
```
✔ Configured runtimeVersion for Android with "2.0.0"
✔ Configured runtimeVersion for iOS with "1.0.0"
```
> [eas-cli] better runtime output

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/errors.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1687487381876689
Improve error message
Test locally
> [eas-cli] print better error message when uploading the project archive tarball fails

- CHANGELOG.md
- packages/eas-cli/src/build/queries.ts
- packages/eas-cli/src/commands/build/run.ts
I love using `eas build:run` to quickly install a build on an emulator/ simulator, but found I had to go back to my project page to check the build ID, because I was occasionally building non-development builds for various test cases (especially when it comes to APK files), and I could't tell which one was which.
Adding build profile to the selected list item lets you match your build with something easily at-hand in your local dev environment (your **eas.json** file), so it's easy to tell if you're grabbing the latest development build, or a standalone internal test version, etc.
Added build profile to the list of data that shows when you arrow down to a build in the list.
Also slightly compressed the not-available warning based on available information..
> Show build profile on `eas build:run`

- packages/eas-cli/src/build/runBuildAndSubmit.ts
https://linear.app/expo/issue/ENG-9165/print-the-list-of-environment-variables-that-we-load-in-eas-cli-when
Print list of env vars we load in EAS CLI and which can be used when evaluating app config for a build.
**Note**: This log will be always printed not only when evaluating `app.config.js`.
> [ENG-9165][eas-cli] print the list of environment variables that we load in EAS CLI when evaluating app config for a build

- CHANGELOG.md
- packages/eas-cli/src/project/publish.ts
People on the bare workflow are running `eas update` with a runtimeVersion policy. When they receive our original error message, they don't know what to do. This PR changes the error message to be more actionable.
Fixes https://github.com/expo/eas-cli/issues/1689 and https://github.com/expo/eas-cli/issues/1899
> [eas-cli] better runtime version error for bare workflow

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/contextUtils/__tests__/getProjectIdAsync-test.ts
- packages/eas-cli/src/commands/build/configure.ts
- packages/eas-cli/src/commands/update/__tests__/configure.test.ts
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/configure.ts
- packages/eas-cli/src/project/expoConfig.ts
- packages/eas-cli/src/update/configure.ts
Why
---
Fail fast with a clear message if the app config contradicts itself or the developer's behavior.
How
---
Throw if useClassicUpdates is set in the app config and the developer is running an EAS Update-related command or if the app config uses an EAS Update URL.
Test Plan
---
Added a unit test for ensureEASUpdateIsConfiguredAsync
> [ENG-9093][eas-cli] Throw if useClassicUpdates is set when the developer is trying to use EAS Update

- CHANGELOG.md
- packages/eas-cli/src/build/__tests__/handleBuildRequestError-test.ts
- packages/eas-cli/src/build/android/build.ts
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/commandUtils/EasCommand.ts
- packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts
CombinedError technically can have more than 1 GraphQLError inside it, even though for now we only use it with 1. In such a case it would be good for the eas-cli to be able to handle and properly log/display all the multiple error messages
See: https://linear.app/expo/issue/ENG-8957/improve-error-handling-in-eas-cli-to-support-case-when-combined-error
CombinedError technically can have more than 1 GraphQLError inside it, even though for now we only use it with 1. In such a case it would be good for the eas-cli to be able to handle and properly log/display all the multiple error messages
Use all error messages from GraphQLErrors in the final message logged/displayed
Tested manually as well as added automated tests
> [eas-cli] [ENG-8957] Handle multiple GraphQLErrors in CombinedError

- CHANGELOG.md
- packages/eas-cli/src/build/__tests__/handleBuildRequestError-test.ts
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/errors.ts
- packages/eas-cli/src/graphql/client.ts
Adds support for a new class of server-side errors related to build limits for free accounts.
This uses existing support for server-side errors to render the error in the console:
> [eas-cli] Handle free user limit error messages

- CHANGELOG.md
- packages/eas-cli/src/update/configure.ts
There is a bug when printing out runtime versions:
When it is an object:
```
✔ Configured runtimeVersion for Android and iOS with "[object Object]"
```
When it is a string
```
✔ Configured runtimeVersion for Android and iOS with "1.0.0"
```
This PR checks if a runtimeVersion is an object or string, then formats it accordingly.
When it is an object:
```
✔ Configured runtimeVersion for Android and iOS with "{"policy":"sdkVersion"}"
```
When it is a string:
```
✔ Configured runtimeVersion for Android and iOS with "1.0.0"
```
> [eas-cli] fix runtime logs

- CHANGELOG.md
- packages/eas-cli/src/user/expoSsoLauncher.ts
Same as https://github.com/expo/expo/pull/23477 but for eas-cli. Closes ENG-8924.
> [eas-cli] Add styling to SSO auth redirect completion page

- CHANGELOG.md
- packages/eas-cli/src/project/ios/entitlements.ts
- packages/eas-cli/src/project/workflow.ts
Fixes ENG-8481
Supersedes #1852
This change depends on https://github.com/expo/expo/pull/23165, and uses the new `ignoreExistingNativeFiles` when using CNG/managed.
There are still a couple of things to do before we can merge this PR.
Optionally:
TBD
> [eas-cli] Ignore the existing entitlements when ios is gitignored

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
To prevent users from uploading too large projects.
https://exponent-internal.slack.com/archives/C017N0N99RA/p1688825990360349
Throw error when archive is over 2GB
1. Create large project
2. Try building it
> [ENG-9283][eas-cli] Throw error when project tarball exceeds 1GB

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/EasCommand.ts
This is very useful when build credentials fails, in case user doesn't have permissions. See https://github.com/expo/expo/issues/22696
Honestly, I didn't make any tests, except static analysis, as I'm still new to this project, I don't know how I can reproduce [the issue](https://github.com/expo/expo/issues/22696) in my local machine, so please analyse it with me and tell me whether this change is valid, or tell me how to test that out in my local machine where my app is (if it's absolutely required);
I'm very happy to find such opportunity to contribute in Expo
thank you
> [Build] Print friendly error msg in case account doesn't have required permission

- CHANGELOG.md
- packages/eas-cli/src/submit/android/AndroidSubmitCommand.ts
- packages/eas-cli/src/submit/android/__tests__/AndroidSubmitCommand-test.ts
- packages/eas-cli/src/utils/expodash/__tests__/capitalize-test.ts
- packages/eas-cli/src/utils/expodash/capitalize.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1689605257077099
Previously the `capitalize` function made the first letter upper case and other letters of the string lower case. So if we run `capitalize('inProgress')` we will get `'Inprogress'`.
This is the code that checks if the release status is supported
https://github.com/expo/eas-cli/blob/57dd372957d5f18da232c3efca5716a691e1f903/packages/eas-cli/src/submit/android/AndroidSubmitCommand.ts#L97-L112
https://github.com/expo/eas-cli/blob/57dd372957d5f18da232c3efca5716a691e1f903/packages/eas-cli/src/graphql/generated.ts#L4618-L4623
As you can see `'Inprogress'` is not a key of the `SubmissionAndroidReleaseStatus` enum, therefore the error will be thrown, which is incorrect behavior because it is a valid option.
Change the …
> [eas-cli] fix incorrect handling of valid `inProgress` release status

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/errors.ts
- packages/eas-json/schema/eas.schema.json
https://exponent-internal.slack.com/archives/C02123T524U/p1689800401918099
Companion to https://github.com/expo/universe/pull/12949
Handle the `EAS_BUILD_LEGACY_RESOURCE_CLASS_NOT_AVAILABLE` error as server-side defined error.
Remove the `intel-medium` option from `eas.schema.json` to not suggest using it in our VSCode plugin.
After:
Before:
> [eas-cli] handle server side defined error for situation when `intel-medium` is not available and remove `intel-medium` for `eas.schema.json`

- CHANGELOG.md
- packages/eas-cli/src/channel/queries.ts
- packages/eas-cli/src/utils/__tests__/relay-test.ts
- packages/eas-cli/src/utils/relay.ts
A utility function to fetch a complete dataset from a Relay compliant endpoint in a batched way. See a concrete usage of it in `getChannelsDatasetAsync`.
> [eas-cli] fetch entire relay compliant dataset

- CHANGELOG.md
- packages/eas-cli/src/channel/__tests__/fixtures.ts
- packages/eas-cli/src/channel/actions/SelectChannel.ts
- packages/eas-cli/src/channel/actions/__tests__/SelectChannel-test.ts
- packages/eas-cli/src/eas-update/__tests__/fixtures.ts
- packages/eas-cli/src/eas-update/utils.ts
- packages/eas-cli/src/rollout/__tests__/branch-mapping-test.ts
- packages/eas-cli/src/rollout/__tests__/fixtures.ts
- packages/eas-cli/src/rollout/actions/SelectRollout.ts
- packages/eas-cli/src/rollout/actions/__tests__/SelectRollout-test.ts
This PR does the following:
- Defines our `Action` model in the `eas-update` folder.  Every action implements the `EASUpdateAction` interface. This  allows us to build our commands with these modular Actions.
- Makes utility classes to select existing channels and rollouts. `SelectChannel` and `SelectRollout` are a concrete example of these Actions
> [eas-cli] select existing rollouts and channels

- CHANGELOG.md
- packages/eas-cli/src/build/android/build.ts
https://linear.app/expo/issue/ENG-9482/implement-utilsinject-android-credentials
Provide credentials for custom Android builds
Tests
> [ENG-9482][eas-cli] provide credentials for custom Android builds

- CHANGELOG.md
- packages/eas-cli/src/update/__tests__/configure-test.ts
- packages/eas-cli/src/update/configure.ts
Whenever someone tries to setup EAS Update, we used to default them to the `sdkVersion` runtime policy because Expo Go for 48 and below would not load any other policy. However, we've changed this in 49 and we can now switch folks over to the more expressive `appVersion`. 
Detect if someone is setting up EAS Update on sdk 49.0.0 or higher. If they are, default them to `appVersion` runtime policy.
> [ENG-8616][eas-cli] change update default runtime policy

- CHANGELOG.md
- packages/eas-cli/src/commands/update/republish.ts
- packages/eas-cli/src/update/republish.ts
`update:republish` is broken, and as of https://github.com/expo/eas-cli/commit/8d57828f7e40c0be2ef6de74ee92857a3ceb9db9 it throws. I added some assertions to `republishAsync` that uncovered the bug where we were confusing `update.id` with its group ID (`update.group`).
Use the correct group and rename some variables to make code clearer
> [eas-cli] fix update:republish group id

- CHANGELOG.md
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/version/get.ts
- packages/eas-cli/src/commands/build/version/sync.ts
- packages/eas-cli/src/commands/metadata/lint.ts
- packages/eas-cli/src/commands/metadata/pull.ts
- packages/eas-cli/src/commands/metadata/push.ts
- packages/eas-cli/src/commands/submit.ts
- packages/eas-cli/src/utils/__tests__/profiles-test.ts
- packages/eas-cli/src/utils/profiles.ts
https://github.com/expo/eas-cli/issues/1975
Revert https://github.com/expo/eas-cli/pull/1954
Tests
Run build locally and see that we don't read `.nvmrc`
> Revert "[ENG-9422][eas-cli] Use .nvmrc to set node version (#1954)"

- CHANGELOG.md
- packages/eas-cli/src/commands/channel/rollout-preview.ts
Add cli flag relationships for rollouts. Followup from https://github.com/expo/eas-cli/pull/1966#discussion_r1281179912
Specify relationships when the user is running in `non-interactive` mode, since any other missing flags in interactive mode can be selected for by the user
> [eas-cli] rollout relationships

- CHANGELOG.md
- packages/eas-cli/src/commands/update/__tests__/republish.test.ts
- packages/eas-cli/src/commands/update/republish.ts
- packages/eas-cli/src/update/republish.ts
This fixes the following issue:
- A republished update will have the same manifest info group but different generated metadata from the server (different groupId and potentially different branch name).
- Previously, this was using the same signature, but for the different blob. Therefore it would fail.
Closes ENG-9596.
This fixes it by requiring providing the private key to republish when code signing is involved.
1. Set up code signing: https://docs.expo.dev/eas-update/code-signing/
1. `eas update`, see it is signed
1. `eas update:republish`, see it signs correctly now
> [eas-cli] Fix republishing with code signing

- CHANGELOG.md
- packages/eas-cli/src/channel/__tests__/branch-mapping-test.ts
- packages/eas-cli/src/channel/branch-mapping.ts
- packages/eas-cli/src/channel/print-utils.ts
- packages/eas-cli/src/channel/queries.ts
- packages/eas-cli/src/channel/utils.ts
- packages/eas-cli/src/commands/channel/edit.ts
Fix these commands to play nice with `channel:rollout` and `channel:rollout-preview`:
- channel:view
- channel:list
- channel:edit
- channel:rollout
use the new rollout branch-mapping primitives to detect if there is a rollout
> [ENG-8715][eas-cli] get channel:{view,list,edit} to play nice with rollouts

- CHANGELOG.md
- packages/eas-cli/src/commands/channel/rollout-preview.ts
- packages/eas-cli/src/commands/channel/rollout.ts
- packages/eas-cli/src/rollout/actions/CreateRollout.ts
- packages/eas-cli/src/rollout/actions/RolloutMainMenu.ts
> [eas-cli] use 'roll out' instead of rollout for verbs

- CHANGELOG.md
- packages/eas-cli/src/rollout/actions/EditRollout.ts
warn the user if they edit their rollout to 0 or 100 that it wont end the rollout. They'll need to end the rollout from the main menu
> [ENG-9603][eas-cli] rollout edit edge case

- CHANGELOG.md
- packages/eas-cli/src/rollout/branch-mapping.ts
If someone has a rollout of 7%, we store it as 0.07. However, in javascript, when you perform 0.07 * 100 it yields 7.000000000000001 due to floating point precision issues. This is problematic when we display the rollout to users. To fix this, when converting a decimal to a whole number, we can run `Math.round` to round it to the nearest integer
> [eas-ci] rollouts: fix fp precision

- CHANGELOG.md
- packages/eas-cli/src/branch/actions/__tests__/SelectBranch-test.ts
- packages/eas-cli/src/channel/actions/__tests__/SelectChannel-test.ts
- packages/eas-cli/src/rollout/actions/CreateRollout.ts
- packages/eas-cli/src/rollout/actions/EndRollout.ts
- packages/eas-cli/src/rollout/actions/RolloutMainMenu.ts
- packages/eas-cli/src/rollout/actions/SelectRuntime.ts
- packages/eas-cli/src/rollout/actions/__tests__/SelectRollout-test.ts
- packages/eas-cli/src/utils/__tests__/relay-test.ts
- packages/eas-cli/src/utils/relay.ts
UX improvements from dogfooding feedback:
- Better runtime selection: remove the option to manually input a runtime in the case where there is no shared runtime on the two rollout branches. Instead, let the user choose a runtime from an existing branch or use the runtime specified in their project config.
- Remove automatic selection if only 1 is available: Automatic selection in this case is the most 'efficient' but causes confusion without human prompting. For example, when determining a channel or branch for a rollout, the selectors used to return the only eligible item without prompting, but this ended up causing confusion. This PR changes the selectors to always require human interaction to select an option (even if there is only 1 available). 
- Print better logs if no eligible …
> [ENG-9614][eas-cli] rollout ux improvements

- CHANGELOG.md
- packages/eas-cli/src/channel/__tests__/branch-mapping-test.ts
- packages/eas-cli/src/channel/branch-mapping.ts
- packages/eas-cli/src/channel/print-utils.ts
- packages/eas-cli/src/commands/channel/edit.ts
- packages/eas-cli/src/rollout/__tests__/fixtures.ts
- packages/eas-cli/src/rollout/actions/CreateRollout.ts
Account for empty branch mappings in `eas channel:*` workflows. Users should be able to view and edit channels linked to no branches.
> [eas-cli] account for empty branch mapping

- CHANGELOG.md
- packages/eas-cli/src/build/ios/credentials.ts
Pass iOS credentials to custom builds
Pass iOS credentials to custom builds
> [eas-cli] pass iOS credentials to custom builds

- CHANGELOG.md
- packages/eas-cli/src/build/ios/credentials.ts
- packages/eas-json/schema/eas.schema.json
- packages/eas-json/src/__tests__/buildProfiles-test.ts
- packages/eas-json/src/build/schema.ts
- packages/eas-json/src/build/types.ts
Add global `withoutCredentials` property to `eas.json` (it currently only exists for Android). We discussed it with Brent and decided that it would be handy for custom builds.
Add global `withoutCredentials` property to `eas.json`
Add automated tests
> [eas-json][eas-cli] add global `withoutCredentials` property to `eas.json`

- CHANGELOG.md
- packages/eas-cli/src/commands/channel/rollout.ts
small nit in developer preview logger to say website support is coming soon for rollouts
> [eas-cli] rollouts websupport

- CHANGELOG.md
- packages/eas-cli/src/channel/__tests__/branch-mapping-fixtures.ts
- packages/eas-cli/src/channel/__tests__/branch-mapping-test.ts
- packages/eas-cli/src/channel/__tests__/utils-test.ts
- packages/eas-cli/src/channel/branch-mapping.ts
- packages/eas-cli/src/channel/utils.ts
- packages/eas-cli/src/rollout/__tests__/branch-mapping-test.ts
- packages/eas-cli/src/rollout/actions/EndRollout.ts
- packages/eas-cli/src/rollout/branch-mapping.ts
- packages/eas-cli/src/rollout/utils.ts
Eventually we will want to move the branch mapping utility functions into their own library. This PR does the following:
- removes dependencies on graphql types so it can be used in other repo's
- replaces the test fixtures used so it doesnt use graphql types, and can be used in other repo's
> [eas-cli] make branch mapping utility files have no dependencies

- CHANGELOG.md
- packages/eas-cli/src/rollout/__tests__/branch-mapping-test.ts
- packages/eas-cli/src/rollout/branch-mapping.ts
extra utility function for branch mapping
> [eas-cli] more branch map utility functions

- CHANGELOG.md
- packages/eas-cli/src/commands/update/__tests__/republish.test.ts
- packages/eas-cli/src/commands/update/republish.ts
- packages/eas-cli/src/commands/update/rollback.ts
As requested by @jonsamp:
> i would love (love!) if this command were the same command as rollback/revert/republish, such that you could “go back” to any state that your app has been in.
the naming is hard because taking the embedded update and making it active again is not the same as re publishing an actual update.
> 
> but thinking as a developer (introspecting), i don’t think id care that much. i think id care a lot more that i knew a command that worked in all situations rather than using republish all the time then having it not work when trying to re-publish an embedded update, only to then be confused and thinking “what, why can’t I??”
> 
> TLDR:
>  - i would love one command to rule them all
>  - if we need two commands, then we need a message when trying the wrong commands with …
> [eas-cli][eas-update] Add rollback disambiguation command

- CHANGELOG.md
- packages/eas-cli/src/update/republish.ts
Accidentally merged https://github.com/expo/eas-cli/pull/2005 into its parent PR rather than waiting for it to land and rebasing on main. This rebases on main and lands there.
> [eas-cli][eas-update] Support republishing roll back to embedded updates

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/log.ts
- packages/eas-cli/src/project/publish.ts
This shows the number of assets in a published update along with info about the limit to help developers be aware of the limits.
Depends on https://github.com/expo/fyi/pull/128.
Closes ENG-9806.
Add message.
```
$ neas update
✔ Which branch would you like to use? › main - current update: "Initial commit
Generated by create-expo-app 2.0.3." (1 minute ago by willtestssouser1)
✔ Provide an update message: … Initial commit
Generated by create-expo-app 2.0.3.
[expo-cli] Starting Metro Bundler
[expo-cli]
[expo-cli] iOS Bundling complete 4213ms
[expo-cli]
[expo-cli] Android Bundling complete 4217ms
[expo-cli] iOS Building Hermes bytecode for the bundle
[expo-cli] Android Building Hermes bytecode for the bundle
[expo-cli]
[expo-cli]
[expo-cli] Bundle                      Size
[expo-cli] ┌ …
```
> [eas-cli] Add info to EAS Update asset upload process about asset counts and limits

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/build/context.ts
- packages/eas-cli/src/build/createContext.ts
- packages/eas-cli/src/build/metadata.ts
- packages/eas-json/package.json
- yarn.lock
Add `developmentClient` to metadata. Companion to https://github.com/expo/universe/pull/13215.
Add `developmentClient` to metadata.
Test manually
> [eas-cli][eas-json] add `developmentClient` to metadata

- CHANGELOG.md
- packages/eas-cli/src/build/runBuildAndSubmit.ts
https://github.com/expo/eas-cli/pull/1885 added code to auto-install expo-updates when channel was set in eas.json. But just installing expo-updates isn't sufficient, and actually when it is installed but not configured it crashes upon startup (separate issue, maybe).
Also make it configure EAS update.
The problem here is that when EAS update is configured, it mutates the ExpoConfig on dis, making the ExpoConfig in the build context in memory stale. The only way to resolve this is to either: a) reload the config (which is prone to bugs), or b) ask the user to run the command again. I went with B.
```
yarn create expo-app testjadskjhadshjkads
export EXPO_STAGING=1
eas init
eas build:configure
```
Add channel to `eas.json`:
```
...
"build": {
"development": {
"developmentClient": true, …
```
> [eas-cli][updates] configure updates as well when somebody tries to run a build with channel set

- CHANGELOG.md
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/channel/queries.ts
- packages/eas-cli/src/commands/channel/create.ts
If someone performs a build, uses `expo-updates`, EAS Update, and they declare a channel in their build profile, check if the channel exists. If it doesnt, create one and link it to a branch of the same name. This flow is shared with `eas channel:create`.
Creating new channel
```
MacBook-Pro:build-test quin$ eas-dev build
✔ Select platform › All
Loaded "env" configuration for the "production" profile: no environment variables specified. Learn more: https://docs.expo.dev/build-reference/variables/
🤖 Android build
✔ Created a new channel on project @quintest113/build-test
Name  production
ID    d6562f1a-7fcd-4928-8ddc-0d506469ca40
✔ We also went ahead and made a branch with the same name and have pointed the channel at it.
Name  production
ID    4bb470a3-d54a-4932-982e-ddb33535bb7a
✔ Using …
```
> [ENG-9685][eas-cli] create a linked channel on build if not exists

- CHANGELOG.md
- packages/eas-cli/src/project/publish.ts
I believe that https://github.com/expo/eas-cli/pull/2002/files introduced this regression. If the `platform` argument for the `eas update` command is specified it currently calls expo cli like
```
expo-cli ... platform
```
instead of
```
expo-cli ... --platform platform
```
what seems to cause this error.
If the `platform` argument is specified for the `eas update` command, pass it to `expo-cli` like `--platform platform`.
Test manually
> [eas-cli] fix `eas update` passing `platform` argument incorrectly to `expo-cli`

- CHANGELOG.md
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/utils/expoCli.ts
Fixes ENG-9308
> This PR assumes that https://github.com/expo/expo/pull/23621 is going to be merged and released.
- Added warning when users create EAS update bundles with `expo.web.bundler = "metro"`
- Added version detection to use the new variadic `--platform` flag
- Added explicit `expo export --platform android --platform ios` flags when creating EAS update bundles
- `$ yarn create expo ./test-updates -t tabs@49` (comes with Metro web)
- `$ cd ./test-updates`
- `$ eas update`
→ should create exports for `android` and `ios`, **_not_** `web`
> fix(eas-cli): implement variadic `--platform` flag when creating EAS updates

- CHANGELOG.md
- packages/eas-cli/src/channel/__tests__/print-utils-test.ts
- packages/eas-cli/src/channel/print-utils.ts
Our `channel:list` and `channel:view` commands have a bug, where if a channel has a branch, but the branch has no updates, we print `There are no branches`. This is not true, so I have refactored and fixed the printing function to do the following:
- print the branch, but dont display updates if there are none
- dont throw on unsupported mappings, just print 'custom mapping detected'
- the print function assumes that the Channel object passed to it has at most one Update group (the function still works if there are multiple, but the log output isn't coherent). Refactor the function to only print the latest Update group if it exists, and make a docblock describing the behaviour.
```
MacBook-Pro:test101-staging quin$ EXPO_STAGING=1 eas-dev channel:list
Channel:
Name  custom-mapping-channel …
```
> [eas-cli] fix printing bug: branch with no update

- CHANGELOG.md
- packages/eas-cli/src/credentials/android/actions/BuildCredentialsUtils.ts
- packages/eas-cli/src/credentials/errors.ts
- packages/eas-cli/src/credentials/manager/ManageAndroid.ts
- packages/eas-cli/src/credentials/manager/__tests__/ManageAndroid-test.ts
https://linear.app/expo/issue/ENG-7536/make-app-config-error-on-credentials-command-not-repeat-indefinitely
If app config error is thrown it is re-thrown with modified message instead of printing it to the as a "cryptic error" and repeating with 0% chances of success (since the config is incorrect)
Added automated test
Tested manually:
The link from the message leads to the docs:
> [eas-cli] [ENG-7536] Stop app config error repeating

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
When someone runs `eas update` to publish an update to a branch (let's call it Branch X for our example), we always print `Channel X points to Branch X`. However, this is not always true. 
I suspect the statement was meant to be put in the adjacent `if` clause, so I've moved it there.
In the event where Branch X does not exist, we create it. Then, we also create a channel with the same name (X). If Channel X can be created, we link it to Branch X. In the case we can create Channel X, then the statement `Channel X points to Branch X` will always be true.
> [eas-cli] only print channel-branch pairing if we created a channel

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/update/__tests__/getBranchNameFromChannelNameAsync-test.ts
- packages/eas-cli/src/utils/statuspageService.ts
Running `yarn generate-graphql-code` pulls a bunch of updated graphql type definitions that conflict with what we expect in `eas-cli` and leads to the `tsc` typechecker failing.
Fix the typecheck errors
> [eas-cli] fix graphql

- CHANGELOG.md
- packages/eas-cli/src/rollout/actions/NonInteractiveRollout.ts
The `codeSigningInfo` option doesn't appear to be reachable. Code signing info looks like it's populated with the `privateKeyPath` option [here](https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/commands/channel/rollout.ts#L184) instead
> [eas-cli] remove unreachable codesigning option

- CHANGELOG.md
- packages/eas-cli/src/commands/channel/rollout.ts
- packages/eas-cli/src/rollout/actions/ManageRollout.ts
- packages/eas-cli/src/rollout/actions/NonInteractiveRollout.ts
- packages/eas-cli/src/rollout/actions/RolloutMainMenu.ts
Support CI better by adding a 'view' action to print rollout details
> [ENG-9828][eas-cli] rollouts: view action for CI

- CHANGELOG.md
- packages/eas-cli/src/rollout/utils.ts
More robust printing function for rollouts
> [eas-cli] rollouts: more robust printing function

- packages/eas-cli/src/project/ios/bundleIdentifier.ts
https://linear.app/expo/issue/ENG-5266/eas-build-doesnt-use-the-bot-name-to-suggest-bundle-identifier
Added special case in `getSuggestedBundleIdentifierAsync`
> [ENG-5266] Suggest correct bundleId when account name not available

- CHANGELOG.md
- packages/eas-cli/src/utils/profiles.ts
https://github.com/expo/eas-cli/issues/1975#issuecomment-1702986526
Node version can be specified as an alias (such as `iojs`, `lts/hydrogen` etc), so validating it as semver may cause errors for some users.
Remove validation
Specify node version in `.nvmrc` as something like `lts/gallium` and run build.
> [FIX] Remove semver validation from node version read from .nvmrc

- CHANGELOG.md
- packages/eas-json/schema/eas.schema.json
We've added a new `macos-ventura-13.6-xcode-15.0` image. It's also a good opportunity to clean up a bit by deprecating some images and deleting images only available for Intel workers which we will delete soon (29th September).
Updated `eas.schema.json`. Use @byCedric suggestion to mark some images as deprecated by using the new syntax.
> [ENG-10176][eas-json] update images info in `eas.schema.json`

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts
- yarn.lock
Seems like it's missing - but not sure if that was intentional or there's any other hindrance to it? 
Add the entitlement object exactly like the others. It doesn't seem like there's anything else to do? 
@EvanBacon It seems `@expo/apple-utils` is a private package, so I cannot contribute a change to add a `TAP_TO_PAY_ON_IPHONE` constant for the `CapabilityType` - for now I just force casted this to keep TS happy. 
Thoughts?
> feat: add tap to pay on iphone entitlement

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/package.json
- packages/eas-cli/src/build/context.ts
- packages/eas-cli/src/build/createContext.ts
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/graphql/generated.ts
- yarn.lock
We want to know what the user's package manager is going to be at the "install custom tools" step of the build process, so we're determining it based on the user's lockfiles and adding it to build metadata.
1. `eas-build-job` https://github.com/expo/eas-build/pull/281
2. `www` https://github.com/expo/universe/pull/13522
3. 👉 `eas-cli` https://github.com/expo/eas-cli/pull/2067
4. `turtle-v2` https://github.com/expo/turtle-v2/pull/1460
Added the field.
Unit tests and building locally.
> [eas-cli] [ENG-10225] add requiredPackageManager to build metadata

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/__tests__/publish-test.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/uploads.ts
For slow connections that take a while to upload, 60s is not enough of a timeout. For example, lets say there's only one asset to upload, and it takes even 1 second to upload and 60s to process (the max of the cloud function), it'll time out. The p99 of the processing cloud function is 29s, so changing this timeout to 90s gives a upload timeout of 60s.
We also change the semantics of when to reset the timeout, and now reset it when the upload is retried. So, in the example above, let's say the asset takes 59 seconds to upload, but fails at the 58th second, it will be retried and the timeout will reset to give it an additional 60 seconds to upload.
This is tough to test. Would need to simulate a super slow connection and some failures.
Tested manually by uploading 5k assets (1 failed …
> [eas-update] Increase asset upload timeout to 90s and reset on upload retry for slow connections

- .github/workflows/changelog-bot.yml
`hub` was removed: https://github.com/mislav/hub/issues/3338
our action is failing: https://github.com/expo/eas-cli/actions/runs/6565215869
Use `gh` CLI instead.
It is preinstalled so it should be good to go.
> [ci] Try to fix changelog-bot usage of hub CLI

- CHANGELOG.md
- packages/eas-cli/src/commands/update/__tests__/roll-back-to-embedded.test.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/commands/update/rollback.ts
- packages/eas-cli/src/project/__tests__/projectUtils.test.ts
- packages/eas-cli/src/project/projectUtils.ts
This feature wasn't officially added and tested until 0.19.0. It still hasn't been fully dogfooded or documented, but should theoretically be ready to release as of 0.19.0.
We can always change this in the future to something higher if we find bugs.
Add condition to running the command and also release commands publicly.
Run new tests.
> [expo-updates] Gate roll back to embedded to expo-updates >= 0.19.0

- .github/workflows/release.yml
https://github.com/expo/eas-cli/actions/runs/6638762355/job/18036077524
Similar to https://github.com/expo/eas-cli/pull/2095
Use `gh` instead of `hub`
> [ci] fix `release-changelog` workflow

- CHANGELOG.md
- packages/eas-cli/src/commands/submit.ts
- packages/eas-cli/src/submit/__tests__/commons-test.ts
- packages/eas-cli/src/submit/android/AndroidSubmitCommand.ts
- packages/eas-cli/src/submit/android/AndroidSubmitter.ts
- packages/eas-cli/src/submit/android/__tests__/AndroidSubmitCommand-test.ts
- packages/eas-cli/src/submit/commons.ts
- packages/eas-cli/src/submit/context.ts
- packages/eas-cli/src/submit/ios/IosSubmitCommand.ts
- packages/eas-cli/src/submit/ios/IosSubmitter.ts
- packages/eas-cli/src/submit/ios/__tests__/IosSubmitCommand-test.ts
https://linear.app/expo/issue/ENG-8973/eas-submit-doesnt-use-asc-configuration-from-selected-build-profile
Moved the archive selection before any submit options are determined, and if the archive is selected from EAS then the profile in the submission context is refreshed to use the submit profile with same name as the name of the build profile in the archive (if exists)
Added automated tests and checked parts of the process manually
When corresponding build profile does not exist
> [eas-cli] [ENG-8973] Use selected builds profile name if not specified

- CHANGELOG.md
- packages/eas-cli/src/project/projectUtils.ts
See https://github.com/expo/expo/pull/25146 for context. We want to link to that page to instruct people how to upgrade in order to get this feature. Note that it is still in alpha.
Add link.
> [eas-cli] Add link to SDK upgrade page for SDK-gated command error

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/package.json
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-json/package.json
- yarn.lock
To accomplish https://linear.app/expo/issue/ENG-10566/create-a-banner-that-links-people-to-changelog-on-build-details-pages www needs to know which image was selected by the user to run the build on and if custom node version was selected.
Companion to https://github.com/expo/universe/pull/13889
Add the `selectedImage` and `customNodeVersion` field to the build's metadata
After https://github.com/expo/universe/pull/13889 is merged and I regenerate GQL schema test manually
> [ENG-10566][eas-cli] add `selectedImage` and `customNodeVersion` to build metadata

- CHANGELOG.md
- packages/eas-cli/src/commands/channel/rollout.ts
Move the rollout out of developer preview, cleanup warning logs
> [eas-cli] move rollouts out of dev preview

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
https://exponent-internal.slack.com/archives/C02123T524U/p1699579569626249
Update `@expo/package-manager` to `1.1.2` so in the manager resolution order `bun` is before `yarn`
Run build maunally
> [eas-cli] update `@expo/package-manager` to `1.1.2`

- CHANGELOG.md
- packages/eas-cli/src/commands/channel/rollout.ts
- packages/eas-cli/src/credentials/ios/actions/SetUpAdhocProvisioningProfile.ts
- packages/eas-cli/src/credentials/ios/actions/__tests__/SetUpAdhocProvisioningProfile-test.ts
https://linear.app/expo/issue/ENG-10555/ios-devices-get-stuck-in-failed-to-provision-state-until-the-developer
https://www.reddit.com/r/expo/comments/17kr7rr/failed_to_provision/?sort=new
The problem happened when the provisioning profile already existed and the user wanted to add new devices to it. In such a case, a missing device was added to the Apple Developer Portal if needed, but the provisioning profile from EAS was used unchanged. This meant that no matter what the devices list in the provisioning profile used was the same as before and thus resulted in a warning message and a failure.
Now another check has been added, if the id of the profile from EAS matches the one from Apple the list of devices is compared. If it's the same then the profile is reused as before. If the list is …
> [eas-cli] [ENG-10555] Fix device provsioning

- CHANGELOG.md
- packages/eas-cli/src/commands/build/run.ts
https://linear.app/expo/issue/ENG-9927/add-support-for-e-profile-to-eas-buildrun
Add `--profile` flag. If the `--profile` flag is present filter using it. 
> [ENG-9927][eas-cli] add `profile` flag to `eas build:run` command

- CHANGELOG.md
- packages/eas-cli/src/build/utils/devClient.ts
https://linear.app/expo/issue/ENG-9772/prevent-interactive-cli-commands-in-build-configuration-step
We don't want to prompt users to install the dev client in non-interactive mode.
Instead of displaying the confirm prompt in non-interactive mode fail with a helpful error message.
Test locally
> [ENG-9772][eas-cli] don't ask user to install dev client if running in non-interactive mode

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/actions/SetUpAdhocProvisioningProfile.ts
- packages/eas-cli/src/credentials/ios/actions/__tests__/SetUpAdhocProvisioningProfile-test.ts
https://exponent-internal.slack.com/archives/C9PRD479V/p1700236895524379
https://exponent-internal.slack.com/archives/C9PRD479V/p1700229660146479
There are other cases when the provisioning profile needs to be refreshed before use and which cannot be easily validated at runtime without bigger changes in the code. It is simpler (at least for the time being) to just refresh existing profile each time
Run automated tests
> [eas-cli] Always refresh provisioning profile

- CHANGELOG.md
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/project/customBuildConfig.ts
If you create a custom build with git ignored config file build on a server will fail even though local validation passed. 
Use the VCS client to check if the file is ignored. Throw an error if it is.
Test locally. Git ignore the config. Make sure the build runs fine without git ignored config.
> [ENG-10464][eas-cli] throw error if custom build config is gitignored

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
bump @expo/steps version
bump @expo/steps version
> [eas-cli] bump @expo/steps version

- CHANGELOG.md
- packages/eas-json/schema/eas.schema.json
We migrated our ubuntu 18 images to ubuntu 20
Update `eas.schema.json`
> [eas-json] move ubuntu 18 images to ubuntu 20

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/build/graphql.ts
- packages/eas-cli/src/build/metadata.ts
- packages/eas-json/package.json
- yarn.lock
We use two build modes meaning the same thing. In https://github.com/expo/universe/pull/14035 I'm merging them into the single `job.mode`.
Updated `eas-build-job` which already removed `buildMode` from metadata. Then adjusted code so it:
- does not send `buildMode` in metadata
- transforms internal `buildMode` to the GraphQL `BuildMode`.
In a test project, triggered:
- [a custom build](https://staging.expo.dev/accounts/sjchmiela/projects/staging-app/builds/3abbbe06-7e64-449c-9fa3-05a4b14652f5) with `EXPO_STAGING=1 easd build -p ios -e demo`
- [a regular build](https://staging.expo.dev/accounts/sjchmiela/projects/staging-app/builds/15dc26e2-3e89-486d-be32-8ee12d81693d) with `EXPO_STAGING=1 easd build -p ios -e simulator`
they both ran as expected.
> [eas-cli] Pass build mode only in `job`

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/commands/update/view.ts
- packages/eas-cli/src/update/utils.ts
Rename `getUpdateGroupJsonInfo` because it is not correct. 
The output of the our `publishUpdateGroups` mutation (which can publish multiple update groups) is an array of updates, belonging to 1 or more groups. With the outputted `Update[]`, we generate some json info with `getUpdateGroupJsonInfo`
> [0/1][eas-cli] rename getUpdateGroupJsonInfo

- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/publish.ts
When we publish an update, a `metadata.json` file gets generated in the `dist` folder. This PR patches the `metadata.json` with some `eas` metadata. 
It would be nice to have this for sentry-expo integration. While it is possible for users to specify the `json` flag for the update command to output the same information, it will be nicer if we can tell people to just run `eas update` and then run another script that will read from the `metadata.json` file
manually tested
> [1/1][eas-cli] generate eas-update-metadata.json  on publish

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/vcs/clients/git.ts
- packages/eas-cli/src/vcs/clients/noVcs.ts
- packages/eas-cli/src/vcs/vcs.ts
This was requested for cases where there isn't a VCS and also no update message is manually supplied.
Closes ENG-9633.
It is already optional in the GraphQL mutation, so this is just a product decision that we need to deliberately make.
I think it's worth having a discussion on the UX benefits/costs of this product decision. This PR is meant to just start the discussion, not convey a strong intent to make the change as I'm probably oblivious to potential downsides.
Create an update and don't specify message.
> [eas-cli][eas-update] Allow undefined update message

- .github/workflows/changelog.yml
- .github/workflows/size.yml
- .github/workflows/test-scripts.yml
- .github/workflows/test.yml
I've noticed tests ran for an old commit even though I pushed a new one.
Added `concurrency` where I thought it was applicable.
None.
> [ci] Cancel in progress jobs when new are run

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/build/graphql.ts
- packages/eas-json/package.json
- yarn.lock
x-ref https://github.com/expo/eas-build/pull/302
Upgraded `@expo/eas-build-job` and fixed the only TS error.
None.
> Remove S3 archive support

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/actions/SetUpAdhocProvisioningProfile.ts
- packages/eas-cli/src/credentials/ios/actions/__tests__/SetUpAdhocProvisioningProfile-test.ts
https://linear.app/expo/issue/ENG-11090/prompt-user-whether-they-want-to-continue-if-we-fail-to-provision
Prompt users if they want to continue if we fail to provision the devices
(Yeah I know it says 0, I commented out the if statement to test it)
> [ENG-11090][eas-cli] prompt users if they want to continue if provisioning the devices fails

- CHANGELOG.md
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/project/projectUtils.ts
As of SDK 50, classic updates is no longer supported. So builds should no longer configure a classic release channel and should instead configure nothing even when "releaseChannel" is set in eas.json for expo-updates.
Related: https://github.com/expo/eas-build/pull/319
Closes ENG-11121.
Check expo-updates version and prevent setting releaseChannel in build job metadata if expo-updates package version >= 0.19.0.
`neas build`, click URL, no longer see releaseChannel set in metadata in resulting build
> [eas-cli] Remove support for classic updates release channel in 50+

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
When the `requireCommit` preference has been set in eas.json (`cli` section), the `eas update` command should read and respect that preference.
Closes ENG-11110.
Apply same function calls as build/submit.
1. Add `requireCommit: true` to eas.json cli section
2. 
```
$ neas update
Warning! Your repository working tree is dirty.
This operation needs to be run on a clean working tree. Commit all your changes before proceeding.
✖ Commit changes to git? … yes
```
> [eas-cli] Support requireCommit for EAS Update

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/actions/CreateAscApiKey.ts
https://linear.app/expo/issue/ENG-11247/fix-console-output-when-creating-asc-key
Information about App Store Connect API key being created was displayed twice to the user. This removes the duplicate
> [eas-cli] [ENG-11247] Remove duplicate log

- .github/workflows/release.yml
- RELEASING.md
https://exponent-internal.slack.com/archives/CRM0Y8JLU/p1706823546329859?thread_ts=1706822844.405259&cid=CRM0Y8JLU
It's super easy to forget about it and prod version is getting out of sync
Bump the `latest-eas-build` tag (the tag determining which EAS CLI version used for GH builds on prod) automatically after publishing the release
> [ci] auto update EAS CLI version used on production for builds triggered using GitHub trigger

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/publish.ts
This reverts commit 8751a2835f38e4be5079c7f2ffe7129f9a060301.
The reason we're reverting this is that it is causing some confusion around whether dev bundles work with EAS update. The answer is that they probably shouldn't, or at least aren't officially supported.
> "Dev" bundles are quite different from production bundles (no minification, possibly different Babel presets running, different NODE_ENV is set, and `__DEV__` value is different). The value of `__DEV__` is used in many places to change behavior to fit a development environment, for example in [expo-asset](https://github.com/expo/expo/blob/dd5f37fc1a8df22b7ae1da98b085b9c5ad06dcd1/packages/expo-asset/src/AssetSourceResolver.ts#L13-L23). If we want to support loading updates that are published in dev mode, we should ensure we …
> Revert "feat(eas-cli): expose expo export dev flag as an option in eas update (#2050)"

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/utils/expoUpdatesCli.ts
Successor to https://github.com/expo/eas-cli/pull/2225 (previous attempt at this).
This PR calls in to the new `expo-updates` CLI command to generate the fingerprint: https://github.com/expo/expo/pull/27119. This ensures that the version of the fingerprint package being used is consistent between builds and this `eas update` command when calculating the runtime version.
In test bare app in expo/expo repo with all the modules installed locally (checked out to https://github.com/expo/expo/pull/27119), run `neas update -p ios` and ensure the fingerprint matches.
Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your …
> [eas-cli] fix expo-updates fingerprinting during update

- CHANGELOG.md
- packages/eas-cli/src/commands/project/init.ts
https://linear.app/expo/issue/ENG-11310/fix-warnings-errors-that-come-up-when-adding-eas-to-a-react-native-cli
When Expo config error is thrown while initiating a project only a warning message is printed instead of throwing an error and failing the command
All tests pass
`eas init`
`eas init`
`eas build -p ios --auto-submit`
> [eas-cli] [ENG-11310] Don't require expo on fresh react-native project

- CHANGELOG.md
- packages/eas-cli/src/update/configure.ts
We run `ensureEASUpdateIsConfiguredAsync` in most of our eas update commands, and if you have a dynamic app.config.js configuration, we tell you to `finish configuring EAS Update` by adding some key values to the config. While this is the final step to configure for `app.json`, if the user is running `eas update:configure`, we still need to configure `eas.json`.
Reword the error message so the user isn't led to believe they are completely done with the configuration process (in the case of `eas update:configure`)
> [eas-cli] reword the update configure instruction

- CHANGELOG.md
- packages/eas-cli/src/project/projectUtils.ts
Currently canaries fail these version checks since their versions are of the form `0.0.1-canary-20240109-93608d8` (semver 0.0.1). We've been investigating changing the canary versioning scheme, but it's a bit more complex than anticipated. Instead, just handle the current canary versioning scheme.
If canary is in the version, assume that it has features (for now).
Inspect.
> [eas-cli] Fix expo-updates package version detection for canaries

- .vscode/settings.json
- CHANGELOG.md
Directories named `build` are a special case in the default vscode search excludes since most projects don't want to search the build folder since it is compiled code (including us in this repo, we build to the `build` folder as destination and don't want the compiled js files to be included in search results).
But, we also have some folders named `build` that need to be named build to appease oclif that we do want to appear in search results and be respected in find/replace.
Add vscode setting to re-include certain `build` folders.
Note that usually I don't recommend checking in this .vscode folder or any editor settings folder (they're excluded by default and even this file is still excluded in this repo, it was force added to the commit), but in this instance I think it's warranted. …
> [vscode] Include src/**/build directories in search and replace

- CHANGELOG.md
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/project/resolveRuntimeVersionAsync.ts
- packages/eas-cli/src/rollout/actions/CreateRollout.ts
- packages/eas-cli/src/utils/expoUpdatesCli.ts
This makes use of https://github.com/expo/expo/pull/27263 to generate the correct runtime version for build metadata and updates.
Call the command in the package to use the versioned config-plugins for the app. This way the runtime version is consistent no matter what version of eas-cli is used (and for canary versions so we don't have to update eas-cli to use canaries).
Run tests.
Manual test:
1. `neas build` with a bare-app in expo/expo
2. `neas update` with same app, including with `EXPO_DEBUG=1` to see fingerprint sources.
> [eas-cli] Use expo-updates runtime version CLI to generate runtime versions

- CHANGELOG.md
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/project/projectUtils.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/project/resolveRuntimeVersionAsync.ts
- packages/eas-cli/src/rollout/actions/CreateRollout.ts
- packages/eas-cli/src/utils/expoUpdatesCli.ts
This reverts commit https://github.com/expo/eas-cli/commit/2b59a5e2ee2ad1a7fcf405380f62f29ce4ba9baf.
Then, this applies a fix on top of it to support older SDKs.
Revert, re-test with SDK 45-50.
```
yarn create expo-app kjdasjkds555hjkdashjk50 --template blank@50
eas init
eas update:configure
~/expo/run-with-local-eas-build.sh build --local
```
(the last step uses a local eas-build to patch the revert in that repo: https://github.com/expo/eas-build/pull/356)
> Revert "Revert "[eas-cli] Use expo-updates runtime version CLI to generate runtime ve…" (#2264)"

- CHANGELOG.md
- packages/eas-cli/src/update/android/UpdatesModule.ts
- packages/eas-cli/src/update/ios/UpdatesModule.ts
This makes use of the new command added in https://github.com/expo/expo/pull/27511 to ensure that the runtime version resolution and synchronization are both versioned.
Call the CLI instead of using the version of config plugins depended on by eas-cli when possible.
In a generic project using fingerprint and `requireCommit: true`:
```
yarn link expo-updates
neas build -p android
```
and ensure the native sync is no longer the old version (meaning it called the CLI to do the native sync).
> [eas-cli] Use new expo-updates configuration:syncnative for versioned native sync

- CHANGELOG.md
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/internal.ts
We want to add support for `--auto-submit` for our GitHub integration. Yet the only place where we can automagically resolve the credentials for GH builds is EAS CLI if don't want to ask the user for any input like bundle identifier and so on and I believe that this is what we decided to do. We already run `eas build:internal` during the build process to resolve build credentials for the same reasons as mentioned above, so we can just add the auto-submit flag to trigger the submission from the build worker.
It's hacky but at the same time, it's not very different from running `eas build:internal` which we already do.
Add `--auto-submit` flags to the `eas build:internal` command.
Tested manually. Checked if a submission was created.
> [ENG-11416][eas-cli] add `--auto-submit` flag to `eas build:internal` command

- CHANGELOG.md
- packages/eas-cli/src/build/configure.ts
- packages/eas-cli/src/build/utils/repository.ts
- packages/eas-cli/src/vcs/clients/git.ts
- packages/eas-cli/src/vcs/vcs.ts
https://linear.app/expo/issue/ENG-11730/dump-git-status-when-ci=1-and-we-abort-eas-build-due-to-dirty-working#comment-2c875628
Added `git status` logging when bailing on dirty repo in non-interactive mode.
> Log dirty files in non-interactive when bailing

- CHANGELOG.md
- packages/eas-cli/src/build/android/prepareJob.ts
- packages/eas-cli/src/build/ios/prepareJob.ts
- packages/eas-cli/src/project/customBuildConfig.ts
Our server expects to get this path with a POSIX separator
Closes https://github.com/expo/eas-cli/issues/2160
If a build is not local use the posix separator for Windows.
Tests
Comment out `process.platform === 'win32'` and see if it works on my Mac machine
I don't have a Windows machine to test it
> [eas-cli] send a path to custom build config to EAS Build server with posix separator for Windows

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
Bump `@expo/apple-utils` to include changes from https://github.com/expo/third-party/pull/99
Bump `@expo/apple-utils`
Tests, test authentication manually
> [eas-cli] bump `@expo/apple-utils` to switch between `developer.apple.com` and `developer-mdn.apple.com` domains when one of them doesn't work

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
nit: there is a `.` before the `:` when printing out the line about asset limits
> [eas-cli] fix asset limit punctuation

- CHANGELOG.md
- packages/eas-cli/src/build/android/__tests__/version-test.ts
- packages/eas-cli/src/build/ios/__tests__/version-test.ts
- packages/eas-cli/src/commandUtils/EasCommand.ts
- packages/eas-cli/src/commandUtils/context/ContextField.ts
- packages/eas-cli/src/commandUtils/context/VcsClientContextField.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/findProjectDirAndVerifyProjectSetupAsync.ts
- packages/eas-cli/src/commands/build/internal.ts
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/__tests__/roll-back-to-embedded.test.ts
- packages/eas-cli/src/project/__tests__/workflow-test.ts
- packages/eas-cli/src/project/android/__tests__/applicationId-test.ts
- packages/eas-cli/src/project/android/__tests__/gradle-test.ts
- packages/eas-cli/src/project/ios/__tests__/bundleIdentifier-test.ts
- packages/eas-cli/src/submit/android/__tests__/AndroidSubmitCommand-test.ts
- packages/eas-cli/src/submit/android/__tests__/ServiceAccountSource-test.ts
- packages/eas-cli/src/submit/ios/__tests__/AscApiKeySource-test.ts
- packages/eas-cli/src/submit/ios/__tests__/IosSubmitCommand-test.ts
- packages/eas-cli/src/vcs/index.ts
We don't want to fail builds when running `eas build:internal` for people who have `requiredCommit: true` and have modified their project files before the `CONFIGURE_PROJECT` build phase is run. We want to always override the `vcsClient` for the `build:internal` command to `GitNoCommitClient`.
While working on it I noticed that resolving the `vcsClient` works correctly when running `getContextAsync` only because it is always specified as a last field in the command `contextDefinition`. If the order was different `getVcsClient` (used in the `vcsClient` field resolver) might have returned an incorrect value because `setVcsClient` is run separately in other places and it might not be well synchronized.
I deleted the `getVcsClient` and `setVcsClient` functions so `getContextAsync` is the only …
> [eas-cli] use `GitNoCommitClient` for `eas build:internal` command

- CHANGELOG.md
- packages/eas-cli/src/commands/credentials/configure-build.ts
- packages/eas-cli/src/commands/credentials/index.ts
- packages/eas-cli/src/commands/credentials/init-build.ts
- packages/eas-cli/src/credentials/manager/Actions.ts
- packages/eas-cli/src/credentials/manager/CheckBuildProfileFlagAgainstEasJson.ts
- packages/eas-cli/src/credentials/manager/ManageAndroid.ts
- packages/eas-cli/src/credentials/manager/ManageIos.ts
- packages/eas-cli/src/credentials/manager/SetUpAndroidBuildCredentials.ts
- packages/eas-cli/src/credentials/manager/SetUpBuildCredentialsCommandAction.ts
- packages/eas-cli/src/credentials/manager/SetUpIosBuildCredentials.ts
To help a developer get configured for GitHub builds, it would be nice to let them use an EAS CLI command locally that sets up credentials for a build without actually executing it. In theory it would be awesome to be able to do this work from the browser/server, but as we know, some constraints prevent us from that.
I added a new command that largely inherits most of its behavior from `ManageIos/ManageAndroid`, but goes right to the `SetUpBuildCredentials` step for each platform, skipping printing out existing credentials and the 4+ step prompt flow that takes you to this action.
With `neas` as an alias pointed to my local build of EAS CLI,
`neas credentials:configure-build` should prompt you for both parameters and execute the build credentials setup for the selected platform.
`neas …
> [eas-cli] add a `credentials:configure-build` subcommand that prepares a project for EAS Build without executing the build from the CLI

- .github/workflows/release.yml
build the `darwin-arm64` executable as well when releasing the new EAS CLI version
These executables are attached to release https://github.com/expo/eas-cli/releases/tag/v7.8.1
build the `darwin-arm64` executable as well when releasing the new EAS CLI version
See if it works on the next release run 
Run `yarn oclif pack:tarballs --no-xz --targets darwin-arm64` locally
> [ci] build `darwin-arm64` executable as well when releasing new EAS CLI version

- CHANGELOG.md
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/project/resolveRuntimeVersionAsync.ts
- packages/eas-cli/src/utils/expoUpdatesCli.ts
It seems that the error thrown by the expo-updates CLI is a normal JS Error, and due to the way the CLI is called, the JS error doesn't print super well when it is thrown.
This PR wraps all stderr output in a new error type that at least shows the full error to the user. Still room for improvement on the expo-updates CLI end to make the stderr cleaner.
```
neas update
...
/Users/wschurman/temp/my-app/node_modules/expo-updates/utils/build/resolveRuntimeVersionAsync.js:24
throw new Error(`You're currently using the bare workflow, where runtime version policies are not supported. You must set your runtime version manually. For example, define your runtime version as "1.0.0", not {"policy": "appVersion"} in your app config. https://docs.expo.dev/eas-update/runtime-versions`);
^
Error: You're …
```
> [eas-cli] Fix display of errors when expo-updates CLI command fails

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/credentials/android/api/graphql/queries/GoogleServiceAccountKeyQuery.ts
- packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts
- packages/eas-cli/src/credentials/ios/api/graphql/queries/AppStoreConnectApiKeyQuery.ts
- packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDeviceQuery.ts
- packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDistributionCertificateQuery.ts
- packages/eas-cli/src/credentials/ios/api/graphql/queries/ApplePushKeyQuery.ts
- packages/eas-cli/src/devices/actions/create/action.ts
- packages/eas-cli/src/devices/actions/create/developerPortalMethod.ts
- packages/eas-cli/src/graphql/generated.ts
Move credentials endpoints to their better paginated counterparts.
Affects dist cert, asc api keys, apple devices and push key fetching
Tested userflows which rely on
> [ENG-11823][2/2] move credentials endpoints to paginated

- .github/workflows/release.yml
https://github.com/expo/eas-cli/actions/runs/8693539811/job/23840805608
Use correct working dir
> [ci] use correct workingdir for getting x86 macos build

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts
- packages/eas-cli/src/credentials/ios/actions/PushKeyUtils.ts
- packages/eas-cli/src/credentials/ios/actions/RemoveDistributionCertificate.ts
- packages/eas-cli/src/credentials/ios/actions/RemovePushKey.ts
I recently capped the number of Entities we load from www on the ApplePushKey `iosAppCredentialsList` edge and the AppleDistributionCertificate `iosAppBuildCredentialsList` edge because we had some outlier users that had thousands of entities on those edges. We use the edges to tell the user which apps still use the credential when users try to delete it. 
Amend the wording to tell the user that they may have more apps relying on the credential if the `www` limit has been hit.
> [eas-cli] amend credential removal wording

- CHANGELOG.md
- packages/eas-json/schema/eas.schema.json
Companion to: https://github.com/expo/turtle-v2/pull/1744
https://linear.app/expo/issue/ENG-11602/preinstall-gradle-and-ndks-used-in-the-3-latests-sdks-on-android
New options for Android images have been added and eas.schema.json needs to reflect that
Updated the eas.schema.json with the current image values for Android images
Automated tests pass
> [eas-cli] [ENG-11602] Update eas.schema.json

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/contextUtils/findProjectDirAndVerifyProjectSetupAsync.ts
https://linear.app/expo/issue/ENG-12116/improve-error-message-displayed-when-eas-cli-version-doesnt-satisfy
Improve error message
> [ENG-12116][eas-cli] improve error message displayed when EAS CLI version doesn't satisfy minimal version required specified in `eas.json`

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts
https://linear.app/expo/issue/ENG-12120/make-multi-select-for-revoking-distribution-certificates-more-readable
Make it look better
test manually
> [ENG-12120][eas-cli] make multi-select for revoking distribution certificates more readable

- CHANGELOG.md
- packages/eas-cli/src/project/projectUtils.ts
Same as https://github.com/expo/eas-build/pull/385 but for eas-cli.
Closes ENG-12103.
Hardcode
Inspect.
> [eas-cli] Fill in min expo-updates version for expo-updates CLI

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/EasCommand.ts
https://linear.app/expo/issue/ENG-12118/improve-error-message-displayed-in-eas-cli-when-somebody-is-logged-in
improve error message
Test manually
> [ENG-12118][eas-cli] improve error message if server returns `UNAUTHORIZED_ERROR`

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
An alternative solution to https://github.com/expo/eas-cli/pull/2339 , after talking to @jonsamp and @wschurman 
When users create an update, we make sure that the branch they publish to is linked to a channel of the same name. However, this behaviour is not always desirable. For example, in the development usecase where someone is trying to load their update in the dev-client, a channel is not necesary. Users will either navigate to the update they want in the dev client menu or via a preview QR code.
- Only create a channel and link it to a branch when the `--channel` flag is passed
> [ENG-11658][eas-cli] dont generate channel on `eas update` without flag

- CHANGELOG.md
- packages/eas-cli/src/user/SessionManager.ts
As noted by @jonsamp, this message could be a bit clearer.
Add more info to what the user can do to list other login options.
Inspect.
> [eas-cli] Improve login info message for other login options

- CHANGELOG.md
- packages/eas-cli/README.md
- packages/eas-cli/src/commands/account/login.ts
As noted by @jonsamp, the login info message was not clear. It was changed to  show use of 'login --help' to see more login options. On checking, the sso login option was missing/hidden in the help and README.
Related PR: https://github.com/expo/eas-cli/pull/2352
Added back the login help option. 
`eas-cli % ./bin/run login --help
log in with your Expo account
USAGE
$ eas login [-s]
FLAGS
-s, --sso  Login with SSO
DESCRIPTION
log in with your Expo account
ALIASES
$ eas login
`
`eas-cli % ./bin/run login --help                  
log in with your Expo account
USAGE
$ eas login [-s]
FLAGS
-s, --sso  Login with SSO
DESCRIPTION
log in with your Expo account
ALIASES
$ eas login
`
> [eas-cli] Show the -s, --sso option in the login command help.

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts
- packages/eas-cli/src/project/projectUtils.ts
- packages/eas-json/schema/eas.schema.json
https://linear.app/expo/issue/ENG-12122/dont-prompt-people-to-set-push-notifications-by-default-if-they-dont
It was noticed that these prompts not always make sense and may be annoying
don't prompt users to set push notifications by default if they don't have the `expo-notifications` installed
test manually
with `promptToConfigurePushNotifications` not set and `expo-notifications` not installed:
with `promptToConfigurePushNotifications` not set and `expo-notifications` installed:
> [ENG-12122][eas-cli] don't prompt users to set push notifications by default if they don't have the `expo-notifications` installed

- CHANGELOG.md
- packages/eas-cli/src/build/createContext.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/index.ts
- packages/eas-cli/src/commands/build/inspect.ts
- packages/eas-cli/src/commands/build/internal.ts
- packages/eas-cli/src/credentials/__tests__/fixtures-appstore.ts
- packages/eas-cli/src/credentials/context.ts
- packages/eas-cli/src/credentials/errors.ts
- packages/eas-cli/src/credentials/ios/actions/ConfigureProvisioningProfile.ts
- packages/eas-cli/src/credentials/ios/actions/CreateProvisioningProfile.ts
- packages/eas-cli/src/credentials/ios/actions/SetUpProvisioningProfile.ts
- packages/eas-cli/src/credentials/ios/actions/__tests__/ConfigureProvisioningProfile-test.ts
- packages/eas-cli/src/credentials/ios/actions/__tests__/CreateProvisioningProfile-test.ts
- packages/eas-cli/src/credentials/ios/actions/__tests__/SetUpProvisioningProfile-test.ts
We currently support passing in an ASC Api Key to eas build through environment variables. However, we've barred modifying iOS credentials automatically in CI. For many credentials like a Push Key, revoking/generating them in CI is a bad idea since an account has a very low limit on how many keys they are allowed to generate and revoking a push key can have a large impact on production. However, modifying provisioning profiles are relatively safe and needed on a semi-regular basis (ie) annual profile expiration
This PR allows for the creation and modification of app store and enterprise Provisioning Profiles in CI. Apple resigns app store provisioning profiles when it is distributed, so this should be relatively safe. For users that want to ensure their credentials don't get modified in …
> [ENG-8801][eas-cli] allow modification of provisioning profile in CI, add `--freeze-credentials` flag

- CHANGELOG.md
- packages/eas-cli/src/build/android/build.ts
- packages/eas-cli/src/build/android/syncProjectConfiguration.ts
- packages/eas-cli/src/build/ios/build.ts
- packages/eas-cli/src/build/ios/syncProjectConfiguration.ts
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/configure.ts
- packages/eas-cli/src/commands/update/configure.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/project/resolveRuntimeVersionAsync.ts
- packages/eas-cli/src/rollout/actions/CreateRollout.ts
- packages/eas-cli/src/update/android/UpdatesModule.ts
- packages/eas-cli/src/update/configure.ts
- packages/eas-cli/src/update/ios/UpdatesModule.ts
- packages/eas-cli/src/utils/expoUpdatesCli.ts
This is the eas-cli equivalent of https://github.com/expo/eas-build/pull/388.
Essentially, when getting the project config in expo-updates CLI, the env must be supplied.
Pass the env to the `spawnAsync`. Note that this passes the build profile env when possible as well (only in build command).
Still need to come up with a test plan here. I think it will be:
1. Create a test app with an app.config.ts similar to https://github.com/expo/expo/blob/main/apps/eas-expo-go/app.config.ts and expo-updates installed (beta). (`yarn create expo-app --template default@beta`)
2. `eas init`, `eas update:configure`, `eas build:configure`
3. Add environment variable to eas.json env key in each profile.
4. Run `eas build -p android`, see it fails (current prod version of eas-cli)
5. Run `neas build -p …
> [eas-cli] Pass env from process.env and build profile to expo-updates CLI calls where applicable

- packages/eas-cli/src/commands/project/onboarding.ts
- packages/eas-cli/src/graphql/mutations/UserPreferencesMutation.ts
There's a bug in how we update onboarding data. UserPreferences is a key-value store with shallow comparison so we also need to pass the other info that was stored there for it to work.
By spreading previous preferences.
Not sure how to test it. @szdziedzic can you help me?
> [eas-cli] fix onboarding mutation

- packages/eas-cli/src/commands/project/onboarding.ts
- packages/eas-cli/src/onboarding/runCommand.ts
- packages/eas-cli/src/vcs/git.ts
improvements to eas onboarding after dogfooding
- add spinner
- don't let EAS CLI crash after git diff with pager is closed with `q`
- remove the redundant white checkmark from logs
- ask the user to which directory we should clone the repo instead of if they want to continue
improvements to eas onboarding after dogfooding
test manually
> [eas-cli] improvements to eas onboarding after dogfooding

- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/update/republish.ts
Implementing @tchayen's suggestion.
Changed wording
None.
> `s/Website link/EAS Dashboard` when displaying update info

- packages/eas-cli/src/commands/project/onboarding.ts
Fix typo in EAS CLI onboarding commit message, when we also include credential changes.
Add missing space.
N/A
> [eas-cli] fix typo in onboarding commit message

- packages/eas-cli/src/ora.ts
I noticed logs look off in CI when running `eas update --auto`.
I pinpointed it to Ora being restarted on every log.
Ran `CI=1 easd update --auto` and got ⬇️ which I think is much more readable.
```
CI=1 easd update --auto
- Exporting...
[expo-cli] Starting Metro Bundler
[expo-cli] Android Bundling complete 3492ms
[expo-cli] iOS Bundling complete 3493ms
[expo-cli] iOS Building Hermes bytecode for the bundle
[expo-cli] Android Building Hermes bytecode for the bundle
[expo-cli] 
[expo-cli] Bundle                      Size
[expo-cli] ┌ index.ios.hbc           858 kB
[expo-cli] ├ index.android.hbc       864 kB
[expo-cli] ├ index.ios.hbc.map      3.45 MB
[expo-cli] └ index.android.hbc.map  3.48 MB
[expo-cli] 
[expo-cli] 💡 JavaScript bundle sizes affect startup time. Learn more: …
```
> [eas-cli] Prevent `ora` flooding logs

- packages/eas-cli/src/commands/project/onboarding.ts
https://exponent-internal.slack.com/archives/C06EBFAVCEA/p1715397103308639
create keystore for Android emulator builds in `init:onboarding`
create keystore for Android emulator builds in `init:onboarding`
test manually
> [eas-cli] create keystore for Android emulator builds in `init:onboarding`

- CHANGELOG.md
- packages/eas-cli/src/commands/diagnostics.ts
Let's give users an information that something is happening when `diagnostics` take a while to gather data.
Add Ora spinner with simple process progress information + small formatting tweaks.
The changes have been tested locally.
https://github.com/expo/eas-cli/assets/719641/0f9fa5aa-4d5f-4b97-9c48-b09c443ab94b
> [eas-cli] diagnostics: add loader and progress information

- packages/eas-cli/src/commands/project/onboarding.ts
install dependencies before resolving the expo config
install dependencies before resolving the expo config
> [eas-cli] install dependencies before resolving expo config in `init:onboarding`

- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/mutations/PublishMutation.ts
We want to save the relationship between a job run and an update.
See https://github.com/expo/universe/pull/15329.
Tested with staging.
> [eas-cli] Add `turtleJobRunId` to `UpdatePublishMutation` input

- packages/eas-cli/src/build/android/prepareJob.ts
- packages/eas-cli/src/build/context.ts
- packages/eas-cli/src/build/createContext.ts
- packages/eas-cli/src/build/ios/prepareJob.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/index.ts
- packages/eas-cli/src/commands/build/inspect.ts
- packages/eas-cli/src/commands/build/internal.ts
- packages/eas-cli/src/commands/project/onboarding.ts
Add the `--repack` flag to the `eas build` command. This flag is not intended to be user-facing, it's just for us to test the onboarding repack flow
Add hidden `--repack` flag to `eas build` command. If the flag is used run build as custom with `__eas/repack.yml` config
test manually
> [eas-cli] add `--repack` flag to `eas build` command

- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
- packages/eas-cli/src/commands/project/onboarding.ts
https://exponent-internal.slack.com/archives/C06EBFAVCEA/p1716401295496209
The error Charlie got was thrown here https://github.com/expo/eas-cli/blob/c76d3dca237945e05f243c4722febae16f1f1b74/packages/eas-cli/src/commandUtils/context/contextUtils/findProjectDirAndVerifyProjectSetupAsync.ts#L78-L91
I believe that the `cwd` was set to the wrong dir in the context of what we are doing in onboarding  and it should be the project target dir (the place where we clone the repo to)
pass correct `cwd`
test manually
> [eas-cli] pass `cwd` to `findProjectRootAsync` in onboarding

- CHANGELOG.md
- packages/eas-cli/src/commands/project/onboarding.ts
https://expo.new is released 🎉 
let's make the `eas init:onboarding` command public ✅ 
remove `hidden` property
> [eas-cli] make `init:onboarding` command public

- CHANGELOG.md
- packages/eas-cli/src/commands/project/onboarding.ts
Instead of extending and overriding some parts of the base config we just created a new, incomplete one
extend and override base config from `expo-template-default` instead of creating a new incomplete one
test manually
> [eas-cli] use correct app config for no gh `init:onboarding` flow

- packages/eas-cli/src/build/android/prepareJob.ts
- packages/eas-cli/src/build/ios/prepareJob.ts
use `BuildMode.REPACK` for `--repack` builds
use `BuildMode.REPACK` for `--repack` builds
run repack build locally
> [eas-cli] use `BuildMode.REPACK` for `--repack` builds

- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/utils/repository.ts
- packages/eas-cli/src/uploads.ts
User doesn't need to know about metadata file, fewer log lines is better.
Removed logging of metadata operations, parallelised uploading project archive and metadata file.
> Remove logging of metadata file upload

- CHANGELOG.md
- packages/eas-cli/src/submit/ArchiveSource.ts
- packages/eas-cli/src/submit/__tests__/ArchiveSource-test.ts
The check for build expiration was wrong.
Instead of relying on an old hardcoded value, use `expirationDate` fetched from GraphQL.
Adjusted tests. Also tested manually:
```
43f278b2-3257-49c6-9c01-615a3f958f27	2023-07-20 14:36:18.021724+00
5167ab23-3913-4741-8e08-db75c9c420ab	2024-07-26 19:54:01.386308+00
f73eec2a-3936-40e3-9504-1cb4ebb29e12	2024-04-27 15:25:24.338+00
```
> Fix expiration date check for build list source

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/EasCommand.ts
I noticed that we don't print any error logs if `CombinedError` has an empty `graphQLErrors` array and contains only `networkError`
https://exponent-internal.slack.com/archives/C017N0N99RA/p1717071253573369
Print network error message if present
> [eas-cli] print network error message if present

- CHANGELOG.md
- packages/eas-cli/src/build/utils/formatBuild.ts
When looking at https://github.com/expo/eas-cli/issues/2404 I noticed that we don't display build profile info in this list, yet we allow people to filter by it which makes it confusing
Display build profile info as well
test manually
> [eas-cli] display build profile in `eas build:list` command details

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/appstore/authenticate.ts
`getenv.int(process.env.EXPO_APPLE_PROVIER_ID)` will lookup the value of the `process.env.EXPO_APPLE_PROVIER_ID` in `process.env` (i.e. `process.env[process.env.EXPO_APPLE_PROVIER_ID]`) and try to parse that (undefined value) as an int.
If at runtime `process.env.EXPO_APPLE_PROVIER_ID` is `12345`, the code will fail with:
```
Authentication with Apple Developer Portal failed!
GetEnv.Nonexistent: 12345 does not exist and no fallback value provided.
```
Where process.env["12345"] does not exist.
Simply try to set EXPO_APPLE_PROVIER_ID to anything on the current eas-cli build.
> fix parsing EXPO_APPLE_PROVIER_ID env var

- CHANGELOG.md
- yarn.lock
Running `yarn typecheck` in **packages/eas-cli** fails due to outdated `@types/node` being used. 
This is caused because our lockfile resolves to the outdated node types.
- Some libraries are using `dependencies: @types/node: *`, which is ok
- Our lockfile resolves `@types/node@*` to `14.0.27`, which is not ok
- Update `@types/node` in our lockfile to only contain `20.11.0`
Run this before changing anything:
- `$ node --print "require('@types/node/package.json').version"`
- Should print `14.0.27`, which is not correct
After pulling this PR:
- `$ yarn install --frozen-lockfile`
- `$ cd packages/eas-cli`
- `$ yarn typecheck` (should pass)
- `$ node --print "require('@types/node/package.json').version"` (should print `20.11.0`)
> fix: update lockfile to only include `@types/node@20.11.0`

- .github/workflows/test.yml
- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-json/package.json
- scripts/package.json
- Node 16 is End Of Life (EOL)
- Node 18 is currently in maintenance LTS
- Node 20 is currently in active LTS
- Node 22 is scheduled to take active LTS status on **2024-10-29**
> Source: https://nodejs.org/en/about/previous-releases
To support Node 22, we'd need to remove `node-fetch`. Starting from Node 18, we can use the built-in fetch which is based on `undici`. Unfortunately, we still need the `undici` package to maintain support for `https_proxy` functionality through `ProxyAgent`.
Dropping support for Node 16 helps in this transition, and matches our other tooling support (which is LTS+ - both maintenance and active LTS versions).
- Removed Node 16 from workflow
- Added Node 22 to workflow
See GitHub Actions.
> chore!: drop support for Node 16

- CHANGELOG.md
- packages/eas-cli/src/build/runBuildAndSubmit.ts
In https://github.com/expo/eas-cli/pull/2101 we added a logic to refresh the submit profile with the new submit profile with `submit profile name === build profile name` (if it exists) unless the `submissionCtx.specifiedProfile` value is set.
However, we didn't set the `submissionCtx.specifiedProfile` for submissions triggered via `eas build --auto-submit` and this caused us to always refresh the submit profile with the submit profile with the name of the build profile.
https://github.com/expo/eas-cli/blob/daf3ed83f8471e75bbce968cf7c40f89086d856d/packages/eas-cli/src/submit/ios/IosSubmitCommand.ts#L45-L47
It's also the root cause of https://exponent-internal.slack.com/archives/C02123T524U/p1718015524335999 issue
Set `submissionCtx.specifiedProfile` for submission triggered by the `eas …
> [eas-cli] resolve correct submit profile configuration for `eas build --auto-submit-with-profile`

- CHANGELOG.md
- packages/eas-cli/src/commands/channel/rollout.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/republish.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/commands/update/rollback.ts
People get confused as to why there is a private-key flag and how it relates to updates. This PR clarifies that it's only relevant if you are using code-signing
Closes ENG-12537.
> [eas-cli] add clarification for codesigning private key flag

- CHANGELOG.md
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-json/schema/eas.schema.json
These images were removed
Remove any mentions of them
tests
> [eas-cli] remove old Xcode images entirerly

- CHANGELOG.md
- packages/eas-cli/src/build/createContext.ts
Track how much is `local` build mode used in analytics
Add `local` to the analytics context
tests, run the command locally
> [eas-cli] track how much is `local` build mode used in analytics

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/graphql.ts
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/build/utils/repository.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/project/resolveRuntimeVersionAsync.ts
- packages/eas-cli/src/rollout/actions/CreateRollout.ts
- yarn.lock
- https://github.com/expo/universe/pull/15517
- 👉 https://github.com/expo/eas-cli/pull/2422
- https://github.com/expo/eas-build/pull/407
- https://github.com/expo/eas-build/pull/421
- https://github.com/expo/turtle-v2/pull/1893
- https://github.com/expo/universe/pull/15592
-  https://github.com/expo/terraform-iam/pull/303
It's very difficult to debug why the local and remote fingerprint are different.
Currently the only way to do it would be manual: add step to print out the remote sources, calculate local fingerprint, diff the two. Ideally we'd like to show the diff in the build step instead.
Save the local fingerprint in a google cloud bucket and show a diff if the fingerprints are different.
Ran turtle and www locally with changes from the these packages manually linked to turtle.
> [eas-cli] [ENG-12650] add fingerprint sources to build metadata

- packages/eas-cli/README.md
updated the readme learn more link, previous link was throwing 404
> fix: readme learn more link

- CHANGELOG.md
- packages/eas-cli/README.md
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/publish.ts
Currently Bugsnag [doesn't support](https://docs.bugsnag.com/platforms/react-native/expo/#eas-update) automatic source map upload after running eas update so I made a script that makes a manual submission after bundling and submitting an update. The script is relying on `eas-update-metadata.json` to obtain the bundle ids.
I am currently using eas-cli@6.1 and the update script is working well, but I have realised that this feature was removed [with the v7 release](https://github.com/expo/eas-cli/releases/tag/v7.0.0) thus preventing me from updating to a newer version of `eas-cli`.
This feature was introduced in #2158 and removed in #2187, so I have reverted the changes and put the feature behind  the `--emit-build-meta` flag rather than having it aways on so nothing will change for people …
> [eas-cli] Add flag to emit build meta

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
https://exponent-internal.slack.com/archives/CHZKBDRN1/p1721069250906039
https://github.com/expo/eas-cli/issues/2305
bump `@expo/apple-utils` version to use the fallback Apple Developer Portal domain on every internal server error
bump `@expo/apple-utils` version
tests
> [eas-cli] bump `@expo/apple-utils` version to use the fallback Apple Developer Portal domain on every internal server error

- CHANGELOG.md
- packages/eas-cli/src/commands/account/login.ts
- packages/eas-cli/src/commands/account/view.ts
Using `EXPO_TOKEN` seems confusing to people.
https://github.com/expo/eas-cli/pull/2460
When using the `eas whoami` command signal that a user is authenticated by using `EXPO_TOKEN`. It seems like people sometimes tend to forget that they have `EXPO_TOKEN` set, then they log in as a different account but `eas whoami` still returns the same value because they are authed using `EXPO_TOKEN` and it seems to be confusing.
Warn people when running `eas login` with the `EXPO_TOKEN` set that this is not necessary. 
Test manually
`eas whoami` after and before
`eas login`
> [ENG-12793][eas-cli] make `eas login` and `eas whoami` behave more clearly when one is authenticated using `EXPO_TOKEN`

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
Extend the timeout from 90 seconds to 180 seconds, because some people have really slow internet connections. Using a p99 of the cloud function time of 29s, we essentially change the upload timeout from 60s to 150s
Why we chose 90 seconds in the first place, from https://github.com/expo/eas-cli/pull/2085:
> For slow connections that take a while to upload, 60s is not enough of a timeout. For example, lets say there's only one asset to upload, and it takes even 1 second to upload and 60s to process (the max of the cloud function), it'll time out. The p99 of the processing cloud function is 29s, so changing this timeout to 90s gives a upload timeout of 60s.
> We also change the semantics of when to reset the timeout, and now reset it when the upload is retried. So, in the example above, …
> [eas-cli] bump asset upload timeout from 90 to 180 seconds

- packages/eas-cli/package.json
- packages/eas-cli/src/build/metadata.ts
- packages/eas-json/src/__tests__/buildProfiles-test.ts
- packages/eas-json/src/build/schema.ts
- packages/eas-json/src/build/types.ts
- yarn.lock
User should be able to specify `environment` in their build profile to select Environment Variables set to be used with their build
* added `metadata` field to build `metadata` (`eas-build`)
* added `metadata` to build profile schema
* passed `metadata` from build profile to build metadata
Added test
> Add environment to Metadata

- CHANGELOG.md
- packages/eas-cli/src/env.ts
- packages/eas-cli/src/project/ios/bundleIdentifier.ts
https://exponent-internal.slack.com/archives/C02123T524U/p1721767590752789
It seems like one of our users got blocked because we weren't able to read the bundle identifier from their Xcode project using the `IOSConfig.BundleIdentifier.getBundleIdentifierFromPbxproj` function. While the root cause of this issue remains unknown we can add a dangerous override env to allow people to unblock themself if such an issue occurs.
We already have an env var that does the same for Android bare workflow builds:
https://github.com/expo/eas-cli/blob/39aff70e83370d694e9790d67ca225cbc8a96826/packages/eas-cli/src/project/android/applicationId.ts#L68-L70
Add `EAS_DANGEROUS_OVERRIDE_IOS_BUNDLE_IDENTIFIER` and use it as bundle id override for bare workflow apps if provided.
Test manually.
> [eas-cli] add support for `EAS_DANGEROUS_OVERRIDE_IOS_BUNDLE_IDENTIFIER` for bare workflow iOS builds

- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/authUtils.ts
- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/commands/env/delete.ts
- packages/eas-cli/src/commands/env/get.ts
- packages/eas-cli/src/commands/env/link.ts
- packages/eas-cli/src/commands/env/list.ts
- packages/eas-cli/src/commands/env/pull.ts
- packages/eas-cli/src/commands/env/push.ts
- packages/eas-cli/src/commands/env/unlink.ts
- packages/eas-cli/src/commands/env/update.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/mutations/EnvironmentVariableMutation.ts
- packages/eas-cli/src/graphql/queries/EnvironmentVariablesQuery.ts
- packages/eas-cli/src/user/SessionManager.ts
- packages/eas-cli/src/user/fetchSessionSecretAndUser.ts
User should be able to synchronise local environment variables with upstream.
- https://linear.app/expo/issue/ENG-11920/add-eas-envpush-command
- https://linear.app/expo/issue/ENG-11919/add-eas-envpull-command
- added `eas env:pull` and `eas env:push` commands
- `eas env:pull` handles sudo access to request values of sensitive variables
> Add eas `env:push` and `env:pull` commands

- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/worker/assets.ts
- packages/eas-cli/src/worker/upload.ts
- Adds batched upload
- This uses a shared `https.Agent` with max sockets limits and `keepAlive` set
- Attempts concurrent uploads up to a maximum of `10` and aborts on any failed upload
- Starts new uploads concurrently as soon as another finishes to keep up concurrency count
- Adds progress bar (reused from `utils/progress`) for file upload progress
- Adds several ora step progress messages
**Note:** This is still not the final output we'll need, but gets us close enough that it's presentable
> refactor(worker): Implement batched uploads and improved progress output

- .eslintignore
- .eslintrc.js
- package.json
- packages/eas-cli/src/.eslintrc.js
- packages/eas-cli/src/build/android/version.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/createGraphqlClient.ts
- packages/eas-cli/src/commands/build/version/sync.ts
- packages/eas-cli/src/commands/project/onboarding.ts
- packages/eas-cli/src/credentials/context.ts
- packages/eas-cli/src/credentials/ios/__tests__/IosCredentialsProvider-test.ts
- packages/eas-cli/src/credentials/ios/appstore/pushKey.ts
- packages/eas-cli/src/credentials/ios/validators/validateProvisioningProfile.ts
- packages/eas-cli/src/metadata/apple/config/reader.ts
- packages/eas-cli/src/metadata/apple/tasks/age-rating.ts
- packages/eas-cli/src/onboarding/runCommand.ts
- packages/eas-cli/src/project/ios/entitlements.ts
- packages/eas-json/src/.eslintrc.js
- yarn.lock
This is part of an effort to bring linting in eas-cli repo up-to-date with other expo repos.
This is in an effort to reduce the class of bugs surrounding promises, but there are many steps to get to that PR.
This PR adds typescript linting to the packages, upgrades eslint-config-universe, and brings over applicable rules to be applied in stacked PRs.
`yarn lint`
> [chore] Add typescript linting to packages

- CHANGELOG.md
- packages/eas-cli/src/.eslintrc.js
- packages/eas-cli/src/build/__tests__/cancel-test.ts
- packages/eas-cli/src/build/__tests__/delete-test.ts
- packages/eas-cli/src/commands/analytics.ts
- packages/eas-cli/src/commands/build/version/sync.ts
- packages/eas-cli/src/commands/update/list.ts
- packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts
- packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts
- packages/eas-cli/src/credentials/ios/actions/ProvisioningProfileUtils.ts
- packages/eas-cli/src/credentials/ios/actions/SetUpAdhocProvisioningProfile.ts
- packages/eas-cli/src/credentials/ios/actions/SetUpProvisioningProfile.ts
- packages/eas-cli/src/credentials/ios/credentials.ts
- packages/eas-cli/src/credentials/ios/validators/validateProvisioningProfile.ts
- packages/eas-cli/src/credentials/manager/ManageIos.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/run/ios/systemRequirements.ts
- packages/eas-cli/src/update/__tests__/getBranchNameFromChannelNameAsync-test.ts
- packages/eas-cli/src/update/__tests__/update-queries-test.ts
- packages/eas-cli/src/user/expoSsoLauncher.ts
This is the real PR I wanted to get to: it uses lint to fix a lot of bugs where promises should have been awaited but weren't. This also fixes bugs where a promise was being accidentally used as a boolean rather than the awaited boolean value.
Closes ENG-13213.
Apply rules, fix manually.
`yarn lint`
> [chore] Enable remaining lint rules and fix lots of bugs

- CHANGELOG.md
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/index.ts
These were deprecated two years ago in https://app.graphite.dev/github/pr/expo/eas-cli/1535/refactor-update-remove-republish-from-update-command?utm_source=chrome-extension. That PR also threw with a descriptive error when one was provided.
Now that it's multiple years later we can remove the code. This is a step towards adding two new flags to this function for rollout updates.
Remove, `yarn tsc`
`yarn tsc`
> [eas-cli] Remove long-deprecated update flags

- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/queries/BranchQuery.ts
- packages/eas-cli/src/graphql/queries/EnvironmentVariablesQuery.ts
- packages/eas-cli/src/graphql/types/Update.ts
- packages/eas-cli/src/project/__tests__/publish-test.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/update/utils.ts
This adds support for the new EAS Update concept: rollout updates. These are updates that are set up to only be served to a certain percentage of users, falling back to a control update. In this PR, the control update is set to the most recent update ID matching the platform and runtime version on the same branch as the branch being published to.
Note that this doesn't care __what__ that update is; it could be a rollout update itself. In this case, the rollout nature of that control update is ignored, essentially ending any previous rollout.
Add flag, gather info and publish when flag is supplied. Note that this required refactoring the platform typescript types.
```
$ neas update
✔ Which branch would you like to use? › main - current update: "Republish "wat" - group: …
```
> [eas-cli] Add rollout-percentage flag to update command

- CHANGELOG.md
- packages/eas-cli/src/commands/update/edit.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/mutations/PublishMutation.ts
This adds the ability to increase a rollout for an update.
Add new command, `update:edit` that takes the rollout-percentage flag.
```
$ neas update:edit 63809081-ee5f-4216-add2-b3412aae7a16
✔ New rollout percentage (min: 30, max: 100) … 31
Update group:
Platforms                 android, ios
Runtime Version           1.0.0
Message                   "wat2" (1 hour ago by wschurman)
Code Signing Key          N/A
Is Roll Back to Embedded  No
Rollout Percentage        31%
Group ID                  63809081-ee5f-4216-add2-b3412aae7a16
$ neas update:view 63809081-ee5f-4216-add2-b3412aae7a16
Update group:
Platforms                 android, ios
Runtime Version           1.0.0
Message                   "wat2" (1 hour ago by wschurman)
Code Signing Key          N/A
Is Roll Back to Embedded  No …
```
> [eas-cli] Add update:edit command for editing rollout

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/project/resolveRuntimeVersionAsync.ts
- yarn.lock
https://app.graphite.dev/github/pr/expo/eas-build/437/eas-build-job-Add-field-to-fingerprint-metadata-indicating-whether-it-is-a-debug-fingerprint added this field to the build job object.
This PR writes the field as part of the build command.
Note that that PR needs to be landed, published, and updated here for this to work in CI.
Update function that generates, uploads, and includes fingerprint info.
Run regular and debug build for app that uses fingerprint, inspect the entity created, see the metadata has the boolean set correctly.
> [eas-cli] Include debug info in fingerprint metadata

- CHANGELOG.md
- packages/eas-cli/src/commands/config.ts
https://exponent-internal.slack.com/archives/CLQ58M23X/p1724709887450179
Make sure that we require authentication only if not run in the `--eas-json-only` mode
test manually
> [eas-cli] make `eas config` command not require authentication when running in `--eas-json-only`  mode

- CHANGELOG.md
- packages/eas-cli/src/commands/build/index.ts
https://github.com/expo/eas-cli/issues/2519
I was able to reproduce the issue and it is indeed true. It seems like we mistakenly added a static project config definition to the `eas build` command context in https://github.com/expo/eas-cli/commit/56510f092527e458aa9dca19feac0b5d425dac56#diff-cd2e00f4d286a4714f8736e14c635f4c3b98c402367cd71a83e4cd743034bd79. The output from it wasn't really used anywhere, but adding it caused the app configs to be evaluated without `buildProfile.env` in the first pass when trying the resolve project ID and slug at the begging of command execution and our slug/project ID assertions to fail. It only affected people with dynamic project IDs and slug fields.
Remove unnecessary static context from context definitions, therefore avoid resolving project ID and …
> [eas-cli] remove unnecessary static project config context definition from eas build command

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts
- yarn.lock
companion to https://github.com/expo/third-party/pull/104
This is my first PR adding new capabilities so please double-check if I did everything correctly, I based it on 6389f52
I got new entitlements from https://developer.apple.com/documentation/bundleresources/entitlements?changes=latest_major and added all available capabilities corresponding to these.
Run prod build manually, add new entitlements for new capabilities to app config, and verify that they were enabled on the provisioning profile
> [eas-cli] add new entitlements added after Xcode 15.0+

- packages/eas-cli/src/commands/worker/deploy.ts
Related ENG-12989
This implements a quick check to ensure that we can differentiate between `output: "server"` and `output: "static"` and explicitly aborts the deployment if we detect `output: "single"` (which is also the current default)
This PR also implements support for the `output: "static"` export mode.
When we go into `static` deployment mode, we now only upload client assets and skip server files from being added to the upload tarball.
In this mode, the entire `dist/` folder is uploaded as client assets.
See: https://github.com/expo/expo-easy-poc/pull/35
- Manually tested
> feat(eas-cli): Add support for static worker deployments

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/graphql.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/project/maybeUploadFingerprintAsync.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/project/resolveRuntimeVersionAsync.ts
Fingerprints are generated at build time and update time, and associated with runtime versions in EAS. Therefore, the fingerprint needs to be supplied as part of publishing an update.
This PR adds support for this.
Closes ENG-12855.
Refactor code to do the upload for both builds and updates.
In a project that uses the fingerprint rtv policy:
1. `neas update`
2. open update on website
3. Query in graphiql:
```
query {
updates {
byId(updateId: "...") {
runtime {
fingerprintDebugInfoUrl
}
}
}
}
```
See that the runtime has the fingerprint debug info and going to the URL appropriately downloads it.
> [eas-cli] Upload fingeprint source as part of eas update command

- packages/eas-cli/src/build/evaluateConfigWithEnvVarsAsync.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/resign.ts
- packages/eas-cli/src/commands/build/version/get.ts
- packages/eas-cli/src/commands/build/version/set.ts
- packages/eas-cli/src/commands/build/version/sync.ts
- packages/eas-cli/src/commands/config.ts
We had an invalid type guard that caused our GQL requests to fetch env vars to fail because of the environment enum option being in lowercase vs uppercase.
Fix the issue and type guard.
Be more verbose about the source of the env vars being loaded to make it easier to understand what's going on
Before
After
> [eas-cli] fix env vars loading issue and be more verbose about where the given env var comes from

- CHANGELOG.md
- packages/eas-cli/src/build/ios/__tests__/version-test.ts
- packages/eas-cli/src/build/ios/version.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1725915931423649
Improve error message to make it more actionable
Test manually
> [eas-cli] improve error message when CFBundleShortVersionString has invalid format

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
We were missing `--non-interactive` which meant that the command wasn't offering to initialize and tie the project to an EAS project when running `worker:deploy`
Add missing flag parsing to `worker:deploy` command.
> chore(cli): Add `--non-interactive` flag to fix `worker:deploy` initialisation

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/worker/assets.ts
- yarn.lock
Deployments should allow environment variables to be added to them.
Source environment variables using `@expo/env`, add them to the manifest, and send them to the deployment API to upload environment variables for deployments.
- Manually tested
> feat(cli): Source `@expo/env` dotenv vars for worker deployments

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/worker/deployment.ts
- packages/eas-cli/src/worker/mutations.ts
This PR is stacked on top of #2548, since we use the alias mutation here too.
This adds the `--prod` flag to `eas worker`, assigning the deployment as production.
> Note, this also changes the URL of the project to use `/projects/<id>/serverless/deployments`. This is to avoid having to use or load `exp.owner` in these URLs.
- Added hint when running `eas worker` without `--prod`
- Added optional `--prod` flag to `eas worker`
- `$ eas worker`
- `$ eas worker --prod`
> feature(eas-cli): add `worker --prod` flag and hint for production deployments

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
This PR is stacked on top of #2548, since we use the alias mutation here too.
This adds the `eas worker --alias <name>`, to assign a custom alias when deploying.
- Added `--alias` and used the existing deployment alias mutation
<details><summary><code>$ eas worker --alias <name></code></summary>
</details>
<details><summary><code>$ eas worker --prod --alias <name></code></summary>
</details>
> feature(eas-cli): add `worker --alias` flag

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
This adds `eas worker --id` to define a custom deployment identifier for the new deployment.
- Added `--id` flag
<details><summary><code>eas worker --id [identifier]</code></summary>
</details>
> feature(eas-cli): add `worker --id` flag

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
Support both `eas worker --prod` and `eas worker --production`, as we use the full "Production" terminology on the dashboard.
- Added `--production` as an alias of `--prod`
- Reduced the amount of spinners
- Dimmed important context but irrelevant info to view a deployment
- Cleaned up command output text
<details><summary><code>$ eas deploy --help</code></summary>
</details>
<details><summary><code>$ eas deploy</code></summary>
</details>
<details><summary><code>$ eas deploy --alias pr-test</code></summary>
</details>
<details><summary><code>$ eas deploy --prod</code></summary>
</details>
<details><summary><code>$ eas deploy --production --alias pr-test</code></summary>
</details>
> refactor(eas-cli): support `eas worker --production` and clean up command output

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/alias.ts
See #2555, this applies the same polishes in terms of help and normal command output.
See #2555
<details><summary><code>easd deploy:alias --help</code></summary>
</details>
<details><summary><code>easd deploy:alias --id xxx --alias pr-test</code></summary>
</details>
> refactor(eas-cli): update `eas worker:alias` with same polishes from `eas worker`

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/worker/assets.ts
This adds EAS Env "pulling" to worker deployments, i.e. pipes environment variables from EAS into the worker deployment.
Reuses existing `--environment` definition. Overriding the help description is TBD.
Manually tested
> [eas-cli] Add `--environment` argument to worker:deploy

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/alias.ts
With `eas worker:alias --json`, we can integrate with other tooling (such as expo-github-action). This adds support for exactly that.
- Swapped the beta warning from `Log.warn` to `console.warn`, avoiding polluting the JSON output
- Added `--json` only output to `eas worker:alias --json` command
<details><summary><code>eas worker:alias --json</code></summary>
</details>
<details><summary><code>eas worker:alias --id xxx --json</code></summary>
</details>
<details><summary><code>eas worker:alias --alias pr-test --json</code></summary>
</details>
<details><summary><code>eas worker:alias --id xxx --alias pr-test --json</code></summary>
</details>
> feature(eas-cli): add `worker:alias --json` support for 3rd parties and custom tooling

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/worker/alias.ts
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/update/__tests__/getBranchNameFromChannelNameAsync-test.ts
- packages/eas-cli/src/worker/fragments/WorkerDeploymentAlias.ts
- packages/eas-cli/src/worker/mutations.ts
- packages/eas-cli/src/worker/utils/logs.ts
This adds `worker:alias --prod` and supports `worker:promote --prod` (we can document either one) to promote existing deployments to production. We could split the command later, if people ask for this use case a lot.
- Added `--prod(uction)` to `worker:alias`
- Added `worker:promote` alias of `worker:alias`
- Pulled both table and json output format into `src/worker/utils/logs.ts`
- Re-implemented table/json output in both `worker` and `worker:alias`
- Updated the dashboard URL from `serverless` to `hosting`
- `$ eas worker`
- `$ eas worker:alias --id <deployment> --alias test-alias`
- `$ eas worker:alias --id <deployment> --alias test-alias --json --non-interactive | jq`
- `$ eas worker:promote --prod --id <deployment> --json --non-interactive | jq`
> feature(eas-cli): add `worker:alias|promote --prod` flag to promote existing deployments

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/worker/deployment.ts
- packages/eas-cli/src/worker/queries.ts
- packages/eas-cli/src/worker/utils/logs.ts
In early user testing it showed that "dev domain" is too ambiguous. Just polished the prompt to make it more clear what it is, and what's allowed.
- Added `.(staging.)expo.app` suffix to show the base URL
- Renamed `dev domain` to `project URL`
- Updated validation messages
https://github.com/user-attachments/assets/eda37e7c-d0f4-47be-9553-edcb46f6eb16
> refactor(eas-cli): polish the dev domain prompt

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/alias.ts
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/worker/deployment.ts
This change makes `eas deploy` always assume we are uploading a static project. That means you could upload just a folder with `output/index.html` file in an Expo project.
- Rewrote project detection to assume `static` projects by default (making `single` also work)
- Only switch to `server` when `output: server` is detected, just by folder names
- Add `created X ago` to the project type in deploy output
> refactor(eas-cli): always default to static uploads and add modified time

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
After user testing `eas-cli@12.4.0` we found out that this is still a bit confusing.
- Restored the "export not found, export with <command>" error
- Reword `created X ago` to `exported X ago`
- Hide `exported X ago` for exports within 1m
- `$ eas deploy`
- `$ npx expo export --platform web && eas deploy`
- `$ eas deploy --export-dir non-existing`
> fix(eas-cli): restore "export not found" error and hide recent exports

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/alias.ts
- packages/eas-cli/src/commands/worker/deploy.ts
The default "Environment variable's environment" explanation isn't enough to describe what it will do for new users. This changes that.
- Enhanced `eas deploy --help`'s `--environment` description
- `$ eas deploy --help`
> refactor(eas-cli): enhance the `--environment` help description

- CHANGELOG.md
- packages/eas-cli/src/worker/deployment.ts
This drops the extra space between `<input> .staging.expo.app` after choosing a project URL.
- Dropped cursor space after selecting project URL
> refactor(eas-cli): remove the cursor space when prompting dev domain after input

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
I parallized these two actions to make the command as fast as possible. Unfortunately, this has the side effect of conflating a prompt with a command error (as seen in the screenshot below).
This reverts the parallized action back into two stages, where they can't be mixed up.
- First validate if a (valid) export is available
- Then validate if the project is set up properly
- `$ bun create expo ./test`
- `$ cd ./test`
- `$ eas deploy`
- Should not trigger the prompt in the screenshot, only the error
> fix(eas-cli): check if export is available before validating project

- CHANGELOG.md
- packages/eas-cli/src/worker/deployment.ts
As discussed in Slack, to align the CLI prompts with the website/dashboard information.
- Reworded the prompts and error messages to mention "preview URL"
- `$ bun create expo ./test-prompt`
- `$ cd ./test-prompt`
- `$ eas worker`
> refactor(eas-cli): reword dev domain prompt to use "preview URL"

- CHANGELOG.md
- packages/eas-cli/src/project/android/applicationId.ts
- packages/eas-cli/src/project/ios/bundleIdentifier.ts
In a submit job we're going to have an IPA/APK to submit. We don't want to resolve any bundle identifiers from the project, we can use one from that IPA/APK.
Let the override env variable override bundle identifier resolution if the workflow is managed too.
I used it to submit an IPA with workflows.
> [eas-cli] Let iOS bundle identifier override always

- CHANGELOG.md
- packages/eas-cli/src/worker/upload.ts
We accidentally were hiding asset upload errors, which should be shown.
Remove code ignoring upload errors accidentally.
Manually tested
> [eas-cli] Fix worker asset upload error not being shown

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/worker/utils/logs.ts
The initial version was a bit conservative, nesting objects to not mix `dashboardUrl` with deployments. This change flattens the `deployment` object into the root object when running with `--json`.
- Flattened the `deployment` object into the root object when running `eas deploy --json`
> refactor(eas-cli): simplify the output of `eas deploy --json`

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/worker/assets.ts
Previously, we checked on the existence of both `/dist/client` and `/dist/server` to enable a deployment for API routes. With upcoming changes in Expo Router, we'd need to support a "server only" deployment. This means, we can't check `/dist/client` as it might not exist.
- Check on `/dist/server/_expo/routes.json` to enable server deployments
- Make `/dist/client` optional during upload
- `$ bun create expo ./test-server-only`
- `$ cd ./test-server-only`
- Create an API route, e.g. `app/test+api.ts` with:
```ts
export function GET() {
return Response.json({ ok: true });
}
```
- Change the output type to `server` in `app.json`'s `web.output = server`.
- `$ rm -rf ./dist/client`
- `$ easd deploy`
> refactor(eas-cli): allow Expo Router server deployments without client directory

- CHANGELOG.md
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/worker/deployment.ts
When running `eas worker --non-interactive`, it aborts on the first deployment due to a missing dev domain name. This changes that by automatically assigning the suggested dev domain when running in non interactive mode.
- Split out prompting dev domain from assigning dev domain
- Automatically assign the suggested dev domain when running in non interactive mode
Test the auto-assignment of the dev domain
- `$ export EXPO_STAGING=1`
- `$ bun create expo ./test-auto-assign`
- `$ cd ./test-auto-assign`
- `$ bun expo export --platform web`
- `$ easd init`
- `$ easd deploy --non-interactive`
<details><summary>Example</summary>
</details>
Test the manual assignment of the dev domain
- `$ export EXPO_STAGING=1`
- `$ bun create expo ./test-manual-assign`
- `$ cd ./test-manual-assign`
- `$ bun …
> refactor(eas-cli): support assigning dev domain in non interactive mode

- packages/eas-cli/src/build/evaluateConfigWithEnvVarsAsync.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commandUtils/flags.ts
- packages/eas-cli/src/commands/build/index.ts
- packages/eas-cli/src/commands/build/resign.ts
- packages/eas-cli/src/commands/build/version/get.ts
- packages/eas-cli/src/commands/build/version/set.ts
- packages/eas-cli/src/commands/build/version/sync.ts
- packages/eas-cli/src/commands/config.ts
On Friday's meeting, we agreed that having both a flag and a field in the build profile for setting the environment might be too much. Additionally, we already have a `--profile` flag that has a `-e` alias which makes it even more confusing. We decided to delete the flag to avoid confusion and make it as straightforward as possible.
Delete the `--environment` flag for build-related commands, rely only on the `environment` field in eas.json.
Tests
> [eas-cli] stop using environment flag in build related commands

- CHANGELOG.md
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/__tests__/republish.test.ts
- packages/eas-cli/src/commands/update/__tests__/roll-back-to-embedded.test.ts
- packages/eas-cli/src/commands/update/republish.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/update/__tests__/getBranchFromChannelNameAndCreateAndLinkIfNotExistsAsync-test.ts
- packages/eas-cli/src/update/getBranchFromChannelNameAndCreateAndLinkIfNotExistsAsync.ts
- packages/eas-cli/src/update/republish.ts
This adds the ability to republish an update group from one branch to another. This will help make the update promotion workflows more seamless. The update group must have the same code signing key.
Add command.
```
$ eas branch:list
Branches:
Branch           hello
Platforms        android, ios
Runtime Version  1.0.0
Message          "Initial commit
Generated by create-expo-app 3.0.0." (12 seconds ago by wschurman)
Group ID         62414475-44c3-43c6-b2bd-ed9f864789f9
———
Branch           production
Platforms        N/A
Runtime Version  N/A
Message          N/A
Group ID         N/A
———
Branch           main
Platforms        android, ios
Runtime Version  1.0.0
Message          "Initial commit
```
```
$ neas update:republish --branch hello --destination-branch production
✔ Load more update …
```
> [eas-cli] Add destination branch arguments to update:republish command

- CHANGELOG.md
- packages/eas-cli/src/credentials/manager/Actions.ts
- packages/eas-cli/src/credentials/manager/AndroidActions.ts
- packages/eas-cli/src/credentials/manager/IosActions.ts
- packages/eas-cli/src/credentials/manager/ManageAndroid.ts
- packages/eas-cli/src/credentials/manager/ManageIos.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1726226230206999
Right now the only way to exit the `eas credentials` command is to kill the process by doing ctrl+c. Let's add an `exit` option to the interactive menu.
Add exit option to menu.
Test manually
> [eas-cli] add exit option to eas credentials interactive menu

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/worker/assets.ts
- packages/eas-cli/src/worker/upload.ts
Depends on: https://github.com/expo/expo-easy-poc/pull/52
Previously, there was no concept of "finalizing" a deployment, which meant:
- the last asset upload implicitly "finalizes" the deployment and marks it as failed or complete
- if any asset upload failed, the deployment wouldn't delete itself, since it doesn't know whether the CLI will retry
- we accepted a full map object of upload URLs rather than reusing tokens, since the API didn't check if an asset or deployment were known
- Validate new result payload from `/deploy` endpoint
- Construct upload URLs to `/asset/:hash?token=`
- Add call to `/deploy/finalize?token=` after uploading assets
- Manually tested against staging deployment
> refactor(eas-cli): Implement updated deployment upload flow

- CHANGELOG.md
- packages/eas-cli/src/update/republish.ts
What it means to republish an update that is being rolled-out is undefined behavior. Rather than try to guess at the user's intent, just throw an error in this case and give guidance about other options to help them clarify intent.
Note that this doesn't hide the groups during interactive chooser, since that'd be even more confusing IMO.
Closes ENG-13613.
Throw error when any update being republished is a rollout update.
```
$ neas update:republish --branch main
✔ Load more update groups? › [Aug 19 16:23 by wschurman, runtimeVersion: 1.0.0] wat2
✔ The republished update group will appear only on: all
✔ Provide an update message. … dsadsasd
Cannot republish an update that is being rolled-out. Either complete the update rollout and then republish or publish a new rollout update.
Error: …
```
> [eas-cli] Disallow republishing an update that is being rolled-out

- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/commands/env/update.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/mutations/EnvironmentVariableMutation.ts
[ENG-13525 Update EAS-CLI for new EnvVar features](https://linear.app/expo/issue/ENG-13525/update-eas-cli-for-new-envvar-features)
Bring up to date `create` and `update` EnvVar mutations.
* Use `updateEnvironmentVariable` operation instead of `createEnvironmentVariable` with an 'overwrite' option.
* Add `type` parameter
* Add `environment` parameter for shared variables
Tested manually, tests will be added in the following PRs
> Update EnvironmentVariableMutation and associated commands

- packages/eas-cli/src/commandUtils/flags.ts
- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/commands/env/delete.ts
- packages/eas-cli/src/commands/env/exec.ts
- packages/eas-cli/src/commands/env/get.ts
- packages/eas-cli/src/commands/env/link.ts
- packages/eas-cli/src/commands/env/list.ts
- packages/eas-cli/src/commands/env/pull.ts
- packages/eas-cli/src/commands/env/unlink.ts
- packages/eas-cli/src/commands/env/update.ts
- packages/eas-cli/src/utils/prompts.ts
EnvVar will support having multiple environments, CLI should support this.
* Add an optional parameter `multiple` to `promptVariableEnvironmentAsync`
* Update commands using `promptVariableEnvironmentAsync`
* Add a new flag `EASMultiEnvironmentFlag`
Tested manually, tests will be added in the following PRs
> Allow prompting for multiple environments

- packages/eas-cli/src/commandUtils/flags.ts
- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableGet.test.ts
- packages/eas-cli/src/commands/env/get.ts
- packages/eas-cli/src/graphql/queries/EnvironmentVariablesQuery.ts
Polished the interface:
- user is prompted for environment only when the name is ambiguous.
- changed `name` parameter to `variable-name`. 
All commands that were using `name` parameter to identify a single variable will use `variable-name` and `variable-environment` instead. This change will enable user to distinguish between `name` and `environment` that is identifying variable that is acted upon, and `name` and `environment` that is a parameter for command.
For example, when the user wants to update variable `TEST` that has environment `production` and change its name and change its environment, they can use:
`eas env:update --variable-name TEST …
> Add tests to EnvironmentVariableGet

- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableDelete.test.ts
- packages/eas-cli/src/commands/env/__tests__/__snapshots__/EnvironmentVariableDelete.test.ts.snap
- packages/eas-cli/src/commands/env/delete.ts
- packages/eas-cli/src/utils/variableUtils.ts
Improve the selector for the variable to delete, rename parameter `name` to `variable-name`. 
All commands that were using name parameter to identify a single variable will use variable-name and variable-environment instead. This change will enable user to distinguish between name and environment that is identifying variable that is acted upon, and name and environment that is a parameter for command.
For example, when the user wants to update variable TEST that has environment production and change its name and change its environment, they can use:
eas env:update --variable-name TEST --variable-environment production --name TEST-update --environment …
> Add tests for EnvironmentVariableDelete

- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableLink.test.ts
- packages/eas-cli/src/commands/env/link.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/queries/EnvironmentVariablesQuery.ts
Add tests, polish the interface
* Use `variable-name` and `variable-environment` to select the variable
* More robust selector of variable to remove ambiguity 
* Use multiselect to clearly indicate which environments are linked and which are not
* Automatic `link` and `unlink` action
All commands that were using name parameter to identify a single variable will use variable-name and variable-environment instead. This change will enable user to distinguish between name and environment that is identifying variable that is acted upon, and name and environment that is a parameter for command.
For example, when the user wants to update variable TEST that has …
> Refactor env:link, add tests

- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableList.test.ts
- packages/eas-cli/src/commands/env/list.ts
Allow selecting multiple environments to display variables from.
* Use `multiselect`, allow specifying multiple `environment` parameters
* List variables from all environments
Added tests
> Refactor env:list and add tests

- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableUnlink.test.ts
- packages/eas-cli/src/commands/env/unlink.ts
Update command to use multiple environments, polish the interface.
* use `variable-name` and `variable-environment` to select the variable
* Use `multiselect` and multiple `environment` parameters to allow unlinking multiple envs
All commands that were using name parameter to identify a single variable will use variable-name and variable-environment instead. This change will enable user to distinguish between name and environment that is identifying variable that is acted upon, and name and environment that is a parameter for command.
For example, when the user wants to update variable TEST that has environment production and change its name and change its …
> Refactor env:unlink, add tests

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
After implementing feedback from dogfooding, this feature is good to launch (or at least un-hide from the CLI).
This PR unhides the flag.
Inspect.
> [eas-cli] Unhide rollout-percentage flag on update publish command

- packages/eas-cli/package.json
- packages/eas-cli/src/__tests__/commands/utils.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commandUtils/context/DynamicProjectConfigContextField.ts
- packages/eas-cli/src/commandUtils/context/OptionalPrivateProjectConfigContextField.ts
- packages/eas-cli/src/commandUtils/context/PrivateProjectConfigContextField.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
- packages/eas-cli/src/commands/project/init.ts
- packages/eas-cli/src/commands/project/onboarding.ts
- packages/eas-cli/src/eas-update/utils.ts
- packages/eas-cli/src/metadata/download.ts
- packages/eas-cli/src/metadata/upload.ts
- packages/eas-cli/src/update/configure.ts
- packages/eas-cli/src/utils/expoCli.ts
- yarn.lock
Rely on ExpoConfig type from the `@expo/config` package in all places for consistency
Rely on ExpoConfig type from the `@expo/config` package in all places for consistency
Tests
> [eas-cli] remove @expo/config-types dependency

- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/commands/env/link.ts
`env:link` prompts user to select a variable interactively even in non-interactive mode.
> Fix in env:link command: fail in non-interactive mode if variable name is ambigous

- packages/eas-cli/src/commands/env/push.ts
- packages/eas-cli/src/graphql/mutations/EnvironmentVariableMutation.ts
`env:push` should support multiple environments, just like other `eas env:*` commands.
* Added `EASMultiEnvironmentFlag`
* Use `environments` input parameter in `createBulkEnvironmentVariablesForApp` mutation to create envvars with multiple envs
* Checking for each environment if variable exists, updating variable when its value doesn't change but environments do.
> Support multiple environments in env:push command

- packages/eas-cli/src/commandUtils/flags.ts
- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableCreate.test.ts
- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableUpdate.test.ts
- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/commands/env/update.ts
- packages/eas-cli/src/utils/prompts.ts
[ENG-13849: When no `--visibility` input is provided `eas env:create` should ask about it by default](https://linear.app/expo/issue/ENG-13849/when-no-visibility-input-is-provided-eas-envcreate-should-ask-about-it)
[ENG-13850: Use the same names for visibility options in EAS CLI as on website](https://linear.app/expo/issue/ENG-13850/use-the-same-names-for-visibility-options-in-eas-cli-as-on-website)
`eas env:*` commands were using obsolete names for visibility options: `public` and `secret`, instead of `plaintext` and `encrypted`. It should be updated.
Also, user is prompted for the variable visibility if not provided.
Updated tests
> Use the same names for visibility options in eas cli as on

- packages/eas-cli/src/commands/env/get.ts
[ENG-13848: Always ask for `environment` in `eas env:get` command](https://linear.app/expo/issue/ENG-13848/always-ask-for-environment-in-eas-envget-command)
> Always ask for environment in env:get

- packages/eas-cli/src/commands/env/get.ts
- packages/eas-cli/src/commands/env/list.ts
- packages/eas-cli/src/commands/env/pull.ts
- packages/eas-cli/src/commands/env/push.ts
- packages/eas-cli/src/commands/env/update.ts
- packages/eas-cli/src/utils/prompts.ts
[ENG-13846: Use lower-case environment names across all `eas env:xyz` commands for consistency](https://linear.app/expo/issue/ENG-13846/use-lower-case-environment-names-across-all-eas-envxyz-commands-for)
> Use lower case environment across all eas env commands

- packages/eas-cli/src/commands/env/list.ts
[ENG-13847: Show `no env vars found for this environment` if 0 env vars exist for given environment in `eas env:list`](https://linear.app/expo/issue/ENG-13847/show-no-env-vars-found-for-this-environment-if-0-env-vars-exist-for)
> Display message when env:list returns an empty result

- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/commands/env/update.ts
- packages/eas-cli/src/utils/prompts.ts
[ENG-13855: When creating `file` type env var in `env:create` ask about file path vs variable value](https://linear.app/expo/issue/ENG-13855/when-creating-file-type-env-var-in-envcreate-ask-about-file-path-vs)
> Ask for file path in env:* commands

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
This resolves the apple authentication errors currently plaguing Expo and [Fastlane](https://github.com/fastlane/fastlane/issues/26368)
- Upgraded to the latest `@expo/apple-utils`
Create a new project, login with apple when building for iOS.
> fix(eas-cli): resolve Apple authentication error

- packages/eas-cli/src/commands/env/push.ts
[ENG-13853: Prompt user to enter the environment when not provided vs fail and rerun when using `eas env:push`](https://linear.app/expo/issue/ENG-13853/prompt-user-to-enter-the-environment-when-not-provided-vs-fail-and)
If the environment is not provided, we ask the user about it in other commands, I think we can do the same here for consistency vs throwing an error and having the user rerun it
> Allow user to select environments manually in env:push

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/channel/__tests__/fixtures.ts
- packages/eas-cli/src/channel/queries.ts
- packages/eas-cli/src/commands/channel/pause.ts
- packages/eas-cli/src/commands/channel/resume.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/queries/ChannelQuery.ts
We want to allow developers to prevent updates from being served to certain builds by "pausing" update channels.
- I added two new CLI commands to toggle the channel pausing state
- I added the pause status to the channel details output in the `view` and `list` commands
Build the CLI locally under the `neas` alias, and run `neas channel:pause development && neas channel:view development && neas channel:resume development && neas channel:view development`:
> [eas-cli] add pause/resume commands for Update Channels

- CHANGELOG.md
- packages/eas-cli/src/commands/update/edit.ts
When writing the docs for update-based rollouts, I noticed that a) this command was still hidden, and b) it didn't have the best UX for interactive mode (https://github.com/expo/eas-cli/pull/2503 didn't add it)
a) unhide the command
b) Make group arg optional, add optional branch flag, and lead user through interactive process to choose an update group to edit if not supplied as an arg
Note that this doesn't filter update groups to those that are editable since it isn't currently possible to query. We can update this in the future if we want, but usability of the feature probably won't suffer much without it since it's likely the latest update group will always be the one chosen to be edited.
`neas update:edit`
`neas update:edit --branch main`
> [eas-cli] Add interactivity to eas update:edit command

- packages/eas-cli/src/build/evaluateConfigWithEnvVarsAsync.ts
Improve logs announcing loading env vars.
https://exponent-internal.slack.com/archives/C06FK950085/p1729215938823339?thread_ts=1729186741.835629&cid=C06FK950085
Improve logs
Test manually.
> [eas-cli] improve logs announcing loading of env variables

- packages/eas-cli/src/commands/env/pull.ts
- packages/eas-cli/src/commands/env/push.ts
File variables were not handled by the `env:pull` command. They should be downloaded just like the other values.
* `env:pull` saves file type variables to `.eas/.env` directory and sets its value in `.env.local` file to its file path
* `env:push` skips file type variables
> Make eas env:pull pull file env vars

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/EasCommand.ts
- packages/eas-cli/src/commandUtils/context/DynamicLoggedInContextField.ts
- packages/eas-cli/src/commandUtils/context/LoggedInContextField.ts
- packages/eas-cli/src/commandUtils/context/MaybeLoggedInContextField.ts
- packages/eas-cli/src/commands/account/view.ts
- packages/eas-cli/src/commands/config.ts
- packages/eas-cli/src/commands/project/__tests__/init.test.ts
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/__tests__/republish.test.ts
- packages/eas-cli/src/commands/update/__tests__/roll-back-to-embedded.test.ts
- packages/eas-cli/src/user/SessionManager.ts
Noticed while reviewing another PR that the `config` command was using the session management context, when that context should only be necessary to use in `login` and `logout` commands.
Digging in a bit, it was needed because the command only required being logged in in a certain conditional codepath, but there was no context construct available to support this.
Ref: https://github.com/expo/eas-cli/pull/2517
Ref: https://github.com/expo/eas-cli/pull/2461
Closes ENG-13892.
1. Add a new context field, `DynamicLoggedIn`, which requires log in but only when the context function is called.
2. Change `config` command to use this.
3. Change logged in contexts to also expose the authentication info so that session isn't needed in `account:view` command.
While both logged in and logged out:
``` …
```
> [eas-cli] Create dynamic logged in context field and clean up erroneous SessionManager context field uses

- packages/eas-cli/src/commands/env/pull.ts
[ENG-13929: eas env:pull overwrites all variables](https://linear.app/expo/issue/ENG-13929/eas-envpull-overwrites-all-variables)
`env:pull` should not overwrite existing values for encrypted variables, but leave them in `.env.local`.
> env:pull uses local values of encrypted variables

- packages/eas-cli/src/commands/env/pull.ts
[ENG-13928: Update "secret" with "encrypted" on eas env:pull](https://linear.app/expo/issue/ENG-13928/update-secret-with-encrypted-on-eas-envpull)
The message informing user about encrypted variables omission can be clearer.
> Improve wording in env:pull command

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
After fixing Apple authentication, we received some reports of unexpected "invalid account name and/or password" errors. These were related to the case sensitivity of the email, used when generating the proof of credentials for Apple (using RSP6a).
This fixes that.
- Make email case insensitive when authenticating with Apple
- `eas credentials`
- Select iOS
- Try to authenticate using a capital letter in the account name (or email)
> fix(eas-cli): make email case insensitive during apple auth

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/DynamicProjectConfigContextField.ts
- packages/eas-cli/src/commandUtils/context/OptionalPrivateProjectConfigContextField.ts
- packages/eas-cli/src/commandUtils/context/PrivateProjectConfigContextField.ts
- packages/eas-cli/src/commandUtils/context/ProjectIdContextField.ts
- packages/eas-cli/src/commandUtils/context/ServerSideEnvironmentVariablesContextField.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/__tests__/getProjectIdAsync-test.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
- packages/eas-cli/src/commands/project/__tests__/init.test.ts
- packages/eas-cli/src/commands/project/init.ts
- packages/eas-cli/src/commands/project/onboarding.ts
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/__tests__/roll-back-to-embedded.test.ts
- packages/eas-cli/src/credentials/__tests__/fixtures-context.ts
- packages/eas-cli/src/credentials/android/actions/BuildCredentialsUtils.ts
- packages/eas-cli/src/credentials/android/actions/CreateKeystore.ts
- packages/eas-cli/src/credentials/context.ts
- packages/eas-cli/src/credentials/ios/actions/BuildCredentialsUtils.ts
- packages/eas-cli/src/credentials/manager/ManageIos.ts
- packages/eas-cli/src/credentials/manager/SetUpIosBuildCredentials.ts
- packages/eas-cli/src/project/expoConfig.ts
- packages/eas-cli/src/project/ios/entitlements.ts
- packages/eas-cli/src/project/projectUtils.ts
https://exponent-internal.slack.com/archives/C02123T524U/p1724970663050089?thread_ts=1724924614.773089&cid=C02123T524U
https://exponent-internal.slack.com/archives/C5ERY0TAR/p1725002816077089
Generally `@expo/config`, `@expo/prebuild-config`, and `@expo/config-plugins` are per SDK concept. Currently, in EAS CLI, we rely on one version of the `@expo/...` package to work well globally for all SDKs. It seems to sometimes bite us like in the case of https://exponent-internal.slack.com/archives/C02123T524U/p1724909908574979, because SDK 51 config wasn't compatible with SDK 50.
It's better to switch to using config-related functions shipped with `@expo/config`, `@expo/prebuild-config`, and `@expo/config-plugins`.  I believe we can assume that `getConfig`, `getPrebuildConfig`, and …
> [eas-cli] use `npx expo config` command to resolve expo config if available

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/schema/metadata-0.json
- packages/eas-cli/src/metadata/apple/config/__tests__/fixtures/ageRatingDeclaration.ts
- packages/eas-cli/src/metadata/apple/config/__tests__/fixtures/appStoreVersion.ts
- packages/eas-cli/src/metadata/apple/config/reader.ts
- packages/eas-cli/src/metadata/apple/config/writer.ts
- packages/eas-cli/src/metadata/apple/types.ts
- yarn.lock
This changes a few properties from `apple.advisory.*` object in the store config. It's just an update to keep up with Apple's changes on the App Store.
- `seventeenPlus` - Dropped in favor of `ageRatingOverride`
- `ageRatingOverride` - New property to override the standard age rating
- `koreaAgeRatingOverride` - Same as `ageRatingOverride`, but for South Korea
If you see this, you can upgrade to use this new format:
- `eas metadata:pull`
> Yep, that's it.
Make sure you don't have any local changes, as this command will override your local store config.
- Updated to `@expo/apple-utils@2.1.0`
Both command should work fine for any listed app.
- `eas metadata:pull`
- `eas metadata:push`
> fix(eas-cli): update EAS Metadata with new props for App Store 3.6.0

- packages/eas-cli/package.json
- packages/eas-cli/src/commands/workflow/validate.ts
- packages/eas-cli/src/workflow/__tests__/validate-test.ts
- yarn.lock
This adds a command to validate YAML in workflow configuration files.
Create a .yml file and test it with `eas workflow:validate path/to/file.yml`. You should see output like the screenshots above.
- Make sure non existent files result in an error
- Make sure non .yml/.yaml files result in an error
- Make sure bad YAML results in an error
- Make sure good YAML results in no error
> Adds workflow:validate command

- CHANGELOG.md
- packages/eas-cli/src/utils/fingerprintCli.ts
This PR does the following:
- Add logs to notify user fingerprint is getting computed
- Lets user know they can skip fingerprint computation if it's taking longer than 5 seconds
- Skips fingerprint computation if `EAS_SKIP_AUTO_FINGERPRINT` is set, as per https://www.notion.so/expo/Soft-fingerprinting-116e5b5735248071951cddcab32ae43d?pvs=4#116e5b57352480e89189eb7feb88dacd
```
Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
✔ Uploaded to EAS 
⌛️ Computing project fingerprint taking longer than expected...
⏩ To skip this step, set the environment variable: EAS_SKIP_AUTO_FINGERPRINT=1
✔ Computed project fingerprint
```
> [eas-cli] improve fingerprint UX

- CHANGELOG.md
- packages/eas-cli/src/build/runBuildAndSubmit.ts
It's convenient to have this be the default value when trying to debug, so that the whole build can be used to debug. Not set on this, but wanted to see what others thought.
Closes ENG-14060.
Default when `Log.isDebug` is true and flag isn't provided.
1. `EXPO_DEBUG=1 neas build`, see debug logs in build.
> [build] Default build-logger-level to debug when EXPO_DEBUG is set

- packages/eas-cli/src/vcs/clients/noVcs.ts
https://staging.expo.dev/accounts/sjchmiela/projects/staging-app/workflows/01932b13-21af-780b-b531-1ed07e3d8228
`eas update --auto` fails in GCS update job because this flag is set to true.
The comment says it can be `false`, so changed it to `false`.
https://github.com/expo/eas-cli/pull/2148/files#diff-a594e233350755033d45aa7b21b78781e4b36322e9312f60e71e7edc79c33a7f
Update message should be changed to `undefined`.
> [eas-cli] Default update message to `undefined` in no-VCS client

- packages/eas-cli/src/commandUtils/flags.ts
- packages/eas-cli/src/commands/update/configure.ts
- packages/eas-cli/src/commands/update/index.ts
During dogfooding it came out that this flag is too long and confusing
Just use `environment`
Tests, types
> [ENG-14180][eas-cli] rename with-as-environment-variables-set eas update flag to environment

- packages/eas-cli/src/utils/prompts.ts
Companion to https://github.com/expo/universe/pull/17484
https://linear.app/expo/issue/ENG-14183/rename-env-vars-visibility-options
Rename encrypted to secret
Tests
> [ENG-14183][website] rename encrypted visibility type to secret

- packages/eas-cli/src/build/evaluateConfigWithEnvVarsAsync.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/loadServerSideEnvironmentVariablesAsync.ts
https://linear.app/expo/issue/ENG-14184/make-eas-cli-print-less-spamy-logs-related-to-loading-env-variables
Make logs less noisy as proposed by Brent
Tests
> [ENG-14184][eas-cli] make logs anouncing loading env variables less noisy

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/commands/workflow/run.ts
- packages/eas-cli/src/commands/workflow/validate.ts
Going to release soon.
Removed `hidden = true` overrides.
`easd --help` printed out information about workflow commands.
```
~/Developer/test-local (main [$!]) easd --help
EAS command line tool
VERSION
eas-cli/13.1.1 darwin-arm64 node-v22.4.0
USAGE
$ eas [COMMAND]
TOPICS
...
workflow     manage workflows
```
```
~/Developer/test-local (main [$!]) easd workflow --help                       
manage workflows
USAGE
$ eas workflow:COMMAND
COMMANDS
workflow:run       Run an EAS workflow
workflow:validate  validate a workflow configuration yaml file
```
> [eas-cli] Unhide workflow commands

- packages/eas-cli/src/commandUtils/flags.ts
- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableCreate.test.ts
- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/commands/env/pull.ts
- packages/eas-cli/src/commands/env/update.ts
- packages/eas-cli/src/utils/prompts.ts
`Encrypted` variables were renamed to `secret`, but it was omitted in a couple places.
Updated tests, tested manually
> Environment Variables: Rename `encrypted` to `secret`

- packages/eas-cli/src/commandUtils/flags.ts
- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableCreate.test.ts
- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableLink.test.ts
- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableList.test.ts
- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableUnlink.test.ts
- packages/eas-cli/src/commands/env/__tests__/EnvironmentVariableUpdate.test.ts
- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/commands/env/delete.ts
- packages/eas-cli/src/commands/env/get.ts
- packages/eas-cli/src/commands/env/link.ts
- packages/eas-cli/src/commands/env/list.ts
- packages/eas-cli/src/commands/env/push.ts
- packages/eas-cli/src/commands/env/unlink.ts
- packages/eas-cli/src/commands/env/update.ts
Stick to account-wide everywhere for now
Rename shared to account-wide, fix some bugs and type issues
Tests
> [ENG-14185][eas-cli] use account-wide vs shared in env commands

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/project/resolveRuntimeVersionAsync.ts
- packages/eas-cli/src/utils/expodash/mapMapAsync.ts
- packages/eas-cli/src/utils/fingerprintCli.ts
This PR computes a fingerprint for each update. 
- If the update does not use the fingerprint policy, it calculates the fingerprint using the exported cli in the `expo` package for projects SDK 52+. 
- If the update uses the fingerprint policy, it just uses the fingerprint that was previously calculated using `expo-updates`.  
- Modified fingerprint computation to handle platform-specific cases
- Updated the fingerprint data structure to use `fingerprintHash` instead of the full fingerprint object
- Added support for computing fingerprints for projects without expo-updates
- Introduced new types and interfaces for handling fingerprint information groups
- Created utility functions for async map operations and fingerprint calculations
- Updated GraphQL schema to support new …
> [eas-cli] create fingerprint on each update

- packages/eas-cli/src/commands/env/__tests__/EnvCreate.test.ts
- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/graphql/mutations/EnvironmentVariableMutation.ts
[ENG-14274: Remove linking from eas-cli](https://linear.app/expo/issue/ENG-14274/remove-linking-from-eas-cli)
Initial release will not include linking account-wide variables to specific projects - they all should be global.
Without explicitly setting `isGlobal` flag, account-wide envvars would be created as non-global, without possibility to link it to anything.
* Added `isGlobal` = true to requests
* Also, removed unnecessary check in non-interactive mode - user should be able to create an account-wide variable with environments without linking it to the current project.
Updated tests
> All account-wide envvars should be global (for now)

- CHANGELOG.md
- packages/eas-cli/src/commands/secret/create.ts
- packages/eas-cli/src/commands/secret/delete.ts
- packages/eas-cli/src/commands/secret/list.ts
- packages/eas-cli/src/commands/secret/push.ts
Deprecate old secret commands
Mark as hidden + print warn when used
Tests
> [ENG-14249][eas-cli] deprecate eas secret commands

- CHANGELOG.md
- packages/eas-cli/src/build/evaluateConfigWithEnvVarsAsync.ts
https://exponent-internal.slack.com/archives/C06FK950085/p1729212611408479?thread_ts=1729186741.835629&cid=C06FK950085
Resolve the default (if not set in the build profile) `environment` to use for a build based on its configuration.
Store build -> `production`
Dev client -> `development`
Other (`internal`) -> `preview`
Test manually
> [ENG-13252][eas-cli] resolve default environment automatically based on build configuration

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/branch/queries.ts
- packages/eas-cli/src/commands/update/__tests__/index.test.ts
- packages/eas-cli/src/commands/update/__tests__/roll-back-to-embedded.test.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/rollout/actions/CreateRollout.ts
- packages/eas-cli/src/rollout/actions/EditRollout.ts
- packages/eas-cli/src/rollout/actions/EndRollout.ts
- packages/eas-cli/src/rollout/actions/ManageRollout.ts
- packages/eas-cli/src/rollout/actions/NonInteractiveRollout.ts
- packages/eas-cli/src/rollout/actions/RolloutMainMenu.ts
- packages/eas-cli/src/rollout/actions/SelectRuntime.ts
- packages/eas-cli/src/update/getBranchFromChannelNameAndCreateAndLinkIfNotExistsAsync.ts
After discussion with @quinlanj  about whether fingerprints should be taken during roll-back-to-embedded publish, we realized that this command actually probably shouldn't rely on the current state of the project in the current working directory for anything (except code signing, but that's an edge case).
The reason for this is that one shouldn't have to check out a release branch to publish the roll-back-to-embedded directive since fingerprint might differ if branch is stale and deps change under the hood, thus making it impossible to issue the directive for the desired binary (rtv).
Closes ENG-14282.
Make this behave more like a rollout or roll-back-to-embedded on the website: ask for all info rather than gathering it from the current working directory.
Run test.
Manual test:
```
$ neas …
```
> [eas-cli][eas-update] Change behavior of roll-back-to-embedded to not use current project state

- CHANGELOG.md
- packages/eas-cli/src/build/validate.ts
https://discord.com/channels/695411232856997968/1309202098591633458/1311040361040183429
Make warning up to date after recent env vars changes
> [eas-cli] fix warning for gitignored google services file

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
https://linear.app/expo/issue/ENG-14410/building-bare-ios-project-on-eas-fails-from-eas-cli1342-on-windows
@byCedric fixed it in https://github.com/expo/expo/blob/sdk-52/packages/%40expo/config-plugins/CHANGELOG.md#9012--2024-12-05, so I use this version for EAS CLI here
Tests
> [ENG-14410] update `@expo/config` and `@expo/config-plugins` to fix eas build command for bare iOS projects on Windows

- packages/eas-cli/package.json
By default, the update notice prints:
```
★ eas-cli@12.6.2 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.
```
This is slightly hard to copy and paste, and has a trailing period that needs to be removed.
This puts it on a new line without the period
```
★ eas-cli@12.6.2 is now available.
To upgrade, run:
npm install -g eas-cli
Proceeding with outdated version.
```
This means you can just triple click, copy, and paste and then it'll run.
> Change package.json update message to allow faster copy and paste

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
Apple changed their auth servers for the SMS endpoint to seemingly geotag sms requests to American devices. This caused the error "Verification codes can’t be sent to this phone number at this time. Please try again later." to be thrown when requesting two-factor authentication with an SMS device.
This PR, in addition to a few others, aims to align the API such that SMS codes can successfully be sent to American phone numbers. I can only verify 4 times every hour, so this may only partially fix the issue.
`eas build -p ios` -> login -> Pick `sms` for the 2fa.
> fix SMS TFA for Apple authentication

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
https://github.com/expo/third-party/pull/115 
https://exponent-internal.slack.com/archives/C017N0N99RA/p1733768696103679
bump apple utils to link to FYI page mentioning workaround for Apple 2fa SMS issues
bump apple-utils
tests
> [eas-cli] bump @expo/apple-utils to add fyi link for apple 2fa sms failure

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/credentials/context.ts
- packages/eas-cli/src/credentials/ios/actions/SetUpTargetBuildCredentials.ts
- packages/eas-cli/src/credentials/ios/appstore/__tests__/bundleIdCapabilities-test.ts
- packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts
- packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts
- yarn.lock
Companion to https://github.com/expo/expo/pull/32623 and https://github.com/expo/third-party/pull/113
https://exponent-internal.slack.com/archives/C02123T524U/p1728981742266059
We want to handle new broadcast push notifications option for push notifications capability
It's a bit atypical because there's no way to enable it by using entitlement (this is how it works for the rest of the capabilities using options). I talked about it with @brentvatne and we decided to add a new field to the app config to manage this option `ios.usesBroadcastPushNotifications`.
If `usesBroadcastPushNotifications` is `true` and push notification entitlement is set use the correct option for the push notification capability in Apple's API.
Make sure that we update the capability at the correct times:
- when the …
> [eas-cli] add support for broadcast push notifications option for push notifications capability

- CHANGELOG.md
- packages/eas-cli/src/branch/utils.ts
- packages/eas-cli/src/commands/branch/create.ts
- packages/eas-cli/src/project/publish.ts
https://exponent-internal.slack.com/archives/C06EFBQK3B7/p1732217583248979
We should never be defaulting to a random branch name for an EAS Update. This would have disastrous consequences for usability and our interfaces, as well as for publishes and channel-branch mappings.
For workflows, this problem is more in the foreground since there's no VCS on the workflow runner.
Closes ENG-14314.
Remove fallback, throw an descriptive error when needed.
Run `neas update --auto` in a directory that doesn't have vcs (remove .git folder). See other error indicating that VCS is required.
Run `neas branch:create`, see that there's no default suggestion in the prompt.
```
$ neas update --auto
It looks like you haven't initialized the git repository yet.
EAS requires you to use a git repository for your …
```
> [eas-cli] Remove random branch name generation for --auto branch name non-vcs fallback

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
There's a CVE in dicer and there's no fix planned: https://github.com/advisories/GHSA-wm7h-9275-46v2
mscdex/dicer#22
`@expo/multipart-body-parser` used dicer until 2.0.0.
Closes ENG-14330.
Fixes https://github.com/expo/expo/issues/20225.
Version 2.0.0 of `@expo/multipart-body-parser` moved it off of dicer.
Publish a code signed update (the part of eas-cli that uses this library):
```
neas update --private-key-path keys/private-key.pem
```
> [eas-cli] Upgrade @expo/multipart-body-parser

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
This outputs a tarball to `deploy.tar.gz` if the `--dry-run` flag is passed, skipping all other work.
- Added flag
- Add early abort with `fs.promises.copyFile` run
> feat(eas-cli): Add `--dry-run` flag to `deploy` command

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
The `--environment` flag was getting sanitised out of the flags so it was always `undefined`.
Added the `environment` flag to `sanitizeFlags`.
Also switched to using the shared `EASEnvironmentFlag` which does additional validation and transforms the flag to uppercase.
Tested locally that `easd deploy --environment production` includes env vars in api routes.
> [eas-cli] Add environment flag to deploy script

- packages/eas-cli/src/commands/update/index.ts
[ENG-14328: store `environment` info on update entity](https://linear.app/expo/issue/ENG-14328/store-environment-info-on-update-entity)
Pass `environment` to `PublishMutation.publishUpdateGroupAsync` to store in the db.
Waits for changes on the `www`. https://github.com/expo/universe/pull/17921
> [ENG-14328] Pass environment to PublishMutation.publishUpdateGroupAsync

- CHANGELOG.md
- packages/eas-cli/src/commands/env/exec.ts
Don't throw an error if no readable env vars are present. Make logs less noisy.
Don't throw an error if no readable env vars are present. Make logs less noisy.
> [eas-cli] improvements to eas env:exec command

- CHANGELOG.md
- packages/eas-cli/src/worker/upload.ts
The error messages from `403` upload error were not being shown in the terminal.
Extract the error message from `403` errors and show to the user when applicable.
Tested locally by uploading a build with 100+ assets.
<details>
<summary>
Before / After
</summary>
</details>
> [eas-cli] show deployment errors

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/alias.ts
- packages/eas-cli/src/commands/worker/deploy.ts
> [eas-cli] Update `deploy`/`alias` log output copy

- CHANGELOG.md
- packages/eas-cli/src/worker/upload.ts
Fixes a regression I introduced in https://github.com/expo/eas-cli/pull/2771/files
_Successful_ deployments error because the body is already parsed.
Only parse the request body when to show the error message when needed.
Ensure `eas deploy` works without errors.
> [eas-cli] parse request body for error only when needed

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/contextUtils/loadServerSideEnvironmentVariablesAsync.ts
- packages/eas-cli/src/commands/build/version/sync.ts
- packages/eas-cli/src/commands/device/delete.ts
- packages/eas-cli/src/commands/device/rename.ts
- packages/eas-cli/src/commands/env/exec.ts
- packages/eas-cli/src/devices/actions/create/currentMachineMethod.ts
- packages/eas-cli/src/devices/actions/create/inputMethod.ts
- packages/eas-cli/src/project/fetchOrCreateProjectIDForWriteToConfigWithConfirmationAsync.ts
- packages/eas-cli/src/utils/statuspageService.ts
Fixes ENG-14562
Fixes ENG-14458
Fixes ENG-10850
Wording tweaks for EAS CLI messages.
The changes have been reviewed by running CLI locally.
> [eas-cli] wording tweaks for messages

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/tsconfig.json
- packages/eas-json/package.json
- packages/eas-json/tsconfig.json
- yarn.lock
Followup from https://github.com/expo/eas-cli/pull/2736#discussion_r1868462449
Standardize TypeScript configuration across packages by adopting the recommended Node.js 18 TypeScript configuration. This helps ensure consistent TypeScript settings and reduces configuration duplication.
- Added `@tsconfig/node18` dependency to `eas-cli` and `eas-json` packages
- Extended the base Node 18 TypeScript configuration in both packages
- Removed redundant compiler options that are already included in the Node 18 preset
- Updated module resolution strategy to explicitly use "node"
Current tests pass
> [eas-cli][eas-json] use node18 as tsconfig base

- CHANGELOG.md
- packages/eas-cli/src/build/android/build.ts
- packages/eas-cli/src/credentials/android/AndroidCredentialsProvider.ts
- packages/eas-json/src/__tests__/buildProfiles-test.ts
- packages/eas-json/src/build/schema.ts
- packages/eas-json/src/build/types.ts
[ENG-14518: Add `keystoreName` field to build profile to allow selecting/creating named keystore to use for a build](https://linear.app/expo/issue/ENG-14518/add-keystorename-field-to-build-profile-to-allow-selectingcreating)
Allow specifying keystore name of credentials to be used with a build.
* Added `keystoreName` to eas.json schema
* Pass `name` option to `AndroidCredentialsProvider`
Added test, tested manually.
1. Create a new android credentials with `eas credentials`
2. Specify `keystoreName` in build profile in `eas.json`
3. Ensure that it works only for android builds
4. Ensure it works only for `remote` `credentialsSource`
5. Ensure that the correct credentials are used
> ENG-14518 Add keystoreName field to build profile

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
fixes https://github.com/expo/eas-cli/issues/2782
`@expo/package-manager@1.7.0` supports bun text-based lock file. this pr bumps the version
ci passed
> [eas-cli] bump package-manager version

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/commands/worker/deploy.ts
- packages/eas-cli/src/worker/assets.ts
- yarn.lock
This allows `--environment` to be combined with local `.env` files, outputting a warning when any variables conflict since EAS environment variables will take precedence.
- Update `createManifestAsync` to return `manifest` and conflicting variable names
- Always call `getEnv` and merge variables into the `env` object
- Output names when conflicts occurred
- Tested locally
> [eas-cli] Combine `.env` and EAS environment variables for `deploy` command

- CHANGELOG.md
- packages/eas-cli/src/commands/env/exec.ts
When using this programmatically to run a command, `env:exec` shouldn't modify the stdout of the sub-command. This makes it possible to run a JSON command, for example.
Concretely, this came up in https://github.com/expo/expo-github-action/pull/316/files#diff-9a4c8863ad4d04f246a265d420c404b948ffcd8902e7de5312c9205cd034fa2eR226 where we are trying to run `npx expo-updates fingerprint:generate` which outputs JSON.
One solution (this solution) is to slightly overload the `non-interactive` flag to also silence all non-command output. Alternatively we could add a separate flag.
I chose to overload the existing flag since I couldn't think of a reason that a non-interactive scenario would want the `Log.log` calls. That being said, I'm open to adding a separate flag like `--raw` or …
> [eas-cli] Silence all non-command output in non-interactive mode of eas env:exec

- CHANGELOG.md
- packages/eas-cli/src/build/evaluateConfigWithEnvVarsAsync.ts
https://linear.app/expo/issue/ENG-14643/shorten-the-message-about-env-selection-for-a-build
Shorten the message about env selection for a build
Test manually
> [ENG-14643][eas-cli] make automatic env resolution message shorter

- CHANGELOG.md
- packages/eas-cli/src/build/android/version.ts
- packages/eas-cli/src/build/ios/version.ts
https://linear.app/expo/issue/ENG-14644/make-no-remote-versions-are-configured-message-green-instead-of-yellow
make "No remote versions are configured" message green instead of yellow
Tests
> [ENG-14644][eas-cli] make "No remote versions are configured" message green instead of yellow

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/fingerprint/compare.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/mutations/FingerprintMutation.ts
Upload the locally computed fingerprint to `www` when someone runs `eas fingerprint:compare` so they can view the diff easier from a website ui
- Added new GraphQL types and mutations for fingerprint management
- Implemented fingerprint comparison functionality in the CLI
- Added support for uploading fingerprints to the server
> [eas-cli] upload fingerprint from local project state

- CHANGELOG.md
- packages/eas-cli/src/commands/env/exec.ts
Rebase and update of https://github.com/expo/eas-cli/pull/2788. (couldn't push to remote to update that PR, would be good to get this in soon).
Cherry-pick, rebase, apply requested changes.
Same as https://github.com/expo/eas-cli/pull/2788.
Manual test:
```
$ neas env:exec preview "npx expo config --json --type publicd" --non-interactive && echo "hello"
$ neas env:exec preview "npx expo config --json --type public" --non-interactive && echo "hello"
{"name":"pkfsapjfasafj...hello
```
> [eas-cli] Enhance `eas env:exec` command by enabling shell execution for commands

- CHANGELOG.md
- packages/eas-cli/src/build/local.ts
As mentioned in my original issue (https://github.com/expo/eas-cli/issues/2782#issuecomment-2591174852), Bun introduced a new text based `bun.lock` file with their Bun v1.1.39+. 
This new lock file was supported by EAS in the cloud builds as seen in PRs https://github.com/expo/eas-cli/pull/2801 abd https://github.com/expo/eas-build/pull/482, and indeed upon verification works perfectly fine in cloud builds (https://expo.dev/accounts/mubin-memorang/projects/new-bun-lock/builds/a8f5d20f-20b8-4b20-9430-cbf48ba88103)
This however was not working with the `--local` flag. 
Upon inspection, the `eas-cli-local-build-plugin` is not updated to the latest version that reflects this new lockfile related changes.
> Bump eas-cli-local-build-plugin to latest version to support new bun lock file

- CHANGELOG.md
- packages/eas-cli/src/commands/worker/deploy.ts
Minor logs tweaks to the `deploy` command.
- hosting is in "preview" (not "beta")
- remove errant curly when logging out when the project was last exported
Run `eas deploy` and verify the logs are printed out correctly.
> [eas-cli] fix deploy command typos

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/project/resolveRuntimeVersionAsync.ts
This renames some fields of runtime version info to make it clearer where the fingerprint source is coming from.
It also stops uploading `runtimeFingerprintSource` as that is no longer used on the server.
Rename, tsc.
Remove field.
With both fingerprint runtime version policy and without, run `neas update` to ensure it works. (ensure fingerprint is attached to runtime version  by checking runtime permalink on website and downloading the fingerprint)
> [eas-cli] Make variable naming more explicit, remove deprecated runtimeFingerprintSource uses

- CHANGELOG.md
- packages/eas-cli/src/worker/upload.ts
The apple app site association file (needed for Universal linking on iOS) does not have a file extension, as it's simply served from `/.well-known/apple-app-site-association`.
However in order for it to be valid, the file need to return `Content-Type: application/json` header.
When content type cannot be detected form the mime type, try parsing the file to check if it's a valid JSON and set the header accordingly.
Deploy a website with an `apple-app-site-association` file and verify that the `Content-Type` header is set to `application/json`.
> [eas-cli] Detect valid JSON files during hosting upload

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/appstore/__tests__/resolveCredentials-test.ts
- packages/eas-cli/src/credentials/ios/appstore/resolveCredentials.ts
https://linear.app/expo/issue/ENG-14629/improve-apple-id-input-validation
- user was asked to log into their Apple account
- prompt displayed for the username, pre-filled with value from cache
- value from cache contains invalid, unprintable characters (`\u0017`)
- user accepts "correct" username
- fails to log in
- user removes the cache file
- logs in successfully when manually typing "the same" username (but without invalid characters)
The username value from prompt is cleared of any invalid unprintable characters before updating cache and using the value to log into Apple account
Added tests for `resolveUserCredentialsAsync` function
Tested the behaviour for a username with reported invalid characters
> [eas-cli] [ENG-14629] Improve AppleID validation

- CHANGELOG.md
- packages/eas-cli/src/build/android/__tests__/version-test.ts
- packages/eas-cli/src/build/android/version.ts
- packages/eas-cli/src/build/ios/__tests__/version-test.ts
- packages/eas-cli/src/build/ios/version.ts
https://linear.app/expo/issue/ENG-14633/start-autoincrement-counter-at-0-so-first-build-has-buildnumber-==-1
When versionCode/buildNumber is initialised ignore autoIncrement and use the initial version
Added tests
> [eas-cli] [ENG-14633] Start autoIncremented builds at 1

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/appstore/__tests__/ensureAppExists-test.ts
- packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts
- packages/eas-cli/src/submit/ios/AppProduce.ts
If the name you selected was taken, it's a bit of a hassle to pick a new one. We had a fallback error message that said to use `--app-name` but this isn't a real flag afaict, and the fallback was never called!
This change catches the duplicate name error and warns that a generated name will be used instead. This name can be instantly changed from the App Store Connect website later so it seems like a better default to ensure complex commands like `eas build --auto-submit` are less prone to failure.
- Added some unit tests to emulate the responses of invalid fixtures.
- Create a project with the name `expo`
- Run `eas submit`
- Observe a warning log like `App name "expo" is already taken. Using generated name "expo (6eb7d6)" which can be changed later from …
> feat(eas-cli): Use a fallback generated name during EAS Submit

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts
- packages/eas-cli/src/credentials/ios/appstore/ensureTestFlightGroup.ts
- packages/eas-cli/src/credentials/ios/appstore/provisioningProfile.ts
- packages/eas-cli/src/project/ios/__tests__/target-test.ts
- packages/eas-cli/src/submit/ios/AppProduce.ts
- yarn.lock
- During `eas submit -p ios`, automatically create an internal TestFlight group `Internal (Expo)` and add all App Managers to it.
- Assuming that non-exempt encryption is set before the build—`expo.ios.infoPlist.ITSAppUsesNonExemptEncryption` in the app.json—then all app admins will have instant access to new builds from TestFlight.
- This greatly streamlines the time-to-testing for developers.
---
- Should we make this feature opt-in? I feel like it's good enough to just have on by default.
- Should there be comprehensive eas.json config settings for configuring the group and adding other groups? Maybe that's out of scope for this PR?
- External groups require manual assignment which would need to take place after a build and not before it. For this, we'd likely want to run the API calls …
> feat: add internal TestFlight group to submit

- CHANGELOG.md
- packages/eas-cli/__mocks__/fs.ts
- packages/eas-cli/src/build/ios/build.ts
- packages/eas-cli/src/project/ios/__tests__/exemptEncryption-test.ts
- packages/eas-cli/src/project/ios/exemptEncryption.ts
Apple requires the non-exempt encryption status be defined on every build before it can be submitted to TestFlight or app review. We can use the Info.plist flag to only ask users one time and reuse that answer for every build. This is a better version of https://github.com/expo/expo/pull/34487
Prompting in the CLI saves users six clicks in App Store Connect for every iOS build.
I copied the bundle identifier prompting logic to a new function for setting non-exempt encryption, made it more optional, and added it to `eas build -p ios`.
If the user indicates that they use non-exempt encryption then we won't write anything this will enable them to see the in-depth warnings in ASC about this option. They can still skip the prompt by manually adding the value to their app.json.
- Run `eas build …
> feat(eas-cli): Ensure non-exempt encryption status

- packages/eas-cli/src/build/android/graphql.ts
- packages/eas-cli/src/build/android/prepareJob.ts
- packages/eas-cli/src/build/evaluateConfigWithEnvVarsAsync.ts
- packages/eas-cli/src/build/ios/graphql.ts
- packages/eas-cli/src/build/ios/prepareJob.ts
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/build/utils/environment.ts
- packages/eas-cli/src/graphql/generated.ts
[ENG-14307: move environment to job object from metadata](https://linear.app/expo/issue/ENG-14307/move-environment-to-job-object-from-metadata)
`Environment` should be considering  a first class citizen in job object instead of being stored in the metadata.
* Pass `environment` in `job` object
* remove `environment` from `metadata`.
1. Start a build specifying `environment` in `eas.json`.
2. Build should use the specified environment (check on website in `Build details`)
> Move environment from metadata to job object

- packages/eas-cli/src/build/configure.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/dev.ts
- packages/eas-cli/src/commands/build/index.ts
- packages/eas-cli/src/commands/build/inspect.ts
- packages/eas-cli/src/commands/build/internal.ts
- packages/eas-cli/src/commands/dev.ts
- packages/eas-cli/src/commands/project/onboarding.ts
https://exponent-internal.slack.com/archives/C1QLM27T9/p1734729481930599?thread_ts=1734708689.473259&cid=C1QLM27T9
Add `eas dev` command that:
1. calculates fingerprint
2. checks if we have simulator/emulator dev client builds with such a fingerprint hash on our servers
a. if we do -  it downloads and launches them on the emulator/simulator using the same logic we use for eas build:run
b. if not -  such a build is created and launched afterward 
Do exactly what I mentioned above. Use as much code and functions from build logic and eas build:run that already exist to make it easier to maintain.
Test manually
https://exponent-internal.slack.com/archives/C1QLM27T9/p1736987685783579?thread_ts=1734708689.473259&cid=C1QLM27T9
> [ENG-14625][eas-cli] add `eas build:dev` command

- CHANGELOG.md
- packages/eas-cli/src/commands/build/index.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1738188149992119
add `--submit` and `-s` aliases to `--auto-submit` flag
test manually
> [eas-cli] add `--submit` and `-s` aliases to `--auto-submit` flag

- CHANGELOG.md
- packages/eas-cli/src/project/ios/exemptEncryption.ts
- Skip the prompts if the user is running in CI or non-interactive.
- Tests keep working
- `eas build --non-interactive` doesn't hang
> fix: Skip non-exempt check in non-interactive mode.

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/compare.ts
Add support for users accidentally passing in update group id into `fingerprint:compare` instead of update id.
Added support for handling update group IDs in the fingerprint comparison command by:
- Attempting to fetch updates using the provided ID as an update group ID
- If successful and there's only one update, using that update directly
- If multiple updates exist in the group, prompting the user to select the specific platform/update
- Falling back to the original update ID logic if the group ID lookup fails
- Adding helpful error messages that include the direct URL to find the correct update ID
> [eas-cli] add update group id for fingerprint:compare

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/compare.ts
Add support for comparing fingerprints from multiple sources in a more flexible way. This includes comparing fingerprints between builds, updates, and local project state with improved interactive selection.
Example:
```EXAMPLES
$ eas fingerprint:compare 	 # Compare fingerprints in interactive mode
$ eas fingerprint:compare <FINGERPRINT-HASH> 	 # Compare fingerprint against local directory
$ eas fingerprint:compare <FINGERPRINT-HASH-1> <FINGERPRINT-HASH-2> 	 # Compare provided fingerprints
$ eas fingerprint:compare --build-id <BUILD-ID> 	 # Compare fingerprint from build against local directory
$ eas fingerprint:compare --build-id <BUILD-ID-1> --build-id <BUILD-ID-2>	 # Compare fingerprint from a build against another build
$ eas fingerprint:compare --build-id <BUILD-ID> --update-id …
```
> [eas-cli] add interactive mode for fingerprint:compare

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/compare.ts
When comparing fingerprints diffs in the CLI, popup the website window for a better viewing experience in interactive mode. 
https://github.com/user-attachments/assets/a16febfe-ac1f-4170-9667-294e3be823ea
Added functionality to automatically open the web-based fingerprint comparison tool in the browser after displaying the CLI output. This provides users with a more comprehensive and interactive way to analyze differences between fingerprints.
The browser only opens when running in interactive mode, preserving the existing behavior for CI/CD environments.
> [eas-cli] popup website in fingerprint:compare

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/compare.ts
This reverts commit 7f46baeb21125e1708c9f79610c08cc8acb04b4a.
Temporarily reverting because we are in the process of changing the URL from the website
> Revert "[eas-cli] popup website in fingerprint:compare (#2859)"

- CHANGELOG.md
- packages/eas-cli/src/vcs/index.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1738630158821649
Print warn message only once
Tests
> [eas-cli] print no vcs warning only once

- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/dev.ts
- packages/eas-cli/src/commands/build/run.ts
- packages/eas-cli/src/run/run.ts
We don't need to redownload app every single time in `eas build:dev`. We can cache it locally. This functionality already exists for `eas build:run`.
Use caching the same way we do for `eas build:run`
> [eas-cli] cache downloaded app archives in eas build:dev

- packages/eas-cli/src/commands/build/dev.ts
Auto-start dev client server at the end of `eas build:dev` command
Auto-start dev client server at the end of `eas build:dev` command
[Screen Recording 2025-02-04 at 13.00.38.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/9YRXgAETSTRMfjZ0IP35/fabf33a3-77e4-474f-a5fe-71725446769f.mov" />](https://app.graphite.dev/media/video/9YRXgAETSTRMfjZ0IP35/fabf33a3-77e4-474f-a5fe-71725446769f.mov)
> [eas-cli] auto start dev client server at the end of eas build:dev

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
receiving an issue for a customer who uses eas environment and continuous-deploy-fingerprint github action. they have build variants setup in their app.config.ts. the app id, scheme and some other properties are determined by their `APP_VARIANT` variable. the `APP_VARIANT` is from eas server environment.
when continuous-deploy-fingerprint first calculates fingerprint, it uses `eas env:exec` for the `npx expo-updates fingerprint:generate` call. the `APP_VARIANT` is correctly passed.
then for `eas update` call, it doesn't pass the `APP_VARIANT` env and generates an inconsistent fingerprint.
pass server env to the `getRuntimeVersionInfoObjectsAsync()` (`npx expo-updates runtimeversion:resolve`)
1. my **app.config.js**
```js
export default ({ config }) => {
config.android.package = …
```
> [eas-cli] pass server env when resolving fingerprint runtime version

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/contextUtils/__tests__/getProjectIdAsync-test.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
As of https://github.com/expo/expo/pull/34209, we no longer need to include the owner field in app config since packages in the SDK no longer use it.
This is needed before the second PR in that stack can land (https://github.com/expo/expo/pull/34210) since it uses eas cli.
Update condition and test.
Run test.
> [eas-cli] No longer require owner field for SDK >= 53 or canary

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/compare.ts
Followup from https://github.com/expo/eas-cli/commit/7f46baeb21125e1708c9f79610c08cc8acb04b4a#r152099396
Add a new `--open` flag to the `eas fingerprint compare` command to provide users with the option to automatically open fingerprint comparisons in their browser. This improves the user experience by eliminating the need to manually copy and paste URLs.
- Added a new boolean flag `open` to the command options
- When the flag is not used, display a helpful message suggesting the use of the flag
- When the flag is used, automatically open the comparison URL in the browser
- Added a link to learn more about fingerprint comparisons in the info message
ran `eas fingerprint compare` with and without `--open`
> [eas-cli] add --open flag to fingerprint:compare

- .github/workflows/test.yml
- CHANGELOG.md
- packages/eas-cli/src/vcs/clients/__tests__/git.test.ts
- packages/eas-cli/src/vcs/clients/git.ts
If you had an `.easignore`, `isFileIgnoredAsync` was always thinking all files are NOT ignored which was causing it to think all builds are in `.GENERIC` mode (with native code) which was not true, because ACTUALLY the files WERE ignored.
All mostly because of forgotten `ignore.initIgnoreAsync()`…
Added `ignore.initIgnoreAsync()`. Also realized whether the file is tracked / not-tracked may affect how actually is it going to behave, so added it to the mix.
Added tests that I think test all cases.
> [eas-cli] Fix `.easignore` behavior for `GitClient`

- packages/eas-cli/src/vcs/__tests__/local-test.ts
- packages/eas-cli/src/vcs/clients/git.ts
- packages/eas-cli/src/vcs/clients/noVcs.ts
- packages/eas-cli/src/vcs/local.ts
`eas-cli@15.0.0-15.0.3` doesn't interpret `.easignore` right because I haven't initialized the `Ignore` class properly.
Make it so it's not possible to use `Ignore` without initializing it.
Tests should pass.
> [eas-cli] Prevent using non-initialized `Ignore`

- CHANGELOG.md
- packages/eas-cli/src/vcs/clients/git.ts
Currently it's not possible to exclude `.git` from being uploaded in project tarball.
In `makeShallowCopyAsync()` we first clone the repository, then we delete files ignored by `.easignore` and then we copy working directory over.
The "delete files ignored by `.easignore`" step is governed by `git ls-files --exclude-from=.easignore`. `git ls-files` is never going to consider `.git` directory to be excluded, even if specified in `.easignore`, so we need to special-case the `.git` directory and remove it manually if specified.
Added `.git` to a test `.easignore`, ran `eas build:inspect` and confirmed the copied directory did _not_ contain `.git` folder.
> [eas-cli] Support excluding `.git` via `.easignore`

- packages/eas-cli/src/build/build.ts
- packages/eas-cli/src/build/utils/repository.ts
- packages/eas-cli/src/project/uploadAccountScopedProjectSourceAsync.ts
Adding `.git` directory to the tarball makes it bigger. Users notice this warning and want it to be actionable, but currently adding `.git` to `.easignore` does nothing.
For now, raise threshold for warning from 100 MiB to 150 MiB. In the next pull request I'm going to fix `.git` exclusion via `.easignore`.
CI should pass.
> [eas-cli] Raise threshold for "big tarball" warning

- CHANGELOG.md
- packages/eas-cli/src/vcs/clients/__tests__/git.test.ts
- packages/eas-cli/src/vcs/clients/git.ts
`git ls-files` returns submodules as a single filepath entry, so `rm` must remove it with `-rf`. Fixes https://github.com/expo/eas-cli/issues/2883.
Added `{ recursive: true, force: true }` to `fs.rm`.
I tried `easd build:inspect -p android -s archive -o ~/testtest --force` on a repo with a submodule in `.easignore`. It succeeded and the submodule was not included in the folder.
> [eas-cli] Fix deleting ignored submodules when archiving project

- CHANGELOG.md
- packages/eas-cli/src/vcs/clients/git.ts
`requireCommit: true` setups expect worktree to be clean (e.g. encrypted files to be locked).
Made it so if `requireCommit` is true we don't copy files over.
I have enabled `git-crypt` in my test repository, added a secret file, ran `easd build:inspect -p android -s archive -o ~/test-production --force`. The clone did contain secret file in plaintext.
Then I enabled `requireCommit: true` and repeated the command. The clone did contain the file encrypted.
> [eas-cli] Skip `makeShallowCopyAsync` if `requireCommit`

- packages/eas-cli/src/vcs/clients/git.ts
- packages/eas-cli/src/vcs/local.ts
Should help debug why `node_modules` get included on Windows.
> [eas-cli] Add more logging around creating a tarball

- packages/eas-cli/src/vcs/clients/git.ts
- packages/eas-cli/src/vcs/local.ts
Since v15 files that should be ignored get added to the tarball on Windows.
After adding some debugging I was able to find that `src`, `srcFilePath` don't match on path separators which breaks `ignore.ignores`.
Added `path.normalize` if `__NORMALIZE` is `1`.
---
Also noticed we used wrong `cwd` for is-tracked check.
Going to release this and test.
> [eas-cli] Allow normalizing root path to fix Windows not ignoring files

- packages/eas-cli/src/vcs/local.ts
`fs` adds a [Win32 File Namespace](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces) to the beginning of the path which breaks `path.relative` if `src` does not have the namespace.
Ensured that running `toNamespacedPath` on an already namespaced path does not add a _second_ namespace:
```
> path.win32.toNamespacedPath("D:\\abc")
'\\\\?\\D:\\abc'
> path.win32.toNamespacedPath(path.win32.toNamespacedPath("D:\\abc"))
'\\\\?\\D:\\abc'
```
Wrapped `src` and `srcFilePath` (two arguments to `path.relative`) with `path.toNamespacedPath` so `path.relative` works.
Will release and test.
> [eas-cli] Try fixing ignoring files not working by namespacing paths

- CHANGELOG.md
- packages/eas-cli/src/vcs/clients/git.ts
- packages/eas-cli/src/vcs/local.ts
With `toNamespacedPath` I was finally able to make ignoring files work properly.
Removed `if (__NORMALIZE)` checks.
Ran `eas build:inspect` on Windows, confirmed no `node_modules` was copied. Also ran `eas build:inspect` on macOS, worked too.
> [eas-cli] Finally fix Windows not-ignoring files

- .github/workflows/test.yml
- CHANGELOG.md
- packages/eas-cli/src/vcs/clients/__tests__/git.test.ts
- packages/eas-cli/src/vcs/clients/git.ts
When we `git clone` the source repository and then copy worktree changes over, we add and modify files. However, we do not _delete_ files that have been deleted in worktree.
When we operate in `requireCommit: false` mode, we add `--no-checkout` to the `git clone` command. This way the destination directory only has `.git` directory when we start copying files over. Thus, files deleted from worktree will not suddenly appear in tarball.
In `requireCommit: true` mode we don't add `--no-checkout`, because we don't copy files.
Added test. Tested manually.
Side effect of this is that `git status` reports that all files have been deleted and there's a bunch of untracked files (which, `git add`-ed, make the repository appear as the source repo). I don't know how to copy the Git index 1-1…
> [eas-cli] Do not include files deleted in working directory

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/channel/queries.ts
- packages/eas-cli/src/commands/channel/delete.ts
- packages/eas-cli/src/commands/channel/edit.ts
- packages/eas-cli/src/commands/channel/pause.ts
- packages/eas-cli/src/commands/channel/resume.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/queries/ChannelQuery.ts
As we've added more features, we've added more fetched data to the default fragments (UpdateFragment). But a lot of callsites don't need all the data. This PR adds a new basic query for getting just the basic info (similar to other query below).
Add new query, replace callsites that can be replaces (rely on tsc to tell me)
`yarn tsc`
> [eas-cli] Narrow amount of data queried for basic update channel operations

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/credentials/ios/appstore/ensureTestFlightGroup.ts
- yarn.lock
- Looks like the internal group API changed recently with v3.8.0 https://github.com/EvanBacon/App-Store-Connect-OpenAPI-Spec/pull/25
- We now get an error:
```
Failed to create an internal TestFlight group. This can be done manually in the App Store Connect website.
UnexpectedAppleResponse: The provided entity includes an attribute with an invalid value - Public link limit cannot be applied to internal group
```
- Removing the extra properties may fix this, hard to explicitly verify.
- Ensure the external TestFlight properties are removed when creating an internal group.
- `easd submit -p ios` -> creates TF internal group without throwing an error.
> fix(submit): Fix TestFlight internal group creation

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/appstore/ensureTestFlightGroup.ts
https://exponent-internal.slack.com/archives/C014YHUJUMN/p1738577486565949?thread_ts=1738574914.864689&cid=C014YHUJUMN
If there are any existing testflight groups skip the creation of the `Team (Expo)` group.
Allow to opt out of the creation y setting `EXPO_SKIP_TESTFLIGHT_SETUP=1`
Tests
> [eas-cli] skip creation of testflight group when there are already exisitng testflight groups + allow to opt out of the behavior by setting env var

- CHANGELOG.md
- packages/eas-cli/package.json
- yarn.lock
- Apple changed the (cookies) API for generating APNS keys so we need to account for that.
- TBD
> bump app store to fix key api

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/compare.ts
The current fingerprint comparison URLs and content identifiers need improvements:
1. URLs should be case-insensitive to match Expo's website behavior
2. Content identifiers need clearer labels and additional React Native specific entries
- Modified URL generation to lowercase account and project names for consistency
- Updated and added new content identifier labels:
- Renamed "Expo config" to "Expo app config" for clarity
- Added entries for React Native package.json
- Added entries for React Native Community autolinking configs
Ran `eas fingerprint:compare` to ensure:
1. fingerprint comparison URLs work with mixed case account/project names
2. Verify content identifiers display correctly
> [eas-cli] lowercase urls, add more pretty prints

- CHANGELOG.md
- packages/eas-cli/src/utils/formatFields.ts
When formatting fields with an empty array, the code would attempt to find the maximum label length, causing an error when reducing an empty array (`Reduce of empty array with no initial value`). This needs to be fixed to handle empty arrays gracefully.
Added an early return statement that checks if the input fields array is empty, returning an empty string before attempting to calculate the column width.
> [eas-cli] fix formatFields to handle empty array

- CHANGELOG.md
- packages/eas-cli/src/utils/__tests__/fingerprintDiff-test.ts
- packages/eas-cli/src/utils/fingerprintDiff.ts
The current git-style diff output in the fingerprint diff utility shows incorrect line numbers in the chunk headers. This affects the readability and accuracy of diff representations when comparing fingerprints.
Updated the chunk header calculation in `fingerprintDiff.ts` to properly account for context lines when determining the line ranges. The fix adjusts both the starting position and total line count by incorporating the context lines in the calculations.
The changes ensure that:
- Starting positions are offset by the number of prior context lines
- Total line counts include both context lines and modified lines
- Default starting position is 1 when undefined
> [eas-cli] fix git diff header in fingerprint:compare

- packages/eas-cli/src/commands/deploy/index.ts
- packages/eas-cli/src/commands/fingerprint/compare.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1739495318680849
use lowercase commands descriptions
run locally
> use lowercase commands descriptions

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/compare.ts
Updates the fingerprint comparison URL structure to use path parameters instead of query parameters, making it consistent with the new URL format on the Expo website.
Modified the URL construction in the fingerprint comparison command to include the fingerprint hashes directly in the path instead of as search parameters. The new format follows the pattern:
`/accounts/{account}/projects/{project}/fingerprints/compare/{firstHash}/{secondHash}`
Ran `fingerprint:compare` with and without the `--open` flag
Example:
```bash
$ eas fingerprint compare first-hash second-hash
```
> [eas-cli] amend fingerprint compare url

- CHANGELOG.md
- packages/eas-cli/src/project/android/applicationId.ts
When building bare RN projects with EAS CLI with `applicationIdSuffix`, the CLI will error due to being unable to determine the application ID from the `build.gradle`. The workaround for this is not obvious.
Update the error message to suggest adding the full application ID in `productFlavors` which is the simplest workaround.
Verified locally.
> [eas-cli] improve applicationIdSuffix error message

- CHANGELOG.md
- packages/eas-cli/src/vcs/__tests__/local-test.ts
- packages/eas-cli/src/vcs/clients/__tests__/git.test.ts
- packages/eas-cli/src/vcs/clients/git.ts
- packages/eas-cli/src/vcs/clients/noVcs.ts
- packages/eas-cli/src/vcs/local.ts
Thanks to [a conversation on Bluesky](https://bsky.app/profile/sjchmiela.bsky.social/post/3lj6k2xo7rk2g) it turned out [this check](https://github.com/expo/eas-cli/blob/3a434940eb44dfa8dddc42af055793134ca9016f/packages/eas-cli/src/vcs/clients/git.ts#L255-L257) is invalid (always true), because `Ignore` has `DEFAULT_IGNORE`, so even if a user had no `.git` in `.easignore`, especially if they had `requireCommit: true`, `.git` would be removed.
- Added a check to disallow `.easignore` if one has `requireCommit: true`.
- Changed logic around `Ignore` so we have separate `createForCopying` (ignores `.git` and `node_modules` always) and `createForChecking` (does not ignore anything by default). I don't like it, but it should work and is the best of what I could come up with without further …
> [eas-cli] Fix `.git` x `.easignore` interaction

- CHANGELOG.md
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/index.ts
Suggest using `eas build:dev` if one runs `eas build` resulting in simulator/emulator dev client build.
Add log to suggest using `eas build:dev`
Tests
> [eas-cli] suggest using eas build:dev when using simulator/emulator dev client configuration

- CHANGELOG.md
- packages/eas-cli/src/project/projectUtils.ts
- packages/eas-cli/src/update/android/UpdatesModule.ts
- packages/eas-cli/src/update/ios/UpdatesModule.ts
When we set updates config, the behavior will be different depending on whether there is an expo-updates package version that is passed in: https://github.com/expo/expo/blob/62af2e5c947ef53e004c3ced6f1973895f474abc/packages/%40expo/config-plugins/src/utils/Updates.ts#L157-L162 - this currently makes it so using `ON_ERROR_RECOVERY` will never work. Additionally, a fix will be required in the config plugins package to actually support `ERROR_RECOVERY_ONLY` - which was added but no conditional branch was ever made for it in the config plugin: https://github.com/expo/expo/blob/62af2e5c947ef53e004c3ced6f1973895f474abc/packages/%40expo/config-plugins/src/utils/Updates.ts#L153-L171
Pass through expo-updates pkg version
> [eas-cli] Pass through the updates version to setUpdatesConfigAsync

- CHANGELOG.md
- packages/eas-cli/src/run/utils.ts
Fixes https://github.com/expo/eas-cli/issues/2919
We indeed use legacy logic for determining whether artifact has expired.
Let's use build.expiredAt
Tests
> [eas-cli] use correct logic to determine whether artifacts expired in eas build:run

- CHANGELOG.md
- packages/eas-cli/src/ApiV2Error.ts
- packages/eas-cli/src/__tests__/api-test.ts
To better attribute reported errors to our internal API sentry, we need the request ID. This is already logged for graphql errors by EasCommand (done long ago in #1924) but we didn't have anything similar for ApiV2Error.
Closes ENG-15209.
Add field.
```
$ EXPO_DEBUG=1 neas login
✔ Email or username …<fake>
✔ Password … **********
Your username, email, or password was incorrect.
ApiV2Error: Your username, email, or password was incorrect. {
expoApiV2ErrorCode: 'AUTHENTICATION_ERROR',
expoApiV2ErrorDetails: undefined,
expoApiV2ErrorServerStack: undefined,
expoApiV2ErrorMetadata: undefined,
expoApiV2ErrorRequestId: '9280b16a-9dc5-4271-8fbf-695995c4b673'
}
Error: account:login command failed.
```
> [eas-cli] Add requestId to ApiV2Error

- packages/eas-cli/src/vcs/clients/noVcs.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1741615912048469
Made it so we don't print warning about `EAS_PROJECT_ROOT` multiple times.
CI should pass.
> [eas-cli] Do not warn about `EAS_PROJECT_ROOT` multiple times

- .github/workflows/changelog.yml
`tj-actions/changed-files` has been compromised. See discussion [here](https://github.com/tj-actions/changed-files/issues/2463).
Pinned to a uncompromised commit. I've also disabled this workflow for the repo.
> [ci] Pin to older tj-actions/changed-files commit.

- CHANGELOG.md
- packages/eas-cli/src/vcs/clients/__tests__/git.test.ts
- packages/eas-cli/src/vcs/clients/git.ts
https://github.com/expo/eas-cli/pull/2925#issuecomment-2710138932
Delete files from `.easignore` even if `requireCommit` is `true`. Instead of erroring, print a warning.
Adjusted tests.
> [eas-cli] Adhere to `.easignore` even if `requireCommit` is `true`

- CHANGELOG.md
- packages/eas-cli/src/commands/update/configure.ts
- packages/eas-cli/src/update/configure.ts
We sync updates config from app.json/config.js when we run `eas build` but not when running `eas update:configure`.
- Always sync native config from app.json/config.js when running `eas update:configure`, even when already set up. This is a safe change
- Do not sync native config when running `eas update`
Create a project, configure updates with `eas update:configure`, run prebuild. Change updates configuration in app.json, run `eas update:configure` again - it should sync the changes to the native directories. Change updates configuration in app.json, run `eas update` - it should not sync changes.
> [eas-cli] Always sync update configuration with eas update:configure

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/compare.ts
- packages/eas-cli/src/commands/fingerprint/generate.ts
- packages/eas-cli/src/fingerprint/cli.ts
- packages/eas-cli/src/fingerprint/utils.ts
This is my current understanding of how a build profile can affect a project's fingerprint. @szdziedzic and @sjchmiela, please let me know if it is correct, or if there are any nuances I am missing!
- A fingerprint contains the [following components](https://staging.expo.dev/accounts/quintest110/projects/staging-sdk-52/fingerprints/653b4ea74e6e03eda64fa4815e8a1dd8430b57ba) which we use to determine compatibility at an app's native layer
- In `eas.json`, we have a bunch of build profiles which define a bunch of parameters like build machine types, update channels, etc. However, it is the set of environment variables produced (specifying build profile parameter as input) which ultimately affects the fingerprint. **Is there any other way a build profile can affect a fingerprint?** 
For …
> [eas-cli] add support for build profiles in fingerprint generation

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/ServerSideEnvironmentVariablesContextField.ts
- packages/eas-cli/src/commands/fingerprint/compare.ts
- packages/eas-cli/src/commands/fingerprint/generate.ts
Add environment support for `eas fingerprint:compare`, similar to https://github.com/expo/eas-cli/pull/2951 .
> [eas-cli] add environment support for fingerprint:compare

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/generate.ts
Make the `eas fingerprint:generate` command public 
```
MacBook-Pro-8:sdk-52-test quin$ ~/Documents/eas-cli/packages/eas-cli/bin/run fingerprint --help
See more details with DEBUG=*
compare fingerprints of the current project, builds, and updates
USAGE
$ eas fingerprint:COMMAND
COMMANDS
fingerprint:compare   compare fingerprints of the current project, builds, and updates
fingerprint:generate  generate fingerprints from the current project
```
> [eas-cli] remove hidden flag from  fingerprint:generate

- CHANGELOG.md
- packages/eas-cli/src/commands/fingerprint/generate.ts
Add `--build-profile` arg to `eas fingerprint:generate`, based on the discussion here: https://exponent-internal.slack.com/archives/C06EFBQK3B7/p1742589956539759?thread_ts=1741971771.992309&cid=C06EFBQK3B7
- Added a new `--build-profile` flag to specify a build profile from eas.json
- Added a `--environment` flag to use environment variables from a specific environment
- Made these flags mutually exclusive
- Updated the command examples to reflect the new options
- Implemented the logic to load environment variables from either the specified build profile or environment
- Updated the context options to include dynamic project configuration
- Confirmed env vars (defined server side and in the 'env' field of `eas.json`) get passed in. `EXPO_STAGING=1 …
> [eas-cli] add build-profile flag

- packages/eas-cli/src/build/utils/url.ts
- packages/eas-cli/src/commands/deploy/index.ts
When we move Workflows to scoped token which has at most DEVELOPER permission, `type: deploy, prod: true` jobs will fail with an ominous
```
You don't have the required permissions to perform this operation.
This can sometimes happen if you are logged in as incorrect user.
Run eas whoami to check the username you are logged in as.
Run eas login to change the account.
Original error message: Entity not authorized: AppDevDomainNameEntity[00000000-0000-0000-0000-000000000000] (viewer = ScopedAccountActorViewerContext[16d62ef3-a219-47ca-936b-89958f6cb1f8], action = CREATE, ruleIndex = -1)
Request ID: 863a1317-882b-4cab-b8f2-c5f5d63b6f29
```
Special-cased the `--prod` && `AppDevDomainEntity` && `CREATE` && `UNAUTHORIZED_ERROR` error.
Not sure if we should call out "as an app admin" in the …
> [eas-cli] Improve unauthorized error for `eas deploy --prod`

- packages/eas-cli/graphql.schema.json
- packages/eas-cli/package.json
- packages/eas-cli/src/commands/update/delete.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/queries/BackgroundJobReceiptQuery.ts
- packages/eas-cli/src/graphql/types/BackgroundJobReceipt.ts
- packages/eas-cli/src/utils/__tests__/pollForBackgroundJobReceiptAsync-test.ts
- packages/eas-cli/src/utils/pollForBackgroundJobReceiptAsync.ts
- yarn.lock
Equivalent to the Expo website PR (https://github.com/expo/universe/pull/19468) but for the CLI.
We're moving update group deletion to be a background job since it can take so long for large update groups.
Copy polling utility from website, use it here to replace existing update group deletion.
`neas update:delete 25d8b9c5-6c8a-4069-a13f-0892c2c66203`
See it successfully deletes the update group.
Run new unit test.
> [eas-cli] Switch update group deletion to be asynchronous

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
This PR refactors the `UpdatePublish` command to improve code readability and flow by removing a nested `else` block and using an early return pattern.
before
```
if (jsonFlag) {
printJsonOnlyOutput(getUpdateJsonInfosForUpdates(newUpdates));
} else {
// all the logic
}
```
after
```
if (jsonFlag) {
printJsonOnlyOutput(getUpdateJsonInfosForUpdates(newUpdates));
return;
} 
// all the logic
```
- Removed the large `else` block that contained most of the code in the `UpdatePublish` command
- Added an early return after handling the JSON flag case
- Kept all the existing functionality intact while making the code more maintainable
- Improved the logical flow by flattening the code structure
Manually tested the `eas update` command to ensure the code path works correctly
> [eas-cli] remove giant else stmt in update routin

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/builds.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/project/publish.ts
When publishing updates, users need to know if there are compatible builds for their fingerprints. This PR prints this information at the end of `eas update` to warn users, if they have updates being published that don't have corresponding builds, causing potential compatibility issues.
Added functionality to check for compatible builds when publishing updates:
1. Enhanced `fetchBuildsAsync` to support filtering by `fingerprintHash`
2. Implemented `findCompatibleBuildsAsync` to find builds matching fingerprints
3. Added warnings in the update publish command when no compatible builds are found for fingerprints
4. Included links to the fingerprint details on the Expo website for easier debugging
Run `eas update` with a fingerprint that doesn't have a compatible build
> [eas-cli] update: add warning if no build exists with fingerprint

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/credentials/ios/appstore/ensureTestFlightGroup.ts
- packages/eas-cli/src/metadata/download.ts
- packages/eas-cli/src/metadata/upload.ts
- packages/eas-cli/src/metadata/utils/__tests__/telemetry.test.ts
- packages/eas-cli/src/metadata/utils/telemetry.ts
- yarn.lock
- Switch to new JWT API which is technically breaking.
- Clean up warning message for TestFlight.
`easd build -p ios --submit`
> chore: bump expo/apple-utils

- packages/eas-cli/src/commands/upload.ts
Follow up of https://github.com/expo/eas-cli/pull/2932
Fixes some of the issues encountered while testing the new upload command 
- Use a Set instead of an array to store app files to ensure no duplicate entries 
- Compress .app files before uploading to GCS 
create build your app locally using Xcode or Android Studio
- Run `easd upload`
- Test both iOS and Android builds
- Observe local build on expo.dev
> [eas-cli][upload] Filter out duplicates and compress apps

- CHANGELOG.md
- packages/eas-cli/README.md
- packages/eas-cli/src/commands/build/download.ts
We want to introduce a feature in `expo-cli` to allow users to download remote builds instead of always building locally if there is an available build with a matching fingerprint. For this "cache" layer to work we need a way to download EAS builds through eas-cli 
Introduce a new `build:download`command
create a couple of builds on expo.dev
- Run `easd build:download --platform [ios|android] --fingerprint [hash]`
- Check if the build was downloaded correctly
> [eas-cli] Add build:download command

- CHANGELOG.md
- packages/eas-cli/README.md
- packages/eas-cli/src/commands/upload.ts
As part of the integration with expo-cli we should support a non-interactive mode when running `eas upload`
Add non-interactive and json flags to `upload` the command
create build your app locally using Xcode or Android Studio
- Run `easd upload --non-interactive --platform ios --json`
- Navigate to http://staging.expo.dev/accounts/gabrieldonadel/projects/fabric-tester/builds/bc7fe643-a5db-40e2-9cac-5362a8601423
- Observe your local build
> [eas-cli] Add non-interactive and json flags to upload command

- CHANGELOG.md
- packages/eas-cli/src/commands/build/download.ts
Users should be able to download non dev-client builds (e.g. builds with `--configuration Release`)
Allow no in dev-client flag for build:download
Run `easd build:download -p ios --fingerprint "5daec8fdf29fd8023ce92fae92f0e33d2eadac33" --no-dev-client`
> [eas-cli] Allow no in dev-client flag for build:download

- CHANGELOG.md
- packages/eas-cli/src/project/__tests__/publish-test.ts
- packages/eas-cli/src/project/publish.ts
This PR changes the file extension detection for launch assets to either `.hbc` or `.js`. If the file extension cannot be determined, we fall back to `.bundle`. It would be great to have this so we can display a UI with someone's update and show whether the bundle is hermes bytecode or js. 
- In [our v1 spec](https://docs.expo.dev/technical-specs/expo-updates-1/#manifest-body), we mention that we dont use the `fileExtension` field for the launch asset:
> launchAsset: A special asset that is the entry point of the application code. The fileExtension field will be ignored for this asset and SHOULD be omitted. 
- In the client code, it doesnt look like we care about the launch asset file extension for [Android updates](https://github.com/expo/expo/blob/177b7e763db899ecb6404441d706215d18508309 …
> [eas-cli] change launch asset file extension

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/project/maybeUploadAssetMapAsync.ts
- packages/eas-cli/src/project/publish.ts
This PR uploads the asset map produced by metro when a user runs `eas update`
- Added new GraphQL schema types for asset maps: `AssetMapGroup`, `AssetMapSourceInput`, and `AssetMapSourceType`
- Created a new function `maybeUploadAssetMapAsync` to handle uploading asset map files to GCS
- Updated the update publish command to collect and upload asset maps alongside other assets
- Added support for including asset map information in the update group publishing process
- Added a new upload session type `EAS_UPDATE_ASSETS_METADATA` for asset map uploads
- Added `assetMapUrl` field to the Update type to expose the asset map URL
- Added `averageMetrics` to UpdateInsights with `averageDownloadSize` field
> [eas-cli] upload assetmap.json when publishing update

- CHANGELOG.md
- packages/eas-cli/src/project/metroConfig.ts
After upgrading to SDK 53 I get this warning when running `eas build` even though I'm definitely using the expo metro config.
Update the check to match that of [Expo Doctor](https://github.com/expo/expo/blob/main/packages/expo-doctor/src/checks/MetroConfigCheck.ts#L20) which does detect this.
Run `easd build` locally and confirm the warning is no longer shown.
> [eas-cli] Detect when expo metro config is used

- CHANGELOG.md
- packages/eas-cli/src/worker/upload.ts
The Cloudflare CDN WAF might block the requests from specific sources when a request contains suspicious contents, a rule has caught the content, or the IP has been rate limited by their bot net protection.
All we can do in this case is:
- Tell the user this has been a CDN-level error
- Quote the Request ID (aka Ray ID) so we can look up the error
Here's an example of what this might look like:
- Add check for `Content-Type: text/html` and output non-JSON error message
- Tested manually locally
> [eas-cli] Add specific error for WAF block events (EAS Hosting)

- CHANGELOG.md
- packages/eas-json/schema/eas.schema.json
The `sdk-52` label  for Android is [set up on EAS](https://github.com/expo/turtle-v2/blob/c571f3208d27d0d196467e04e989b1a9c9175a81/src/services/launcher/src/workerImages.json#L17) but the alias was not added to the schema.
Add the `sdk-52` alias to the schema.
Unsure.
> [eas-json] Add android sdk-52 image to schema

- CHANGELOG.md
- packages/eas-cli/src/build/android/prepareJob.ts
- packages/eas-cli/src/build/context.ts
- packages/eas-cli/src/build/createContext.ts
- packages/eas-cli/src/build/ios/prepareJob.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/index.ts
[ENG-13286: Provide an option for EAS Build that indicates we should use the verbose logging version of the install command](https://linear.app/expo/issue/ENG-13286/provide-an-option-for-eas-build-that-indicates-we-should-use-the)
User should be able to easily enable verbose logs for build phase for easier debugging.
- added `--verbose-logs` option to `eas build` command
- flag is sent as an additional `EAS_BUILD_ENABLE_VERBOSE_LOGGING` variable
- start a build command with a flag `--verbose-logs`
- js package manager, `pod install` and `gradlew` should run in verbose mode
1. https://github.com/expo/eas-build/pull/527
2. https://github.com/expo/eas-cli/pull/3000
> [eas-cli][ENG-13286] Add --verbose-logs option to `eas build` command

- CHANGELOG.md
- packages/eas-build-cache-provider/README.md
- packages/eas-build-cache-provider/package.json
- packages/eas-build-cache-provider/src/.eslintrc.js
- packages/eas-build-cache-provider/src/helpers.ts
- packages/eas-build-cache-provider/src/index.ts
- packages/eas-build-cache-provider/src/log.ts
- packages/eas-build-cache-provider/tsconfig.build.json
- packages/eas-build-cache-provider/tsconfig.json
Follow up of https://github.com/expo/expo/pull/36314
Given that the cache provider logic is directly tied to eas-cli, there is no reason for this code to live on the expo/expo repo
Extract the code from https://github.com/expo/expo/blob/e0128f52abf313f9a8c99460bbab5b8c4e3cc3f9/packages/%40expo/cli/src/utils/remote-build-cache-providers/eas.ts to a separate package
I'll add proper types in a follow-up PR once they are exported by `@expo/config`
app.json
```json
{
"expo": {
"experiments": {
"remoteBuildCache": {
"provider": {
"plugin": "eas-build-cache-provider"
}
}
}
}
}
```
Run `nexpo run:ios`
> Add eas-build-cache-provider package

- CHANGELOG.md
- packages/eas-build-cache-provider/package.json
- packages/eas-build-cache-provider/src/helpers.ts
- packages/eas-build-cache-provider/src/index.ts
- yarn.lock
With `@expo/config`  11.0.6 we can now import remote build cache provider types
Use remote build cache provider types types from @expo/config
yarn tsc
> [build-cache-provider] Read types from @expo/config

- CHANGELOG.md
- packages/eas-cli/src/build/android/__tests__/build-test.ts
- packages/eas-cli/src/build/android/build.ts
- packages/eas-cli/src/project/android/__tests__/gradle-test.ts
- packages/eas-cli/src/project/android/__tests__/gradleUtils-test.ts
- packages/eas-cli/src/project/android/gradle.ts
- packages/eas-cli/src/project/android/gradleUtils.ts
[ENG-15618: Support different suffixes of custom gradle commands](https://linear.app/expo/issue/ENG-15618/support-different-suffixes-of-custom-gradle-commands)
Currently when user specifies a custom gradle command that does not end with `*Release` or `*Debug` the command is not parsed correctly. Build type and flavour are not parsed, which causes problems with setting code version and app version down the line.
- Changed the regexp that parses gradle command to be more flexible, allowing any suffix that starts with a capital letter.
- add a custom gradle command to `eas.json`, for example 
```
"development": {
"android": {
"gradleCommand": ":app:assembleAbcStaging"
}
},
```
- add a `buildType` and packageFlavor to `build.gradle` file:
```
productFlavors {  
abc { // New flavor
versionCode …
```
> [eas-cli] Allow any suffix for gradle command build type

- CHANGELOG.md
- packages/eas-build-cache-provider/README.md
- packages/eas-build-cache-provider/package.json
- packages/eas-build-cache-provider/src/index.ts
- yarn.lock
Follow-up of https://github.com/expo/expo/pull/36643
Update the exported object to use the new function names and the readme to recommend using the `buildCacheProvider` key
Run `nexpo run:ios`
> [build-cache-provider] Use new buildCacheProvider key

- CHANGELOG.md
- packages/eas-cli/src/commands/workflow/run.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/queries/WorkflowRunQuery.ts
Affirm asked for this.
Added `--json` flag which is going to print out all useful job information.
`--wait --json`:
```
{
"id": "0196c564-5553-70ed-8835-adff6484e8cf",
"name": "easd.yml",
"status": "SUCCESS",
"createdAt": "2025-05-12T16:46:49.171Z",
"workflow": {
"id": "48ee38cd-44d3-4359-8b35-d71297545ea5",
"fileName": "easd.yml"
},
"jobs": [
{
"id": "0196c564-58c9-75da-a3ef-931c64b756a2",
"key": "test",
"name": "test",
"type": "CUSTOM",
"status": "SUCCESS",
"outputs": {},
"createdAt": "2025-05-12T16:46:50.057Z"
}
],
"url": "http://expo.test/accounts/stanley/projects/test-local/workflows/0196c564-5553-70ed-8835-adff6484e8cf"
}
```
`--json`:
```
{
"id": "0196c563-5a25-75e1-9447-e35d82f8fef0",
"url": "http://expo.test/accounts/stanley/projects/test-local/workflows/0196c563-5a25-75e1-9447-e3 …
```
> [eas-cli] Add `--json` flag to `workflow:run`

- CHANGELOG.md
- packages/eas-cli/package.json
- packages/eas-cli/src/commands/upload.ts
- packages/eas-cli/src/utils/plist.ts
- yarn.lock
A user requests the ability to upload internal distribution builds in our Canny (https://expo.canny.io/feature-requests/p/upload-local-build-to-eas). Although we can't collect the same information as when a build is generated through EAS, we should allow users to upload IPA files.
Add support for uploading IPA files and update the simulator detection logic. In order to determine if an iOS app was built for a simulator, we should read the `DTPlatformName` value from the main `Info.plist`.
Tested manually with multiple different file formats
> [eas-cli] Add support for uploading for ipa files

- CHANGELOG.md
- packages/eas-cli/src/build/android/prepareJob.ts
- packages/eas-cli/src/build/ios/prepareJob.ts
- packages/eas-cli/src/build/metadata.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
- packages/eas-cli/src/project/projectUtils.ts
Part 2 of #2835. Missed some cases in that one.
Essentially the `username` field is supplied in EAS build jobs and in the build metadata. It is only used for an environment variable which is known to be undefined for robots: https://docs.expo.dev/eas/environment-variables/#:~:text=learn%20more)-,EAS_BUILD_USERNAME,-%3A%20the%20username%20of
This makes two changes:
1. If project ID is not set and a command is run that needs to generate it, it must be run as a human actor (to know which account to set it to). getAccountNameForEASProject in that path now throws if `eas init` has not yet been run (projectId is not yet set) and a robot is running the command.
2. This removes the overloaded function responsibility of `getUsername` (used by build and build metadata). Previously this function was …
> [eas-cli] Further no longer require owner field for SDK >= 53 or canary

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/api.ts
- packages/eas-cli/src/build/runBuildAndSubmit.ts
- packages/eas-cli/src/commands/build/configure.ts
- packages/eas-cli/src/commands/project/onboarding.ts
- packages/eas-cli/src/commands/update/configure.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/commands/update/roll-back-to-embedded.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/types/Update.ts
- packages/eas-cli/src/project/projectUtils.ts
- packages/eas-cli/src/update/configure.ts
- packages/eas-cli/src/update/republish.ts
- packages/eas-cli/src/update/utils.ts
- packages/eas-json/src/schema.ts
- packages/eas-json/src/types.ts
- packages/eas-json/src/utils.ts
CLI change corresponding to https://github.com/expo/universe/pull/20131.
This adds the ability to override the manifest and asset hosts for EAS Update such that a set of proxy hosts can be used.
Closes ENG-15804.
Considered putting these in flags, but it turned out that many many commands need to detect EAS Update configuration so they need access to these as well. Therefore, I added the new fields to `eas-json`.
The fields are:
- `manifestHostOverride` - a host to replace `u.expo.dev` in the URL.
- `assetHostOverride` - a host to replace `assets.eascdn.net` in asset URLs in the generated update manifests.
Then, in every place in EAS CLI when we generate a manifest URL, instead use the overridden URL.
Then, supply the manifest URL and asset URL overrides when creating updates (or …
> [eas-json][eas-cli] Add support for manifest host and asset host overriding

- CHANGELOG.md
- packages/eas-cli/src/commands/update/republish.ts
- packages/eas-cli/src/project/publish.ts
- packages/eas-cli/src/update/republish.ts
Add support for specifying a rollout percentage when republishing updates using the `eas update:republish` command. This allows for gradual rollouts of a known good update (previously tested on a separate branch, no need to rebuild) 
- Added a new `--rollout-percentage` flag to the `eas update republish` command that accepts an integer between 1 and 100
- When specified, the update will only be available to the specified percentage of users
- Users not in the rollout will be served the previous latest update on the branch
- Extracted `getUpdateRolloutInfoGroupAsync` from `getRuntimeToUpdateRolloutInfoGroupMappingAsync` to make it reusable
- Updated the output to display rollout information when applicable
- Ran ` eas-dev update:republish --group 90fb267a-119a-4206-b72c-d168e9889ddf …
> [eas-cli] add rollout flag to update:republish

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/context/contextUtils/__tests__/findProjectDirAndVerifyProjectSetupAsync-test.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/findProjectDirAndVerifyProjectSetupAsync.ts
https://exponent-internal.slack.com/archives/C089ED313PV/p1748545207578949?thread_ts=1748543276.564549&cid=C089ED313PV
Added support for `EAS_SKIP_CLI_VERSION_CHECK` environment variable.
Added tests.
> [eas-cli] Allow skipping version check

- CHANGELOG.md
- packages/eas-cli/src/commandUtils/workflows.ts
- packages/eas-cli/src/commands/workflow/cancel.ts
- packages/eas-cli/src/commands/workflow/list.ts
- packages/eas-cli/src/commands/workflow/runs.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/mutations/WorkflowRunMutation.ts
Allow user to cancel one or more workflow runs, as requested in @jonsamp 's [workflow CLI design document](https://www.notion.so/expo/EAS-CLI-workflow-commands-8bc5ccc4f9f949c8adfec1347817113c).
The CLI will print a separate message (success or error message) for each workflow run ID that it attempts to cancel.
```bash
$ eas workflow:cancel --help
Cancel one or more workflow runs. If no workflow run IDs are provided, you will be prompted to select IN_PROGRESS runs to cancel.
USAGE
$ eas workflow:cancel [--non-interactive]
FLAGS
--non-interactive  Run the command in non-interactive mode.
DESCRIPTION
Cancel one or more workflow runs. If no workflow run IDs are provided, you will be prompted to select IN_PROGRESS runs
to cancel.
```
Example:
```bash
$ eas workflow:cancel
? Select IN_PROGRESS …
```
> [eas-cli] Implement workflow:cancel

- CHANGELOG.md
6636f76cff830c77847372c97f17f42e408eac61 had a logical merge conflict in the changelog since a new version was released.
Move the entry to the correct release.
Inspect.
> [eas-cli] Fix changelog merge conflict

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/workflow/run.ts
- packages/eas-cli/src/graphql/generated.ts
[exponent-internal.slack.com/archives/C06EFBQK3B7/p1750180529429209](https://exponent-internal.slack.com/archives/C06EFBQK3B7/p1750180529429209)
Copied what we do for builds — https://github.com/expo/eas-cli/blob/b0522484afdbc7c80c7da84c724480ade8f16f55/packages/eas-cli/src/build/ios/prepareJob.ts#L37-L38 — and added `projectRootDirectory` to workflow runs.
I hoped there's a `node:path` method that would do what `slash` does, but I found none and Cursor did not know of one either.
Tested end to end with https://github.com/expo/universe/pull/20644.
> [eas-cli] Add `projectRootDirectory` to `workflow:run` payload

- CHANGELOG.md
- packages/eas-cli/src/build/utils/printBuildInfo.ts
- packages/eas-cli/src/commands/workflow/run.ts
The two commands should print the same text when returning the URL for the run logs, and not have unnecessary messages.
CI should pass
> [eas-cli] align text of messages from build and workflow:run

- CHANGELOG.md
- packages/eas-cli/src/commands/update/republish.ts
Noticed this condition was inverted during creation of a new related command.
Correct the if statement. It should warn when platform is not `all`.
Run `neas update:republish --platform ios`, see logged message:
```
$ eas update:republish --platform ios
✔ Find update by branch or channel? › Branch
✔ Select branch from which to choose update › main
✔ Load more update groups? › [Jun 23 11:14 by wschurman, runtimeVersion: 1.0.0] Initial commit
Generated by create-expo-app 3.4.2.
You are republishing an update group that wasn't published for all platforms.
✔ The republished update group will appear on the same platforms it was originally published on: ios
✔ Provide an update message. … Republish "Initial commit
Generated by create-expo-app 3.4.2." - group: 8e1b11be-ef82-4ccd-8294-a4e7075849d1 …
```
> [eas-cli] Fix bug in log during update:republish

- packages/eas-cli/src/commands/submit/internal.ts
Since https://linear.app/expo/issue/ENG-14634/add-support-for-groups-option-in-fastlane-pilot-call we support passing `--groups` parameter to `eas submit` and configuring submission profile with `groups` parameter ("undocumentedly").
I need to add support for this property to `submit:internal`. We're going to source the `groups` to pass to `fastlane pilot` from either:
- submit profile (this pull request adds this)
- or workflow config (in which case we'll don't use this output).
Added `groups` output to the `submit:internal` JSON object. We're going to parse it in https://github.com/expo/universe/blob/5dcea35fb50bf9fc8e3ae4ffe445f958bb5789e6/server/www/src/data/entities/workflow/job/WorkflowSubmitJob.ts#L192-L200.
Ran `easd submit:internal --id 60a2d86a-b6d8-4ba2-b7dd-bf05bdd78791 …
> [eas-cli] Add `groups` to the output of `submit:internal`

- CHANGELOG.md
- packages/eas-cli/src/build/build.ts
Why
===
The message about queuing builds faster mentions the Production and Enterprise plans. The Starter plan is also a good choice.
How
===
This PR changes the message just to say "paid plan" which is simple and understandable.
Test Plan
===
Just automated tests since this is a copy change.
> [build] Replace mention of specific plans

- CHANGELOG.md
- packages/eas-cli/src/commands/upload.ts
Make the `eas upload` command public
remove hidden flag from `upload` command
Run `easd -h`
> [eas-cli] remove hidden flag from upload

- CHANGELOG.md
- packages/eas-cli/graphql-codegen.yml
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/user/fetchUser.ts
While creating a previous PR, I moved a graphql query into a directory not explicitly specified in `graphql-codegen.yml`. It took me a while to figure out what was going on (only error was `tsc`).
To avoid other devs running into this, just generate it for all files in src.
1. Update paths
2. Fix `fetchUserAsync` to be typed and have a unique query name.
```
neas logout
neas login
neas whoami
```
> [eas-cli] Fix graphql codegen to look in all directories

- CHANGELOG.md
- packages/eas-cli/src/commands/deploy/index.ts
- packages/eas-cli/src/worker/assets.ts
- packages/eas-cli/src/worker/upload.ts
- packages/eas-cli/src/worker/utils/multipart.ts
This implements the new EAS Hosting asset upload protocol. This should improve parallel asset upload performance by grouping asset uploads into fewer requests. Because some assets can be small, the cost associated with making requests (even in parallel, and even with `keepAlive`) from scratch is likely high and outstrips the performance gains from the parallelization we have.
The new EAS Hosting assets protocol, when active, changes the `/deploy` endpoint to return an `upload` result paramter. This contains batches of SHA-512 arrays. When this parameter is received, `eas-cli` _may_ use this parameter to send the assets as batches instead.
Each batch is encoded as a `multipart/form-data` request payload. The payload contains a non-standard `Content-Length` header for each part, which …
> feat(eas-cli): Implement new batched EAS Hosting asset upload protocol

- packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts
- packages/eas-cli/src/credentials/ios/appstore/capabilityList.ts
This PR refactors the iOS capability synchronization logic to make it more "linear" and easier to maintain
- Encapsulating capability-specific logic with the capability definition
- Making the operation decision process more explicit and easier to follow
- green CI
- local tests
> [eas-cli] refactor capability syncing

- CHANGELOG.md
- packages/eas-cli/src/credentials/ios/appstore/__tests__/bundleIdCapabilities-test.ts
- packages/eas-cli/src/credentials/ios/appstore/__tests__/capabilityIdentifiers-test.ts
- packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts
- packages/eas-cli/src/credentials/ios/appstore/capabilityIdentifiers.ts
The current implementation of capabilities syncing can lead to provisioning profiles becoming invalid. This PR refactors the syncing process to avoid this issue by making the following improvements:
1. Preventing unnecessary creation of capability identifiers that already exist
2. Only updating bundle capabilities when necessary
closes https://github.com/expo/eas-cli/issues/1069
closes https://github.com/expo/eas-cli/issues/1445
I refactored the capability syncing logic to:
- Add test coverage for faulty behaviors. More tests are [up the stack](https://github.com/expo/eas-cli/pull/3086/files#diff-09c5aad6e72a7a336e9783710d3899ff2ea432146929bc07ba8bfec7c7bbd2a8).
- Only create capability identifiers that don't already exist on the server
- Skip updating bundle capabilities when no changes …
> [eas-cli] fix CapabilityModel creation and syncing

- CHANGELOG.md
- packages/eas-cli/src/worker/assets.ts
- packages/eas-cli/src/worker/upload.ts
- packages/eas-cli/src/worker/utils/multipart.ts
We're basically using `Readable.from(asyncGenerator)` and `for await (const chunk of fs.createReadStream(filePath))` to read files. However, if the `createReadStream()` ends with an `'end'` event, in some Node.js versions they're subject to an early termination timing bug. When this happens, the file output ends earlier than expected, which causes the upload to become corrupted.
- Switch to `fs.promises.open` and `filehandle.read` to work around async-iterable early termination bug
- Double-check the file's length (from the known size) while uploading
- Double-check the file's checksum (from the computed SHA-512) while uploading
- Use `Readable.from(asyncIterator, { objectMode: false })` to enter binary mode
This ensures that:
- we're now working around the early termination issue
- we're …
> [eas-cli] Fix batch uploads being subject to early-termination issues corrupting multipart upload parts

- packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts
Change the confirmation message for push notification key:
Firstly, "Push Notifications setup for app-name: bundle id" should say "set up" (verb), not "setup" (noun). That is, unless the value of `bundleId` was the value of a push notification setup, which doesn't make sense.
Secondly, the message contains information which is already printed in the row right before it, so it's redundant.
> [eas-cli] change push notification confirmation message

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/commands/deploy/alias/delete.ts
- packages/eas-cli/src/commands/deploy/alias/index.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/worker/deployment.ts
- packages/eas-cli/src/worker/mutations.ts
- packages/eas-cli/src/worker/queries.ts
Part of ENG-16625
Related to https://github.com/expo/eas-cli/pull/3106
Deployments cannot be deleted if they are assigned to an alias, so in order to fully support automating deleting deployments, we also need to support deleting aliases.
- `eas deploy:alias:delete` will show a paginated list of aliases (& can choose one to delete)
- `eas deploy:alias:delete name` will delete alias `name`
> [eas-cli] Add command for deleting worker aliases

- packages/eas-cli/src/user/expoSsoLauncher.ts
I'm working in a weird setup where the browser won't launch from cli. This required me to visit the url manually from my browser. To get the url, I had to add a `console.log` to the cli's code directly. Figured this change will make it easier for similar users to login, without exposing sensitive data
Added small `log` call
Tested manually on the compiled code, not the best
> [TINY] SSO Login: print browser url

- .github/workflows/release.yml
- .github/workflows/trigger-release.yml
- CHANGELOG.md
- RELEASING.md
- scripts/src/release.sh
The current release script requires that the user executing the script have permission to push changes to main without any PR requirement or checks.
To allow us to add PR requirements and checks, I have added a manual GitHub workflow so that the existing script is executed by the expo-bot user, which is exempted from PR requirements.
I have also made a few adjustments to the `release.yml` workflow (remove incorrect release name, update Node version to 22).
- CI should pass
- Try a release after this PR is merged
> New workflow to trigger releases

- .github/workflows/trigger-release.yml
The existing release trigger workflow does not obtain the GItHub history and tags, so that Lerna cannot correctly determine which package versions to bump.
Set `fetch-depth: 0` in the checkout action, and do an explicit fetch of all tags.
- After merge, a dry run of the release trigger should correctly bump only changed packages.
> Adjust release workflow so Lerna detects version changes

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/build/utils/formatBuild.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/types/Build.ts
Customers would like to show the fingerprint in the output of build:list and build:view, to enable download of builds by fingerprint.
E.g.
```
$ easd build:list
Builds for @douglowderexpo/NativewindMultiplatform:
ID            e4ce41be-f410-4820-a0f8-7876700ccb42
Platform      Android
Status        finished
Profile       development:tv
Distribution  internal
SDK Version   53.0.0
Version       1.0.0
Version code  1
Commit        a4920c388664314656bf9cbe30c72eb46abc4b5d
Logs          https://expo.dev/accounts/douglowderexpo/projects/NativewindMultiplatform/builds/e4ce41be-f410-4820-a0f8-7876700ccb42
Artifact      https://expo.dev/artifacts/eas/ufJ8mxmRrSQo8CkRAyaUzh.apk
Fingerprint   7ae6fffc4fb5c61c450f6e5b9e5b0fc0fbce763b
Started at    8/6/2025, 3:14:41 PM
Finished at   8/6/2025, 3:23:20 …
```
> Show fingerprints in build:view and build:list commands

- packages/eas-cli/src/commands/metadata/pull.ts
- packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts
- packages/eas-cli/src/credentials/ios/actions/PushKeyUtils.ts
Some doc links in the eas-cli output are missing. When user clicks those links they show 404 pages instead of useful instructions.
Replace broken links with correct ones.
Visit links to verify.
> [eas-cli] fix broken docs links

- packages/eas-json/src/__tests__/buildProfiles-test.ts
- packages/eas-json/src/build/resolver.ts
- yarn.lock
When a user tries to build with a non-existent profile, the error message could be a bit better by showing the available profiles.
Updated the `MissingProfileError` message in `packages/eas-json/src/build/resolver.ts` to include a list of available profiles in the error message.
- added a test case
> chore: include available profiles in 'Missing build profile' error

- CHANGELOG.md
- packages/eas-cli/src/commands/update/rollback.ts
Make it easier for customers to use `eas update:rollback` in CI.
Add description text on the underlying commands that do support the non-interactive flag.
> Add better description to update:rollback

- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/graphql/generated.ts
Sync up the schema to reflect recent additions to the server GraphQL schema
`yarn --cwd packages/eas-cli verify-graphql-code`, then inspect changes in schema and generated code.
CI should pass
> Sync GraphQL schema and generated code with server schema

- packages/eas-cli/src/commands/submit/internal.ts
Preparation for merging the rest of `track`-related pull requests.
Currently, the only place fetching `track` from `www` for display is `submit:internal` command. There, we fetch the submission config to know what parameters to supply to `fastlane supply` in the Submit workflow job.
Currently, we're using a mapping of `{ PRODUCTION: production, INTERNAL: internal, ... }` to transform the GraphQL value (enum key) to config value ("enum value").
Since we're planning to make `androidConfig.track` be a plain string (e.g. `internal`), we should fall back to the actual value if the mapping does not produce a match.
This currently should not change anything (`track` is guaranteed to be a GraphQL enum value). This is a preparation for landing of https://github.com/expo/universe/pull/21827 which …
> [eas-cli] Support unknown tracks in `submit:internal`

- CHANGELOG.md
- packages/eas-cli/src/commands/update/index.ts
```
Branch             livestream
Runtime version    1.0.0
Platform           android, ios
Update group ID    7d01437f-2960-4efc-bd3b-abfef18c1a09
Android update ID  416bdd21-a78c-4a70-bf3c-4f56d8d8252c
iOS update ID      041ef585-4f7a-49cf-aaeb-9874cf96d2e2
Message            Ready
Commit             f6c1eff71c1030ac500b7f8a13c5a13f4660f539*
EAS Dashboard      https://expo.dev/accounts/brents/projects/hello-updates/updates/7d01437f-2960-4efc-bd3b-abfef18c1a09
No compatible builds found for the following fingerprints:
iOS fingerprint:  08e0d74c33061720148b4c5cbb0534b357646282
URL            :  https://expo.dev/accounts/brents/projects/hello-updates/fingerprints/08e0d74c33061720148b4c5cbb0534b357646282
Android fingerprint:  3876a23c19cd256285dd2f3b6eb3e57933609ec2
URL                : …
```
> [cli] Temporarily remove warnings when no compatible build found, need to refine the message

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/api.ts
- packages/eas-cli/src/commandUtils/workflow/validation.ts
- packages/eas-cli/src/commands/workflow/run.ts
- packages/eas-cli/src/commands/workflow/validate.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/log.ts
- packages/eas-cli/src/utils/workflowFile.ts
Improve the validation of workflow files:
- Add client-side checks for valid syntax, and compatibility with the user's EAS build profiles
- Make validation usable with future improvements to `workflow:create`
- New `validation.ts` in `commandUtils` with the various validation checks separated cleanly into different functions
- `workflow:validate` command refactored to use the new utility and wrap errors
- The new code reads the workflow schema from `<ExpoAPIBaseURL>/v2/workflows/schema`
- For testing purposes only, a local copy of the schema can be used by setting EXPO_TESTING_WORKFLOW_SCHEMA_PATH
- An existing check in `workflowFile.ts` has been modified to remove the requirement for a Github repository, as that is no longer required to run workflows
- Tested against different workflow …
> Improvements to workflow:validate

- CHANGELOG.md
- packages/eas-cli/graphql.schema.json
- packages/eas-cli/src/build/evaluateConfigWithEnvVarsAsync.ts
- packages/eas-cli/src/build/utils/environment.ts
- packages/eas-cli/src/commandUtils/EasCommand.ts
- packages/eas-cli/src/commandUtils/context/ContextField.ts
- packages/eas-cli/src/commandUtils/context/contextUtils/loadServerSideEnvironmentVariablesAsync.ts
- packages/eas-cli/src/commandUtils/flags.ts
- packages/eas-cli/src/commands/build/resign.ts
- packages/eas-cli/src/commands/deploy/index.ts
- packages/eas-cli/src/commands/env/__tests__/EnvCreate.test.ts
- packages/eas-cli/src/commands/env/__tests__/EnvDelete.test.ts
- packages/eas-cli/src/commands/env/__tests__/EnvGet.test.ts
- packages/eas-cli/src/commands/env/__tests__/EnvList.test.ts
- packages/eas-cli/src/commands/env/__tests__/EnvUpdate.test.ts
- packages/eas-cli/src/commands/env/create.ts
- packages/eas-cli/src/commands/env/delete.ts
- packages/eas-cli/src/commands/env/exec.ts
- packages/eas-cli/src/commands/env/get.ts
- packages/eas-cli/src/commands/env/list.ts
- packages/eas-cli/src/commands/env/push.ts
- packages/eas-cli/src/commands/env/update.ts
- packages/eas-cli/src/commands/fingerprint/compare.ts
- packages/eas-cli/src/commands/fingerprint/generate.ts
- packages/eas-cli/src/commands/update/index.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/queries/EnvironmentVariablesQuery.ts
- packages/eas-cli/src/utils/prompts.ts
- packages/eas-cli/src/utils/variableUtils.ts
- packages/eas-cli/src/worker/assets.ts
We're removing the `EnvironmentVariableEnvironment` enum from the api. All existing code will work as before, but this update is needed in order to unblock future graphQL schema updates. (If you update the schema, the `EnvironmentVariableEnvironment` will no longer exist).
> [!IMPORTANT]
> This can't be merged until the `www` update is deployed
All tests and lint should pass.
> [eas-cli] Use local EnvironmentVariableEnvironment enum

- CHANGELOG.md
- packages/eas-cli/src/commands/workflow/run.ts
- packages/eas-cli/src/graphql/generated.ts
- packages/eas-cli/src/graphql/mutations/WorkflowRevisionMutation.ts
- packages/eas-cli/src/graphql/mutations/WorkflowRunMutation.ts
Add a `--ref` flag so that `eas workflow:run` can initiate a workflow run from an existing ref in the project's GitHub repository.
- Avoids the need to upload the entire project from a local machine
- Ensures that the workflow starts from a known reference point in the project's source control, with no unexpected local changes
- If the ref flag is set, the run command will ensure that the ref is valid, and that the workflow can be used for that ref (using the new mutation for this from https://github.com/expo/universe/pull/22132)
- If the ref flag is set, the run command starts the run from that ref (using https://github.com/expo/universe/pull/20161)
- If the user chooses ref = HEAD, `git rev-parse` is called to convert that to a commit
- The flow is designed to work the same for running …
> Support workflow:run from a Git ref
