packages/config/src/Config.types.ts, packages/config/src/EasJsonSchema.ts
Backports the changes from https://github.com/expo/expo-cli/pull/2765
=> [config] Add 'releaseChannel' to generic build schema

packages/eas-cli/src/commands/account/login.ts, packages/eas-cli/src/commands/account/logout.ts
=> Consistently use log.ts for all logging

.github/PULL_REQUEST_TEMPLATE
Copy-pasted from universe - https://github.com/expo/universe/blob/master/.github/PULL_REQUEST_TEMPLATE
=> add PR template

packages/eas-cli/src/submissions/ios/AppProduce.ts
- I found it not clear that I could submit with a different name than what was in my app config. 
- show that we are aware of these errors and have solutions for working around them.
Log a warning about using the flag or changing the name in the app config.
- (invalid characters) Submit an app with the name: "Speed 🏁"
- (name taken) Submit an app with the name: "Speedway"
=> Improve error messages for invalid name cases

packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/ios/build.ts
Fixes #114
Better error message
run generic build in manged project
=> [eas-cli] detect missing android or ios directories

packages/eas-cli/package.json, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/commands/release/create.ts, packages/eas-cli/src/project/projectUtils.ts
Create a channel for a project.
Default pointing to no releases.
=> [eas-cli] add channel:create

packages/eas-cli/src/uploads.ts, packages/eas-cli/src/utils/git.ts
This is the first of 4 PR's to add `eas release:publish`
Add 2 helper functions used in https://github.com/expo/eas-cli/pull/147
tested in https://github.com/expo/eas-cli/pull/146
=> [eas-cli] add helper functions 1/4

packages/eas-cli/src/build/build.ts, packages/eas-cli/src/log.ts, packages/eas-cli/src/submissions/utils/files.ts, packages/eas-cli/src/uploads.ts, packages/eas-cli/src/utils/progress.ts, packages/eas-cli/src/utils/timer.ts
Replace the loading bar with a percentage ticker (also fix the loading progress).
> ✔ Uploaded to EAS 1s
=> Implement new progress logs

packages/eas-cli/__mocks__/ora.ts, packages/eas-cli/src/build/android/configure.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/credentials.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/device/view.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/credentials/android/actions/FcmKey.ts, packages/eas-cli/src/credentials/android/actions/RemoveKeystore.ts, packages/eas-cli/src/credentials/android/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/android/actions/UpdateCredentialsJson.ts, packages/eas-cli/src/credentials/android/actions/UpdateKeystore.ts, packages/eas-cli/src/credentials/ios/actions/CreateDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/CreateProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/RemoveDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/RemoveProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/UpdateCredentialsJson.ts, packages/eas-cli/src/credentials/ios/actions/UpdateDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/UseDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/CreateDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/appstore/resolveCredentials.ts, packages/eas-cli/src/log.ts, packages/eas-cli/src/project/ensureProjectExists.ts, packages/eas-cli/src/submissions/BaseSubmitter.ts, packages/eas-cli/src/submissions/archiveSource/ArchiveFileSource.ts
- make CLI match video updates
=> Improve logging

packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/ios/appstore/AppStoreApi.ts, packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts
=> [submit] Unify app creation code

package.json, packages/eas-cli/.eslintrc.js, packages/eas-cli/graphql-codegen.yml, packages/eas-cli/graphql.schema.json, packages/eas-cli/package.json, yarn.lock
setup [eslint for graphql](https://github.com/apollographql/eslint-plugin-graphql) with no rules - rules will be applied in later PR's. Setup includes:
- introspection json from server
- required graphql plugin from .eslintrc.js
=> [eas-cli] 1/n setup eslint for graphql

packages/eas-cli/.eslintrc.js, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleAppIdentifierQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDeviceQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDistributionCertificateQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleProvisioningProfileQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleTeamQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppBuildCredentialsQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppCredentialsQuery.ts, packages/eas-cli/src/user/User.ts
Ensure all graphql operations have a name. More info here: https://github.com/apollographql/eslint-plugin-graphql
=> [eas-cli] 3/n apply  named operations rule

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/new/CreateDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/DeviceUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/DistributionCertificateUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/ProvisioningProfileUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleAppIdentifierMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDeviceMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDeviceRegistrationRequestMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDistributionCertificateMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleProvisioningProfileMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleTeamMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppBuildCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleAppIdentifierQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDeviceQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDistributionCertificateQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleProvisioningProfileQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleTeamQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppBuildCredentialsQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppCredentialsQuery.ts, packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/graphql/generated.ts
the credentials version of https://github.com/expo/eas-cli/pull/198
=> [eas-cli] use autogen query types - credentials

packages/eas-cli/src/build/utils/repository.ts
Will allow reading git specific info, e.g. sentry could read commit hash of the current build
Create a shallow cone of the local repo and pack it into a tar.gz.
Run build on local turtle
=> [eas-cli] create tarball with shallow clone of repository

CONTRIBUTING.md
I added the npm publish step to the release docs.
=> update release instructions

packages/eas-cli/src/project/projectUtils.ts
=> [eas-cli] Fix missing android.package error

packages/eas-cli/package.json, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-json/package.json, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/__tests__/EasJsonReader-test.ts, packages/eas-json/src/__tests__/deepMerge-test.ts, yarn.lock
Support configuring build environment
add values to eas.json schema and pass them to the job
build on staging
=> [eas-cli] configurable builder environment

packages/eas-cli/src/credentials/__tests__/fixtures-appstore.ts, packages/eas-cli/src/credentials/__tests__/fixtures-context.ts, packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/__tests__/fixtures-new-ios.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/RemoveDistributionCertificate-test.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/RemoveProvisioningProfile-test.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts
tests for https://github.com/expo/eas-cli/pull/221
=> [eas-cli] tests for credential removal

packages/eas-cli/src/prompts.ts
=> [eas-cli] fix tsc in prompt.ts

packages/eas-cli/graphql-codegen.yml, packages/eas-cli/src/commands/branch/delete.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/graphql/generated.ts
Add `eas branch:delete <name>`
delete the branch name.
Added an additional `no/yes` toggle as this is a sensitive operation.
created and deleted branches.
Confirmed it doesn't delete a branch which a channel is pointing at.
Confirmed it deletes a branch with/without updates on it.
=> [eas-cli] add branch:delete command

.github/PULL_REQUEST_TEMPLATE
Usually, people don't remember adding entries to the CHANGELOG. I've added a checklist (with only one item for now) to the PR template.
=> add first item to the PR checklist (changelog entry)

packages/eas-cli/package.json, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-json/package.json, yarn.lock
It's breaking change but it's breaking unpublished behaviour so I'm not adding that to the CHANGELOG
Changes in turtle-v2 affecting error format
Run build locally, check if error is displayed correctly
=> [eas-cli] update external errors logic

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/graphql/generated.ts
Add support for rollouts
If branch mapping data has a length of 2, display both branches and the rollout percentage.
Tested locally:
=> [eas-cli] add support for rollouts to channel:view command

packages/eas-cli/src/graphql/client.ts
Some server side errors are transient, this checks for them and notifies the user if so.
Looked at how errors are structured and added an appropriate check and a logging.
=> [eas-cli] add more info to transient errors

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-json/package.json, yarn.lock
Add support for --clear-cache flag in `eas build`
run local build
=> [eas-cli] support --clear-cache

packages/eas-cli/src/credentials/manager/ManageIosBeta.ts
There's quite a lot of actions in the beta credentials manager, and it's becoming difficult to navigate. It'll be even harder when we add push key support 😓 .  I've split the actions into different categories and changed the wording so it's easier to use.
=> [eas-cli] add high level actions to beta manager

packages/eas-cli/src/credentials/manager/ManageIosBeta.ts
Add the equivalent of the RemoveProvisioningProfile Action in the current credentials manager to the beta manager
=> [eas-cli] add RemoveProvisioningProfile to beta manager

CHANGELOG.md, packages/eas-cli/src/build/create.ts
#356 
Increase timeout to 1 hour
not tested
=> [eas-cli] increase build wait timeout

packages/eas-cli/src/build/utils/url.ts
Follow up from https://github.com/expo/eas-cli/pull/371 code review
=> [eas-cli] assert

packages/eas-cli/graphql-codegen.yml, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/credentials/AndroidAppBuildCredentials.ts, packages/eas-cli/src/graphql/types/credentials/AndroidAppCredentials.ts, packages/eas-cli/src/graphql/types/credentials/AndroidKeystore.ts
- Added some basic Android graphql fragments
- ran `yarn generate-graphql-code` to update generated types
=> [eas-cli] android graphql types

packages/eas-cli/src/credentials/manager/ManageIos.ts
feedback from @ide 
1. Setup -> set up 
2. EAS servers -> EAS
3. Add a dist cert: It is technically adding to your account first, then will later ask to add it to your project if you are in the correct context. Word it similarly to the 'delete' action for dist certs
=> [eas-cli] credentials manager DX nits

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-json/package.json, packages/eas-json/src/EasJsonSchema.ts, yarn.lock
Allow for users to specify what version of expo-cli to use in their build.
Add `expoCli` to the builder environment schema and then set it on the job.
Built locally and tested against production.
=> Add expoCli parameter.

packages/eas-cli/src/credentials/__tests__/fixtures-android-new.ts, packages/eas-cli/src/credentials/android/actions/new/AssignFcm.ts, packages/eas-cli/src/credentials/android/actions/new/CreateFcm.ts, packages/eas-cli/src/credentials/android/actions/new/__tests__/AssignFcm-test.ts, packages/eas-cli/src/credentials/android/actions/new/__tests__/CreateFcm-test.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/android/api/graphql/mutations/AndroidAppCredentialsMutation.ts, packages/eas-cli/src/credentials/android/api/graphql/mutations/AndroidFcmMutation.ts
add some simple graphql create and assign actions for fcm api key
=>  [eas-cli] fcm create and assign graphql actions

packages/eas-cli/src/credentials/manager/ManageIos.ts
because the previous version was harder to read
=> [eas-cli] refactor ios manager

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/ios/actions/PushKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/RemovePushKey.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/credentials/ApplePushKey.ts
Show the projects that depend on a push key, addressing feedback from https://github.com/expo/eas-cli/pull/470#discussion_r656112334
=> [ENG-1398][eas-cli] show projects that depend on a push key

CHANGELOG.md, packages/eas-cli/src/credentials/manager/ManageAndroid.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts
People will sometimes get unhelpful errors and ask for help about it. Unfortunately, it's really hard to figure what's going on if all the error says is `received unexpected null` without any additional context 😭   With oclif, we can pass in the DEBUG=* env var to get a stack trace, which will help immensely to track down the problem.
=> [eas-cli] better debugging experience 

CHANGELOG.md, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts
https://github.com/expo/eas-cli/issues/488
change order of operations when resolving package
run submit
=> [eas-cli] override value from app.json with param

packages/eas-cli/src/commands/branch/delete.ts, packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/commands/channel/edit.ts, packages/eas-cli/src/commands/channel/list.ts, packages/eas-cli/src/commands/channel/view.ts
While working on https://github.com/expo/eas-cli/pull/500/files noticed some UI improvements that I am splitting into a separate PR.
Tested in demo repo
=> [eas-cli] import UI in branch:* channel:* commands

packages/eas-cli/src/submissions/utils/errors.ts
closes #179
A follow-up of https://github.com/expo/turtle-v2/pull/599 and https://github.com/expo/fyi/pull/38
Pretty print that error message and displays link to a FYI page
Not tested - just added error message to the list.
Merge https://github.com/expo/fyi/pull/38 first!
=> [eas submit] Pretty-print iPad multitasking error message

package.json, packages/eas-cli/src/build/android/UpdatesModule.ts, packages/eas-cli/src/commands/build/list.ts, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/credentials/android/actions/AssignFcm.ts, packages/eas-cli/src/credentials/android/actions/BuildCredentialsUtils.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/actions/ConfigureProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/SetupAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/SetupTargetBuildCredentialsFromCredentialsJson-test.ts, packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfileAdhoc.ts, packages/eas-cli/src/credentials/ios/utils/__tests__/printCredentials-test.ts, packages/eas-cli/src/credentials/ios/utils/printCredentials.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/credentials/manager/SelectAndroidBuildCredentials.ts, packages/eas-cli/src/credentials/manager/__tests__/SelectIosDistributionTypeGraphqlFromBuildProfile-test.ts, packages/eas-cli/src/devices/actions/create/registrationUrlMethod.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/submissions/SubmissionService.ts, ts-declarations/xcode/index.d.ts, yarn.lock
I upgraded typescript to the latest in https://github.com/expo/eas-cli/pull/533. It seems it's not compatible with the `eslint-config-universe` version we use. I got this warning locally:
```
dsokal@Dominiks-MacBook-Pro  ~/work/expo/eas-cli   main  yarn lint                                                                                                                                                                               
yarn run v1.22.10                                                                                                                                                                                                                                     
$ eslint . --ext .ts …
```
=> [chore] upgrade: eslint, prettier, etc.

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/commands/build/cancel.ts, packages/eas-cli/src/commands/build/list.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/BuildQuery.ts, packages/eas-cli/src/submissions/utils/builds.ts
We want to make it possible to narrow down the result of `build:list` by introducing various filter params.
https://linear.app/expo/issue/ENG-1475/additional-filters-for-eas-buildview-and-eas-buildlist#comment-bbfe4a30-87e2-4520-9283-3d1b4405f8a8
https://forums.expo.io/t/cant-download-tar-builds-from-expo-cli/53904
I added more filter params to `build:list`. See the code.
Merge https://github.com/expo/universe/pull/7950 first
=> [ENG-1475] Additional filters for eas build:list

CHANGELOG.md, packages/eas-cli/src/build/build.ts
```
Waiting for build to complete. You can press Ctrl+C to exit.
⠸ Builds created: 2	Builds in unknown state: 2
```
=> [eas-cli] fix unknown state error

CHANGELOG.md
=> [changelog] fix formatting

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/project/ios/bundleIdentifier.ts, packages/eas-cli/src/project/ios/scheme.ts, packages/eas-cli/src/project/projectUtils.ts, yarn.lock
https://forums.expo.dev/t/eas-build-fail-every-time/56483
update config plugins
test with local builds(proper test requires server changes to also be deployed https://github.com/expo/eas-build/pull/45)
=> [eas-cli] support for names with unicode only characters

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/credentials/__tests__/fixtures-android.ts, packages/eas-cli/src/credentials/android/actions/CreateGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/actions/__tests__/CreateGoogleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/android/api/graphql/mutations/GoogleServiceAccountKeyMutation.ts, packages/eas-cli/src/credentials/android/credentials.ts, packages/eas-cli/src/credentials/android/utils/googleServiceAccountKey.ts, packages/eas-cli/src/credentials/utils/promptForCredentials.ts, packages/eas-cli/src/graphql/generated.ts
This PR allows the user to create a new GoogleServiceAccountKey on the www servers. It will eventually be used in the credentials management workflow and the submissions workflow.
=> [eas-cli] create GoogleServiceAccountKey

packages/eas-cli/package.json, packages/eas-cli/src/analytics.ts, yarn.lock
Updates the analytics client to the latest version. Will reduce the size and remove unneeded dependencies.
Patched the npm package. Made small adjustments to code around the new async flush.
Ran some commands, made sure events were showing up in the backend
=> [eas-cli] Patch @expo/rudder-sdk-node

CHANGELOG.md, packages/eas-cli/src/build/android/__tests__/version-test.ts, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/configure.ts, packages/eas-cli/src/build/android/version.ts, packages/eas-cli/src/build/ios/__tests__/version-test.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/build/ios/version.ts, packages/eas-cli/src/build/utils/version.ts, packages/eas-json/src/EasBuild.types.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/index.ts
extend auto incrementing to Android.
Followed this PR: https://github.com/expo/eas-cli/pull/231
Added tests.
Ran a a managed and bare demo repo with `autoIncrement : true` and confirmed that the appropriate files were mutated.
=> [eas-cli] Enable autoIncrementing on Android

CHANGELOG.md, packages/eas-cli/src/credentials/ios/utils/__tests__/__snapshots__/printCredentials-test.ts.snap, packages/eas-cli/src/credentials/ios/utils/__tests__/printCredentials-test.ts, packages/eas-cli/src/credentials/ios/utils/printCredentials.ts
Fix the way we print iOS credentials, followup from https://github.com/expo/eas-cli/pull/649#discussion_r717252597
=> [eas-cli] fix ios print formats

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/package.json, packages/eas-cli/src/build/android/graphql.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/graphql.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/utils/devClient.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-json/package.json, packages/eas-json/src/EasBuild.types.ts, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/__tests__/EasJsonReader-build-test.ts, yarn.lock
https://github.com/expo/universe/pull/8322#discussion_r737112924
See also: 
- https://github.com/expo/universe/pull/8381
- https://github.com/expo/turtle-v2/pull/697
- https://github.com/expo/eas-build/pull/53
Rename `useDevelopmentClient` -> `developmentClient`.
CI
=> rename `useDevelopmentClient` to `developmentClient`

.eslintrc.js, .gitignore, .prettierrc, package.json, yarn.lock
Superseeds:
* #760
Unfortunately I have an outdated a bit fork, did not spot that before the initial PR has been published. 🤦 
This PR salvages all still valid changes from the mentioned above PR.
It also includes an addition od `.idea` directory to the `.gitignore` file.
`yarn lint` check was successful.
`yarn build` in both packages was successful.
=> [workspace] update Prettier

CHANGELOG.md, packages/eas-cli/src/build/utils/devClient.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/utils/__tests__/profiles-test.ts, packages/eas-cli/src/utils/profiles.ts, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/__tests__/EasJsonReader-build-test.ts
https://github.com/expo/eas-cli/issues/758
It seems the error message is not descriptive enough.
Make the error message more descriptive.
Unit tests.
=> make the missing build/submit profile error message more descriptive

CHANGELOG.md, packages/eas-cli/src/build/local.ts
Fixes https://github.com/expo/eas-cli/issues/778
Check if npm >= 7.0.0 and pass `-y` to `npx`.
=> check npm version when building locally

CHANGELOG.md, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/commands/build/configure.ts, packages/eas-cli/src/vcs/clients/git.ts
Closes https://github.com/expo/eas-cli/issues/779
Make the error message more descriptive.
=> better error message when git is not installed

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
Closes #796
https://github.com/expo/plugin-warn-if-update-available/commit/2d1e9fc46745eb1c8a1c559d3461d30c96fa6476
changed version in package.json to lower value and run some build command with `2>/dev/null` and without it
=> print warning about outdated version to stderr

CHANGELOG.md, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/commands/update/configure.ts
We want a way to auto configure the EAS Update URL.
Added command `eas update:configure`
tested in demo repo.
=> [eas-cli] add eas update:configure

packages/eas-cli/src/commands/channel/edit.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/update/utils.ts
=> [eas-cli] fix typos in eas channel:view logging

CHANGELOG.md, packages/eas-cli/src/submit/ios/IosSubmitCommand.ts
error message for someone that run submit first time in non-interactive mode is not clear
=> [eas-cli] improve error message for missing ascAppId

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
expo-cli has been released. We should stay up-to-date with `@expo/*` deps.
Fixes https://github.com/expo/eas-cli/issues/795
Upgrade `@expo/*` deps
CI
=> upgrade @expo/* deps

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/metadata.ts, packages/eas-json/package.json, yarn.lock
Add react-native version to metadata
resolve react-native version using resolvFrom
if node_modules do not exist or react-native is not installed it should fail silently
run build
=> detect react-native version + update eas-build-job

packages/eas-cli/src/commands/update/publish.ts
It's a nicer UX to fill out all the prompts before starting the bundling.
cut/paste code
Tested in demo repo.
=> [eas-cli] ask for publish message before staring bundling

packages/eas-cli/src/commands/update/index.ts
'eas update' fails silently when it is run and the project has no branches
Drop into a prompt and ask the user to name the new branch.
demo repo
=> [eas-cli] handle 'eas update' when there are no branches

packages/eas-cli/src/commands/update/configure.ts
"eas update:configure" sets the runtimeVersion to a policy. Runtime version policies are not supported in bare.
Set runtime version to "1.0.0"
demo repo bare/managed
=> [eas-cli] Make default runtime version 1.0.0 for bare workflow

packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/update/utils.ts
=> [eas-cli] fix table column names

packages/eas-cli/src/commands/update/index.ts
"eas update --republish" does not prompt for missing update message.
Add it back in.
demo repo
=> [eas-cli] fix missing republish message

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/Submission.ts, packages/eas-cli/src/submit/utils/urls.ts
Fixes https://github.com/expo/eas-cli/issues/844
Use `app.slug` instead of `app.name` when formatting the submission url.
=> fix submission url

packages/eas-cli/src/api.ts, packages/eas-cli/src/commands/update/configure.ts, packages/eas-cli/src/commands/update/index.ts
To make development easier, support staging and local update URLs
=> [eas-cli] support staging and local Update URLs

.github/workflows/install.yml, bin/install.sh
Fixes broken installer workflow.
=> fix install.sh

CHANGELOG.md, packages/eas-cli/src/commands/channel/delete.ts, packages/eas-cli/src/commands/channel/edit.ts, packages/eas-cli/src/graphql/generated.ts
Add eas channel:delete
copied eas branch:delete
tested in demo repo
=> [eas-cli] add channel:delete

packages/eas-cli/src/commands/channel/delete.ts, packages/eas-cli/src/graphql/generated.ts
The oclif package needed to be upgraded to fix the conflict.
=> [eas-cli] fix merge conflict in #846

packages/eas-cli/src/commands/branch/create.ts, packages/eas-cli/src/commands/branch/delete.ts, packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/branch/rename.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/commands/channel/edit.ts, packages/eas-cli/src/commands/channel/list.ts, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/commands/update/delete.ts, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/commands/update/view.ts
Applying suggestions from this comment more generally: https://github.com/expo/eas-cli/pull/846#discussion_r768701581
=> [eas-cli] fix json output in EAS Update commands

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
Adds autocompletion for EAS CLI.
Install `@expo/plugin-autocomplete` which is a fork of `@oclif/plugin-autocomplete` with upgraded `cli-ux` and removed `moment`.
The same as in https://github.com/expo/eas-cli/pull/852
=> add autocompletion plugin

.github/ISSUE_TEMPLATE/bug_report.yml
We often need to ask the issue's author to provide the build details page URL. Let's ask the user to provide it in the issue template.
=> update issue template

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-json/package.json, yarn.lock
=> [eas-cli] add Monterey image

packages/eas-cli/src/commands/update/delete.ts
`eas branch:publish` has been renamed `eas update`
=> [eas-cli] update error message to new publish command

packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/credentials/ios/actions/RemoveAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/RemovePushKey.ts, packages/eas-cli/src/credentials/ios/actions/SetUpDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/__mocks__/ConfigureProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/__mocks__/CreateProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/__mocks__/SetUpDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/RemoveAscApiKey-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/RemovePushKey-test.ts, packages/eas-cli/src/credentials/ios/appstore/AppStoreApi.ts, packages/eas-cli/src/credentials/ios/appstore/__tests__/capabilityIdentifiers-test.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfile.ts, packages/eas-cli/src/project/projectUtils.ts, packages/eas-cli/tsconfig.json
There are unused variables in the eas-cli code base.
Set "noUnusedParameters" and  "noUnusedLocals" in the tsconfig.
Delete unused code.
tests pass
=> [eas-cli] add tsconfig unused var rules

packages/eas-cli/package.json, packages/eas-cli/src/build/android/UpdatesModule.ts, packages/eas-cli/src/build/ios/UpdatesModule.ts, packages/eas-cli/src/utils/code-signing.ts, yarn.lock
https://github.com/expo/eas-cli/pull/964#discussion_r802701522
Upgrade packages, make required changes, remove any casts.
Run tests.
=> [eas-cli] Update @expo/config-types and related packages

CHANGELOG.md, packages/eas-cli/src/commands/build/index.ts
=> [eas-cli] remove unused flag

CHANGELOG.md, packages/eas-cli/src/user/User.ts, packages/eas-cli/src/user/__tests__/User-test.ts
fix regression introduced in #1000
=> [eas-cli] Fix login request + update CHANGELOG

CHANGELOG.md, packages/eas-cli/src/build/build.ts
=> [eas-cli] Fix build status when build is canceled

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/fetch.ts, packages/eas-cli/src/graphql/client.ts, yarn.lock
Add proxy support
proxy traffic if `http_proxy` env is present
Setup local proxy and verify all requests go through it ( tested with `eas credentials` including apple authentication)
=> [eas-cli] proxy support

CHANGELOG.md, package.json, packages/eas-cli/package.json, packages/eas-json/package.json, yarn.lock
=> upgrade dependencies

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
- Related https://github.com/expo/expo-cli/pull/4300
-  Bump @expo/apple-utils@0.0.0-alpha.31
=>  Bump @expo/apple-utils@0.0.0-alpha.31

packages/eas-cli/package.json, packages/eas-json/package.json, yarn.lock
=> [eas-cli] update eas-build-job

CHANGELOG.md, packages/eas-cli/src/submit/submit.ts, packages/eas-cli/src/submit/utils/errors.ts
Addresses @brentvatne's feedback from https://github.com/expo/turtle-v2/pull/973#issuecomment-1141560790
Add new common error code + error message.
The first run is before and the second after this change:
=> add common error code - fastlane timeout

.github/ISSUE_TEMPLATE/bug_report.yml
I see a lot of issues reported where expo doctor points out some issues, even if it's not the issue it slows down the process of identifying the problem.
=> Update issue template (expo doctor output)

CHANGELOG.md, packages/eas-cli/package.json
This file is required for `eas metadata:push` and is part of the linting process.
Added `/schemas` to `package.json` files.
`npm pack`, see if the `/schemas/metadata-0.json` in there.
=> [eas-cli] Add schemas to the bundled files

packages/eas-cli/src/build/build.ts, packages/eas-cli/src/submit/__tests__/ArchiveSource-test.ts, packages/eas-cli/src/submit/utils/files.ts, packages/eas-cli/src/uploads.ts
https://github.com/expo/eas-cli/pull/1207#issuecomment-1184606788
Rename the function to avoid future confusion.
CI
=> rename uploadAsync -> uploadFileAtPathToS3Async

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/package.json, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/createContext.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-json/package.json, yarn.lock
We want to allow users to attach messages to builds.
- Add `--message` / `-m` param to `eas build`.
- Add message to metadata.
I ran `eas build -m "test message"` and checked that the message was saved to metadata.
=> [ENG-5836] add --message param to eas build

packages/eas-cli/graphql.schema.json, packages/eas-cli/package.json, packages/eas-cli/src/build/__tests__/metadata-test.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-json/package.json, yarn.lock
A Follow-up to the discussion under https://github.com/expo/eas-cli/pull/1239
We want to add the git commit message to build metadata.
Add git commit message to metadata.
I ran a build and changed the message was stored with other build metadata.
=> [ENG-5836] add git commit message to metadata

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/graphql.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/android/syncProjectConfiguration.ts, packages/eas-cli/src/build/android/version.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/graphql.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/ios/syncProjectConfiguration.ts, packages/eas-cli/src/build/ios/version.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/commands/build/version/set.ts, packages/eas-cli/src/commands/build/version/sync.ts, packages/eas-cli/src/commands/update/configure.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/project/remoteVersionSource.ts
Autoincrement versions when building with version source set to remote. This is the last part to make it work, but before this PR lands I still need to update docs and add new runtime version policy
Android
iOS
run few build for managed and bare projects
=> [eas-cli] managed versions support

CHANGELOG.md, packages/eas-json/package.json
It looks like we are including everything in the npm package.
Include only the build directory.
Not sure how to test, I based this on eas-cli package.json
=> [eas-json] Stop including sources in npm package

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/BuildQuery.ts, packages/eas-cli/src/graphql/types/Build.ts, packages/eas-cli/src/submit/submit.ts
Closes #1181 
Run:
- `eas build --json --no-wait --non-interactive --auto-submit`
- `eas build --json --no-wait --non-interactive`
- `eas build --json --non-interactive --auto-submit`
=> [ENG-5536][eas-cli] add submit info to json only output

CHANGELOG.md, packages/eas-cli/src/build/android/version.ts, packages/eas-cli/src/build/ios/version.ts
Few wording/formatting changes suggested by Dominik.
=> [eas-cli] Improve wording for version bumps

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/vcs/clients/git.ts, yarn.lock
Fixes https://github.com/expo/eas-cli/issues/1276
Initialize git repo in workspace root.
- Followed the repro steps from https://github.com/expo/eas-cli/issues/1276
- Initialized a new project with `create-expo-app`, removed `.git`, and run `eas build`.
=> [eas-cli] init git repo in monorepo root

.github/workflows/test.yml, CHANGELOG.md
We do not have any shell scripts anymore.
=> [eas-cli] remove shell check

CHANGELOG.md
This got in here in https://github.com/expo/eas-cli/pull/1278#pullrequestreview-1076134919.
Remove.
N/A
=> [eas-cli] Remove git merge artifact from CHANGELOG

CHANGELOG.md, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/submit/utils/wait.ts, yarn.lock
https://linear.app/expo/issue/ENG-6102/remove-timeout-from-eas-build-command
Remove timeout when waiting for build / submit.
None
=> remove timeout when waiting for build / submit

CHANGELOG.md
This change is not a part of `1.0.0`.
Correct Changelog.
N/A
=> [cli] correct Changelog

packages/eas-cli/src/graphql/queries/EnvironmentSecretsQuery.ts
All params passed to this function are `projectId`.
Rename param as it is incorrect.
`yarn start`
=> [eas-cli] Fix EnvironmentSecretsQuery param name

CHANGELOG.md, packages/eas-cli/src/project/projectUtils.ts
Before and after (IMO looks better):
=> improve instructions on setting eas.projectId in app.json

CHANGELOG.md, packages/eas-cli/src/branch/queries.ts, packages/eas-cli/src/update/utils.ts
Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.
Branch list would error when the following command was performed: `eas branch:create "test" && eas branch:list`
Fix error where platform-less branches would throw a type error
Run `eas branch:create "test" && eas branch:list` with `v1.2.0`, see an error, run again with this branch and see it succeed
=> Fix viewing branch list when a branch has no associated platforms

CHANGELOG.md
Changlog for linked PRs.
Update changelog.
Inspect.
=> [eas-cli] Update changelog for recent series of stacked commits

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-json/package.json, packages/eas-json/schema/eas.schema.json, yarn.lock
Companion to https://github.com/expo/turtle-v2/pull/1058
Add new image to `eas-json` schema
=> [eas-json] add Xcode 14 image

packages/eas-cli/src/credentials/android/actions/CreateFcm.ts, packages/eas-cli/src/credentials/android/actions/CreateGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/actions/CreateKeystore.ts, packages/eas-cli/src/credentials/android/actions/RemoveGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/actions/UseExistingGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/__tests__/IosCredentialsProvider-test.ts, packages/eas-cli/src/credentials/ios/actions/AscApiKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/CreateAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/CreateDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/CreatePushKey.ts, packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts, packages/eas-cli/src/credentials/ios/actions/PushKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/RemoveAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/RemoveDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/RemovePushKey.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/SetUpInternalProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleTeamMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/types/AppLookupParams.ts, packages/eas-cli/src/credentials/ios/types.ts, packages/eas-cli/src/credentials/ios/utils/__tests__/printCredentials-test.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/devices/actions/create/__tests__/action-test.ts, packages/eas-cli/src/devices/actions/create/action.ts, packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/user/Account.ts
This will enforce that everywhere we deal with accounts that they've been appropriately queried from graphql with enough info to be used anywhere.
Replace.
Run tests.
=> [9/n][eas-cli] Account -> AccountFragment

CHANGELOG.md
Add changelog entry for recent stacked PRs (no single PR in the stack could have the changelog)
Add changelog
N/A
=> [eas-cli] Add changelog entry for command context

CHANGELOG.md
Landed a large stack that didn't include any changelog changes since it's messy to do so in a stack.
Add changelog entries.
Inspect.
=> [eas-cli] Update Changlog for recent stack land

packages/eas-cli/src/commands/update/index.ts
Wrong verb form was used
Change the error message to use the correct verb form.
N/A
=> [eas-cli] Fix typo when failing to publish updates

CHANGELOG.md
Updating changelog for recent PRs.
Update the changelog
Inspect
=> [eas-cli] Update changelog

packages/eas-cli/src/commandUtils/EasCommand.ts, packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts, packages/eas-cli/src/commands/project/__tests__/init.test.ts, packages/eas-cli/src/user/SessionManager.ts
Reverts expo/eas-cli#1439
Why: https://github.com/expo/eas-cli/pull/1439#issuecomment-1278347345
=> Revert "[eas-cli] Fix command statistic analytics"

CHANGELOG.md, packages/eas-cli/src/submit/utils/errors.ts
Companion to https://github.com/expo/turtle-v2/pull/1106
Change old errors and handle new ones.
None
=> handle new EAS Submit errors

packages/eas-cli/src/commands/project/__tests__/init.test.ts, packages/eas-cli/src/commands/project/init.ts
All three of these fields (`extra.eas.projectId`, `owner`, `slug`) must be set up and matching for EAS and other tooling to work. https://github.com/expo/eas-cli/pull/1376 added the ability to specify the id via a flag during init. https://github.com/expo/eas-cli/pull/1405 added code to ensure that all three are in alignment during command running.
This PR adds code to ensure and correct alignment during the init command.
The goal is for the user to not have to add owner/slug during setup.
Previously:
```
<create app on website>
npx create-expo-app watwatddd
<manually add owner field>
eas init --id <id copied from website>
```
Now:
```
<create app on website>
npx create-expo-app watwatddd
eas init --id <id copied from website>
```
Add code to verify consistency and test to ensure this …
=> [eas-cli] Update init command to handle slug and owner

CHANGELOG.md, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/project/projectUtils.ts
=> chore(updates): fix up install prompt language

CHANGELOG.md
Forgot to do this in the PR itself.
Add entry.
Inspect.
=> [eas-cli] Add changelog entry for #1452

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-json/package.json, packages/eas-json/schema/eas.schema.json
Companion to https://github.com/expo/turtle-v2/pull/1142
Add Xcode 14.1 image. Change `latest` and `default` tags.
Run test builds
=> [ENG-6892][eas-json] add Xcode 14.1 image

CHANGELOG.md, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/submit/ArchiveSource.ts, packages/eas-cli/src/submit/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submit/ios/__tests__/IosSubmitCommand-test.ts
We still use "Submission Service" in some parts of the code.
Replace all occurrences of "Submission Service" with "EAS Submit". 
None.
=> change wording: "Submission Service" -> "EAS Submit"

CHANGELOG.md, packages/eas-cli/src/build/createContext.ts
Add SDK version to tracking context
run build
=> [ENG-6893][eas-cli] Add SDK version to tracking context

CONTRIBUTING.md, RELEASING.md
Fixes https://github.com/expo/eas-cli/issues/1578
- Mosty copy paste https://github.com/expo/eas-cli/compare/%40dsokal/contributing?expand=1 and leave important parts. 
- Add instructions on using local/staging API server.
None
=> update CONTRIBUTING.md + add RELEASING.md

CHANGELOG.md, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/commands/project/init.ts, packages/eas-cli/src/credentials/ios/utils/convertHTMLToASCII.ts, packages/eas-cli/src/log.ts, packages/eas-cli/src/project/fetchOrCreateProjectIDForWriteToConfigWithConfirmationAsync.ts, packages/eas-cli/src/submit/utils/urls.ts
We have an util to format links in messages, but it is not used consistently.
Ensure that all links included in messages are decorated with `link` util, relay on `fallback` instead of directly checking the flag.
All `eas-cli` tests are passing.
=> [eas-cli] ensure that all links are clickable, unify display

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/UserQuery.ts, packages/eas-cli/src/user/User.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1673454832098399
https://github.com/expo/eas-cli/pull/1616/commits/471e494a93e24f3a22631a0187ffdfb6f7bb8ade
Apply changes suggested by @Izkb.
Tests
=> [eas-cli] improve handling SSOUser type

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/android/graphql.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/graphql.ts, packages/eas-cli/src/build/ios/graphql.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/BuildMutation.ts, packages/eas-cli/src/update/__tests__/getBranchNameFromChannelNameAsync-test.ts
Update metadata from internal builds
Use new graphql endpoint to update metadata from `eas build:internal` command
Tested with local www
=> [eas-cli] Update build metadata for internal builds

CHANGELOG.md, packages/eas-json/schema/eas.schema.json
https://linear.app/expo/issue/ENG-7389/add-build-image-for-xcode-142
Companion to https://github.com/expo/turtle-v2/pull/1209
=> [ENG-7389][eas-json] add Xcode 14.2 image to schema

packages/eas-cli/README.md
It looks like oclif was looking at generated js files to generate README, so new commands showed up that were only existing locally for developer that ran `yarn relealse`
`yarn run version`
=> [eas-cli] Fix README.md

CHANGELOG.md, packages/eas-cli/src/commandUtils/context/contextUtils/__tests__/getProjectIdAsync-test.ts, packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
https://github.com/expo/eas-cli/issues/1695#issuecomment-1431727582
This clarifies this condition for robots.
Closes https://github.com/expo/eas-cli/issues/1695.
Fork error for robots. Add test.
Run test.
=> [eas-cli] Clarify missing owner field error message for Robot users

packages/eas-cli/src/commands/channel/rollout.ts
When dogfooding this new feature, these small things were noticed.
Closes ENG-7994.
- Add better branch selection.
- Unhide the command.
`~/expo/eas-cli/packages/eas-cli/bin/run channel:rollout main`, see branch selector
=> [eas-cli] Unhide channel:rollout command and modernize

packages/eas-cli/package.json, packages/eas-cli/src/project/customBuildConfig.ts, yarn.lock
Follow-up to https://github.com/expo/eas-build/pull/215.
Validate custom build configuration in EAS CLI and print a meaningful error message.
Tested manually:
=> [ENG-7926] validate custom build config in CLI

packages/eas-cli/src/project/publish.ts
This was incorrect due to a faulty refactor. This reverts it back to the previous message. We may consider making a rollback-to-embedded-update specific version of this message but it's probably not necessary.
Fix.
Inspect.
=> [eas-cli] Fix update message prompt

CHANGELOG.md, packages/eas-cli/src/project/publish.ts
Similar issue to https://github.com/expo/eas-cli/pull/1791. Refactored code had an issue in it. (we really have zero test coverage for this stuff, we should improve that).
Fixes #1799.
Closes ENG-8393.
Fix return value.
Run `eas update` with a long message, ensure it is truncated.
=> [eas-cli] Fix message truncation for update message

CHANGELOG.md, packages/eas-json/schema/eas.schema.json
Add info about new image
Add info about new image
=> [ENG-8074][eas-json] add info about new image

packages/eas-cli/src/__tests__/commands/__snapshots__/build-version-get-test.ts.snap, packages/eas-cli/src/__tests__/commands/build-version-get-test.ts, packages/eas-cli/src/__tests__/commands/build-version-set-test.ts, packages/eas-cli/src/__tests__/commands/build-version-sync-test.ts, packages/eas-cli/src/__tests__/commands/utils.ts, packages/eas-cli/src/commandUtils/EasCommand.ts, packages/eas-cli/src/project/__mocks__/applicationIdentifier.ts, packages/eas-cli/src/prompts.ts
More test.
Write tests.
Run tests.
=> [eas-cli] add tests for `eas build:version:*` commands

.github/workflows/test.yml
Tests are failing randomly.
Increase heap limit for tests
CI
=> [eas-cli] Fix random test failures

packages/eas-cli/package.json, yarn.lock
update `@expo/steps`
update `@expo/steps`
=> [eas-cli] update `@expo/steps`

packages/eas-cli/package.json, yarn.lock
bump `@expo/steps` version
bump `@expo/steps` version
tests
=> [eas-cli] bump `@expo/steps` version

CHANGELOG.md, packages/eas-cli/src/commands/update/configure.ts, packages/eas-cli/src/vcs/clients/git.ts
When you run`eas update:configure` and you don't have git installed, ask to initialize the repo just like `eas build:configure` does.
Before:
```
quins-MacBook-Pro:AwesomeProject quin$ ~/Documents/eas-cli/packages/eas-cli/bin/run update:configure
💡 The following process will configure your project to run EAS Update. These changes only apply to your local project files and you can safely revert them at any time.
git exited with non-zero code: 128
```
After:
```
uins-MacBook-Pro:AwesomeProject quin$ ~/Documents/eas-cli/packages/eas-cli/bin/run update:configure
💡 The following process will configure your project to run EAS Update. These changes only apply to your local project files and you can safely revert them at any time.
It looks like you haven't initialized the git repository yet.
EAS …
```
=> [eas-cli] updates: error gracefully if no git repo

packages/eas-json/schema/eas.schema.json
update images info after adding Xcode 14.3.1 image
https://github.com/expo/turtle-v2/pull/1352
update images info after adding Xcode 14.3.1 image
=> [ENG-9189][eas-json] update images info after adding Xcode 14.3.1 image

CHANGELOG.md, packages/eas-cli/src/channel/branch-mapping.ts, packages/eas-cli/src/channel/utils.ts, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/rollout/__tests__/utils-test.ts, packages/eas-cli/src/rollout/utils.ts
This PR:
- adds branch mapping utility functions and updates their definitions to be the same as www. The previous definitions were a rough approximation of what was declared in www and were not correct.
- does not change the behaviour of our commands does not change. However, some assertions were added in order to get our cli code to play well with the new branch mapping definitions.
- adds rollout utility functions for use later
=> [eas-cli] branch mapping utility functions

packages/eas-cli/src/channel/__tests__/fixtures.ts, packages/eas-cli/src/channel/__tests__/utils-test.ts, packages/eas-cli/src/channel/utils.ts
This PR:
- Adds graphql test fixtures for channels
- Makes a basic test for a new utility function
=> [eas-cli][2/2] update channel basic tests and fixtures

CHANGELOG.md, packages/eas-cli/src/channel/queries.ts, packages/eas-cli/src/utils/__tests__/relay-test.ts, packages/eas-cli/src/utils/relay.ts
I accidentally merged https://github.com/expo/eas-cli/pull/1953 into my base branch instead of main
=> [eas-cli] fetch entire relay compliant dataset

packages/eas-cli/package.json, yarn.lock
Bump package version
Bump package version
Tested manually on custom builds
=> [eas-cli] update `@expo/steps` version

CHANGELOG.md, packages/eas-cli/src/channel/__tests__/fixtures.ts, packages/eas-cli/src/channel/branch-mapping.ts, packages/eas-cli/src/rollout/__tests__/branch-mapping-test.ts, packages/eas-cli/src/rollout/branch-mapping.ts, packages/eas-cli/src/rollout/utils.ts
This PR adds support for:
- Rollout convenience objects
- more branch mapping utilities
- printing functions for rollout state
=> [eas-cli] more branch mapping utility

CHANGELOG.md, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/commands/build/version/get.ts, packages/eas-cli/src/commands/build/version/sync.ts, packages/eas-cli/src/commands/metadata/lint.ts, packages/eas-cli/src/commands/metadata/pull.ts, packages/eas-cli/src/commands/metadata/push.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/utils/__tests__/profiles-test.ts, packages/eas-cli/src/utils/profiles.ts
https://exponent-internal.slack.com/archives/C02123T524U/p1689882938014309
Read .nvmrc content and set `node` value in `buildProfile`.
1. Create valid .nvmrc file
2. Build project
3. Check in build logs if non-default node version is installed.
=> [ENG-9422][eas-cli] Use .nvmrc to set node version

packages/eas-cli/src/project/ios/target.ts
I was looking for something and stumbled upon a typo :)
=> [eas-cli] fix 'manged' typo in ios target

CHANGELOG.md, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/commands/update/republish.ts, packages/eas-cli/src/rollout/actions/CreateRollout.ts, packages/eas-cli/src/rollout/actions/EditRollout.ts, packages/eas-cli/src/rollout/actions/EndRollout.ts, packages/eas-cli/src/rollout/actions/SelectRuntime.ts, packages/eas-cli/src/rollout/utils.ts, packages/eas-cli/src/update/republish.ts
more grammar feedback from dogfooding
=> [eas-cli] more grammar fixes

CHANGELOG.md, packages/eas-cli/src/rollout/actions/SelectRuntime.ts
Link the `expo.fyi` article written for rollouts. It's currently a placeholder `expo.fyi/todo`
=> [ENG-9666][eas-cli] rollouts: link fyi

CHANGELOG.md, packages/eas-cli/src/channel/__tests__/branch-mapping-test.ts, packages/eas-cli/src/channel/branch-mapping.ts
=> [eas-cli] more branch mapping utils

CHANGELOG.md, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/commands/build/version/get.ts, packages/eas-cli/src/commands/build/version/sync.ts, packages/eas-cli/src/commands/metadata/lint.ts, packages/eas-cli/src/commands/metadata/pull.ts, packages/eas-cli/src/commands/metadata/push.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/utils/__tests__/profiles-test.ts, packages/eas-cli/src/utils/profiles.ts
https://exponent-internal.slack.com/archives/C02123T524U/p1689882938014309
Read .nvmrc content and set `node` value in `buildProfile`.
1. Create valid .nvmrc file
2. Build project
3. Check in build logs if non-default node version is installed.
1. https://github.com/expo/turtle-v2/pull/1393
2. https://github.com/expo/eas-cli/pull/1998
=> [ENG-9422]  nvmrc support for setting node version

packages/eas-cli/package.json, packages/eas-json/package.json, scripts/package.json, scripts/yarn.lock, yarn.lock
bump `semver` version
bump `semver` version
Tests
Test manually
=> [eas-cli][eas-json] bump `semver` version

packages/eas-json/schema/eas.schema.json
Remove doubled definition of `pnpm` field from eas.schema.json
=> [Fix] Remove doubled definition of `pnpm` field from eas.schema.json

CHANGELOG.md, packages/eas-cli/src/rollout/actions/__tests__/EditRollout-test.ts, packages/eas-cli/src/rollout/actions/__tests__/SelectRuntime-test.ts
Rollout tests i didnt get around to writing during launch week
=> [eas-cli] rollout tests

CHANGELOG.md, packages/eas-json/schema/eas.schema.json
https://linear.app/expo/issue/ENG-10384/add-images-for-jdk-17-and-21
Update `eas.schema.json`
=> [ENG-10384][eas-json] update `eas.schema.json` to include new JDK 17 image

CHANGELOG.md, packages/eas-json/schema/eas.schema.json
We are adding Xcode 15.1 image
Add new Xcode 15.1 image to `eas.schema.json`
Tests
=> [ENG-10922][eas-json] add new Xcode 15.1 image to `eas.schema.json`

CHANGELOG.md, packages/eas-cli/src/build/configure.ts
Simplification, unification.
Removed bare-specific template.
None.
=> [eas-cli] Remove bare-specific eas.json template

CHANGELOG.md, packages/eas-json/schema/eas.schema.json
Update `eas.schema.json` after adding Xcode 15.2 image
Update `eas.schema.json` after adding Xcode 15.2 image
=> [ENG-11092][eas-json] update `eas.schema.json` to add support for Xcode 15.2 image

CHANGELOG.md, packages/eas-cli/src/submit/ios/IosSubmitCommand.ts, packages/eas-cli/src/submit/ios/__tests__/IosSubmitCommand-test.ts, packages/eas-json/src/__tests__/submitProfiles-test.ts, packages/eas-json/src/schema.ts, packages/eas-json/src/submit/resolver.ts, packages/eas-json/src/submit/schema.ts, packages/eas-json/src/utils.ts
https://exponent-internal.slack.com/archives/C3M7V1T7Z/p1706298474970749
=> Revert "[eas-json] validate EAS Submit inputs better"

CODEOWNERS
Add @sjchmiela as code owner
Add @sjchmiela as code owner
=> [CODEOWNERS] add @sjchmiela as code owner

CHANGELOG.md, packages/eas-json/schema/eas.schema.json
Add Xcode 15.3 image
Add Xcode 15.3 image
=> [eas-json] add Xcode 15.3 image

.github/workflows/release.yml
https://github.com/expo/eas-cli/actions/runs/8850365600/job/24307670926
Make sure `distutils` are available
Try to retry workflow after merging this PR
=> [ci] fix build macos workflow

packages/eas-cli/src/commands/project/onboarding.ts
Small tweaks and fixes for onboarding command logs.
Adjust whitespace, linkify back to website URL, fix casing, change emojis.
The changes have been reviewed locally.
=> [eas-cli] onboarding logs content tweaks

CHANGELOG.md, packages/eas-json/schema/eas.schema.json
Update image tags in `eas.schema.json`
Update image tags in `eas.schema.json`
Tests
=> [eas-json] update image tags in `eas.schema.json`

packages/eas-cli/src/commands/project/onboarding.ts
improve prompt asking the user to specify target clone dir in `eas init:onboarding`
Show the target path more clearly
=> [eas-cli] improve prompt asking user to specify target clone dir in `eas init:onboarding`

CHANGELOG.md, packages/eas-cli/src/credentials/ios/actions/SetUpAdhocProvisioningProfile.ts, packages/eas-cli/src/devices/actions/create/registrationUrlMethod.ts
https://exponent-internal.slack.com/archives/C06EBFAVCEA/p1715694057685649
compress the bottom text into fewer lines
Before:
After:
=> [eas-cli] display device registration qr code better

packages/eas-cli/src/commands/project/onboarding.ts
Counterpart to https://github.com/expo/universe/pull/15336.
Applied the same changes.
None.
=> [eas-cli] Update default onboarding `eas.json`

CHANGELOG.md, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-json/schema/eas.schema.json
Add new images, deprecate old Android images
Add new images, deprecate old Android images
=> [eas-cli][eas-json] update and deprecate images

CHANGELOG.md, packages/eas-cli/src/project/ios/target.ts
---
**Fixed an issue where extensions were incorrectly retrieving the main app's entitlements instead of their own. Updated the code to use `dependency.name` for fetching the correct entitlements.**
---
In a project with multiple targets (one main app and two extensions), each target has its own `.entitlements` file with specific capabilities. However, the EAS CLI currently retrieves the `.entitlements` file for all targets using the main app's `.entitlements` file, leading to incorrect capability synchronization with Apple. This behavior causes issues when setting up credentials and syncing capabilities for each target, especially for extensions that require different capabilities from the main app.
The issue was addressed by modifying the `resolveBareProjectDependenciesAsync` function …
=> [eas-cli] Fix entitlements resolution for multiple iOS targets

packages/eas-cli/src/commands/env/pull.ts
https://exponent-internal.slack.com/archives/C06FK950085/p1725586296781109
warn people if pulling secret env vars in env:pull command
=> [eas-cli] warn people if pulling secret env vars in env:pull command

packages/eas-cli/src/commands/env/exec.ts, packages/eas-cli/src/utils/prompts.ts
Add the `eas env:exec` command. This command allows you to run any arbitrary bash command with env vars from a given environment.
Add `eas env:exec` command
Test manually
=> [eas-cli] add eas env:exec command

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/env/get.ts, packages/eas-cli/src/commands/env/update.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/EnvironmentVariablesQuery.ts
[ENG-13525 Update EAS-CLI for new EnvVar features
](https://linear.app/expo/issue/ENG-13525/update-eas-cli-for-new-envvar-features) 
Update EnvVar queries - allow quering using environments.
* Added optional `environment` parameter to queries
* Fix typing of the `--environment` parameter
=> Update Environment Variables queries:

CHANGELOG.md, packages/eas-cli/src/build/build.ts
Let people know that they can add more concurrencies easily
Make the message more clear
-
=> [eas-cli] Add message about concurrency add-on

CHANGELOG.md, packages/eas-json/schema/eas.schema.json
Add new Xcode 16.1 image and `sdk-52` tag to `eas.schema.json`
Add new Xcode 16.1 image and `sdk-52` tag to `eas.schema.json`
Tests
=> [eas-json] add new Xcode 16.1 image and  tag to

packages/eas-cli/src/commands/update/configure.ts
Add support for `with-eas-environment-variables-set` flag in `eas update:configure` command
Use the flag the same way we do for `eas update`.
Run command.
=> [eas-cli] add support for `with-eas-environment-variables-set` flag in `eas update:configure` command

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/commandUtils/flags.ts, packages/eas-cli/src/commands/env/create.ts, packages/eas-cli/src/commands/env/delete.ts, packages/eas-cli/src/commands/env/exec.ts, packages/eas-cli/src/commands/env/get.ts, packages/eas-cli/src/commands/env/list.ts, packages/eas-cli/src/commands/env/pull.ts, packages/eas-cli/src/commands/env/push.ts, packages/eas-cli/src/commands/env/update.ts
Make `eas env` commands visible
Make `eas env` commands visible
Tests
=> [eas-cli] make eas env flags visibile

CHANGELOG.md, packages/eas-cli/src/commands/env/pull.ts
https://exponent-internal.slack.com/archives/C06FK950085/p1732258126230829
Improve logs
Tests
=> [eas-cli] improve eas env:pull logging

CHANGELOG.md, packages/eas-cli/src/commands/worker/alias.ts, packages/eas-cli/src/commands/worker/deploy.ts
=> feat(eas-cli): Unhide `deploy` and `deploy:alias` commands

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/build/list.ts, packages/eas-cli/src/graphql/generated.ts
Allow filtering by `--fingerprint-hash` in the `eas build:list` command
Update GQL schema to add a new filter field, and add a new flag to use it.
Test locally
=> [eas-cli] allow filtering by fingerprint-hash in eas build:list command

.github/workflows/release.yml
It's been failing for a while. I think we'll have renovate some time in universe which will make this obsolete.
=> [infra] Remove disabled job

CHANGELOG.md, packages/eas-cli/src/commands/fingerprint/compare.ts
Reapply https://github.com/expo/eas-cli/pull/2859
=> [eas-cli] reapply website launcher

packages/eas-cli/src/commands/workflow/run.ts
https://linear.app/expo/issue/ENG-14752/update-copy-at-the-end-of-workflowrun
=> [eas-cli] Rephrase message at the end of workflow:run

CHANGELOG.md, packages/eas-cli/src/commands/fingerprint/compare.ts
=> [eas-cli] add oxford comma

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-json/schema/eas.schema.json, packages/eas-json/src/build/schema.ts, packages/eas-json/src/build/types.ts
Closes https://github.com/expo/eas-cli/issues/2401
Add `corepack` field to `eas.json`
Tests, tested manually
=> [eas-cli] add corepack field to eas.json

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/workflow/run.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/WorkflowRunQuery.ts
https://exponent-internal.slack.com/archives/C083Q88U4M8/p1747060067200209
Added `--wait`/`--no-wait` flag to `workflow:run`. It's off by default (keeping current behavior).
```
Compressing project files and uploading to EAS. Learn more: https://expo.fyi/eas-build-archive
✔ Uploaded project archive to EAS 1s
✔ Uploaded eas.json to EAS 
✔ Uploaded package.json to EAS 
See logs: http://expo.test/accounts/stanley/projects/test-local/workflows/0196c530-e558-7357-85ab-139314b21171
✔ Workflow run started successfully.
```
```
See logs: http://expo.test/accounts/stanley/projects/test-local/workflows/0196c52f-0536-774a-8639-1e9de629d88e
Waiting for workflow run to complete. You can press Ctrl+C to exit.
✖ Workflow run has failed.
```
```
See logs: …
```
=> [eas-cli] Add `--wait` flag to `workflow:run`

CHANGELOG.md, packages/eas-cli/src/credentials/android/utils/__tests__/printCredentials-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/DistributionCertificateUtils-test.ts, packages/eas-cli/src/credentials/ios/utils/__tests__/printCredentials-test.ts, packages/eas-cli/src/utils/__tests__/fingerprintDiff-test.ts
Some unit tests are failing locally due to incomplete mocks .
=> [eas-cli] Fix failing unit tests

CHANGELOG.md, packages/eas-cli/src/project/android/__tests__/fixtures/multiflavor-with-dimensions-array-build.gradle, packages/eas-cli/src/project/android/__tests__/gradleUtils-test.ts, packages/eas-cli/src/project/android/gradleUtils.ts
https://exponent-internal.slack.com/archives/C06EFBQK3B7/p1748956922999689
Added support for `flavorDimensions` specified as array of strings.
Added tests.
=> [eas-cli] Add support for array `flavorDimensions`

.github/workflows/release.yml, .github/workflows/test-graphql.yml, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/graphql/generated.ts
Noticed that a recent release failed the GraphQL check. This ensures that the release will fail if the check does not pass.
=> Add GraphQL check to release workflow

CHANGELOG.md, packages/eas-cli/src/user/expoSsoLauncher.ts
Graphite accidentally landed #3113. Not sure why. But it needed a changelog and a lint fix based on my requested review.
Fix, add changelog.
CI lint
=> [eas-cli] Fix lint
