packages/eas-cli/__mocks__/ora.ts, packages/eas-cli/src/submissions/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submissions/android/__tests__/ServiceAccountSource-test.ts
Replaced `ora`, `console.log` and `console.warn` with mocks in submission tests to improve readability of `yarn test`.
=> [eas-cli][tests] Remove console logs from submission tests

packages/config/src/EasJsonReader.ts, packages/eas-cli/package.json, packages/eas-cli/src/build/android/UpdatesModule.ts, packages/eas-cli/src/build/android/configure.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/UpdatesModule.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/bundleIdentifer.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/build/utils/repository.ts, packages/eas-cli/src/build/utils/updates.ts, packages/eas-cli/src/commands/build/configure.ts, packages/eas-cli/src/log.ts, packages/eas-cli/src/project/projectUtils.ts, yarn.lock
add `build:configure` command
- creates eas.json if it doesn't exist
- configure native project (android: create eas-build.gradle, ios: bundle identifier in xcode project)
- configure updates (set values in AndroidManifest.xml, Expo.plist, ios build phase script, android gradle script)
add a step to `build:create` command
- verify if `build:configure` was run before
- update sdk version or runtime version if app.json value changed
=> [expo-cli] configure EAS Build

packages/eas-cli/src/submissions/BaseSubmitter.ts, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submissions/android/AndroidSubmitter.ts, packages/eas-cli/src/submissions/commons.ts, packages/eas-cli/src/submissions/ios/IosSubmitCommand.ts, packages/eas-cli/src/submissions/ios/IosSubmitter.ts, packages/eas-cli/src/submissions/utils/summary.ts
Chained PR for #56
- Extracted common parts from `IosSubmitter` and `AndroidSubmitter`, created class hierarchy - they now derive from `BaseSubmitter`
- Extracted common methods from `AndroidSubmitCommand` and `IosSubmitCommand` to `commons.ts`
- Implemented "Print Summary" for iOS and extracted common code
=> Extract common code for submission commands

packages/eas-cli/src/commands/account/login.ts, packages/eas-cli/src/commands/account/logout.ts, packages/eas-cli/src/commands/account/view.ts
```
% ./bin/run account --help
Log in with your EAS account
USAGE
$ eas account:COMMAND
COMMANDS
account:login   Log in with your EAS account
account:logout  Log out
account:view    Show the username you are logged in as
```
=> Align account command names with the style guide

.github/workflows/release.yml, lerna.json, packages/config/package.json, packages/eas-cli/README.md, packages/eas-cli/package.json
This PR builds on #62 and adds Windows 32-bit and 64-bit installers, built with `oclif-dev pack:win`. We build these on Ubuntu because that's how the pack commands in `oclif-dev` are supposed to be used (they don't run on Windows).
=> Windows builds

.github/workflows/release.yml, lerna.json, packages/config/package.json, packages/eas-cli/README.md, packages/eas-cli/package.json
Change the release action to use `macos-latest` to build the macOS release packages, so that they include the correct `optionalDependencies` (for example `@expo/traveling-fastlane-darwin`).
=> Build macOS tarballs on macOS

packages/config/src/EasJsonReader.ts, packages/eas-cli/package.json, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/configure.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/credentials/__tests__/fixtures-context.ts, packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/android/AndroidCredentialsProvider.ts, packages/eas-cli/src/credentials/android/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/android/actions/UpdateCredentialsJson.ts, packages/eas-cli/src/credentials/android/utils/keystore.ts, packages/eas-cli/src/credentials/credentialsJson/__tests__/update-test.ts, packages/eas-cli/src/credentials/credentialsJson/read.ts, packages/eas-cli/src/credentials/credentialsJson/update.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/UpdateCredentialsJson.ts, packages/eas-cli/src/credentials/manager/ManageAndroidApp.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, yarn.lock
Reaching feature parity with expo-cli (for builds) + full support for managed workflow
- actions for syncing credentials.json with www under `eas credentials` command
- `credentials.json` support when building
- support for managed builds
- test fixtures for ios credentials api
- fixes to the project configuration when running `eas build:create`
=> credentials.json support + fixes for managed

packages/eas-cli/src/project/projectUtils.ts, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submissions/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submissions/commons.ts, packages/eas-cli/src/submissions/ios/IosSubmitCommand.ts, packages/eas-cli/src/submissions/ios/__tests__/IosSubmitCommand-test.ts
close https://github.com/expo/eas-cli/issues/72
Left name as `getProjectIdAsync` as I am under the impression that we want to move away from `app`.
=> [eas-cli] relocate getProjectIdAsync

packages/eas-cli/src/commands/credentials.ts, packages/eas-cli/src/credentials/CredentialsManager.ts
credentials manager started from `eas credentials` should ignore errors triggered by failing actions, but if run it from build command error should be propagated.
Add flag to `runManagerAsync`
=> [eas-cli] standalone credentials manager error handling

packages/eas-cli/package.json, packages/eas-cli/src/commands/build/submit.ts, packages/eas-cli/src/help.ts
This re-purposes the `helpLabel` property of flags (previously used to override the left column in `--help`) to be used as a group, so that flags can be grouped in the help output.
This is currently used in `eas build:submit --help`.
=> Add support for grouping flags in --help

packages/eas-cli/src/credentials/ios/appstore/provisioningProfileAdhoc.ts
`travelingFastlane` doesn't have the properties `provisioningProfile` and `provisioningProfileId`.
Looks like this code was added in #59.
=> Fix a typo in provisioningProfileAdhoc.ts

packages/eas-cli/package.json, packages/eas-cli/src/credentials/ios/appstore/authenticate.ts, packages/eas-cli/src/credentials/ios/appstore/bundleId.ts, packages/eas-cli/src/credentials/ios/appstore/distributionCertificate.ts, packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts, packages/eas-cli/src/credentials/ios/appstore/experimental.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfile.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfileAdhoc.ts, packages/eas-cli/src/credentials/ios/appstore/pushKey.ts, yarn.lock
- upgraded apple-utils which now requires request context (`{ teamId, providerId }`) be passed to every request.
- In an Expo project -> `eas credentials` -> iOS -> sign in -> Ensure all credentials are valid
=> upgraded apple utils to support request contexts

.github/workflows/test.yml
Turns out `tsc` was not running in the CI for all PRs at the moment.
Run `tsc` after the tests to ensure that there are no type errors.
=> Add tsc to CI pipeline

packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts, packages/eas-cli/src/submissions/ios/IosSubmitCommand.ts, packages/eas-cli/src/submissions/ios/utils/__tests__/language-test.ts, packages/eas-cli/src/submissions/ios/utils/language.ts
A step towards removing `traveling-fastlane`
- The whole process now uses the new API when `USE_APPLE_UTILS=1` env var is set
- Updated `--language` parameter to support both fastlane and new API, it is now smarter and supports both `English` and `en-US` formats interchangeably. 
- ~~Fixed `authenticateAsync()` not to prompt for team again when it's already selected.~~ Fix moved to https://github.com/expo/eas-cli/pull/85
TODO in the future:
- Add possibility to update app name on ASC (currently API doesn't allow us to do it)
- [Optional] Update bundle ID capabilities (the same way as `ensureAppExists()` does it for push notifications) based on app config
=> [eas-cli] Support for App Store API in iOS submissions

packages/eas-cli/package.json, packages/eas-cli/src/build/__tests__/credentials-test.ts, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/credentials.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/utils/repository.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-json/package.json, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/__tests__/EasJsonReader-test.ts, packages/eas-json/src/index.ts, yarn.lock
Copied from slack
>   :bulb: we decided to remove generating credentials for ios from build:configure for now (do it while running eas build instead, this is what happens for android already). in the future, we work towards handling credentials generation more ergonomically in the build:configure command but will do this when new credentials work is all ready.
>  change the way we handle a dirty git index when running build:configure and build
-  :bulb: build:configure: don’t block running on dirty git index, just warn and let the user proceed if they want (https://www.notion.so/expo/Minimal-suggested-new-output-401a03083eb041a8b619edc41b7147be)
-  :bulb: build: it’s important that we can commit changes during the build command, for example to bump runtime version. so, we will prompt …
=> improve user interaction for build and configure + cleanup types

packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/utils/repository.ts
If a build is updating some parts of the project, those changes won't be applied in the build process because changes are not committed
- commit changes before upload
- remove `modifyAndCommitAsync`
- configure project before credentials generation (bundle identifier might change during that process)
run configure and build with changed runtimeVersion
=> [eas-cli] commit changes when updating runtime version

packages/eas-cli/src/commands/release/edit.ts, packages/eas-cli/src/commands/release/rename.ts
While the graphql allows us to edit a release's name by either its `ID`, or the combination of `projectID` + `releaseName`, this command only implements the latter: `projectId` + `releaseName`. Adding both options seemed to add more clutter than utility.
Even though there is only one `edit` option: `rename` chose to require a special flag `--rename`.  This allows extensibility in the future and will also match other edit commands with more options, like the `channel:edit` command (which will have 2 possibilities).
=> [eas-cli] add release:edit

packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/create.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/commands/build/create.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/project/isEasEnabledForProject.ts, packages/eas-cli/src/project/projectUtils.ts, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submissions/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submissions/ios/IosSubmitCommand.ts, packages/eas-cli/src/submissions/ios/__tests__/IosSubmitCommand-test.ts, packages/eas-cli/src/submissions/types.ts
For Open Preview, we want to allow using EAS services (Build and Submit) only for paid (_paying?_) users.
- https://www.notion.so/expo/Allowlist-Free-Priority-Plan-for-existing-external-testers-for-EAS-Build-5b69631944134d8bb71a0112ef316dfc
- https://www.notion.so/expo/Gate-Open-Preview-behind-Dev-Services-558c8aefb4f348d9b8ab3739a867810c
API changes are in https://github.com/expo/universe/pull/6477
=> [eas-cli] disable eas build & submit for non-paying users

packages/eas-cli/src/build/android/applicationId.ts, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/configure.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/bundleIdentifer.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/build/utils/repository.ts, packages/eas-cli/src/commands/build/configure.ts, packages/eas-cli/src/credentials/ios/actions/UpdateCredentialsJson.ts, packages/eas-cli/src/credentials/manager/HelperActions.ts, packages/eas-cli/src/project/projectUtils.ts, packages/eas-cli/src/prompts.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts, packages/eas-cli/src/utils/git.ts
- getBundleIdentifier was inconsistent with the rest of configuration and validation steps when building
- We need to configure applicationId for android to support new credentials API
- when reading appIdentifier(bundle identifier or application id) read from app.json and fallback to native project if possible (The same approach as (`exp.owner ?? user.username`)
- when running `build` and app identifiers in a native project do not match thro exception
- when running `configure` ask which value is correct and update either native project or app.json
- if static config exists it will be updated, if only dynamic config is available throw an exception and ask user to update it
- for android only applicationId is updated by default
- package name will be updated with flag …
=> [eas-cli] configure app identifier for iOS and Android

packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/__tests__/EasJsonReader-test.ts
I put up a PR to update the "Configuration with eas.json" page in docs (https://github.com/expo/expo/pull/11192). I mentioned there the `distribution` config option for Android. 
I've realized that we should have more strict validation of internal distribution build profiles on Android.
There are two cases:
- generic projects:
- `gradleCommand` should produce an APK - I added a warning if it includes string `bundle` (`bundle*` produces AAB)
- @brentvatne do we want to prompt the user if they want to proceed? or the warning is fine?
- managed projects:
- validation of eas.json fails if `distribution = internal` and `buildType != apk`
I also fixed passing `releaseChannel` to turtle workers.
- Added unit tests for EasJsonReader.
- Tested manually by building Android for internal …
=> [eas-cli] improve internal distribution on android

packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/utils/repository.ts
This leaves some implementation details out of the messages because they aren't relevant to users. This PR is stacked on top of #103.
```
╰─$ easd build -p android
✔ Ensuring project @notbrent/tabsy is registered on Expo servers
Resolving credentials source (auto mode)
Using credentials stored on the Expo servers
✔ Project tarball created.
Uploading project to AWS S3
[====================================                            ] 56% 2.4s
```
```
╰─$ easd build -p android
✔ Ensuring project @notbrent/tabsy is registered on Expo servers
Resolving credentials source (auto mode)
Using credentials stored on the Expo servers
✔ Project ready to be uploaded
Uploading project to build servers
[====================================                            ] 56% 2.4s
```
=> [eas-cli] Improve wording around archiving and uploading project

packages/eas-cli/src/build/android/applicationId.ts, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/configure.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/bundleIdentifer.ts, packages/eas-cli/src/build/ios/configure.ts
app identifier is not validated when running build
- regexp and some of the error messages reused from expo-cli
- validate during build and configuration commands
run build and configure with valid and invalid app identifiers
=> [eas-cli] validate bundleIdentifer and applicationId

packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/commands/build/create.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/log.ts, packages/eas-cli/src/project/isEasEnabledForProject.ts, packages/eas-cli/src/submissions/android/ServiceAccountSource.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts, packages/eas-cli/src/submissions/ios/AppSpecificPasswordSource.ts, packages/eas-cli/src/submissions/ios/IosSubmitCommand.ts, packages/eas-cli/src/submissions/utils/errors.ts
- In prep for marketing, follow the style of our other tools a little closer (still doesn't implement linked text support).
- dim the `Learn more: <URL>`
- underline the URL
- downgrade user error message to warning
=> unify learn more url's format and clean up logs

packages/eas-cli/README.md, packages/eas-cli/src/build/android/applicationId.ts, packages/eas-cli/src/build/ios/bundleIdentifer.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/commands/account/login.ts, packages/eas-cli/src/commands/account/logout.ts, packages/eas-cli/src/commands/account/view.ts, packages/eas-cli/src/credentials/android/actions/__tests__/UpdateKeystore-test.ts, packages/eas-cli/src/credentials/context.ts, packages/eas-cli/src/credentials/credentialsJson/update.ts, packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts, packages/eas-cli/src/credentials/ios/actions/ProvisioningProfileUtils.ts, packages/eas-cli/src/credentials/ios/actions/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/SetupProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/api/Client.ts, packages/eas-cli/src/credentials/ios/utils/provisioningProfile.ts, packages/eas-cli/src/credentials/manager/HelperActions.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/project/ensureProjectExists.ts, packages/eas-cli/src/submissions/archiveSource/ArchiveTypeSource.ts
- noticed some typos while recording, did a small audit to get others
- changed "Artifact url: <URL>" to "App: <URL>"
- "Ensuring project ${chalk.bold(projectFullName)} is registered on Expo servers" -> "Ensuring ${chalk.bold(projectFullName)} is created on Expo"
=> cleaner logging + typos

packages/eas-cli/src/build/create.ts, packages/eas-cli/src/credentials/ios/actions/ConfigureProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/appstore/authenticate.ts, packages/eas-cli/src/credentials/ios/appstore/distributionCertificate.ts, packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfile.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfileAdhoc.ts, packages/eas-cli/src/credentials/ios/appstore/pushKey.ts, packages/eas-cli/src/credentials/ios/validators/validateProvisioningProfile.ts, packages/eas-cli/src/devices/actions/create/inputMethod.ts
- unify spinner behavior and logging format
- make error handling a bit better
=> clean up spinners and logs

packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/create.ts, packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/build/utils/repository.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/credentials/android/AndroidCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/CreateProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/SetupProvisioningProfile.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts
#120
- pass flag in the credentials provider
- verify nonInteractive param before some of the prompts
Run build for different credentials setups
=> [eas-cli] Fix support for non-interactive and skip-credentials-check

packages/eas-cli/src/credentials/ios/appstore/authenticate.ts
- silently terminate when the user does ctrl+c when logging in
=> terminate silently on apple-utils abort

packages/eas-cli/src/credentials/ios/actions/ConfigureProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/ProvisioningProfileUtils.ts, packages/eas-cli/src/credentials/ios/actions/SetupProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfile.ts, packages/eas-cli/src/credentials/ios/validators/validateProvisioningProfile.ts
- added a spinner for Expo API call to sync the profile
- Provisioning Profile -> provisioning profile (where appropriate)
- merged "Updating provisioning profile ..." logs together
=> typos and formatting

.github/workflows/release.yml, lerna.json, package.json, packages/eas-cli/README.md, packages/eas-cli/package.json, packages/eas-json/package.json
The build was failing, e.g. https://github.com/expo/eas-cli/runs/1518995963
Need to make sure all packages are built with `tsc` before running `oclif-dev pack`.
Push a version tag and check the results.
=> Fix the release action

packages/eas-cli/src/credentials/ios/appstore/distributionCertificate.ts
- fix #133 
- Download all certs and filter locally.
- Remove unused cert querying method.
- Make similar filtering change to another cert method (untested, but logical).
- #133 lays out an internal test plan that I've verified.
=> fetch all certificates, and filter locally

packages/eas-cli/src/build/create.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts
From Slack conversation with @brentvatne: 
> we should be more clear when the build is complete where users can go to install the app on their phone. currently we just show: “App: https://turtle-v2-artifacts.s3.amazonaws.com/etc-etc-etc”
In the case of internal distribution builds, I changed the message after the build completes. EAS CLI is now printing the URL to the build details page as well as a QR code.
=> [eas-cli] print better message when internal distribution build completes

packages/eas-cli/src/commands/release/view.ts, packages/eas-cli/src/config.ts
Implement `release:view`
Currently we list the last 1000 `updateGroup`s. Should this be truncated to last 10? If so, should we paginate?
=> [eas-cli] add release:view

packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/types.ts
**Merge only after https://github.com/expo/universe/pull/6597 is merged and pushed to prod.**
https://www.notion.so/expo/iOS-Internal-Distribution-doesn-t-work-when-the-app-is-not-published-e622b160521c412bafe98a940fd0ebda
https://github.com/expo/universe/pull/6597
To fix internal distribution for unpublished projects.
- I added two new fields to build metadata:
- `appName` - (`expo.name` in app.json/app.config.js)
- `appIdentifier`
- iOS builds: the bundle identifier (expo.ios.bundleIdentifier in app.json/app.config.js)
- Android builds: the application id (expo.android.package in app.json/app.config.js)
- **See also https://github.com/expo/universe/pull/6597**
Ran a build and saw that the metadata were stored in the db.
=> [eas-cli] add app name and app identifier to build metadata

packages/eas-cli/src/credentials/ios/appstore/keychain.ts
Fails with `Error: Expected darwin platform, got: linux` on Linux
Add check for platform
Auth to apple
=> [eas-cli] fix apple auth on linux

.github/workflows/size.yml, package.json
We should be intentional about adding dependencies and be aware of the effect they have on the download size of EAS CLI, because making it too large will make installing the tools too slow. The target time to install our tools is 30 seconds. To be able to achieve this, the full EAS CLI download should probably not be larger than ~40 MB it is at the moment.
Added a GitHub Action inspired by https://github.com/expo/eas-cli/issues/7.
Make sure the action succeeds.
=> Add GitHub Actions workflow measuring the difference in size of the CLI

packages/eas-cli/src/project/projectUtils.ts
For several of the eas-cli commands under development, it will be useful to translate the user supplied releaseName to a releaseId.
Add a method to translate a releaseName into a releaseId.
Tested in graphql playground
=> [eas-cli] add getReleaseByNameAsync

packages/eas-cli/src/build/constants.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts
A more pleasant ending to a successful build.
```
Platform: Android, Build details: https://expo.io/accounts/notbrent/builds/0bc60508-6e5d-4084-88fc-3a5db55dc241
Platform: iOS, Build details: https://expo.io/accounts/notbrent/builds/dc4c2578-3893-43b8-9804-adc8fba54e7a
Waiting for build to complete. You can press Ctrl+C to exit.
✔ All builds have finished
Open this link on your Android devices to install the app:
https://expo.io/accounts/notbrent/builds/0bc60508-6e5d-4084-88fc-3a5db55dc241
Open this link on your iOS devices to install the app:
https://expo.io/accounts/notbrent/builds/dc4c2578-3893-43b8-9804-adc8fba54e7a
```
```
Android build details: https://expo.io/accounts/notbrent/builds/0bc60508-6e5d-4084-88fc-3a5db55dc241
iOS build details: …
```
=> [eas-cli] Slightly easier to read output when build is completed

packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/commands/device/list.ts, packages/eas-cli/src/commands/device/view.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDeviceQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleTeamQuery.ts, packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/devices/utils/formatDevice.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/utils/formatFields.ts
This adds commands to view registered devices for an account.
Depends on https://github.com/expo/universe/pull/6614
=> [eas-cli] Add device:list and device:view commands

packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/commands/build/configure.ts
It's strange to get eas.json populated with ios and android build configuration when you request only one of the platforms.
Updated related configure code to work as expected for a single platform. Should have included tests but it looks like there wasn't any existing testing around this, so we should follow up on this later.
I tested the scenarios above
=> [eas-cli] Only configure eas.json for the requested platform

packages/eas-cli/package.json, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/submissions/utils/files.ts, packages/eas-cli/src/uploads.ts, yarn.lock
Requires https://github.com/expo/turtle-v2/pull/343/files and the new version of `@expo/eas-build-job` to be published
Support for private bucket uploads/downloads
Update code to new job schema
Pass s3 bucket key to the job instead of url
run build locally
=> [eas-cli] private bucket support for project archive

packages/eas-cli/__mocks__/@expo/config.ts, packages/eas-cli/src/__tests__/project-utils.ts, packages/eas-cli/src/build/android/UpdatesModule.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/UpdatesModule.ts, packages/eas-cli/src/commands/account/view.ts, packages/eas-cli/src/commands/release/create.ts, packages/eas-cli/src/commands/release/rename.ts, packages/eas-cli/src/credentials/__tests__/fixtures-constants.ts, packages/eas-cli/src/credentials/context.ts, packages/eas-cli/src/credentials/credentialsJson/update.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/credentials/manager/SelectAndroidApp.ts, packages/eas-cli/src/devices/__tests__/manager-test.ts, packages/eas-cli/src/devices/context.ts, packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/UserQuery.ts, packages/eas-cli/src/project/__tests__/project-utils.ts, packages/eas-cli/src/project/__tests__/projectUtils-test.ts, packages/eas-cli/src/project/projectUtils.ts, packages/eas-cli/src/user/Account.ts, packages/eas-cli/src/user/User.ts, packages/eas-cli/src/user/__tests__/User-test.ts, packages/eas-cli/src/user/__tests__/actions-test.ts, packages/eas-cli/src/user/__tests__/sessionStorage-test.ts, packages/eas-cli/src/user/actions.ts
This adds support for robot users, through `EXPO_TOKEN=<robot-user-token> eas ...`. 
We could wait for the outcome of the `Actor.displayName` discussion. That could replace the `getActorUserName` helper and make our usernames easier to use.
It's similar to [PR #2440](https://github.com/expo/expo-cli/pull/2440), but implemented in such way that it's heavily reliant on the `CurrentUserQuery` result. If we add properties, like `isExpoAdmin` to this query, they are propagated everywhere once you run `$ yarn generate-graphql-code`.
This has a lot of benefits, including easier to maintain and more type-related to the output of the API. But, relating it more the GraphQL API also has its downsides. For example, the `meActor.accounts` is typed in GraphQL as `accounts: [Account]` meaning:
- …
=> [eas-cli] Add support for Robot users

packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/ios/prepareJob.ts
With the robot integration we can't use `username` from the user, robots don't have one. Always use the "project owner" or "username of a normal user" instead, through `getProjectAccountName(Async)`
Replaced username with `getProjectAccountNameAsync` method.
Run a managed job with EAS.
=> [eas-cli] Use project account name in prepare managed job

packages/eas-cli/src/submissions/android/AndroidSubmitter.ts, packages/eas-cli/src/submissions/ios/IosSubmitter.ts, packages/eas-cli/src/submissions/utils/summary.ts
- Match the simpler UI used in the promo video. 
- make links usable
- remove unused app specific password
=> [submit] Simplify table logs

packages/eas-cli/src/build/utils/repository.ts
- most projects don't need to show logging for the tar zip as it's very quick, but for projects without the cocoapods gitignored, we should show the spinner. This adds a timeout to optimize for showing less logs. The feature is disabled in debug mode.
=> Show tar logging if it takes a while

packages/eas-cli/src/credentials/android/utils/keystore.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1607874915439400
calling `keytool` might fail with even if binary is in PATH
Treat those cases the same as if keytool was not installed.
Can't reproduce that on my system, but it should work
=> [eas-cli] Improve keytool detection

packages/eas-cli/src/submissions/utils/errors.ts
Fixes #115 
- Fixed the _"Redundant Binary Upload"_  error handling was missing in CLI
- Added error handling for (https://github.com/expo/turtle-v2/pull/341):
- Missing App Icon (`TMS-90022`, `ITMS-90704`)
- Invalid App Signature (`ITMS-90034`) - seems to happen when Distribution Cert, tied to app Provisioning Provile, is revoked
Tested manually:
=> [eas submit] Add missing iOS error messages

packages/eas-cli/src/credentials/android/actions/__tests__/UpdateKeystore-test.ts, packages/eas-cli/src/credentials/android/credentials.ts, packages/eas-cli/src/credentials/utils/promptForCredentials.ts
Prompts for auto generation are too complex:
```
Would you like to upload a Keystore or have us generate one for you?\nIf you don't know what this means, let us generate it! :) [Use arrow keys ...]
- Generate new keystore
- I want to upload my own file
```
Is now a confirm prompt
```
? Generate a new Android Keystore? (Y/n)
```
```
✔ Do you want to generate new credentials? … yes
✔ Generate a new Android Keystore? … no
In this mode, we won't be able to make sure that your credentials are valid.
Please double check that you're uploading valid files for your app otherwise you may encounter strange errors!
When building for IOS make sure you've created your App ID on the Apple Developer Portal, that your App ID
is in app.json as `bundleIdentifier`, and that the provisioning profile you …
```
=> Simplify the prompts for auto generation

packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/utils/git.ts, packages/eas-cli/tsconfig.json
Enforcing no implicit returns has been useful in catching errors in `www` and we seem to have an explicit is better than implicit philosophy in this repo already.
added tsconfig and fixed two violations.
yarn tsc
=> [expo-cli] set noImplicitReturns to true

packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/BuildQuery.ts, packages/eas-cli/src/graphql/queries/UserQuery.ts
**Merge only after https://github.com/expo/universe/pull/6702 is merged**
We want to print an error when there's another pending build for a given platform.
- I added printing an error (and exiting the build command) when we detect that the user has another pending build for a given platform.
- This check is skipped for Expo admins, and they're allowed to run as many builds as they want.
=> [eas-cli] eas build - print an error when there's another pending build

packages/eas-cli/package.json
We are receiving reports about `MODULE_NOT_FOUND` errors related to `invariant`. Somehow `@expo/plist@0.0.10` doesn't have this as listed dependencies, but the code still requires it. In `0.0.11`, `invariant` is fully removed and should work as expected.
Not sure why NPM would pick `0.0.10` over `0.0.11` when using the `^0.0.10` version. It could be related to the version being an early alpha version. I know that `0.1.0` -> `0.2.0` would be [considered a breaking change because there is no stable version yet](https://semver.org/#spec-item-4) and thus not updated to `0.2.0` when using `^0.1.0`. Could be similar to `0.0.1`.
> Edit, this also seems to be happening for Yarn.
Force-bumping this to `0.0.11` should fix the issue, see below how to repro, check and fix this manually.
**Repro the …
=> [eas-cli] Force update plist library to fix missing invariant

packages/eas-cli/package.json, packages/eas-cli/src/log.ts, yarn.lock
- format links optimally for iTerm and other CLIs that support complex links.
- Links can be disabled by toggling a couple different env variables https://github.com/jamestalmage/supports-hyperlinks/blob/master/index.js
=> format links

packages/eas-cli/package.json, packages/eas-cli/src/credentials/ios/appstore/resolveCredentials.ts, packages/eas-cli/src/submissions/ios/AppSpecificPasswordSource.ts, packages/eas-cli/src/submissions/ios/IosSubmitCommand.ts, yarn.lock
- Moved from https://github.com/expo/eas-cli/pull/176
- Wrap more optimally when chalk effects are in use.
- Also deduplicated dependencies.
=> use wrap-ansi instead of wordwrap

packages/eas-cli/src/commands/release/publish.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts, yarn.lock
This is the final of 4 PR's to add `eas release:publish`. 
It adds the command.
Ask for: `inputDir`, `releaseName`, `runtimeVersion`, and `updateMessage`.
yarn test
Also ran this in the alpha.
=> [eas-cli] add release:publish 4/4

packages/eas-cli/src/graphql/generated.ts
I cleaned up the credentials graphql types in www, this PR updates the autogenerated types
When we autogenerate graphql types in eas-cli, types like `[Foo]!` are automatically typed as `Maybe<Foo>[]`. This is inconvenient because you have to resolve `Maybe<Foo>` in the client, yet the server is always sending down `Foo[]` and never an array with a null value in it.
=> [eas-cli] cleanup pesky Maybe types

packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/user/Account.ts
- Cleaned up graphql types in www (https://github.com/expo/universe/pull/6773) to update everything to stricter types. For example, types like `Maybe<Array<Maybe<Foo>>>` get converted to `Array<Foo>` where possible.
- This PR updates the autogenerated schema
- Removed `@todos` that hack around `Maybe` types
=> [eas-cli] more gql type cleanup

packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleAppIdentifierMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDeviceMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDeviceRegistrationRequestMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDistributionCertificateMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleProvisioningProfileMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleTeamMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppBuildCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleAppIdentifierQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDeviceQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDistributionCertificateQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleProvisioningProfileQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleTeamQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppBuildCredentialsQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppCredentialsQuery.ts, packages/eas-cli/src/graphql/fragment.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/App.ts, packages/eas-cli/src/graphql/types/credentials/AppleAppIdentifier.ts, packages/eas-cli/src/graphql/types/credentials/AppleDevice.ts, packages/eas-cli/src/graphql/types/credentials/AppleDeviceRegistrationRequest.ts, packages/eas-cli/src/graphql/types/credentials/AppleDistributionCertificate.ts, packages/eas-cli/src/graphql/types/credentials/AppleProvisioningProfile.ts, packages/eas-cli/src/graphql/types/credentials/AppleTeam.ts, packages/eas-cli/src/graphql/types/credentials/IosAppBuildCredentials.ts, packages/eas-cli/src/graphql/types/credentials/IosAppCredentials.ts
- The graphql code generator won't parse AST strings unless it is in a `gql` tag or preceded by the `/* GraphQL*/ ` comment.
- This PR allows fragments types to be autogenerated so we can use them in the future
=> [eas-cli] generate fragment types

packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/ProjectQuery.ts
this pr makes sure that everything covered by the codegen tool is named
https://the-guild.dev/blog/graphql-codegen-best-practices
```
It's highly important to name your GraphQL operations, because otherwise it will be difficult for your GraphQL client to cache and manage it. It will also make it difficult for the codegen to create easy-to-use types, and it will fallback to Unnamed_Operation_.
```
=> [eas-cli] gql nits

packages/eas-cli/src/project/__tests__/projectUtils-test.ts, packages/eas-cli/src/submissions/ios/utils/__tests__/language-test.ts
There are some unmocked console.logs and console.warns in test output
```
PASS  src/submissions/ios/utils/__tests__/language-test.ts
● Console
console.log
undefined
at consoleLog (src/log.ts:28:11)
PASS  src/credentials/android/actions/__tests__/RemoveKeystore-test.ts
PASS  src/project/__tests__/projectUtils-test.ts
● Console
console.warn
An Expo user account is required to proceed.
32 |   _updateIsLastLineNewLine(args);
33 | 
> 34 |   console.warn(...args);
|           ^
35 | }
36 | 
37 | function consoleError(...args: any[]) {
at consoleWarn (src/log.ts:34:11)
at Function.warn (src/log.ts:66:3)
at ensureLoggedInAsync (src/user/actions.ts:30:9)
at getProjectAccountNameAsync (src/project/projectUtils.ts:31:16)
at Object.<anonymous> (src/project/__tests__/projectUtils-test.ts:141:5) …
```
=> [eas-cli] make test output cleaner

packages/eas-cli/.eslintrc.js, packages/eas-cli/src/commands/release/view.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleAppIdentifierMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDeviceMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDeviceRegistrationRequestMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDistributionCertificateMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleProvisioningProfileMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleTeamMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppBuildCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleAppIdentifierQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDeviceQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDistributionCertificateQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleProvisioningProfileQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleTeamQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppBuildCredentialsQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppCredentialsQuery.ts, packages/eas-cli/src/graphql/fragment.ts, packages/eas-cli/src/graphql/types/App.ts, packages/eas-cli/src/graphql/types/credentials/AppleAppIdentifier.ts, packages/eas-cli/src/graphql/types/credentials/AppleDevice.ts, packages/eas-cli/src/graphql/types/credentials/AppleDeviceRegistrationRequest.ts, packages/eas-cli/src/graphql/types/credentials/AppleDistributionCertificate.ts, packages/eas-cli/src/graphql/types/credentials/AppleProvisioningProfile.ts, packages/eas-cli/src/graphql/types/credentials/AppleTeam.ts, packages/eas-cli/src/graphql/types/credentials/IosAppBuildCredentials.ts, packages/eas-cli/src/graphql/types/credentials/IosAppCredentials.ts
Apply the graphql `template-strings` rule which perform a bunch of validations, most notably disallowing template literals in certain part of the AST string. More info here: https://github.com/apollographql/eslint-plugin-graphql
- I've also refactored the `Fragments` as discussed here: https://github.com/expo/eas-cli/pull/185#issuecomment-756765674
=> [eas-cli] 2/n apply template literals rule

packages/eas-cli/.eslintrc.js, packages/eas-cli/src/commands/release/list.ts, packages/eas-cli/src/commands/release/view.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleAppIdentifierMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDeviceMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDeviceRegistrationRequestMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDistributionCertificateMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleProvisioningProfileMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleTeamMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppBuildCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleAppIdentifierQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDeviceQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDistributionCertificateQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleProvisioningProfileQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleTeamQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppBuildCredentialsQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppCredentialsQuery.ts, packages/eas-cli/src/graphql/mutations/PublishMutation.ts, packages/eas-cli/src/graphql/queries/BuildQuery.ts, packages/eas-cli/src/project/projectUtils.ts
Require that we get the `id` field whenever possible in our graphql queries and mutations. I have mixed feelings about this rule because:
- it has a huge upside. Most graphql cachers will rely on the presence of `id` to figure whether to invalidate or add to the cache. I have personally experienced many painful bugs because of this 😭 
- downside: this rule doesn't look for `id` in referenced fragments, leading to a lot of redundancy. This is currently an unresolved bug: https://github.com/apollographql/eslint-plugin-graphql/issues/248
=> [eas-cli] 4/n apply required id field rule

packages/eas-cli/.eslintrc.js
Enforce our naming conventions. There aren't really any `.ts` changes here because I applied them all from the previous rules.  More info here: https://github.com/apollographql/eslint-plugin-graphql .
=> [eas-cli] 5/n apply caps name rule

packages/eas-cli/graphql-codegen.yml, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppQuery.ts, packages/eas-cli/src/graphql/generated.ts
This is mostly a proposal on using more accurate Graphql Types in our codebase. I only changed `AppQuery` and `AppFragment` for a concrete example. If everyone is happy with these changes, i'll propagate them everywhere else.
1. Graphql codegenerate can't autogenerate queries that use template literals in certain parts of the AST string. For example:
```
query($fullName: String!) {
app {
byFullName(fullName: $fullName) {
...${AppFragment.name} // <-------- Not OK
}
}
}
${AppFragment.definition}  // <-------- Seems to be OK
```
There are several workarounds, like using [graphql-tag-pluck ](https://github.com/ardatan/graphql-tools/tree/master/packages/graphql-tag-pluck) to resolve them. However, it just seemed simpler to change the `AppFragment` variable to have the same name as the graphql …
=> [eas-cli] use more accurrate graphql types

packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/PublishMutation.ts, packages/eas-cli/src/graphql/queries/BuildQuery.ts, packages/eas-cli/src/graphql/queries/ProjectQuery.ts, packages/eas-cli/src/graphql/queries/PublishQuery.ts
1. Use autogenerated query/mutation types instead of having to manually write it out
2. Return a more accurate Graphql type (ie) a `FooQueryResult` or `FooFragment` type instead of the entire `Foo` object defined by www. 
In the case of duplicate identifiers, I've renamed the graphql operations as needed.
=> [eas-cli] use autogen graphql types

packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppCredentialsQuery.ts, packages/eas-cli/src/credentials/ios/utils/printCredentialsBeta.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/App.ts, packages/eas-cli/src/graphql/types/credentials/IosAppBuildCredentials.ts, packages/eas-cli/src/graphql/types/credentials/IosAppCredentials.ts, packages/eas-cli/src/utils/date.ts
This is the start of an effort to move all credential api requests from apiv2 to graphql, and to bring the UX of the credentials manager closer to what we see in the website. This PR fetches all the initial credentials required to print out the user's credentials when they first run `eas credentials`. The excalidraw wireframes are [here](https://excalidraw.com/#json=5197280390938624,q3HFlStPaD1zjYI2WdG_FQ)
- We want the credentials manager to show information in the same way the website's UI does
- I'll be committing these incremental changes in `beta` files. It's a bit difficult to integrate the new API changes to the existing code because of caching issues. The current credentials manager maintains a cache of credentials from apiv2, and it'll be hard to keep the graphql and apiv2 caches …
=> [eas-cli] initial fetch for credentials manager

packages/eas-cli/src/build/build.ts
eas-cli does not properly detec `TURTLE_DEPRECATED_JOB_FORMAT` in error response
- check correct field in error
- fix message
run the same changes on old commit
=> [eas-cli] fix message for deprecation errors

packages/eas-cli/src/commands/credentials.ts, packages/eas-cli/src/credentials/CredentialsManager.ts, packages/eas-cli/src/credentials/__tests__/fixtures-context.ts, packages/eas-cli/src/credentials/android/AndroidCredentialsProvider.ts, packages/eas-cli/src/credentials/android/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/android/actions/__tests__/RemoveKeystore-test.ts, packages/eas-cli/src/credentials/android/actions/__tests__/SetupBuildCredentials-test.ts, packages/eas-cli/src/credentials/android/actions/__tests__/UpdateKeystore-test.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/SetupProvisioningProfile.ts, packages/eas-cli/src/credentials/manager/ManageAndroidApp.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts, packages/eas-cli/src/credentials/manager/SelectAndroidApp.ts, packages/eas-cli/src/credentials/manager/SelectPlatform.ts
Simplify credentials manager logic
- use only runActionAsync
- replace pushNextAction with similar logic in actions that need that
- CredentialsManager just runs `runAsync` (Left that class there to simplify mocking in tests)
- runActionAsync can return values
run build and few actions in credentials manager
=> simplify credentials manager

packages/eas-cli/package.json, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/credentials/credentialsJson/__tests__/read-test.ts, packages/eas-cli/src/credentials/credentialsJson/__tests__/update-test.ts, packages/eas-cli/src/credentials/credentialsJson/read.ts, packages/eas-cli/src/credentials/credentialsJson/update.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, yarn.lock
This is the second piece adding support for building multi-target iOS projects with EAS Build. Previous PR: https://github.com/expo/expo-cli/pull/3076
This PR adds support for building multi-target iOS projects via credentials.json. This means that if a user specifies the credentials for all native targets in credentials.json, they should be able to successfully build the binary.
Reference: https://www.notion.so/expo/Multi-Target-Support-V1-Credentials-json-8d1c1c934f644ba6b098e33b456ffad8
The last piece (EAS Build) is implemented in https://github.com/expo/turtle-v2/pull/384
- I updated the schema of credentials.json. It's now possible to specify either one credentials set (if the project has only one target) or a map of credentials where the key is the target name and the value is the …
=> [eas-cli] add support for building multi-target ios projects via credentials.json

packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
Previously we were relying on `expo export` to build the bundles published by `eas publish`. `expo export` turns out to do a lot of unrelated stuff with the assumption the developer is going to use the output for privately hosted static endpoints. The core elements of `expo export` were factored out and put into a new command `expo bundle` https://github.com/expo/expo-cli/pull/3074. 
`expo bundle` outputs the bundle in a new format. This PR updates `eas publish` to expect this new format.
Rewrote `collectAssets`.
Confirmed the `collectAssets` output test still passed after updating it to the new formate.
Made a test publish after building the bundle in the new format.
=> [eas-cli] rework expected bundle format for eas publish

packages/eas-cli/src/commands/release/publish.ts
I wanted to release a new version of eas-cli and noticed that the `release:publish` command is displayed in the README.
https://github.com/expo/eas-cli/commit/b27590f4f54e532049e365bb55a784f8cbfb8b83#diff-a252b5d7d93d02fa1b5f26d73bb4608c49feefb7c32c6d3b47b0e1d448e042bcR217
Set `ReleasePublish.hidden` to `true`. 
I'll run `yarn release` one more time.
=> [eas-cli] hide release:publish command

packages/eas-cli/src/credentials/ios/actions/new/DistributionCertificateUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/DistributionCertificateUtils-test.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/__snapshots__/DistributionCertificateUtils-test.ts.snap, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/__mocks__/AppleDistributionCertificateQuery.ts, packages/eas-cli/src/credentials/ios/appstore/CredentialsUtilsBeta.ts
Utility functions to select a distribution certificate
- the options are multiline now
- moved a lot of existing utility functions that operated on the old api to the 'new' directory for the new api
- beta files are files that are only used by the WIP credentials manager
=> [eas-cli] select dist certs

packages/eas-cli/src/prompts.ts
When prompts is called on ci it exits from the process with 0 exit code
The error does not need to be descriptive because all commands that might be run on CI should support `--non-interactive` flag, this change is only to ensure non-zero exit code.
- if stdin is not readable before prompts call, then throw an error.
- skip check if running in test `!global.test` (explained in a comment below)
Reproduced with `eas build -p andorid < /dev/null`
=> [eas-cli] return non-zero exit code if prompt is displayed on CI

packages/eas-cli/package.json, packages/eas-cli/src/build/android/UpdatesModule.ts, yarn.lock
- Merge https://github.com/expo/expo-cli/pull/3103
- Publish config-plugins
- Bump config-plugins in EAS CLI.
This PR fixes configuring expo-updates when the react native project is in a yarn/npm workspace.
- I made some changes in config-plugins (https://github.com/expo/expo-cli/pull/3103). Mainly, I added logic that removes incorrect paths to `create-ios-manifest.ios` / `expo-updates/scripts/create-manifest-android.gradle`.
- I made the logic for configuring expo-updates for Android similar to what we have for iOS. I moved the actual code that modifies the contents of `build.gradle` to config-plugins. EAS CLI is only responsible for overriding the file.
I ran `eas build:configure` in a monorepo. Both `build.gradle` and `project.pbxproj` had wrong paths to `create-ios-manifest.ios` / …
=> [eas-cli] improve monorepo support - fix configuring expo-updates

packages/eas-cli/src/prompts.ts
bug introduced in https://github.com/expo/eas-cli/commit/256a0e1f226eedb7654cf12940c6d5514d288824
It seems that `process.stdin.readableFlowing === null` was not correct, if the prompt is happening early enough it would be false. checking for tty seems to be more reliable.
run `eas build` (it shows prompt for platform
run `eas buil < /dev/null ` (it fails with error)
=> [eas-cli] check if tty is attached on prompt

packages/eas-cli/src/build/create.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/commands/build/list.ts
Support `canceled` build status
Add cases for canceled build status: 
- when displaying build info
- when waiting for a build to finish
- as value for status param in `build:list` command
Run `eas build` -> cancel builds on website -> `eas build:list` -> `eas build:list  --status=canceled` -> `eas build:view someid`
=> [eas-cli] support `canceled` build status

packages/eas-cli/src/build/android/UpdatesModule.ts, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/configure.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/ios/UpdatesModule.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/log.ts
When refactoring `expo-cli` in a similar manner to https://github.com/expo/eas-cli/pull/223, I noticed some places where `Log.log` was being passed as an argument which would cause the this binding to not be correct. To fix this, we could change the callsites to `Log.log.bind(Log)`, change the functions to arrow functions (doesn't work with static properties as far as I can tell), or just explicitly use `Log` internal to the class to reference the static type rather than `this`. I chose the latter.
Replace calls to `this` in `Log` to `Log`.
Also fix the casing of some imports (merge conflict from the last PR).
`yarn tsc`
=> Fix potential broken this binding when passing logger function

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/create.ts, packages/eas-cli/src/commands/build/cancel.ts, packages/eas-cli/src/commands/build/view.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/BuildQuery.ts
Cancel builds from cli
Add `eas build:cancel` command:
- takes build Id as an argument
- if an argument is not provided it's displing select prompt with a list of unfinished builds (or confirm prompt if it's only one build)
```
> eas build:cancel --help
cancel an unfinished build
USAGE
$ eas build:cancel [BUILD_ID]
```
Run builds and cancel them
=> [eas-cli] add build:cancel command

packages/eas-cli/src/commands/build/index.ts
Fixes #225 
Allowed no to be specified overriding the true wait default
Run `eas build -p all --no-wait` from an EAS enabled project:
```
❯ eas build -p all --no-wait
✔ Linked to project @...
✔ Uploaded to EAS 14s
[ snip ]
✔ Uploaded to EAS 6s
Android build details: https://expo.io/accounts/xxx
iOS build details: https://expo.io/accounts/xxx
```
=> [eas-cli] Allow wait to be set to false for eas build

packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/ios/prepareJob.ts
If you run `eas build` in the subdirectory of your react-native project, build is started correctly, but a relative path to eas.json is not correct
Do not rely on `process.cwd`
Run build from `ios` directory
=> [eas-cli] fix running builds from subdirectory

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/branch/create.ts, packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/commands/branch/rename.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/PublishMutation.ts, packages/eas-cli/src/project/projectUtils.ts
We are renaming `release` to `branch`.
Just landed the server side PR: https://github.com/expo/universe/pull/6904
search and replace.
note: there are still `releaseChannel` etc. as it is a separate concept from EAS release->branch.
grep'd and 🤞
=> [eas-cli] rename EAS release to branch

packages/eas-cli/src/utils/git.ts
Remove trailing `\n` for default branch name.
Checked it created a branch without a trailing whitespace.
=> [eas-cli] remove trailing whitespace from default branch name

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/credentials/ios/actions/new/DistributionCertificateUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/ProvisioningProfileUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/RemoveDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/RemoveProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/__snapshots__/DistributionCertificateUtils-test.ts.snap, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDistributionCertificateMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleProvisioningProfileMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDistributionCertificateQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/__mocks__/AppleDistributionCertificateQuery.ts, packages/eas-cli/src/credentials/ios/appstore/CredentialsUtilsBeta.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/App.ts, packages/eas-cli/src/graphql/types/credentials/AppleDistributionCertificate.ts, packages/eas-cli/src/graphql/types/credentials/AppleProvisioningProfile.ts
This is a basic implementation of RemoveDistributionCertificate with the new graphql api. This version does NOT have caching implemented yet.  
Core changes:
- basic implementation of RemoveDistCert, RemoveSpecificDistCert, RemoveSpecificProvisioningProfile
- Added build dependencies to `AppleDistributionCertificateFragment`. When we fetch a dist cert, we usually need to know the apps that depend on it (ie) UX purposes like telling developer that `this dist cert is used by apps x,y,z`, or functional purposes like removing the provisioning profiles that depend on the dist cert. 
- UX changes to select dist cert
=> [eas-cli] basic RemoveDistCert (and RemoveProvisioningProfile)

packages/eas-cli/package.json, packages/eas-cli/src/build/android/UpdatesModule.ts, packages/eas-cli/src/build/ios/UpdatesModule.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/bundleIdentifer.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/project/projectUtils.ts, packages/eas-json/package.json, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/__tests__/EasJsonReader-test.ts, packages/eas-json/src/index.ts, yarn.lock
Another part of https://linear.app/expo/issue/ENG-27/buildconfiguration-option-for-ios-builds
See also https://github.com/expo/turtle-v2/pull/412
We want to allow users to override the build configuration (release/debug) for a particular build scheme.
- I updated `@expo/config-plugins` and made appropriate changes in EAS CLI.
- I added a new config option for generic iOS build profiles - `schemeBuildConfiguration` (`Release`/`Debug`). That field is optional. If it's not passed, then fastlane proceeds with its default behavior.
- I added a new config option for managed iOS build profiles - `buildType` (`release` / `development-client`). It's not used yet by EAS Build workers.
I ran three generic builds:
- with `schemeBuildConfiguration` set to `Release` - the value was successfully …
=> [eas-cli][eas-json] add schemeBuildConfiguration to eas.json

packages/eas-cli/package.json, packages/eas-cli/src/build/ios/build.ts, yarn.lock
I just published `@expo/config-plugins`. The new version includes the fix for detecting application target (https://github.com/expo/expo-cli/commit/a5e81c42b9ec36209813ec00695e91b0c3b8132c)
I bumped `@expo/config-plugins` to `1.0.19-alpha.0`.
Tests are still passing.
=> [eas-cli] bump @expo/config-plugins to 1.0.19-alpha.0

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-json/package.json, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/index.ts, yarn.lock
We want to enable users to build simulator builds.
The server-side was implemented in https://github.com/expo/turtle-v2/pull/417
- I added a new `distribution` type for iOS builds - `simulator`
- Credentials are not required for `simulator`.
Tested by building both managed and generic projects with `distribution` set to `simulator` (and also set to `store`).
=> add support for ios simulator builds

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/branch/create.ts, packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/commands/branch/rename.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/PublishMutation.ts, packages/eas-cli/src/project/projectUtils.ts
Following @fson observation about excessively verbose attribute names, we refactored a bunch of the graphQL methods server side.
This PR brings the eas-cli up to speed.
renamed and ran `yarn generate-graphql-code`
tested that all of the `eas branch:*` and `eas channel:create` commands work.
=> [eas-cli] rename updateGroup, updateMessage, branchName, channelName

packages/eas-cli/package.json
https://forums.expo.io/t/eas-build-validationerror-android-and-ios/49117
I'm not sure 100% if the use of `^` was the issue here, but it seems to be most likely.
=> [eas-cli] use fixed version of @expo/eas-json

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/__tests__/credentials-test.ts, packages/eas-cli/src/build/android/applicationId.ts, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/constants.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/create.ts, packages/eas-cli/src/build/credentials.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/bundleIdentifer.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/commands/build/cancel.ts, packages/eas-cli/src/credentials/android/AndroidCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/UpdateCredentialsJson.ts, packages/eas-cli/src/project/projectUtils.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts, packages/eas-json/package.json, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/EasJsonSchema.ts, yarn.lock
To upgrade `@expo/eas-build-job` to the latest version. There were a lot of changes there, related to the changed eslint configuration.
- I upgraded `@expo/eas-build-job` from `0.2.12` to `0.2.13`.
- I made all necessary changes to the codebase.
Tests are still passing.
=> upgrade @expo/eas-build-job 0.2.12 -> 0.2.13

packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
Currently in order to publish we have to go through a 2 step process:
1. manually create the bundles with `expo-cli export --experimental-bundle --force`.
2. publish with `eas branch:publish`
The commands are seperate so that a developer can select their preferred bundler. However, we also want the `publish` command to be a short and simple as possible. This PR makes usage of `expo-cli` the default behavior: `eas branch:publish` will automatically check to see if `expo-cli` is installed and then run step (1). 
We use the same expo-cli verison as yarn.
If expo-cli is not installed, the option to install it will be offered via the wrapper in `node_modules/.bin/cli.js`.
If the developer wishes to avoid this behavior and handle bundling on their own, they can set the new `--skip-bundler` …
=> [eas-cli] add default bundler for branch:publish

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
closes https://linear.app/expo/issue/ENG-219/rename-filehash-to-filesha256
`fileHash` has been renamed to the more descriptive `fileSHA256`
search replace
made a test publish.
=> [eas-cli] rename fileHash to fileSHA256

packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/commands/branch/rename.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/channel/create.ts
Logging JS objects/arrays will return a format provided by `util`, which isn't JSON. This fixes that for:
- `branch:publish`
- `branch:rename`
- `branch:view`
- `channel:create`
- Added `JSON.stringify()` around the content
You can run the command, with `--json` flag, and parse it with `jq`. E.g.:
- `$ eas channel:create <name> --json | jq '.'`
This should not throw "invalid token" errors.
=> [eas-cli] Fix json output for branch and channel commands

packages/eas-cli/src/build/build.ts
got instance is creating error with `expoApiV2ErrorCode` field, so we don't need to use raw response to parse that
use expoApiV2ErrorCode
I didn't update CHANGELOG because that change does not affect anything userfacing
run build where www returned TURTLE_DEPRECATED_JOB_FORMAT
=> [eas-cli] use error.expoApiV2ErrorCode to check error code

CHANGELOG.md, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/utils/repository.ts
We are not committing untracked files before build in `ensureGitStatusIsCleanAsync`
add `git add -A`
this change does not affect commits that are created as part of the build or as part of the configuration
run build when there are untracked files in repo
=> [eas-cli] commit all files before build

CHANGELOG.md, packages/eas-cli/src/build/utils/repository.ts
https://linear.app/expo/issue/ENG-370/extend-git-warning-on-running-eas-build-to-also-check-for-untracked
check for untracked files
`touch file` -> `eas build`
=> [eas-cli] detect untracked files when checking for changes in repository

CHANGELOG.md, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/utils/provisioningProfile.ts
https://linear.app/expo/issue/ENG-285/internal-distribution-support-for-self-managed-credentials
> A user has expressed interest in being able to have access to shareable app download links available with internal distribution without using automatically managed credentials.
This was pretty straightforward. The only "hack" is that I disabled checking for remote credentials in the case where credentials.json exists and it's an internal distribution build.
I ran an internal distribution build with credentials defined in credentials.json and it worked fine.
=> enable internal distribution support for self-managed credentials

CHANGELOG.md, packages/eas-cli/src/submissions/utils/files.ts
If ipa/apk/aab is in subdir inside tar.gz file, submit can't detect it
https://linear.app/expo/issue/ENG-325/handle-eas-build-tar-artifacts
fix wildcard
ios build with artifactPath: './ios/build/**/*' + eas submit
=> [eas-cli] fix submit with tar.gz files

CHANGELOG.md, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/utils/repository.ts, packages/eas-cli/src/utils/files.ts, packages/eas-cli/src/utils/progress.ts
https://linear.app/expo/issue/ENG-399/log-the-size-of-the-archived-project-when-uploading
- add size to log after project archive is created
- add size to upload progress bar
- fix unhandled error in the tarball creation
- removed `--local` flag (it's unrelated to this PR, I just noticed that this flag is ignored either way)
- values larger than 100 are displayed as integer and smaller ones with one decimal point (e.g 700 MB , 55.3 MB)
=> [eas-cli] display size of the archive

packages/eas-cli/src/commands/branch/create.ts, packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/branch/rename.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/build/cancel.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/commands/channel/edit.ts, packages/eas-cli/src/commands/channel/list.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/graphql/generated.ts
Using generated graphql code types for commands leaves less room for error.
Used pregenerated graphql types where appropriate.
tested commands still work in a test project.
=> [eas-cli] use generated graphql types

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/android/UpdatesModule.ts, packages/eas-cli/src/build/ios/UpdatesModule.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/utils/git.ts, yarn.lock
https://linear.app/expo/issue/ENG-326/add-build-profile-to-build-metadata
See also https://github.com/expo/universe/pull/7080
I made EAS CLI send more build metadata to www:
- release channel
- build profile
- git commit hash
I ran a build and used graphql to fetch the metadata.
=> [ENG-326] send more build metadata: release channel, build profile, git commit hash

CHANGELOG.md, packages/eas-cli/src/submissions/BaseSubmitter.ts, packages/eas-cli/src/submissions/android/AndroidSubmitter.ts, packages/eas-cli/src/submissions/archiveSource/ArchiveFileSource.ts, packages/eas-cli/src/submissions/archiveSource/index.ts, packages/eas-cli/src/submissions/ios/IosSubmitter.ts, packages/eas-cli/src/submissions/utils/summary.ts, packages/eas-cli/src/utils/formatFields.ts
Addresses internal feedback, a little improves user experience.
- After successful iOS submission, a message with app store link is displayed along with information about processing by Apple. For Android, unfortunately, there's no easy way to achieve link to Google Play Console.
- Changed Submission Summary table - this was done before #157 (had to rebase due to duplication of my changes)
- Removed `App Specific Password` row - it was useless (always displayed `[hidden]`)
- Reordered table values for  both platforms (see below)
- Instead of displaying `Archive URL`, the real user choice is now displayed (path / build id). This needed modification of `ArchiveFileSource.ts` to return also real user choice.
> Maybe, in case of uploading local file, an archive URL should also be displayed - …
=> [eas submit] UX improvements

CHANGELOG.md, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/__tests__/EasJsonReader-test.ts
https://linear.app/expo/issue/ENG-406/ejected-project-with-simulator-distribution-type-does-debug-build-by
- I set the default value for `schemeBuildConfiguration` to `Release`.
- I introduced a new value for `schemeBuildConfiguration`: `Auto`. It means that the build configuration will be set to the value defined in the chosen scheme.
I followed the repro steps from https://linear.app/expo/issue/ENG-406/ejected-project-with-simulator-distribution-type-does-debug-build-by:
- I inited a managed project with `expo init`.
- I ran `expo eject`.
- I ran `eas build:configure` and then modified eas.json to build a simulator build (`"distribution": "simulator"`).
- I ran `eas build`.
- I downloaded the archive, ran the app in the simulator, and I observed it was built for release.
=> iOS builds: default to build configuration 'Release'

CHANGELOG.md, packages/eas-cli/src/build/ios/configure.ts, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/EasJsonSchema.ts
https://linear.app/expo/issue/ENG-357/support-for-schemes-with-different-bundle-identifiers-in-generic-apps
- if `experimental.disableBundleIdValidation` is set then skip bundleIdedentifier validation or configuration
- user needs to specify a scheme explicitly
- this solution is not enough to support multiple slugs if you use expo-updates, because there is only one file that contains URL to project, build will work but configure will override project URL with new slug
build and build configure on https://github.com/brentvatne/myapp
=> [eas-json] add experimental.disableBundleIdValidation flag

packages/eas-cli/package.json, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/types.ts, packages/eas-json/package.json, yarn.lock
Part 1 of https://linear.app/expo/issue/ENG-392/expose-system-environment-variables-with-context-about-the-build
`@expo/eas-build-job` exports the metadata type now.
I used the `Metadata` type from `@expo/eas-build-job` instead of the one defined in eas-cli.
Tests are still passing.
=> [ENG-392][eas-cli] use Metadata type from @expo/eas-build-job

CHANGELOG.md, packages/eas-cli/src/commands/device/list.ts
https://linear.app/expo/issue/ENG-445/eas-devicelist-says-i-am-on-team-null
use id instead of name if not available
`eas device:list`
=> [eas-cli] handle unknown team name in device list

CHANGELOG.md, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/new/AppleTeamUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/errors.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts
https://linear.app/expo/issue/ENG-444/support-internal-distribution-in-non-interactive-builds
We want to support running internal distribution builds in non-interactive mode.
- I removed the requirement of running `eas build` for internal distribution in interactive mode.
- I added a new branch in the `SetupAdhocProvisioningProfile` action. When running in non-interactive mode there is only a simple check for the provisioning profile existence. If the credentials are not set up this action throws an error saying to re-run the command in interactive mode.
- I added a similar branch in the `SetupDistributionCertificate` action. There's a check for the existence of the cert. If it doesn't exist, then an error is thrown.
- Unit tests are still passing.
- I ran `eas build -p ios` (for a …
=> [ENG-444] support internal distribution in non-interactive builds

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/create.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/commands/build/configure.ts, packages/eas-cli/src/log.ts, packages/eas-cli/src/submissions/ios/IosSubmitter.ts, packages/eas-json/package.json, yarn.lock
We want to provide users with meaningful error messages when their builds fail.
I added printing the common error messages (if detected). The list of the errors (with messages and FYI URLs) is defined in `@expo/eas-build-job`.
=> print common error messages when builds fail

CHANGELOG.md, packages/eas-cli/src/submissions/archiveSource/ArchiveFileSource.ts
Fixes ENG-509. When running `eas submit -p ios` and selected local archive path, the prompt asked for `.aab` file instead of `.ipa`.
Modified prompt messages to be platform-dependant.
Tested by running command locally for both platforms.
=> [ENG-509][submit] Fix local archive prompt

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-json/package.json, packages/eas-json/src/EasJsonSchema.ts, yarn.lock
https://linear.app/expo/issue/ENG-438/play-nicely-with-existing-fastlane-installations
I added a new config option for iOS builds - `bundler`. It allows for specifying the https://bundler.io/ version
Tested by building a project with `Gemfile` and `Gemfile.lock`. I specified the `bundler` version in eas.json and it was successfully installed.
=> [ENG-438] allow for installing custom bundler version

packages/eas-cli/src/build/android/applicationId.ts, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/configure.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/bundleIdentifer.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/build/cancel.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/build/list.ts, packages/eas-cli/src/commands/build/view.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/commands/channel/edit.ts, packages/eas-cli/src/commands/channel/list.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/commands/device/list.ts, packages/eas-cli/src/commands/device/view.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/credentials/ios/actions/UpdateCredentialsJson.ts, packages/eas-cli/src/devices/context.ts, packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/project/__tests__/projectUtils-test.ts, packages/eas-cli/src/project/projectUtils.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts
We call `getConfig` multiple times in functions from `projectUtils.ts`.
I made those functions accept an object of ExpoConfig type.
- `yarn build`
- `yarn test`
=> refactor project utils

CHANGELOG.md, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/prepareJob.ts
If the name does not contain any alphanumeric characters sanitized version is empty string and can't be used as target name
verify before and after sanitization whether `exp.name` is empty
run build with invalid name
=> [eas-cli] verify that "name" in app.sjon can be used as iOS target name

CHANGELOG.md, packages/eas-json/src/EasJsonReader.ts
Detecting deps cycle does not work
`delete buildProfile.extends` was removing `extends` keyword on first read fo a profile and by doing that it also removed cycle
```
“override”: {
“workflow”: “generic”,
“extends”: “override”,
```
`eas build`
=> [eas-json] Detect dependency cycle for build profiles

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/constants.ts, packages/eas-cli/src/build/credentials.ts, packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/build/list.ts, packages/eas-cli/src/commands/build/view.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/BuildQuery.ts, packages/eas-cli/src/graphql/types/Build.ts
We want to stop using REST endpoints in EAS CLI. This PR is the first part of the effort.
It makes `eas build:list` and `eas build:view` use GraphQL instead.
This was rather straightforward. I temporarily introduced a new function for formatting builds - `formatGraphQLBuild` - it will later replace the `formatBuild` function when we make build creation work via GraphQL.
I ran `eas build:list` and `eas build:view` for a project with existing builds and for a one without any builds.
=> make build:view and build:list use GraphQL instead of REST endpoints 

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/branch/delete.ts, packages/eas-cli/src/commands/branch/rename.ts, packages/eas-cli/src/commands/secrets/create.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/AppMutation.ts, packages/eas-cli/src/project/ensureProjectExists.ts, packages/eas-cli/src/project/projectUtils.ts
Another part of the refactor to stop using REST endpoints in EAS CLI.
This PR makes EAS CLI use GraphQL to create the app record if it does not exist yet.
I used the mutation added in https://github.com/expo/universe/pull/7218
- `expo init newproject`
- `eas build:configure`
- `eas build` was able to create the app record in the db 🎉
=> use graphql to create unpublished app

packages/eas-cli/src/credentials/__tests__/fixtures-appstore.ts, packages/eas-cli/src/credentials/__tests__/fixtures-new-ios.ts, packages/eas-cli/src/credentials/ios/actions/new/CreateProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/CreateProvisioningProfile-test.ts
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to create a provisioning profile using the new Graphql Api. This will eventually replace the old `CreateProvisioningProfile` here:  https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/ios/actions/CreateProvisioningProfile.ts
=> [eas-cli] create provisioning profile using graphql api

packages/eas-cli/src/credentials/ios/actions/new/SetupAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupDistributionCertificate.ts
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to setup a dist cert using the new Graphql Api in a generic way -- it is no longer constrained to just Adhoc apps. 
i manually tested this
=> [eas-cli] make dist cert setup generic with graphql api

CHANGELOG.md, packages/eas-cli/src/build/utils/formatBuild.ts
I need to see distribution and release channels in `eas build:list` and `eas build:view` helping me to differentiate production build with staging build.
Helpful for some internal CI doing different things based of this flags.
- Updated formatBuild.ts used by `build:list` and `build:view.` by using `build.metadata` informations.
- Fallback to "unknown" if metadata not specified.
=> Add distribution/channel informations in build:view/list

packages/eas-cli/src/commands/branch/delete.ts, packages/eas-cli/src/commands/secrets/delete.ts
"irreversable" is correctly spelled "irreversible"
=> [eas-cli] fix "irreversible" typo

packages/eas-cli/src/commands/channel/edit.ts, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/commands/channel/view.ts
Create a command to manage rollout on a channel.
closes #684
closes #685
closes #686
There are three possible branches:
1. if there is no active rollout, a new one is started based on the `branch` and `percent` specified by the user.
2. if there is an active rollout
a. user can modify it by changing the percent
b. user can end it by setting the --end flag and specifying a branch to consolidate to.
~~There is a bit of of confusing nuance. In a rollout a user is converted to a number in the unit interval and sent to the new Branch if they are less than the rollout percent, old branch otherwis.~~
~~If we use a strict inequality then we get `[0,rolloutPercent)` a weak inequality, `[0,rolloutPercent]`.~~
~~When the rollout percent is `0`, then the strict inequality sends 0 to the new branch …
=> [eas-cli] add command `eas channel:rollout`

CHANGELOG.md, packages/eas-cli/src/commands/secrets/create.ts
Creating a secret from the prompt flow was broken because of a missing `!` in the validation code.
`easd secrets:create` without args and it should now accept valid names.
=> [eas-cli] fix secret name validation when prompted

packages/eas-cli/src/commands/secrets/create.ts, packages/eas-cli/src/commands/secrets/delete.ts
`secrets:list` is already visible in the help output.
- I unhide the `secrets:create` and `secrets:delete` commands.
- I updated the `secrets:delete` description (removed the first empty line) so it's visible in the `eas secrets --help output`.
Before
After
=> unhide secrets:create and secrets:delete

CHANGELOG.md, packages/eas-cli/src/commands/secrets/create.ts, packages/eas-cli/src/commands/secrets/list.ts
@brentvatne had really good feedback stating that the CLI command should take flags rather than positional args for better UX.
Also Closes ENG-758
- used the flags feature in oclif for user input
- renamed target to scope since that is simpler to understand
- reordered secrets:list table columns to show ID before the timestamp
=> [eas-cli] use flags for secrets:create and rename target to scope

packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/ios/actions/new/ConfigureProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/ConfigureProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/errors.ts
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to create a provisioning profile using the new Graphql Api. This will eventually replace the old `ConfigureProvisioningProfile` here:  https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/ios/actions/ConfigureProvisioningProfile.ts
- Throw a specialized error if provisioning profile on Expo servers isn't found on Apple Developer portal. We can recover from this particular error in `SetupProvisioningProfile` later.
=> [eas-cli] configure provisioning profile using new api

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/graphql.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/graphql.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/graphql.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/BuildMutation.ts
https://github.com/expo/universe/pull/7247 added graphql mutations for creating builds.
This PR uses those instead of the REST endpoints.
I replaced the REST endpoint calls with graphql mutation calls.
I ran `eas build` for both platforms for two projects: managed and generic.
=> eas build - use GraphQL instead of REST endpoints

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/constants.ts, packages/eas-cli/src/build/create.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/commands/build/cancel.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/Build.ts
This PR replaces the remaining REST endpoint calls with GraphQL counterparts.
I replaced the calls for querying builds.
- I ran `eas build` a couple of times and everything seemed to be working fine.
- I also checked that these changes work fine when the user has pending builds and EAS CLI prints the details for them.
=> eas build - use GraphQL instead of REST endpoints for build queries

packages/eas-cli/graphql.schema.json, packages/eas-cli/package.json, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/UploadSessionMutation.ts, packages/eas-cli/src/project/publish.ts, packages/eas-cli/src/submissions/archiveSource/__tests__/ArchiveFileSource-test.ts, packages/eas-cli/src/submissions/utils/files.ts, packages/eas-cli/src/uploads.ts, yarn.lock
https://github.com/expo/universe/pull/7279 adds GraphQL mutation for generating upload sessions.
I replaced the REST API call with the GraphQL mutation call.
I ran `eas build` and I noticed the project archive got uploaded to S3.
=> use graphql for generating upload sessions

CHANGELOG.md, packages/eas-cli/src/build/create.ts, packages/eas-cli/src/graphql/queries/BuildQuery.ts
This fixes an issue that I introduced in https://github.com/expo/eas-cli/commit/279dfd00c8f779d3de5db91f1be881f08119aa42
Because of the default graphql cache policy the build status never gets updated when running `eas build`.
I set the cache policy to `network-only` for the `BuildQuery.byIdAsync` query
I ran a build and observed the build status transitions.
=> don't use graphql cache for polling builds

CHANGELOG.md, packages/eas-cli/src/commands/secrets/delete.ts, packages/eas-cli/src/commands/secrets/list.ts, packages/eas-cli/src/graphql/queries/EnvironmentSecretsQuery.ts
To improve the UX of deleting an environment secret via CLI (which previously involved 2 commands and a copy/paste), we want to allow the user to pick from a list.
- pulled code for getting all secrets for a project and account into a centralized place
- made `delete [ID]` optional
- if ID isn't specified, prompt the user with a list of all of their secrets for the current app and account 
`easd secrets:delete` in an Expo project directory:
=> [eas-cli] use autocomplete list for secrets:delete

packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/ios/actions/new/CreateProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/__mocks__/ConfigureProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/__mocks__/CreateProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/__mocks__/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/CreateProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/SetupProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/validators/validateProvisioningProfile.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/credentials/AppleProvisioningProfile.ts, packages/eas-cli/src/graphql/types/credentials/IosAppBuildCredentials.ts
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to create a provisioning profile using the new Graphql Api. This will eventually replace the old `SetupProvisioningProfile` here:  https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/ios/actions/SetupProvisioningProfile.ts
Flow works the following way now:
- check to see if user has valid build credentials
- continue if build credentials aren't fully configured
- if there is something wrong with current profile, try to fix it
- else just create a new profile
=> [eas-cli] setupProvisioningProfile using graphql

CHANGELOG.md, packages/eas-cli/src/submissions/utils/errors.ts
More errors are now handled by server-side submission service, we need to reflect them in eas-cli.
Added support for the following error messages:
- When user provides a `tar.gz` archive which is corrupt.
- When provided `tar.gz` archive doesn't contain any `(apk|aab|ipa)` file, depending on platform (e.g. iOS accepts only ipa). 
- When user provides incorrect Apple ID or App-specific password.
N/A
=> [eas submit] Added new common error messages

CHANGELOG.md, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/commands/build/index.ts
Fixes https://linear.app/expo/issue/ENG-835/regression-in-eas-build-configuration-around-bundleidentifier
- `ensureProjectConfiguredAsync` can modify app.json
- We need to re-read the config afterwards.
Followed the repo steps in https://linear.app/expo/issue/ENG-835/regression-in-eas-build-configuration-around-bundleidentifier
=> fix first ios build for a project without ios.bundleIdentifier in app.json

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/webhook/create.ts, packages/eas-cli/src/commands/webhook/delete.ts, packages/eas-cli/src/commands/webhook/list.ts, packages/eas-cli/src/commands/webhook/update.ts, packages/eas-cli/src/commands/webhook/view.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/WebhookMutation.ts, packages/eas-cli/src/graphql/queries/WebhookQuery.ts, packages/eas-cli/src/graphql/types/Webhook.ts, packages/eas-cli/src/webhooks/formatWebhook.ts, packages/eas-cli/src/webhooks/input.ts
https://github.com/expo/universe/pull/7305 added infra for webhooks management.
This PR adds a bunch of new commands for webhooks management: `webhook:create`, `webhook:view`, `webhook:list`, `webhook:update`, `webhook:delete`.
- https://github.com/expo/eas-cli/pull/314/commits/93836ad71fba3064e32c292c4bd70e350d653b30 adds `webhook:create`.
- https://github.com/expo/eas-cli/pull/314/commits/af003b1e5de64caa8667610d13434b3d8843cf1a adds `webhook:list`.
- https://github.com/expo/eas-cli/pull/314/commits/482bf46c8852957030f475420145609007d2b493 adds `webhook:view`.
- https://github.com/expo/eas-cli/pull/314/commits/460d9777797c592fbb9594c7b65cbf9ee5b7381a adds `webhook:update`.
- https://github.com/expo/eas-cli/pull/314/commits/700623a34d6ef5c384d0c32af1aef91318e3f676 adds `webhook:delete`
- …
=> add commands for managing webhooks

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/branch/delete.ts, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/credentials/ios/actions/CreateDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/UpdateDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/CreateDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/RemoveDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/__mocks__/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/SetupProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/utils/printCredentialsBeta.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/credentials/AppleProvisioningProfile.ts
This is the first part of adding support for internal distribution with Apple Enterprise Teams. This PR refactors some of the new credentials actions so they are more developer-friendly.
- https://github.com/expo/eas-cli/pull/321/commits/d942929a65e8cd1241e36173c5e458ed54049484 makes `SetupAdhocProvisioningProfile.runAsync` return iOS app build credentials. They used to be accessed via a getter.
- https://github.com/expo/eas-cli/pull/321/commits/fc367beeeb5bc2d7201bdbf8fc111e0f9eacbfe7 makes `SetupDistributionCertificate.runAsync` return iOS app build credentials. They also used to be accessed via a getter.
- https://github.com/expo/eas-cli/pull/321/commits/a4f41705cf4af178503995cad4f8c3832696e7ea removes the `unifyCredentialsFormatAsync` method as it's no longer needed because both …
=> refactor credentials actions

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/channel/list.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/graphql/generated.ts
Standardize and clean up formatting of channel/branch list/view display of their associated `updates`.
* Consolidated representation of update to three columns: `UPDATE_COLUMNS = ['update description', 'update runtime version', 'update group ID'];`
* Used `formatUpdate` to make a compact description in all 4 commands.
Chose to have a separate column for 
1. `update runtime version` to highlight it to the user and avoid confusion.  
2. `update group ID` due to its importance for further investigation with `eas update:view <ID>`
* fixed graphQL calls to correct `username` and other misc typos.
=> [eas-cli] clean up formatting of list/view commands

package.json, packages/eas-cli/package.json, packages/eas-json/package.json
When I'm working on EAS CLI and I need to make some changes in `@expo/eas-json`, I have to run `yarn build --watch` in both `packages/eas-cli` and `packages/eas-json` directories. This PR allows me to type fewer commands to achieve the same.
I added the `start` script in the root package.json. It runs the `watch` scripts in all workspaces, in parallel. 
I also added the `watch` scripts in all workspaces (`tsc --watch`).
I ran `yarn start` and noticed that it executed `tsc --watch` for both packages in parallel.
=> add start script

packages/eas-cli/src/commands/branch/publish.ts
Change publish syntax from:
`eas branch:publish --branch [name]`
to
`eas branch:publish [name]`
to match the syntax in the other commands.
tested a publish.
=> [eas-cli] make branch name a positional instead of a named arg

packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/channel/list.ts
A branch with no updates throws an error during `eas branch:list`
Also `eas channel:list` does not display an informative message when the update is missing.
switched to optional chaining and nullish coalescing.
tested on sample repo:
=> [eas-cli] handle branch with no updates gracefully

CHANGELOG.md, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/create.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/local.ts, packages/eas-cli/src/commands/build/index.ts
Support for local builds
- run `eas-build-local`(this name might not be final version) executable and pass job object to stdin
- `eas-build-local` path is resolved by
- checking EAS_LOCAL_BUILD_PLUGIN_PATH env (for development)
- using node `require.resolve()` (binnaries installed globally via yarn often are not in PATH)
- looking for binary in PATH
run builds
=> [eas-cli] Support for local builds

packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/channel/list.ts, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/graphql/generated.ts
Currently we only display a single branch for each channel. This PR updates the command to display multiple branches when a rollout is present:
We iterate of the channels and use the same function to display rollouts as is used in `eas channel:view`
Tested on sample repo.
This PR replaces this in progress PR: https://github.com/expo/eas-cli/pull/304
=> [eas-cli] update channel:list to handle rollouts

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/update/delete.ts, packages/eas-cli/src/graphql/generated.ts
Add update:delete
Since this is a dangerous operation that a user should avoid unless in situations like accidental secret publication an extensive warning message is included.
Note the default is to abort.
Tested on sample repo.
#Note 
This replaces PR https://github.com/expo/eas-cli/pull/261 which was targeted at deleting a single update. However after discussion we decided that this would lead to confusing errors and thus we should only expose the update *group* to developers.
=> [eas-cli] add update:delete command

CHANGELOG.md, packages/eas-cli/src/credentials/ios/appstore/__tests__/ensureAppExists-test.ts, packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts
I've noticed that if the provisioning profile had been generated during a previous `eas build` run, it's invalidated at the start of the consecutive build. I've figured out that the reason is the bundle id capabilities synchronization. We run it every time, even if there are no changes to be made. Updating bundle id capabilities somehow invalidates the associated provisioning profile.
Instead of updating capabilities every time, I made a change so they're updated only when needed.
Added unit tests.
=> don't update capabilities if there's nothing to change

packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/__tests__/IosCredentialsProvider-test.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/new/BuildCredentialsUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/ConfigureProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/CreateProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/RemoveDistributionCertificate-test.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/RemoveProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/SetupBuildCredentialsFromCredentialsJson-test.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/SetupProvisioningProfile-test.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts
This is part of the effort to move all credentials apiv2 calls to our graphql API. This is also the first part of adding support for internal distribution within enterprise teams. This PR refactors the `IosCredentialsProvider` class so it uses GraphQL.
- I removed all apiv2 calls from `IosCredentialsProvider` and replaced them with a single Graphql query (by calling a util from Quin's PR).
- I moved the `getAppLookupParamsFromContext` method from `MethodIosBeta` to a more generic place as it's widely used.
Added some unit tests.
=> refactor IosCredentialsProvider to use graphql

packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/new/BuildCredentialsUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupInternalProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/SetupProvisioningProfile-test.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/index.ts
This is the first part of adding support for internal distribution within enterprise teams.
This PR introduces a new property to eas.json (`enterpriseProvisioning: 'adhoc' | 'universe'`) as well as the support for generating adhoc/universal distribution provisioning profiles.
- https://github.com/expo/eas-cli/pull/335/commits/4b42fd861ca5c3be8c91a07f51d1f775aa048af1 adds the new optional prop to eas.json (`enterpriseProvisioning`).
- https://github.com/expo/eas-cli/pull/335/commits/6e7513892f00c71413fe69b5c642c22e9662ab20
- It makes the `SetupProvisioningProfile` action generic, which means it's now capable of setting up both app store and enterprise provisioning profiles (it's passed as an argument to the constructor).
- I changed the `SetupBuildCredentials` so it accounts for the …
=> add support for adhoc and universal distribution within enterprise teams

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/commands/branch/publish.ts, yarn.lock
This PR adds support for a special runtime version indicating that the runtime is an expo SDK preset runtime (SDK version). With this special runtime version the user will be able to load the app in Expo Go (as long as expo go has that runtime version). Otherwise the user will need to use the dev client to develop their app.
From https://github.com/expo/universe/pull/7299:
> - In eas-cli (this PR) publish default to the `runtimeVersion` returned from `getRuntimeVersionForSDKVersion` when one isn't supplied and the project is managed.
> - In native code, parse this runtime version to extract the sdk version. https://github.com/expo/expo/pull/12521
> - In home query for EAS updates and parse their runtime versions. If a runtime version is this special format, allow it to be launched in Expo …
=> Use special Expo SDK runtime version for managed projects

CHANGELOG.md, packages/eas-cli/src/credentials/ios/actions/new/SetupAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDeviceQuery.ts, packages/eas-cli/src/devices/actions/create/action.ts
Currently, if the user is running an internal distribution build but they haven't registered any devices yet, we throw an error `Run 'eas device:create' to register your devices first`.
This PR makes it possible to register the devices without the need to run another command.
I reused the device registration logic from `device:create`.
=> allow for registering devices when building app for internal distribution

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/android/graphql.ts, packages/eas-cli/src/graphql/generated.ts
Fixes https://linear.app/expo/issue/ENG-900/buildtype-apk-produces-aab-in-managed-app
The server-side fix was implemented in https://github.com/expo/universe/pull/7397
- I re-generated the graphql code. 
- I passed `buildType` to the Android managed build mutation.
Followed the repo steps from the linear task and it worked fine.
=> fix building APKs for Android managed projects

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/project/projectUtils.ts, packages/eas-json/package.json, yarn.lock
- We want to expose the `EAS_BUILD_USERNAME` env var for all EAS Build builds https://linear.app/expo/issue/ENG-912/expose-eas-build-username-as-built-in-environment-variable
- https://github.com/expo/eas-cli/pull/159 introduces incorrect behavior where the project account name was used as the username. In some cases, when the `owner` field is set, the project account name is different than the initiating user's username.
- I added the `username` to the build metadata.
- I changed the `username` property used for the managed builds input to reflect the real username. It's set to `undefined` for robots.
I'll test this manually once the server-side changes are deployed to staging.
=> send username as build metadata property

packages/eas-cli/src/credentials/ios/actions/new/SetupAdhocProvisioningProfile.ts
is it just me or does the function look like it is doing the opposite of the original name? ❓ ❔
=> [eas-cli] adhoc opposite name

CHANGELOG.md, packages/eas-cli/src/build/build.ts
After switch to graphql we don't detect API incompatibility errors
check for graphql error code
run local builds when
- grqphql API si not compatible
- turtle returns unsupported error
=> fix api deprecation error

CHANGELOG.md, packages/eas-cli/src/credentials/__tests__/fixtures-context.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/credentials/ios/__tests__/IosCredentialsProvider-test.ts, packages/eas-cli/src/credentials/ios/actions/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/new/BuildCredentialsUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupInternalProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/SetupInternalProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppCredentialsQuery.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts, packages/eas-cli/src/graphql/generated.ts
- This PR makes it possible to set up both ad-hoc and enterprise credentials when someone is using an enterprise team but didn't set the `enterpriseProvisioning` property in `eas.json`.
- This also adds offline validation of a distribution certificate.
- I implemented the logic in `SetupInternalProvisioningProfile` - it's run when the user didn't specify the `enterpriseProvisioning` property in eas.json.
- I removed handling of the `--skip-credentials-check` flag for iOS builds. The flag was necessary because we didn't have proper offline validation of the provisioning profile/distribution certificate. This PR adds the offline dist cert validation and makes it possible to get rid of the flag.
Added unit tests.
=> implement SetupInternalProvisioningProfile

packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/credentialsJson/__tests__/update-test.ts, packages/eas-cli/src/credentials/credentialsJson/update.ts, packages/eas-cli/src/credentials/ios/actions/UpdateCredentialsJson.ts, packages/eas-cli/src/credentials/ios/actions/new/UpdateCredentialsJson.ts, packages/eas-cli/src/credentials/ios/actions/new/__tests__/SetupBuildCredentialsFromCredentialsJson-test.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts, packages/eas-cli/src/credentials/manager/__tests__/SelectIosDistributionTypeGraphqlFromBuildProfile-test.ts
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to update credentials json from data on eas servers using the new Graphql Api. This will eventually replace the old `UpdateCredentialsJson` here:  https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/ios/actions/UpdateCredentialsJson.ts
It also converts the old UpdateCredentialsJson to use the refactored logic in `updateIosCredentialsAsync`
=> [eas-cli] refactor UpdateCredentialsJson

packages/eas-cli/src/credentials/manager/SelectBuildProfileFromEasJson.ts, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/__tests__/EasJsonReader-test.ts
Add a convenience method, `getBuildProfileNamesAsync ` to eas-json, based on wojtek's feedback here: https://github.com/expo/eas-cli/pull/348#discussion_r616548554
=> [eas-cli][eas-json] add getBuildProfileNamesAsync helper

packages/eas-cli/src/credentials/ios/actions/new/AppleTeamUtils.ts, packages/eas-cli/src/credentials/ios/actions/new/CreateDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupBuildCredentialsFromCredentialsJson.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/new/SetupProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/manager/ManageIosBeta.ts
The current credentials manager has CreateDistCert and UseExistingDistCert functionalities. This PR adds this functionality to the beta manager. `CreateDistCert` is slightly different here, as we made an optimization in `expo-cli` where if we were in a project context, we would also assign it to the project. We do something similar, but we setup build credentials with the new dist cert if we detect the user to be in project context.
=> [eas-cli] add CreateDistCert and UseExistingDistCert to beta manager

CHANGELOG.md, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
We want to make the new EAS Update manifest compliant with the Expo Updates protocal. This requires the asset key be defined purely by the bundler.
We used to add a file extension to deal with pecularities of expo-asset
that has been fixed here: #12624 
This removes the addition of a file extension.
update tests
publish to sample project and observer that the manifest no longer has extensions appended to its keys.
=> [eas-cli] create asset keys without an extension

packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts
`getAppAsync` is not used anywhere outside the GraphqlClient class, so get rid of it in jest mocks and stop exporting it.
=> [eas-cli] stop exporting getAppAsync 

CHANGELOG.md, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/build/utils/url.ts
The workflow to download an internal build on your device is not optimal. You need to log into Expo on your phone and find the build you want. OK that's not too bad but we can show a QR code to download or install the internal distribution build to make it easier
Added a QR code before the link to the build details page
- You should get a QR code after running `eas build --profile preview`
- On iOS it should install the app directly, with a message like this `"exp.host" would like to install "app"`
=> [eas-cli] add QR code to install internal distribution build on device

packages/eas-cli/src/credentials/__tests__/fixtures-android-new.ts, packages/eas-cli/src/credentials/__tests__/fixtures-constants.ts, packages/eas-cli/src/credentials/android/actions/BuildCredentialsUtils.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/android/api/graphql/queries/AndroidAppCredentialsQuery.ts, packages/eas-cli/src/credentials/android/utils/__tests__/__snapshots__/printCredentialsBeta-test.ts.snap, packages/eas-cli/src/credentials/android/utils/__tests__/printCredentialsBeta-test.ts, packages/eas-cli/src/credentials/android/utils/printCredentialsBeta.ts, packages/eas-cli/src/credentials/context.ts, packages/eas-cli/src/credentials/manager/ManageAndroidBeta.ts
This is the start of the beta Android credentials manager. It just prints credentials right now. Unfortunately, in the old Android credentials system, Android things were just logged under the Expo app. This is very different from iOS, which logged credentials under an Expo app and a bundleIdentifier.
The new Android credentials system brings everything to parity with iOS, and credentials are logged under an Expo app and an application identifier (`android.package` in app.json). 
When the user has either legacy credentials or modern credentials, but NOT both
When the user has both legacy credentials AND modern credentials
=> [eas-cli] basic beta android manager

CHANGELOG.md, packages/eas-cli/src/project/publish.ts
- [x ] I've added an entry to [CHANGELOG.md](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#main) if necessary.
https://github.com/expo/expo-cli/pull/3395/files breaks `eas branch:publish` since we pass `--force` to `expo export`.
Remove `--force`
This breaks `eas branch:publish` for `expo-cli` <= 4.4.3, but since this is still just in internal testing 🚀 
Tested publish works.
=> [eas-cli] remove --force to fix eas publish

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/credentials/__tests__/fixtures-android-new.ts, packages/eas-cli/src/credentials/__tests__/fixtures-context.ts, packages/eas-cli/src/credentials/android/actions/new/CreateKeystore.ts, packages/eas-cli/src/credentials/android/actions/new/__tests__/CreateKeystore-test.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/android/api/graphql/mutations/AndroidKeystoreMutation.ts, packages/eas-cli/src/graphql/generated.ts
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to create a new keystore using the new Graphql Api. This is *PARTIALLY* what will eventually replace the old `UpdateKeystore` here:  https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/android/actions/UpdateKeystore.ts
=> [eas-cli] create keystore action

CHANGELOG.md, packages/eas-cli/README.md, packages/eas-cli/src/graphql/client.ts
network requests are failing opaquely.
Change the default urql requestPolicy to `network-only`
Perhaps we can roll this back to a less aggressive policy, but for now priority is to get things working.
In a demo project, installed the output of `npm pack`
confirmed that builds were failing.
Adjusted default request policy. cleaned node_modules and installed new `npm pack`
confirmed that builds are no longer failing.
=> [eas-cli] set default urql requestPolicy to network-only

CHANGELOG.md, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
We want to be able to publish/republish to specific platforms.
Added a --platform flag:
`eas branch:publish main --platform ios`
will publish an update group with a single update in it. 
On a demo project:
* published to a single platform
* republished a multiplatform update to a single platform.
* confirmed publish and republish still work without the --platform flag
updated publish-test.ts
=> [eas-cli] add --platform flag to branch:publish command

.yarnrc
This is a follow-up to https://github.com/expo/eas-cli/pull/399
We want to avoid adding non-strict versions to package.json
I set an empty `save-prefix` in `.yarnrc`.
- `yarn add moment`
- I saw that it added `"moment": "2.29.1", ` to package.json
- `yarn remove moment`
- I deleted the `.yarnrc` file.
- I ran `yarn add moment` and saw that `"moment": "^2.29.1", ` was added to package.json.
=> set empty save-prefix

packages/eas-cli/src/commands/branch/create.ts, packages/eas-cli/src/commands/branch/delete.ts, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/commands/branch/rename.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/commands/channel/edit.ts, packages/eas-cli/src/commands/channel/list.ts, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/commands/secret/create.ts, packages/eas-cli/src/submissions/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submissions/ios/__tests__/IosSubmitCommand-test.ts
getProjectIdAsync is superior to ensureProjectExistsAsync as it will check to see if the ID is saved locally. This switch will reduce the number of network calls and make the CLI significantly "snappier",
find/replace. Also made use of the `getFullName` util to further simplify code.
Would appreciate @FiberJW eyes on places I'm unfamiliar with usage in places like:
https://github.com/expo/eas-cli/blame/main/packages/eas-cli/src/commands/secret/create.ts#L50
in particular.
tested various commands in a demo project.
=> [eas-cli] replace ensureProjectExistsAsync with getProjectIdAsync

packages/eas-cli/graphql.schema.json, packages/eas-cli/package.json, packages/eas-cli/src/credentials/__tests__/fixtures-android-new.ts, packages/eas-cli/src/credentials/android/actions/BuildCredentialsUtils.ts, packages/eas-cli/src/credentials/android/actions/new/SetupBuildCredentials.ts, packages/eas-cli/src/credentials/android/actions/new/__tests__/SetupBuildCredentials-test.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/android/api/graphql/mutations/AndroidAppBuildCredentialsMutation.ts, packages/eas-cli/src/credentials/android/api/graphql/mutations/AndroidAppCredentialsMutation.ts, packages/eas-cli/src/credentials/errors.ts, packages/eas-cli/src/credentials/ios/actions/ConfigureProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/CreateProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/SetupAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/SetupDistributionCertificate.ts, packages/eas-cli/src/credentials/ios/actions/SetupProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/ConfigureProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/CreateProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/SetupProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/errors.ts, packages/eas-cli/src/graphql/generated.ts, yarn.lock
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to create a new keystore using the new Graphql Api. This is what will eventually replace the old `SetupBuildCredentials` here:  https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/android/actions/SetupBuildCredentials.ts
1. If user has legacy or modern default credentials, return that
2. If user has no credentials setup, set up some modern default credentials
If user specifies a named configuration to setup, we do the following: 
1. If user has credentials setup under the named configuration, return that
2. Else set up some credentials under the named configuration
In the modern android credentials setup, we have the concept of unique 'configuration names'. For …
=> [eas-cli] setup android build credentials with graphql

packages/eas-cli/package.json, yarn.lock
- Supports a new apple server error, prevents throwing an invalid credential error when Apple servers are down.
- https://github.com/expo/expo-cli/pull/3496
=> Bump @expo/apple-utils@0.0.0-alpha.20 to support Apple server errors

packages/eas-cli/src/project/projectUtils.ts
Put the projectId caching to app.json (introduced in https://github.com/expo/eas-cli/commit/09682754f89fc675b8262100eca05b1b8bf09fa4) behind a flag until we roll out a better user UX for dealing the the projectId.
In demo project confirmed that `eas branch:publish` queries graphql for the projectId each time instead of attempting to read it from app.json. Both when there is an `eas.projectId` key and when there is not.
confirmed it saves and queries the projectId when the flag is set.
=> [eas-cli] put projectId caching behind EAS_ENABLE_PROJECT_ID flag

CHANGELOG.md, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/__tests__/EasJsonReader-test.ts
It is intended to be possible to do ` development-client` build when using `distribution: internal`
Update the eas.json validation to allow this.
Run a build using local eas-cli with these changes using this config:
```json
"development": {
"workflow": "managed",
"distribution": "internal",
"buildType": "development-client"
}
```
=> [eas-json] Include development-client in valid buildType for internal distribution

CHANGELOG.md, packages/eas-cli/src/commands/branch/publish.ts
publishing without platform flag fails
substitute `defaultPlatforms` for `all` appropriately.
When this command was made initially, we didn't default to 'all' so this check was looking for an `undefined`.
Tested in demo repo, no flag and each different possible flag.
```
eas branch:publish main
eas branch:publish main --platform all
eas branch:publish main --platform android
eas branch:publish main --platform ios
```
=> [eas-cli] fix bug when publishing without platform flag

packages/eas-cli/src/commands/branch/publish.ts
There are complexities when republishing an update group to a different set of platforms that is was originally published to.
* republishing to a super set: log a warning that the original updateGroup was not published for all platforms
* republishing to a platform that does not exist on the original: throw an error
* add a Log.withTick describing the platforms to which we are republishing.
On a demo repo:
select an update that was only published to one platform:
attempt to republish a group that was published to a disjoint set of platforms:
publish to a group with an equal set of platforms:
interactive prompt filters by platform correctly:
=> [eas-cli] make republish work smoothly with different platforms

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/graphql.ts, packages/eas-cli/src/graphql/generated.ts
I've found out that even though that https://github.com/expo/eas-cli/pull/413 has been released, the `appBuildVersion` is not being sent to api. 
This is because I forgot to do two things:
- Regenerate graphql code
- Update the metadata transformer 
- I regenerated GraphQL code.
- I updated the metadata transformer so now it passes the `appBuildVersion` to the build mutation. 
This time I double-checked that the `appBuildVersion` is sent with other metadata to the API (checked the records in db).
=> fix sending `appBuildVersion` to api

CONTRIBUTING.md
Currently the contributing guide reads a bit strangely because we recommend copying the changelog over to the release on Github and marking it as released before updating the changelog in the repo or publishing.
I moved the Github release update to after the "Update `CHANGELOG.md` step
I followed these steps for 0.15.0
=> Move updating the release on Github to after the release is completed

CHANGELOG.md, packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts
Help debug [this forums post](https://forums.expo.io/t/eas-build-managed-workflow-for-ios-disables-sign-in-with-apple-and-associated-domains/) and give the ability to opt out of capability syncing without needing to downgrade eas-cli.
Talked to @EvanBacon and he shared this code snippet mostly.
Ran these commands
```
EXPO_DEBUG=1 ENVIRONMENT=STAGING easd build --platform ios --profile staging
EXPO_NO_CAPABILITY_SYNC=1 EXPO_DEBUG=1 ENVIRONMENT=STAGING easd build --platform ios --profile staging
```
=> Add env var to disable capability sync and extra logs when EXPO_DEBUG is set

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
Fixes https://github.com/expo/eas-cli/issues/430
I actual fix has been implemented in https://github.com/expo/expo-cli/pull/3533
This PR upgrades the @expo/config-plugins package to the latest.
Followed the repro steps from https://github.com/expo/eas-cli/issues/430#issuecomment-850932792
=> fix bundle identifier getter

packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/configure.ts, packages/eas-cli/src/project/android/__tests__/applicationId-test.ts, packages/eas-cli/src/project/android/applicationId.ts
Refactor Android Application Identifier configuration so it behaves the same way as iOS. In the managed workflow, we will help the user configure their application identifier if it is not present. In the generic workflow, we skip this and we return an appropriate error message if the application identifier is not configured properly by the time we call `getApplicationId`
More details: https://github.com/expo/eas-cli/pull/431#discussion_r641394021
=> [eas-cli] refactor application id configuration

packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/credentials/android/AndroidCredentialsProvider.ts
Replace the old Android SetupBuildCredentials with the new one
=> [eas-cli] use new android build credentials provider

CHANGELOG.md, packages/eas-cli/src/build/utils/repository.ts
A developer trying out `eas build` on their project on Windows using git-lfs was unable to start their build:
```
✔ Using remote Android credentials (Expo server)
✖ Compressing project files
Error: git exited with non-zero code: 128
```
We looked into this a bit and found that `git clone --depth ...` was only working for them if they added an added an additional `/` in `file://C:/...` to make `file:///C:/...`
```
PS C:\Git\app> git clone --no-hardlinks --depth 1 file:///C:\Git\app ./deleteme
fatal: destination path './deleteme' already exists and is not an empty directory.
Cloning into './deleteme'...
remote: Enumerating objects: 1134, done.
remote: Counting objects: 100% (1134/1134), done.
remote: Compressing objects: 100% (1096/1096), done.
remote: Total 1134 (delta 22), reused 598 …
```
=> [eas-cli] Fix git repo root path on Windows

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/credentials/android/api/graphql/mutations/AndroidKeystoreMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleAppIdentifierMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDeviceMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleDistributionCertificateMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleProvisioningProfileMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppleTeamMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppBuildCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppCredentialsMutation.ts, packages/eas-cli/src/graphql/generated.ts
cleanup input types to use the generated ones
=> [eas-cli] refactor credential input types

CHANGELOG.md, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/commands/build/configure.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/credentials/credentialsJson/__tests__/read-test.ts, packages/eas-cli/src/credentials/credentialsJson/read.ts, packages/eas-cli/src/credentials/credentialsJson/types.ts
- `experimental.npmToken` in credentials.json is a legacy way of providing the token to EAS Build. EAS Secrets should be used instead. This is what our docs are suggesting to do - https://docs.expo.io/build-reference/how-tos/#how-to-use-private-package-repositories
- `--allow-experimental` flag for `eas build:configure` has no effect now (it's not related to the previous point).
- I updated the credentials.json schema and removed the `experimental.npmToken` field.
- I removed `--allow-experimental` flag from `eas build:configure`.
None
=> clean up legacy stuff 

packages/eas-cli/src/credentials/android/actions/new/DownloadKeystore.ts, packages/eas-cli/src/credentials/android/actions/new/__tests__/DownloadKeystore-test.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/android/utils/printCredentialsBeta.ts, packages/eas-cli/src/credentials/manager/ManageAndroidBeta.ts, packages/eas-cli/src/credentials/manager/SelectAndroidBuildCredentials.ts
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to download a new keystore using the new Graphql Api. This is what will eventually replace the old `DownloadKeystore` here:  https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/android/actions/DownloadKeystore.ts
=> [eas-cli] download and backup keystore action

packages/eas-cli/src/credentials/manager/HelperActions.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/credentials/manager/SelectPlatform.ts
previously, the user has to choose their build profile each time they navigate anywhere through the UI. 
- changed this so the user only needs to choose their build profile once when the manager is run. If they want a different build profile, they can choose 'Go Back' from the main menu and run the ios manager again
=> [eas-cli] more manager dx improvements

packages/eas-cli/src/credentials/__tests__/fixtures-android-new.ts, packages/eas-cli/src/credentials/android/actions/new/RemoveFcm.ts, packages/eas-cli/src/credentials/android/actions/new/RemoveKeystore.ts, packages/eas-cli/src/credentials/android/actions/new/__tests__/RemoveFcm-test.ts, packages/eas-cli/src/credentials/android/actions/new/__tests__/RemoveKeystore-test.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/android/api/graphql/mutations/AndroidFcmMutation.ts, packages/eas-cli/src/credentials/android/api/graphql/mutations/AndroidKeystoreMutation.ts, packages/eas-cli/src/credentials/manager/ManageAndroidBeta.ts, packages/eas-cli/src/graphql/generated.ts
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to remove a keystore and fcm api key using the new Graphql Api. This is what will eventually replace the old `RemoveKeystore` and add the option for the user to delete their FCM Api Key here:  https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/android/actions/RemoveKeystore.ts
=> [eas-cli] remove android fcm/keystore actions

CHANGELOG.md, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/credentials/android/AndroidCredentialsProvider.ts, packages/eas-cli/src/log.ts
- [n/a] I've tagged the changelog entry with `[EAS BUILD API]` if it's a part of a breaking change to EAS Build API (only possible when updating `@expo/eas-build-job` package).
Context in https://linear.app/expo/issue/ENG-1103/remove-skip-credentials-check
- Delete usage of `skipCredentialsCheck`
- Add warning to when the `--skip-credentials-check` flag is passed in to `eas build`
- Create a logging helper that we can use for future flag deprecations to ensure we have a consistent format (using the same format as expo-cli, eg: run `expo start --config example.json` anywhere to see a similar warning.
- Hide the flag from `eas build --help`
```
╰─$ easd build --help
Start a build
USAGE
$ eas build
OPTIONS
--clear-cache                     Clear cache before the build
--local …
```
=> [eas-cli] Deprecate --skip-credentials-check flag for build

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-json/package.json, yarn.lock
add big sure image
update eas-build-job
=> [eas-cli] add support for big sur image for ios builds

packages/eas-cli/src/credentials/android/actions/UpdateCredentialsJson.ts, packages/eas-cli/src/credentials/android/actions/new/SetupBuildCredentialsFromCredentialsJson.ts, packages/eas-cli/src/credentials/android/actions/new/UpdateCredentialsJson.ts, packages/eas-cli/src/credentials/android/actions/new/__tests__/SetupBuildCredentialsFromCredentialsJson-test.ts, packages/eas-cli/src/credentials/credentialsJson/__tests__/update-test.ts, packages/eas-cli/src/credentials/credentialsJson/update.ts, packages/eas-cli/src/credentials/manager/ManageAndroidBeta.ts
This is part of the effort to move all credentials apiv2 calls to our graphql api. This PR allows you to update/download build credentials between your local credentials.json and the EAS servers using the new Graphql Api. This is what will eventually replace the old `SetupBuildCredentialsFromCredentialsJson` and `UpdateCredentialsJson` here:  https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/android/actions/SetupBuildCredentials.ts and https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/credentials/android/actions/UpdateCredentialsJson.ts
=> [eas-cli] action to upload/download credentials.json to www

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/types.ts
We track usage of dev client in order to to understand how it's used and to improve the experience.
Added properties to `BuildContext.trackingCtx`.
Because these properties get added to all build events, only did a spot check of a couple of events.
- Added logging to `analytics.ts`
- In a managed project with `expo-dev-client` installed, ran `eas build`
- Observed that the properties were included.
Tested `dev_client: false` case:
- Ran `yarn remove expo-dev-client`.
- Ran `eas build`.
- Checked that `dev_client` property was `false` and `dev_client_version` property was not defined.
=> Record dev client builds created and downloaded to analytics

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/credentials/__tests__/fixtures-context.ts, packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/credentialsJson/__tests__/update-test.ts, packages/eas-cli/src/credentials/ios/__tests__/IosCredentialsProvider-test.ts, packages/eas-cli/src/credentials/ios/actions/AssignPushKey.ts, packages/eas-cli/src/credentials/ios/actions/CreatePushKey.ts, packages/eas-cli/src/credentials/ios/actions/PushKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/AssignPushKey-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/CreatePushKey-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/SetupProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/SetupTargetBuildCredentialsFromCredentialsJson-test.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/ApplePushKeyMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppCredentialsMutation.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/IosAppCredentialsQuery.ts, packages/eas-cli/src/credentials/ios/appstore/CredentialsUtils.ts, packages/eas-cli/src/credentials/ios/appstore/pushKey.ts, packages/eas-cli/src/credentials/ios/validators/validatePushKey.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/credentials/IosAppCredentials.ts
CreatePushKey and AssignPushKey actions along with some refactors. Sorry it's a bit messy - I can split this up if its too hard to review.
Refactors include:
- Removing unused mocks and renaming others to be simpler (getNewIosApiMockWithCredentials, getNewIosApiMockWithoutCredentials)
- Removed unused Graphql queries (IosAppCredentialsQuery.byAppIdentifierIdAsync)
- Removed `IosAppCredentialsFragment` and replaced it with `CommonIosAppCredentialsFragment`. We only really use it in 1-2 places, and it's easier to reason about the code when there is the same fragment being passed around (`CommonIosAppCredentialsFragment`)
- Replaced `IosAppCredentialsWithBuildCredentialsQueryResult` with `CommonIosAppCredentialsFragment`
=> [eas-cli] create and assign push key actions

CHANGELOG.md, packages/eas-cli/src/build/configure.ts
It should be easy to make a build for internal distribution with dev client included.
Automatically configure a build profile for internal distribution in `eas.json` when `eas build:configure` is run.
I did this by modifying the default values added to `eas.json`.
Ran `eas build:configure -p all` in a managed app. Contents of `eas.json`:
```json
{
"builds": {
"android": {
"release": {
"workflow": "managed"
},
"development": {
"workflow": "managed",
"buildType": "development-client",
"distribution": "internal"
}
},
"ios": {
"release": {
"workflow": "managed"
},
"development": {
"workflow": "managed",
"buildType": "development-client",
"distribution": "internal"
}
}
}
}
```
Ran `eas build:configure -p all` in a bare app. Contents of `eas.json`:
```json
{
"builds": {
"android": {
"release": …
```
=> Add an internal distribution with dev client to `build:configure` defaults

packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/ios/actions/AppleTeamUtils.ts, packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts, packages/eas-cli/src/credentials/ios/actions/PushKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/SetupPushKey.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/SetupPushKey-test.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/ApplePushKeyQuery.ts, packages/eas-cli/src/credentials/ios/appstore/CredentialsUtils.ts, packages/eas-cli/src/credentials/ios/validators/validatePushKey.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/graphql/generated.ts
Add the action to setup a new push key. It works the following way :
- If a push key is already configured, return
-  If the user has no push keys in their account, create a new one for them
- If the user has a valid push key in their account, ask if they want to use that one (autoselection)
- Else, give the option to use an existing push key or to create a new one
=> [eas-cli] setup push key action

packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/ios/actions/RemovePushKey.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/RemovePushKey-test.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/ApplePushKeyMutation.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/graphql/generated.ts
Add the 'remove push key' action. It works the following way:
- user chooses a push key from their account to delete
- remove push key from eas servers
- ask if they want to revoke the push key on apple servers
=> [eas-cli] add 'remove push key' action

packages/eas-cli/README.md, packages/eas-cli/clean-readme.py, packages/eas-cli/package.json, packages/eas-cli/patch-readme.js
Not applicable
Majority of the `See code` links in the README resolve to nonexistent paths causing 404s. For example, [build/commands/account/login.ts](https://github.com/expo/eas-cli/blob/v0.17.0/build/commands/account/login.ts) should resolve to [src/commands/account/login.ts](https://github.com/expo/eas-cli/blob/v0.17.0/packages/eas-cli/src/commands/account/login.ts).
Closes #350.
Simple find and replace with the links and updating relevant text using `patch-readme.js` script added to `package.json`.
Clicked through the links to make sure they all resolve to right locations.
=> [docs] update 'See code' links in README

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/create.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/commands/build/cancel.ts, packages/eas-cli/src/commands/build/list.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/BuildQuery.ts
`new` is now the initial build status. A build is in this state when it's not yet enqueued. This can happen when the account reaches the concurrency limit.
Part of https://linear.app/expo/issue/ENG-1395/add-status-to-reflect-prequeue-state-to-www
www PR: https://github.com/expo/universe/pull/7756
- I grepped the repo for `BuildStatus` and added support for the new status.
- Deleted `getPendingBuildIdAsync` as it hasn't been used anywhere.
I ran a build in staging and the CLI didn't break.
=> support new build status: `new`

CHANGELOG.md, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/__tests__/EasJsonReader-test.ts, yarn.lock
https://linear.app/expo/issue/ENG-1396/make-default-image-dependent-on-sdk-version
Expo SDK 41 (and lower) projects won't build with Xcode 12.5.
If we detect that a project uses SDK <= 41 we use image `macos-catalina-10.15-xcode-12.4`. 
- I ran a build for an SDK 41 project without `image` in `eas.json`. I saw that `macos-catalina-10.15-xcode-12.4` was used for the build.
- I ran another build for the same project but with `image` set in `eas.json`. The image was propagated to the job object.
=> [ENG-1396] change default ios image for sdk <= 41

CHANGELOG.md, packages/eas-cli/src/build/utils/repository.ts, packages/eas-cli/src/vcs/git.ts
I noticed that I was being prompted to commit my changes even when I had a clean git index:
```
╭─~/code/abcd ‹main›
╰─$ gs                                                                                                                                                                                                                                                  130 ↵
On branch main
nothing to commit, working tree clean
╭─~/code/abcd ‹main›
╰─$ easd build:configure
💡 The following process will configure your iOS and/or Android project to be compatible with EAS Build. These changes only apply to your local project files and you can safely revert them at any time.
✔ Which platforms would you like to configure for EAS Build? › All
Warning! Your repository working tree is dirty.
It's …
```
=> [eas-cli] Fix inverted conditional so we actually only prompt about commit when index is dirty

CHANGELOG.md, packages/eas-cli/src/project/ios/bundleIdentifier.ts
Support bundle identifiers that begin with a dot `.`.
- https://github.com/expo/expo-cli/issues/3315
Copied over from my update in Expo CLI.
=> Support bundle identifiers that start with a dot

packages/eas-cli/src/credentials/android/actions/__tests__/DownloadKeystore-test.ts, packages/eas-cli/src/credentials/android/actions/__tests__/RemoveKeystore-test.ts
I've noticed that running `yarn test` produces some files.
Mock `fs-extra` so `yarn test` doesn't produce any files.
=> mock fs-extra so tests don't produce files

CHANGELOG.md, packages/eas-cli/src/credentials/android/AndroidCredentialsProvider.ts
Remove restriction on `keyPassword` for keystores -- this is only required for JKS keystores and pkcs12 ones don't have them
=> [eas-cli] remove nullthrows on keystore keyPassword

CHANGELOG.md, packages/eas-cli/src/project/android/__tests__/applicationId-test.ts, packages/eas-cli/src/project/android/applicationId.ts, packages/eas-cli/src/project/ios/__tests__/bundleIdentifier-test.ts, packages/eas-cli/src/project/ios/bundleIdentifier.ts
Fixes https://linear.app/expo/issue/ENG-1377/auto-suggest-application-id-and-bundle-identifier-and-provide-context
> Currently we ask the user to provide an application id and bundle identifier without any suggested default value in eas-cli. This is a good start and much better than erroring without any options, but we can do a bit better than this and have the same behavior as in expo-cli:
>
> <img width="574" alt="Screen Shot 2021-06-17 at 10 55 21 AM" src="https://user-images.githubusercontent.com/5256730/123648055-eb208300-d828-11eb-89d6-f9199ebc7cbc.png">
I implemented the logic as described in the linear task:
> The logic suggested name is approximately com.username.slug, and if we are prompting for both, one after the other, we should use the value that the user provides for the …
=> [ENG-1377] auto-suggest application id and bundle identifier

packages/eas-cli/graphql.schema.json, packages/eas-cli/package.json, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/graphql.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/graphql.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/graphql.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/BuildMutation.ts, packages/eas-json/package.json, packages/eas-json/src/Config.types.ts, yarn.lock
use new BuildMutation with unified API for generic and managed workflow
switch to new API, should not contain any user-facing changes
run builds on staging
=> [eas-cli] use new build mutation

CHANGELOG.md, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/commands/build/index.ts
- If you run `eas build -p ios` and you have not configured EAS yet, you are prompted to set an Android application id and configure Android in eas.json if it's not configured already.
- If you run `eas build -p ios` and Android is already configured but iOS is not, we currently bail out rather than configuring iOS:
```
✔ Linked to project @notbrent/brandnew
Error: There is no profile named release for platform android
```
- This is undesirable because you should be able to run `eas build -p ios` and configure only iOS stuff and then run `eas build -p android` and configure only Android stuff.
I made the function that checks if we need to configure the project aware of the current configuration state. I also had to fix a small bug in `build/configure.ts` where we'd spread the existing …
=> [eas-cli] Support configuring one platform at a time when running `eas build`

CHANGELOG.md, packages/eas-cli/src/credentials/manager/ManageAndroid.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/project/__tests__/projectUtils-test.ts, packages/eas-cli/src/project/ensureProjectExists.ts, packages/eas-cli/src/project/projectUtils.ts
- Add a way to prompt user to create a project if it doesn't exist  -- `findProjectIdByAccountNameAndSlugNullableAsync`
- Add more guardrails to the credentials manager (ie) tell people if they aren't in a project directory, prompt to create project if it doesnt exist on eas servers yet
=> [eas-cli] prompt to create project if not exists, more credentials guardrails

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/ios/UpdatesModule.ts, yarn.lock
Follow-up to https://github.com/expo/expo-cli/pull/3634
I bumped `@expo/config-plugins` to the latest.
The same as in https://github.com/expo/expo-cli/pull/3634
=> bump @expo/config-plugins to 3.0.3

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/project/info.ts, packages/eas-cli/src/commands/project/init.ts, packages/eas-cli/src/graphql/generated.ts
We want to transition the eas-cli to relying on the project ID instead of the `fullName`.
This command displays the project ID as well as the current `fullName`. Since `project:info` gives the user a way to see the current `FullName`, we are set up up to deprecate the current custom of the printing out of the fullName each time the user runs a command.
`project:*` commands are hidden so am not updating the changelog.
Added command and a graphQL query.
Tested in demo repo
=> [eas-cli] add project:info command

CHANGELOG.md, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/configure.ts, packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/project/ios/scheme.ts, packages/eas-json/src/Config.types.ts, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/__tests__/EasJsonReader-test.ts, packages/eas-json/src/index.ts
unify generic and managed workflow
support the same set of option for both workflows
Run builds with few different combinations of options in eas.json against production
=> [eas-cli] unify generic and manged workflows

packages/eas-cli/src/build/build.ts
Handle error message for eas downtime
run local build with kill switch enabled
=> [eas-cli] Error message for eas build downtime

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/credentials/ios/appstore/__tests__/bundleIdCapabilities-test.ts, packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts, yarn.lock
- iOS 15 added new capabilities, this PR adds support for those new capabilities.
- https://github.com/expo/third-party/pull/58
- Downloaded the Xcode beta to get the entitlement keys
- Updated the unit tests
- Tested the API directly
- Ran local EAS on a project with the following app.json:
```
{
"expo": {
"ios": {
"entitlements": {
"com.apple.developer.family-controls": true,
"com.apple.developer.group-session": true,
"com.apple.developer.usernotifications.communication": true,
"com.apple.developer.usernotifications.time-sensitive": true
}
}
}
}
``` 
- Got the following message: 
```
✔ Synced capabilities: Enabled: Family Controls, Group Activities, Communication Notifications, Time Sensitive Notifications
```
- Checked https://developer.apple.com/account/resources/identifiers/bundleId …
=> Added iOS 15 capabilities

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/android/UpdatesModule.ts, packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/Build.ts
https://linear.app/expo/issue/ENG-1474/update-eas-buildlist-and-buildshow-to-include-new-metadata
> We show version info, git commit sha, and more in the web ui now. We should dump all build metadata in build:list and build:show.
- I added more build metadata to the table:
- Channel - for new expo-updates backend
- SDK Version
- Version - `expo.version` (from app config) or value defined in the native project
- Version code / Build number
- Git commit hash
- I also added filtering for values that are null / undefined (e.g. we don't show `release` if the user has `releaseChannel` configured).
=> [ENG-1474] build:list / build:view: print more metadata

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/metadata.ts, packages/eas-json/package.json, yarn.lock
https://linear.app/expo/issue/ENG-1460/add-runtimeversion-to-build-job-metadata
We want to display the runtime version on the website.
I added the runtime version to build metadata. 
I had `runtimeVersion` defined in the app config, I ran a build and checked it was sent to www.
Merge after https://github.com/expo/universe/pull/7821 is merged and deployed.
=> [ENG-1460] add runtime version to build metadata

CHANGELOG.md, packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/Build.ts
We want to display the runtime version in the build:view / build:list output.
Generated GraphQL code + updated the build details printer.
=> build:list / build:view - print runtime version

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/commands/project/info.ts, packages/eas-cli/src/commands/project/init.ts, packages/eas-cli/src/commands/secret/delete.ts, packages/eas-cli/src/commands/secret/list.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/EnvironmentSecretsQuery.ts
This removes `fullName` from the log messages as well as the graphQL calls in everything *but* the credentials commands.
The credentials are somewhat involved and will be done in a separate PR to keep things easily reviewable.
* remove fullName in message logs
* replace graphQL calls that use fullName with their `byId` analog.
* remove `hidden` from `project:*` commands.
Also cleaned up the `topic` display:
Before:
After:
(another option is to just remove the descriptions of these topics as they are pretty redundant)
Q: Are there any other blockers to removing the `EAS_ENABLE_PROJECT_ID` gating?
Tested commands in demo repo.
* branch:*
* channel:*
* build:*
* secrets:*
=> [eas-cli] un-hide project:*

packages/eas-cli/src/build/build.ts
Better error message
based on error code
=> [eas-cli] add error message when free tier is disabled

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/analytics.ts, yarn.lock
Closes #507 
default retry handler is throwing unhandled exception if domains are not reachable, replacing it with `OfflineRetryHandler` solves the issue
tested using dnsmasq with `address=/amplitude.com/0.0.0.0` rule
=> [eas-cli] handle blocked amplitude domains

CHANGELOG.md, packages/eas-cli/src/commands/secret/create.ts, packages/eas-cli/src/commands/secret/delete.ts, packages/eas-cli/src/graphql/queries/EnvironmentSecretsQuery.ts
This is a proposal to help users tie their app properties better into their git workflow. Someone in discord mentioned they want to use the pipeline ID as version code. In the most ideal scenario, people would be able to specify additional environment variables when they start a build. But this seems like a quick alternative.
```bash
$ eas secret:create --name=PIPELINE_ID --value=$GITHUB_RUN_ID --force
$ eas build ...
```
**Pros**
- Keep environment variables up to date, programmatically
- Allows for tighter integration with existing workflows
**Cons**
- Running multiple builds at once will not inherit the right env var
Added force option to `secret:create` instead of a new `secret:update` command. This reflects better what it actually would do, delete and create.
```bash
$ eas …
```
=> [eas-cli] Add force option to overwrite existing secrets

CHANGELOG.md, packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts
- Fixes https://github.com/expo/eas-cli/issues/452
- Was finally able to repro by adding a comprehensive entitlements object:
```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>aps-environment</key>
<string>development</string>
<key>com.apple.developer.applesignin</key>
<array>
<string>Default</string>
</array>
<key>com.apple.developer.healthkit</key>
<true/>
<key>com.apple.developer.healthkit.access</key>
<array/>
<key>com.apple.developer.networking.wifi-info</key>
<true/>
<key>com.apple.developer.nfc.readersession.formats</key>
<array>
<string>NDEF</string>
<string>TAG</string>
</array>
</dict>
</plist>
```
The issue was that the wrong array was being …
=> Fix capability syncing 

.gitignore, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/SubmissionMutation.ts, packages/eas-cli/src/submissions/BaseSubmitter.ts, packages/eas-cli/src/submissions/SubmissionService.ts, packages/eas-cli/src/submissions/android/AndroidSubmitter.ts, packages/eas-cli/src/submissions/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submissions/archiveSource/ArchiveFileSource.ts, packages/eas-cli/src/submissions/archiveSource/__tests__/ArchiveFileSource-test.ts, packages/eas-cli/src/submissions/archiveSource/index.ts, packages/eas-cli/src/submissions/ios/IosSubmitter.ts, packages/eas-cli/src/submissions/ios/__tests__/IosSubmitCommand-test.ts, packages/eas-cli/src/submissions/utils/builds.ts, packages/eas-cli/src/submissions/utils/summary.ts
In https://github.com/expo/universe/pull/7799 we created relationship between builds and submissions. When an EAS build is submitted, we should attach its ID to the submission.
- Ran graphql codegen
- When the _Latest_ or _Build ID_ option is selected during `eas submit`, besides `artifactUrl` we query for other build metadata (id, date, app version...)
- The build ID is propagated into `createSubmissionMutation`.
- Having more data, I improved the _Submission Summary_ table to display some build details
> It only displayed `Build ID` or the `[latest]` string before.
> The values on this screenshot are random 😅  used some old staging builds for tests
Updated unit tests, added a test case. Also tested manually.
=> [eas submit] propagate build id to submission mutation

.eslintrc.js, packages/eas-cli/src/build/utils/credentials.ts, packages/eas-cli/src/commands/secret/create.ts, packages/eas-cli/src/commands/secret/delete.ts, packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfileAdhoc.ts, packages/eas-cli/src/credentials/ios/utils/convertHTMLToASCII.ts, packages/eas-cli/src/help.ts, packages/eas-cli/src/utils/timer.ts
I've noticed that we don't have this rule (`curly`) enabled. It's enabled in our other repositories, e.g. in www - https://github.com/expo/universe/blob/main/server/www/.eslintrc.js#L30
I enabled the `curly` eslint rule and ran `yarn lint --fix`.
CI
=> enable lint rule for curly braces around blocks

CHANGELOG.md, packages/eas-cli/src/build/android/version.ts
When building a managed project that doesn't have `android.versionCode` and/or `ios.buildNumber` we record the `appBuildVersion` differently for Android and iOS:
- iOS: `IOSConfig.Version.getBuildNumber()` returns `"1.0.0"`
- Android: `AndroidConfig.Version.getVersionCode` returns `null`
This PR makes those values consistent. Which is, when the `android.versionCode` is not defined, we default to `1`.
This is a temporary fix until https://github.com/expo/expo-cli/pull/3713 is merged.
I ran Android and iOS builds for a fresh managed project and they had the default values recorded for `appBuildVersion`.
=> use default version code when it's not defined for managed project in app.json

CHANGELOG.md, packages/eas-cli/src/build/android/prepareJob.ts
When building Android for internal distribution and neither `gradleCommand` nor `buildType` is defined, we should build an APK.
I added a conditional in `prepareJob` for Android.
I ran a build with the following build profile:
```
{
"builds": {
"android": {
"release": {
"workflow": "managed",
"distribution": "internal"
}
}
}
}
```
The build produced an APK.
=> fall back to APK when building for internal distribution

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
As of https://github.com/expo/universe/pull/7893, the server will support storing and serving the `extra.expoClient` field in the eas update manifest. As part of that, we need to upload it during the update group publish process.
Include the public `exp` project config in the `updateInfo` fields. This is the same thing that is uploaded in the `expo-cli` publish process as the "manifest" (https://github.com/expo/expo-cli/blob/master/packages/xdl/src/project/getPublishExpConfigAsync.ts#L35), which is what we want to put in the `extra.expoClient` field.
The format of the `extra.expoClient` field is defined in https://github.com/expo/expo-cli/pull/3606.
Waiting on the dependent www PR to go to staging/prod, but after it does the test plan will be:
- `eas branch:publish` and then get a …
=> [eas-cli] Upload exp config as client config when publishing or republishing

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/credentials/ios/appstore/__tests__/bundleIdCapabilities-test.ts, packages/eas-cli/src/credentials/ios/appstore/__tests__/capabilityIdentifiers-test.ts, packages/eas-cli/src/credentials/ios/appstore/bundleIdCapabilities.ts, packages/eas-cli/src/credentials/ios/appstore/capabilityIdentifiers.ts, packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts, yarn.lock
It's a bit peculiar that we don't manage more aspects of iOS capabilities automatically. This PR adds support for creating and linking capability identifiers to the application automatically. Based on the project entitlements, we'll link IDs for Apple Pay, iCloud containers, and shared App Groups. Capability IDs need to be unique, so we provide enhanced error handling for cases where you accidentally register a reserved value.
- Resolve https://github.com/expo/eas-cli/issues/523
Sync capability identifiers with the bundle identifier, remove local duplicates, print when new IDs are created.
This functionality can be skipped using `EXPO_NO_CAPABILITY_SYNC=1`.
- Added unit tests
- E2E tested that a project with the following entitlements in the app.json, syncs as expected:
```json
{
"expo": …
```
=> Create and link capability identifiers automatically

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/graphql.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/Build.ts, packages/eas-json/package.json, yarn.lock
https://linear.app/expo/issue/ENG-1292/account-for-universal-enterprise-distribution-in-install-modal
I added `iosEnterpriseProvisioning` to build metadata.
Tested by running a local build and fetching `iosEnterpriseProvisioning` from GraphQL.
=> add `iosEnterpriseProvisioning` to build metadata

CHANGELOG.md, packages/eas-cli/src/project/ios/scheme.ts, packages/eas-cli/src/project/workflow.ts
Closes #529
- check if pbxproj exists(xcodeproj directory might exist locally for some users if project was ejected in the past, because git does not track directories)
- handle case where there is no shared scheme in the project
try to start builds with
- missing pbxproj
- missing .xcscheme files
=> [eas-cli] use .pbxproj file to check if native Xcode project is present

CHANGELOG.md, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submissions/android/ServiceAccountSource.ts, packages/eas-cli/src/submissions/android/__tests__/ServiceAccountSource-test.ts, packages/eas-cli/src/utils/filterAsync.ts
Resolves #511
In future, we may prepend this with proposing stored credentials
If the `--key` param is not specified, `eas submit -p android` tries to find a valid JSON key in the project directory.
- If a single file is found, asks user for confirmation to use this key.
- If multiple files are found, a chooser is displayerd with additional option "None of the above".
- Falls back to old prompt for path if not found or user rejected the detected file[s]. 
A valid key is found by:
1. glob `**/*.json` in project dir.
2. read json and check if it contains
```json
{
"type": "service_account"
}
```
3. based on number of files found:
- `> 1` - display a chooser
- `= 1` - ask for confirmation
- `< 1` - fallback to prompt
Unit tests, manual tests.
=> [eas submit][android] Autodetect google-services JSON key path

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-json/package.json, yarn.lock
It's best practice to upgrade deps regularly.
- I upgraded TS to the latest (4.3.5)
- I removed unused dependencies.
CI
=> upgrade typescript + clean up deps

CHANGELOG.md, packages/eas-cli/src/credentials/android/actions/CreateKeystore.ts, packages/eas-cli/src/credentials/android/actions/__tests__/CreateKeystore-test.ts
Users who wanted to upload their keystores found that a new one was generated instead
return the uploaded keystore
=> [eas-cli] fix keystore upload bug

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/metadata.ts, packages/eas-json/package.json, yarn.lock
validate metadata before sending build request
run build with buildNumber set to a number(it failed with an `ValidationError: "appBuildVersion" must be a string` error)
run correct build (it succeeded)
=> [eas-cli] validate metadata in build request

CHANGELOG.md, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/ios/__tests__/version-test.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/version.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/utils/template.ts, packages/eas-cli/src/credentials/ios/types.ts, packages/eas-cli/src/project/ios/target.ts
https://linear.app/expo/issue/ENG-1570/evaluate-interpolated-version-strings-for-metadata
It's common to have versions refer to $(SOME_VALUE) on iOS. We should evaluate these when populating metadata.
- I read build settings from pbxproj - these are the vars used to evaluate the templates.
- I made evaluated version strings in `readShortVersionAsync` and `readBuildNumberAsync`.
- Tested manually with a project with 
```
<key>CFBundleVersion</key>
<string>$(CURRENT_PROJECT_VERSION)</string>
```
in Info.plist. The version has been resolved properly.
- Added unit test.
=> [ENG-1570] evaluate interpolated iOS version strings

CHANGELOG.md, packages/eas-json/src/EasJsonSchema.ts
The new build profile format is missing the `simulator` key in JSON schema validation. Fixes #545
Ran the new format in development, realized it's broken, and fixed it.
`eas build --profile development` should not throw an error when `simulator: true` is present in the build profile.
=> [eas-json][eas-cli] add simulator key to build profile json validator

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
storageBucket is determined server side, and has been for a while.
Note: Landing/publishing should happen after this PR: https://github.com/expo/universe/pull/7970
removed storageBucket, updated tests and types.
yarn test
tested publish in demo repo.
=> [eas-cli] stop sending deprecated storageBucket field

CHANGELOG.md, packages/eas-cli/src/build/metadata.ts
Fixes https://forums.expo.dev/t/eas-build-fails-after-upload-ios/55210
I noticed that we were properly extracting the build settings in the metadata context, but that we weren't passing it into the version resolver as expected, so I fixed that.
I made a new project, went to Info.plist and changed the "Bundle version string (short)" to `$(MARKETING_VERSION)`:
Next, I set the version in the general tab for the target (this sets the `MARKETING_VERSION` build setting):
`eas build -p ios` will fail after uploading the project with this error: `ReferenceError: MARKETING_VERSION is not defined`
If you apply this patch, it will not fail and the version will be properly set on the build job (eg: https://expo.dev/accounts/notbrent/projects/attempt-repro/builds/02d01ceb-88ba-4b0e-9e63-59ca026732ea)
=> [eas-cli] Pass through build settings metadata context to app version resolver

CHANGELOG.md, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/commands/branch/view.ts
We want a flag to automatically set the branch name and update message to the git branch and commit message.
Also made command create a branch if it doesn't already exist.
Tested in demo repo.
=> [eas-cli] add --auto flag to publish

CHANGELOG.md, packages/eas-cli/src/submissions/BaseSubmitter.ts, packages/eas-cli/src/submissions/types.ts
Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.
Now that we have a submissions page on the site, we can direct users to see the status of their submissions (similar to what we do with the build command)
Logged out the url just before the submission status spinner begins - the formatting / copy was taken from the builds logs which is a very similar feature
Run a local submit and ensure that the link is correct:
=> [submit] log submissions link at end of eas-submit

CHANGELOG.md, packages/eas-cli/src/build/utils/url.ts
A user reported this issue:
Notice that where the slug should be, there is a string that would be a valid slug -- this is actually the project name.
We don't actually have `project.slug` available on `BuildFragment` so I shortened the URL and just linked to `/accounts/${owner}/builds/${build.id}` -- without including the project segment. This will redirect to the appropriate place. That said, we likely want to properly fix this as I'm unsure what the downsides are of using this specific path, cc @jonsamp.
Run a build and use a `name` that is different from `slug`, notice that it is used in the build details URL and  the link will be invalid. Run again with this PR, notice that the URL will work but won't include the project `name` or `slug`.
=> [eas-cli] Stop using project name in build details URL

CHANGELOG.md, packages/eas-cli/src/build/metadata.ts
simulator builds are marked as app store ones
run build
=> [eas-cli] fix metadata for simulator builds

CHANGELOG.md, packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts
When reviewing #555 I realised that `sku` is not being propagated to App Store Connect API when running `eas submit -p ios --sku=My_SKU_Here`
It was a matter of propagating the `--sku` command flag value down to `App.createAsync()`.
`console.log` based debugging 😉
=> [eas cli] Fix SKU not being applied to App Store Connect

packages/eas-cli/package.json, packages/eas-cli/src/analytics.ts, yarn.lock
We'd like to send events from the EAS CLI to other destinations besides Amplitude. RudderStack is introduced for this purpose, and to keep consistent with how analytics are implemented across the Expo platform.
- adds RudderStack to the analytics file
- updates analytics file to include proper write keys 
- adds some slight changes to how amplitude sent events previously to address an issue where some properties were not getting sent along with events
All analytics calls should now be sent to both Amplitude and RudderStack. This way we can compare volumes. If everything looks alright after some monitoring, I'll submit another PR to remove Amplitude.
I tested by locally running `eas build` and ensuring that events were sent to the proper destinations.
=> [eas-cli] Adds RudderStack

CHANGELOG.md, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/build/list.ts, packages/eas-cli/src/commands/build/view.ts, packages/eas-cli/src/utils/json.ts
https://linear.app/expo/issue/ENG-1602/add-json-flag-to-some-eas-cli-commands-to-output-results-as-json
- if json flag is specified override `process.stdout.write` with `process.stderr.write`
- when printing actual json result use original stdou write function
- for build require non-interactive flag because this approach does not work when prompts are showing up
- for now we print directly graphql objects, it still an open question whether we want to do that or display only curated list of values. cc @brentvatne 
run build build:list and build view with and without json flag
=> [eas-cli] support --json flag for build commands

CHANGELOG.md, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/submissions/android/AndroidSubmissionConfig.ts, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submissions/android/AndroidSubmitter.ts, packages/eas-cli/src/submissions/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submissions/types.ts, packages/eas-json/src/EasJsonSchema.ts, packages/eas-json/src/EasSubmit.types.ts
Closes #489
add an option to the cli and submit profile
run submit and console log www request
=> add `changesNotSentForReview` option to android submissions

CHANGELOG.md, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/validate.ts
add warnings around common issues
- warn if NODE_ENV=production is set
- warn if `googleServicesFile does exist but it's gitingored or not part of the repository
- provide a way to silence warning for googleServicesFile
run builds that trigger those warnings
=> [eas-cli] warn if NODE_ENV or googleServicesFile is missing

CHANGELOG.md, packages/eas-cli/graphql-codegen.yml, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/PublishMutation.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
If a user specifies platform specific runtimes, we want to automatically publish multiple groups, one for each runtime.
Updated graphQL to take an array here: https://github.com/expo/universe/pull/8036
The graphQL call is slightly more general than needed, for now we automatically create updateGroups based on the rtv's specified in the app.json.
Tested in a demo repo pointed at the a local server running: https://github.com/expo/universe/pull/8036
Double publish output (Note added a message emphasizing that two groups are created as in discussions we agreed that this maybe a bit surprising if we were not clear about it):
Confirmed that two update groups are created:
Single publish still works 
(added a `platforms` this PR as well):
Confirmed only 1 group created by single publish:
=> [eas-cli] add ability to double publish

CHANGELOG.md, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/utils/url.ts, packages/eas-cli/src/project/ensureProjectExists.ts, packages/eas-cli/src/utils/progress.ts
The main motivation here was to provide an FYI link in the "Upload" phase, so that users can learn more about what exactly is being uploaded. I was hesitant to add another log message specifically for archiving the project -- it's an additional line of output and I'm not sure it's needed. That said, if we start supporting alternative version control systems we may want to do this in order to be very explicit about what tool we're using to archive the project.
I extended `createProgressTracker` to support a `completedMessage` function (alternative to the string), which allowed me include a "Learn more" link. I played with three styles for this, as you can see below.
I opted for the last style because it adds least noise, and I think is relatively easy to read, while still maintaining …
=> [eas-cli] Improve build command output

CHANGELOG.md, packages/eas-cli/src/build/utils/printBuildInfo.ts, packages/eas-cli/src/devices/actions/create/registrationUrlMethod.ts, ts-declarations/qrcode-terminal/index.d.ts
We introduced a QR code to install internal distribution builds here: https://github.com/expo/eas-cli/pull/371
During standup yesterday, @ccheever raised an issue where the QR code is too big to fit in the terminal and also mentioned some difficulties to install the .apk directly: https://docs.google.com/presentation/d/1pKmuhzBjXiWatTwqrPTa2Dw0mqklNAkvoC7zIxVp47E/edit#slide=id.ge85bd431ff_1_37
This PR solves these two issues. Closes https://linear.app/expo/issue/ENG-1845/update-android-internal-distribution-qr-code and https://linear.app/expo/issue/ENG-1846/smaller-qr-codes
- Used `logsUrl` instead of `installUrl` for Android internal build to redirect to the build details page instead of S3
- Used `qrcode-terminal` small option: …
=> [eas-cli] update QR code url for Android internal distribution build and generate smaller QR code

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
- Related https://github.com/expo/expo-cli/pull/3798
- This should only change what happens when users encounter server errors (status 500-600) -- I couldn't repro so all of my testing was done via mock axios tests.
=> Bump apple-utils to v25

.eslintrc.js
Prevents runtime errors on released `eas-cli` caused by relative imports between packages, like https://github.com/expo/eas-cli/commit/951eea2396591bd612aa7cb3038da35e45c33bb8 
Added [`import/no-relative-packages`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-relative-packages.md) to `.eslintrc.js`
- Ran VSCode command: `ESLint: Restart ESLint Server` to make VS Code apply this rule.
- Locally reverted https://github.com/expo/eas-cli/commit/951eea2396591bd612aa7cb3038da35e45c33bb8 to see if it's working:
=> Add ESLint rule to prevent relative package imports

.github/workflows/release.yml, .github/workflows/size.yml, .github/workflows/test.yml, CHANGELOG.md, packages/eas-cli/package.json, packages/eas-json/package.json
- Node versions < 12 are not supported anymore - https://nodejs.org/en/about/releases/ 
- Expo CLI doesn't support Node < 12 -  https://github.com/expo/expo-cli/blob/master/packages/expo-cli/package.json#L42
- Needed for https://github.com/expo/eas-cli/issues/516
- I updated `engines.node` in `package.json`.
- I made the `test` workflow run on Node 16. I made the other workflows also run on Node 16.
CI
=> drop support for node < 12

CHANGELOG.md, packages/eas-cli/src/analytics.ts, packages/eas-cli/tsconfig.json
We've dropped support for Node < 12. We can now change the typescript target to newer.
I changed the target from `ES2017` to `ES2019`.
CI
=> bump typescript target to ES2019

CHANGELOG.md, jest/babel.config.js, jest/jest.config.js, package.json, packages/eas-cli/package.json, packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts, packages/eas-cli/src/credentials/__tests__/fixtures-android.ts, packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/android/utils/__tests__/printCredentials-test.ts, packages/eas-cli/src/credentials/credentialsJson/__tests__/update-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/CreatePushKey-test.ts, packages/eas-cli/src/project/__tests__/projectUtils-test.ts, packages/eas-cli/src/user/__mocks__/User.ts, packages/eas-cli/src/user/actions.ts, packages/eas-cli/src/vcs/index.ts, packages/eas-json/package.json, yarn.lock
To simplify the jest config and get rid of the babel dependencies.
I replaced `babel-jest` with `ts-jest` and fixed failing tests.
CI
=> Use `ts-jest` instead of `babel-jest`

CHANGELOG.md, packages/eas-cli/src/build/validate.ts, packages/eas-cli/src/vcs/vcs.ts
Closes #577 
- check if path points inside directory first
- pass normalized path (remove leading `./` with path.relative)
run builds with and without EAS_NO_VCS and with services  file gitignored and outside of the repo
=> [eas-cli] fix detecting  `googleServicesFile` with `EAS_NO_VCS=1`

CHANGELOG.md, packages/eas-cli/src/vcs/git.ts
detect if there are filename differences when `core.ignorecase` is enabled.
Not sure if this should be a warning or an error cc @brentvatne 
- set core.ignorecase' false
- check status
- restore old state
- above changes are only applied on macos, I assume that someone using Linux or windows had to set this value explicitly and if they did then they should know what they are doing
- affected files are displayed using `git status --short`
run build with file renamed
=> [eas-cli] detect case inconsistencies on macos

.eslintrc.js, package.json, packages/eas-cli/package.json, packages/eas-json/package.json, packages/eas-json/tsconfig.json, yarn.lock
- `yarn install` produces a lot of warnings
- Developers can use different node/yarn versions when working on the CLI. This could lead to hard to debug issues.
- I moved `eslint-plugin-graphql` from the root package.json to the eas-cli specific one.
- I installed `@babel/core` and `typescript` as dev deps.
- I configured volta to use `node@16.8.0` and `yarn@1.22.11`.
- I fixed one minor lint warning and configured `yarn lint` to lint .js files as well.
- I bumped typescript target in `eas-json` to `es2019` as I forgot to do that in https://github.com/expo/eas-cli/commit/4cb726f3740c95b2db3e6115528ac895060ff93d
`yarn install`
Before:
<details>
```
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning …
```
=> clean up repo deps + use volta

packages/eas-cli/src/build/utils/analytics.ts, packages/eas-cli/src/commands/credentials.ts, packages/eas-cli/src/credentials/android/actions/CreateKeystore.ts, packages/eas-cli/src/credentials/android/actions/__tests__/CreateKeystore-test.ts, packages/eas-cli/src/credentials/android/actions/__tests__/SetupBuildCredentials-test.ts, packages/eas-cli/src/credentials/android/utils/__mocks__/keystore.ts, packages/eas-cli/src/credentials/android/utils/keystore.ts
We'd like to understand what percentage of users are blocked from creating credentials because they do not have `keytool` installed.
Adds a new event, `ANDROID_KEYSTORE_CREATE`, containing a property called`step` which can be either `fail`, `success`, or `attempt`. We can construct the funnel of create attempts => falures using this schema. I also converted the `credentials` command to an `EASCommand` so that it can fire `action` events on start.
I had to mock some things out in `CreateKeystore-test` & `SetupBuildCredentials-test` to account for getting the project id inside the create keystore action.
I ran this locally and confirmed events were making it to the backend.
=> [eas-cli] Adds keystore create tracking

CHANGELOG.md, packages/eas-cli/src/vcs/git.ts
When `git config --get core.ignorecase` is run and the variable is not currently set, it will return with an exit code of 1 thus causing the `eas build` command to fail.
This also appears to have happened in the wild for others [1](https://forums.expo.dev/t/eas-build-platform-ios-issue-git-exited-with-non-zero-code-128/53612/5).
To solve this, we try/catch and then return undefined to allow for the default behavior.
Prior to finding this, I added the variable and ensure that `eas build` ran normally.  I then removed the variable and `eas build` failed.  After adding this change and running my patched version `eas build` operated properly.
=> fix: git config --get core.ignorecase exits with code 1

package.json, yarn.lock
fixes error
```
An unexpected error occurred: "expected workspace package to exist for \"@babel/core\"
```
where running yarn add in eas-cli
=> remove `@babel/core` dependency

CHANGELOG.md, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/configure.ts, packages/eas-cli/src/build/constants.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/build/utils/credentials.ts, packages/eas-cli/src/commands/build/configure.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/build/list.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/platform.ts, packages/eas-cli/src/project/metroConfig.ts, packages/eas-cli/src/submissions/BaseSubmitter.ts, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submissions/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submissions/commons.ts, packages/eas-cli/src/submissions/context.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts, packages/eas-cli/src/submissions/ios/IosSubmitCommand.ts, packages/eas-cli/src/submissions/ios/IosSubmitter.ts, packages/eas-cli/src/submissions/ios/__tests__/IosSubmitCommand-test.ts, packages/eas-cli/src/submissions/utils/summary.ts
Another part of https://linear.app/expo/issue/ENG-755/submitting-automatically-on-build-success. It's probably the last part before we can start working on the actual feature in the CLI. (Maybe I'll implement the `--non-interactive` flag first.)
It's currently possible to submit to only one platform at a time. This PR implements the support for `--platform all` - similarly to what we have for `eas build`.
I implemented the support for the `--platform all` parameter.
=> [ENG-755] eas submit - implement --platform all

CHANGELOG.md, packages/eas-cli/src/build/validate.ts
https://forums.expo.dev/t/googleservicesfile-is-not-checked-in-to-your-repository/56336/6
normalize path (C:/path/to/repo -> C:\path\to\repo)
tested on windows
=> [eas-cli] fix google service detection on windows

CHANGELOG.md, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/credentials/android/actions/__tests__/CreateKeystore-test.ts, packages/eas-cli/src/credentials/android/actions/__tests__/SetupBuildCredentials-test.ts, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submissions/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submissions/commons.ts, packages/eas-cli/src/submissions/context.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts, packages/eas-cli/src/submissions/ios/IosSubmitCommand.ts, packages/eas-cli/src/submissions/ios/__tests__/IosSubmitCommand-test.ts
`eas submit` should fail with an error if it has been run with the `--non-interactive` flag but a user interaction is required (prompt).
- I made `eas sumit` fail if the user didn't provide all necessary data with eas.json and env vars, and ran the submit with `--non-interactive`. 
- I refactored resolving iOS asc app identifier and apple id.
- Added basic unit tests.
- Tested manually.
=> [ENG-755] add --non-interactive flag for `eas submit`

CHANGELOG.md, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-cli/src/graphql/types/AppPlatform.ts, packages/eas-cli/src/project/ensureProjectExists.ts, packages/eas-cli/src/submissions/ArchiveSource.ts, packages/eas-cli/src/submissions/__tests__/ArchiveSource-test.ts, packages/eas-cli/src/submissions/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submissions/submit.ts, packages/eas-cli/src/submissions/utils/builds.ts, packages/eas-cli/src/submissions/utils/logs.ts
This is the last part for https://linear.app/expo/issue/ENG-755/submitting-automatically-on-build-success
The PR adds `--submit` and `--submit-with-profile` params to `eas build` that allow for submitting automatically on build complete.
- All parts were already almost in place. I basically copy-pasted some code from `eas submit`.
- I added two CLI params to `eas build`:
- `--submit` - creates a submission that's waiting for the build to complete. The CLI can be killed (CTRL+C) as soon as the submission has been created. The user doesn't need to wait for the build to complete. When this flag is supplied, the submit profile with the same name as the build profile is picked up.
- `--submit-with-profile` - works the same as `--submit` but allows for using another submit profile.
- Currently, …
=> [ENG-755] implement auto-submits

CHANGELOG.md, packages/eas-json/package.json, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/EasSubmit.types.ts, packages/eas-json/src/__tests__/EasJsonReader-submit-test.ts, ts-declarations/env-string/index.d.ts, yarn.lock
Closes https://github.com/expo/eas-cli/issues/601
I made it possible to use env var in `android.serviceAccountKeyPath` (eas.json)
Added unit test.
=> [eas-json] allow env vars in android.serviceAccountKeyPath

CHANGELOG.md, packages/eas-cli/src/commands/secret/create.ts, packages/eas-cli/src/graphql/mutations/EnvironmentSecretMutation.ts, packages/eas-cli/src/graphql/queries/EnvironmentSecretsQuery.ts
We got a report that force-creation of secrets wasn't working. https://forums.expo.dev/t/cant-delete-or-force-update-a-secret/56640 
This report also included other mutation bugs.
- Supplied the correct parameter to a secrets lookup call
- Fixed mutation helpers (it was previously calling a query with a mutation string rather than a proper mutation).
The following reproduction plan should no longer result in errors:
```
eas secret:create --scope=account --name=WHATEVER --value=a_secret
eas secret:create --scope=account --name=WHATEVER --value=a_new_secret --force
eas secret:delete --id=<my-secret-id>
eas secret:create --scope=project --name=WHATEVER_PROJECT_SECRET --value=a_secret
```
=> [eas-cli] fix secrets mutations

CHANGELOG.md, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submissions/context.ts, packages/eas-cli/src/submissions/ios/AppProduce.ts
https://github.com/expo/eas-cli/pull/603#issuecomment-917251233
Use env vars from the build profile to resolve app config when running `eas build` with the `--auto-submit` flag.
=> use envs from build profile for resolving app config when auto-submiting

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/android/__tests__/version-test.ts, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/version.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/version.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/credentials/android/AndroidCredentialsProvider.ts, packages/eas-cli/src/credentials/android/actions/BuildCredentialsUtils.ts, packages/eas-cli/src/credentials/manager/ManageAndroid.ts, packages/eas-cli/src/project/android/__tests__/applicationId-test.ts, packages/eas-cli/src/project/android/__tests__/fixtures/build.gradle, packages/eas-cli/src/project/android/__tests__/fixtures/multiflavor-build.gradle, packages/eas-cli/src/project/android/__tests__/fixtures/multiflavor-with-dimensions-build.gradle, packages/eas-cli/src/project/android/__tests__/gradle-test.ts, packages/eas-cli/src/project/android/__tests__/gradleUtils-test.ts, packages/eas-cli/src/project/android/applicationId.ts, packages/eas-cli/src/project/android/gradle.ts, packages/eas-cli/src/project/android/gradleUtils.ts, packages/eas-cli/src/submissions/android/AndroidSubmitCommand.ts, ts-declarations/gradle-to-js/index.d.ts, yarn.lock
blocked by https://github.com/expo/expo-cli/pull/3830
applicationId and versions are read incorrectly if there are multiple flavors defined
this PR adds support for
- build command
- credentials command
- [moved gradle utils from expo-cli to eas-cli] https://github.com/expo/expo-cli/pull/3830
- if parsing fails fallback to old behavior for applicationId
fixed existing tests
tested by running builds and credentials manager on a test project
=> [eas-cli] support multiflavor android projects

CHANGELOG.md, packages/eas-cli/src/submissions/ArchiveSource.ts, packages/eas-cli/src/submissions/__tests__/ArchiveSource-test.ts, packages/eas-cli/src/submissions/commons.ts
https://linear.app/expo/issue/ENG-1347/improve-feedback-when-user-enters-incorrect-url-for-build-eas-submit
Detect if the user provided the build details page URL as the build artifact URL and ask if they know what they're doing. EAS CLI parses the URL and suggests submitting the build with the id from the URL.
Tested manually + unit test.
=> [ENG-1347] eas submit: suggest using build id instead of build details page

CHANGELOG.md, packages/eas-cli/src/commands/build/index.ts, packages/eas-json/package.json, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/migrate.ts
Fixes https://linear.app/expo/issue/ENG-1915/better-error-message-when-easjson-is-invalid-json
I used `@expo/json-file` to read eas.json. If the JSON is invalid it shows the line with the syntax error.
```
JsonFileError: Found invalid JSON in eas.json. Error parsing JSON: {
"build": {
"release": {
"android": {
"gradleCommand": "blahblah"
}
"env": {
"BLAH": "456"
}
}
},
"submit": {
"release": {
"android": {
"serviceAccountKeyPath": "$GOOGLE_SERVICE_ACCOUNT",
"track": "internal",
"releaseStatus": "draft"
},
"ios": {
}
}
}
}
├─ File: /Users/dsokal/work/expo/example-apps/teecee/eas.json
└─ Cause: SyntaxError: Unexpected string in JSON at position 101
5 |         "gradleCommand": "blahblah"
6 |       }
>  7 |       "env": {
|       ^
8 |         "BLAH": "456"
9 |       }
10 |     }
Code: …
```
=> [ENG-1915] show syntax errors in eas.json

CHANGELOG.md, packages/eas-cli/src/submissions/ArchiveSource.ts
Some users expect EAS Submit to recognize the Turtle v1 build ids.
Print a warning about Turtle v1 when couldn't find the build with the provided ID.
=> eas submit: warn about turtle v1 build ids

packages/eas-cli/src/log.ts, packages/eas-cli/src/submissions/ArchiveSource.ts, packages/eas-cli/src/submissions/__tests__/ArchiveSource-test.ts, packages/eas-cli/src/submissions/utils/builds.ts
Fixes https://github.com/expo/eas-cli/commit/b7ae91892cfc33606ac77f1d80c978a0efc9b56f made error about platform mismatch not displayed
- Move the platform mismatch handling outside helper function and got rid of it.
- Display original error message in debug mode
Updated tests
---
Platform mismatch:
<details>
<summary>`EXPO_DEBUG=1`:</summary>
</details>
=> [eas-cli] eas submit: Fix error message not displayed

packages/eas-cli/package.json, packages/eas-cli/src/analytics.ts, packages/eas-cli/src/commands/analytics.ts, packages/eas-cli/src/user/UserSettings.ts, yarn.lock
This is a follow up to #563 which removes amplitude (currently we're double tracking to ensure event volumes match). Everything's been looking good, so it seems as good a time as any to remove amplitude.
Deleted references to Amplitude, uninstalled packages.
As per comments in the previous PR, I renamed user settings with `amplitude` in the name to `analytics` and included some logic to check for both strings. Eventually, we can just check for the presence of `analytics...`
Ran `yarn test`, tried enabling/disabling analytics, made sure events made it to the backend when they should.
=> [eas-cli] Remove Amplitude

CHANGELOG.md, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/utils/devClient.ts, packages/eas-cli/src/build/utils/repository.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/diagnostics.ts, packages/eas-cli/src/log.ts, packages/eas-cli/src/project/publish.ts, packages/eas-cli/src/user/UserSettings.ts, packages/eas-cli/src/utils/expoCommand.ts
https://linear.app/expo/issue/ENG-1792/validate-that-project-includes-expo-dev-client-when-building-with
We want to validate that project includes `expo-dev-client` when building with `developmentClient` flag.
If `developmentClient` is set to `true` but `expo-dev-client` is not installed:
- [managed] offer to install the package with `expo install ...` and then commit the changes
- [bare] ask the user if they want to proceed, and print instructions on how to install `expo-dev-client` if they don't proceed
Managed project:
Bare project:
=> [ENG-1792] Validate that project includes expo-dev-client when building with developmentClient flag

CHANGELOG.md, packages/eas-cli/src/commandUtils/EasCommand.ts, packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts, packages/eas-cli/src/commands/account/login.ts, packages/eas-cli/src/user/actions.ts
Fixes https://github.com/expo/eas-cli/issues/625
Don't show prompt when ran a command with `--non-interactive` and not logged in, throw a meaningful error instead
=> print meaningful error message when not logged in in non-interactive mode

codecov.yml
We should start to care more about code coverage. This PR makes the codecov bot comment on the PR so the coverage is more visible to the developers.
=> add PR comment with code coverage

packages/eas-cli/src/ora.ts
Without this, the `ora.fail`, etc. methods won't change the message: https://github.com/expo/expo-cli/pull/3867/files
=> Forward ora props

CHANGELOG.md, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/submit/utils/wait.ts
https://exponent-internal.slack.com/archives/C02123T524U/p1632243270044100
Sometimes, the build command fails when waiting for the build to complete. Usually, it's because of a transient network error.
```
Build details: https://expo.io/...
Waiting for build to complete. You can press Ctrl+C to exit.
Error: Got unexpected null
```
Do not fail if a transient network error occurs.
=> do not fail in case of transient network errors

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/log.ts, packages/eas-cli/src/utils/progress.ts, yarn.lock
The green ticks style is not consistent. Reported by @EvanBacon on Slack.
Use `log-symbols` (`ora` is using it under the hood) to unify green ticks style.
=> use log-symbols to unify green ticks style

CHANGELOG.md, packages/eas-json/src/EasJson.types.ts, packages/eas-json/src/EasJsonReader.ts, packages/eas-json/src/__tests__/EasJsonReader-build-test.ts, packages/eas-json/src/__tests__/EasJsonReader-submit-test.ts
When running `eas build --auto-submit` in a fresh project, the CLI creates the `eas.json` for the user. The default configuration looks like this:
```
{
build: {
release: {},
development: {
developmentClient: true,
distribution: 'internal',
},
},
submit: {
release: {},
},
}
```
Note that the `release` submit profile doesn't have the `android` and `ios` empty objects. There's a bug so that the eas.json reader assumes the profile doesn't exist if an empty object for a platform does not exist.
Return the default profile if the platform-specific profile is not defined but the submit profile exists (`{ submit: { release: {} } }`)
Unit tests + tested manually.
=> fix auto-submitting in fresh project

CHANGELOG.md, packages/eas-cli/src/project/metroConfig.ts
Fixes https://github.com/expo/eas-cli/issues/643
Check if running in non-interactive mode and proceed even if the metro config seems invalid
=> fix experience with validating metro config in non-interactive mode

CHANGELOG.md, packages/eas-cli/src/credentials/manager/ManageAndroid.ts
Stop asking user for android build profile every time they choose an action. Instead, prompt the user once and then use the chosen profile for the rest of the actions.
=> [eas-cli] creds manager: stop prompting every iteration

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-json/package.json, yarn.lock
=> update eas-build-job adds xcode 13 support

.eslintrc.js, CHANGELOG.md, package.json, packages/eas-cli/__mocks__/fs.ts, packages/eas-cli/patch-readme.js, packages/eas-cli/src/build/android/__tests__/UpdatesModule-test.ts, packages/eas-cli/src/build/android/__tests__/version-test.ts, packages/eas-cli/src/build/ios/UpdatesModule.ts, packages/eas-cli/src/build/ios/__tests__/UpdatesModule-test.ts, packages/eas-cli/src/build/ios/__tests__/version-test.ts, packages/eas-cli/src/commands/branch/publish.ts, packages/eas-cli/src/credentials/ios/appstore/entitlements.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/android/__tests__/applicationId-test.ts, packages/eas-cli/src/project/android/__tests__/gradle-test.ts, packages/eas-cli/src/project/android/__tests__/gradleUtils-test.ts, packages/eas-cli/src/project/android/applicationId.ts, packages/eas-cli/src/project/ios/__tests__/bundleIdentifier-test.ts, packages/eas-cli/src/project/ios/__tests__/scheme-test.ts, packages/eas-cli/src/project/publish.ts, packages/eas-cli/src/vcs/local.ts, yarn.lock
It's good practice to always use async functions in node (vs. sync counterparts) if available. We sometimes use sync functions from `fs` and usually without a good reason.
- Add a eslint plugin with `node/no-sync` that disallows use of `...Sync` functions.
- Refactor code to use only async fs functions.
CI
=> make eslint disallow use of sync fs functions

CHANGELOG.md, packages/eas-cli/src/credentials/__tests__/fixtures-android.ts, packages/eas-cli/src/credentials/android/actions/UseExistingGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/actions/__tests__/UseExistingGoogleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/android/api/graphql/queries/GoogleServiceAccountKeyQuery.ts, packages/eas-cli/src/credentials/android/utils/__tests__/__snapshots__/printCredentials-test.ts.snap, packages/eas-cli/src/credentials/android/utils/printCredentials.ts, packages/eas-cli/src/credentials/manager/ManageAndroid.ts, packages/eas-cli/src/graphql/generated.ts
This PR:
- allows the user to assign an existing GoogleServiceAccountKey to their project on the www servers
- adds an action to assign an existing key in the credentials management workflow
It will also eventually be used in the submissions workflow.
=> [eas-cli] use existing google service account key

CHANGELOG.md, packages/eas-cli/src/credentials/android/utils/__tests__/__snapshots__/printCredentials-test.ts.snap, packages/eas-cli/src/credentials/android/utils/printCredentials.ts
Fix the way we print Android credentials, followup from https://github.com/expo/eas-cli/pull/649#discussion_r717252597
=> [eas-cli] fix android print formats

CHANGELOG.md, packages/eas-cli/src/credentials/__tests__/fixtures-android.ts, packages/eas-cli/src/credentials/android/actions/RemoveGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/actions/UseExistingGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/actions/__tests__/RemoveGoogleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/api/GraphqlClient.ts, packages/eas-cli/src/credentials/android/api/graphql/mutations/GoogleServiceAccountKeyMutation.ts, packages/eas-cli/src/credentials/android/utils/googleServiceAccountKey.ts, packages/eas-cli/src/credentials/manager/ManageAndroid.ts, packages/eas-cli/src/graphql/generated.ts
This PR:
- allows the user to remove a GoogleServiceAccountKey from their account
- adds this action to the credentials management workflow
=> [eas-cli] remove google service account key

CHANGELOG.md, packages/eas-cli/src/credentials/android/actions/SetupGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/actions/__tests__/SetupGoogleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/manager/ManageAndroid.ts
This PR:
- allows the user to setup a GoogleServiceAccountKey (either use existing or uploading a new one)
- adds an action to setup the key in the credentials management workflow
It will also eventually be used in the submissions workflow.
=> [eas-cli] setup google service account key

CHANGELOG.md, packages/eas-cli/src/credentials/android/actions/CreateGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/actions/__tests__/CreateGoogleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/actions/__tests__/SetupGoogleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/utils/__tests__/googleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/utils/googleServiceAccountKey.ts
The current logic in the Android submission service has some features that detect potential Google Service Jsons and suggest them to the user. I think this is a very good idea, so I've taken most of this logic, made minor adjustments to it, and put it in the credentials service. 
This logic is copied over instead of refactored because in a followup PR, I'm thinking the submissions logic [here](https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/submit/android/AndroidSubmitCommand.ts#L142) can be changed to something like this:
```
// path is explicitly passed in
if (serviceAccountKeyPath) {
return result({
sourceType: ServiceAccountSourceType.path,
path: serviceAccountKeyPath,
});
} 
// fallback to credentials service otherwise
if (keyIsSetupOnCredentialsService) {
return …
```
=> [eas-cli] use google service key detection in credentials service

CHANGELOG.md, packages/eas-cli/src/utils/json.ts
Fixes https://github.com/expo/eas-cli/issues/666
`--json` doesn't seem to work when running EAS CLI on GitHub Actions.
https://github.com/cheeaun/hackerweb-native-2/runs/3774224934?check_suite_focus=true
Use `.bind(...)` instead of `.call(null, ...)`.
Patched `json.js` and verified it works fine now - https://github.com/dsokal/eas-test/commit/ede28d1ac742fcd41f62c8b812c87afffd42e6da
=> fix --json flag when running on GitHub Actions

CHANGELOG.md, packages/eas-cli/src/credentials/android/actions/__tests__/CreateGoogleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/actions/__tests__/SetupGoogleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/credentials.ts, packages/eas-cli/src/credentials/android/utils/__tests__/googleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/utils/googleServiceAccountKey.ts, packages/eas-cli/src/submit/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submit/android/AndroidSubmitter.ts, packages/eas-cli/src/submit/android/ServiceAccountSource.ts, packages/eas-cli/src/submit/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submit/android/__tests__/ServiceAccountSource-test.ts, packages/eas-cli/src/submit/context.ts
**I haven't done any testing for this PR yet. I wanted to make sure this PR is on the right track  before I write the tests**
This PR integrates the credentials service into the Android submission workflow. Notable changes:
- If the user passes in the path argument when they run submissions, we use that and fall back to a prompt if there the path they passed was invalid. No credentials are saved on www in this case.
- If there is no path argument when submissions is run, we use the credentials service.
=> [eas-cli] integrated credentials service with android submissions

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/credentials/ios/api/graphql/queries/__mocks__/IosAppCredentialsQuery.ts, packages/eas-cli/src/credentials/ios/utils/__tests__/__snapshots__/printCredentials-test.ts.snap, packages/eas-cli/src/credentials/ios/utils/printCredentials.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/credentials/AppStoreConnectApiKey.ts, packages/eas-cli/src/graphql/types/credentials/IosAppCredentials.ts
Asc Api Key graphql types and printing support
=> [eas-cli] asc api key graphql type and print support

CHANGELOG.md, packages/eas-cli/src/build/utils/devClient.ts
Commit should not be required in default workflow, but the prompt shows up after installing dev client
check if commit required before triggering commit prompt
`expo init`
`eas build --profile development --platform android`
=> [eas-cli] check if commit is required after dev client install

CHANGELOG.md, packages/eas-cli/src/credentials/__tests__/fixtures-appstore.ts, packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/ios/actions/AscApiKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/CreateAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts, packages/eas-cli/src/credentials/ios/actions/PushKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/AscApiKeyUtils-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/CreateAscApiKey-test.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/AppStoreConnectApiKeyMutation.ts, packages/eas-cli/src/credentials/ios/appstore/AppStoreApi.ts, packages/eas-cli/src/credentials/ios/appstore/Credentials.types.ts, packages/eas-cli/src/credentials/ios/appstore/__tests__/ascApiKey-test.ts, packages/eas-cli/src/credentials/ios/appstore/ascApiKey.ts, packages/eas-cli/src/credentials/ios/credentials.ts, packages/eas-cli/src/credentials/ios/validators/validateAscApiKey.ts, packages/eas-cli/src/credentials/utils/promptForCredentials.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/submit/ios/AscApiKeySource.ts, packages/eas-cli/src/submit/ios/IosSubmitter.ts, packages/eas-cli/src/submit/ios/__tests__/AscApiKeySource-test.ts
This PR adds support for the following:
- Creating an Asc Api Key using baconlane and saving it to www
- Automatically getting Issuer ID if user is authenticated in the prompt case
- Validating Asc Api Keys
- Cleaning up some Apple quirks (their uuids aren't rfc compliant), char limits in their naming, api weirdness etc
=> [eas-cli] create + validate asc api key, infer issuer ids

packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/ios/actions/AssignAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/AssignAscApiKey-test.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/mutations/IosAppCredentialsMutation.ts, packages/eas-cli/src/credentials/manager/Actions.ts, packages/eas-cli/src/credentials/manager/IosActions.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/graphql/generated.ts
- Assign an Asc Api Key to a project for EAS Submissions
- Add the create and assign actions to the credentials manager
=> [eas-cli] assign asc api keys to project

CHANGELOG.md, packages/eas-cli/src/credentials/__tests__/fixtures-appstore.ts, packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/ios/actions/AscApiKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/RemoveAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/RemoveAscApiKey-test.ts, packages/eas-cli/src/credentials/ios/api/GraphqlClient.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppStoreConnectApiKeyQuery.ts, packages/eas-cli/src/credentials/manager/Actions.ts, packages/eas-cli/src/credentials/manager/IosActions.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/graphql/generated.ts
Add support for removal of Asc Api Keys in the credentials manager
=> [eas-cli] support removal of asc api keys

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
Same as in https://github.com/expo/expo-cli/issues/3949
Update @expo/apple-utils as @EvanBacon did in expo-cli
I believe, based on the original issue, you would need to sign in to an Apple account that triggers a 403 response. I'm not sure how to reproduce this.
=> [eas-cli] Bump @expo/apple-utils to better handle some error messages

packages/eas-cli/README.md, packages/eas-cli/src/commands/secret/delete.ts
`eas secrets` usage wasn't updated to `eas secret`.
Replaced instances with `eas:secret`.
=> Replace eas:secrets with eas:secret

CHANGELOG.md, packages/eas-cli/src/credentials/ios/actions/AscApiKeyUtils.ts, packages/eas-cli/src/credentials/utils/promptForCredentials.ts
followup from https://github.com/expo/eas-cli/pull/718#discussion_r740837814
=> [eas-cli] cleanup up creds prompt method

CHANGELOG.md, packages/eas-cli/src/build/utils/formatBuild.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/Build.ts, packages/eas-cli/src/submit/ArchiveSource.ts
Resolves #726 
- Took advantage of gql field `Actor.displayName` introduced in https://github.com/expo/universe/pull/8393
- Added `Authored by:` field to submission build choice prompt as requested in #726
- Replaced author name logic in `eas build:list` with the new gql field
- Updated graphql schema
---
=> [eas-cli] Use actor `displayName` when printing build info

CHANGELOG.md, packages/eas-cli/src/commands/build/index.ts
After selecting to opt-in into old vcs workflow commit prompt was very generic
- ask for a workflow
- (if old workflow) commit all changes if git state is not clean (with genric prompt)
- based on selected workflow modify eas.json
- (if old workflow) commit eas.json changes prompt specific to eas.json changes
run build on clean working dir
run build on dirty working dir
=> [eas-cli] improve vcs migration experience

CHANGELOG.md, packages/eas-cli/src/submit/utils/errors.ts
Resolves #725 
- Handled that error on submission worker: https://github.com/expo/turtle-v2/pull/708
- Added user-friendly message to the CLI (this PR)
> Note: This PR doesn't have to wait for merging the turtle one
None, it's kinda 🐒 job
=> [eas-cli] Handle Apple servers maintenance in `eas submit`

CHANGELOG.md, packages/eas-cli/graphql-codegen.yml, packages/eas-cli/src/__tests__/api-test.ts, packages/eas-cli/src/api.ts, packages/eas-cli/src/build/utils/url.ts, packages/eas-cli/src/graphql/client.ts
Checklist
---
Why
---
To match the API server domain the website uses, this commit switches the API domain for EAS CLI from exp.host to api.expo.dev.
How
---
URL paths for api.expo.dev are different than those for exp.host.
* GraphQL: api.expo.dev/graphql
* API v2: api.expo.dev/v2/...
Updated the main functions that return the API server origin and the API v2 and GraphQL clients that create the URLs for each type of API.
Test Plan
---------
Looked at the places `getExpoApiBaseUrl()` is called and made sure the call sites were updated. Searched for `--/` and `/--` to find likely exp.host code to update.
* Unit tests: `yarn test`
* Log in and out: `yarn eas login`, `yarn eas logout` (tests API v2)
* Project management: `yarn eas project:view` (tests GraphQL) -> confirm project gets created …
=> [api] Change API domain for EAS CLI

packages/eas-cli/src/__tests__/api-test.ts, packages/eas-cli/src/api.ts, packages/eas-cli/src/build/utils/url.ts, packages/eas-cli/src/graphql/client.ts
Follow-up to https://github.com/expo/eas-cli/pull/744. I didn't notice it before but that PR broke development with the local www server.
Use different API URL when `EXPO_LOCAL` is set.
`EXPO_LOCAL eas whoami` works now.
=> fix working with local api server

CHANGELOG.md, packages/eas-cli/src/commands/build/index.ts
Fixes https://github.com/expo/eas-cli/issues/731
When auto-submitting, check if `--auto-submit-with-profile` was passed.
=> fix --auto-submit-with-profile

CHANGELOG.md, packages/eas-cli/src/submit/ios/AppSpecificPasswordSource.ts, packages/eas-cli/src/submit/ios/CredentialsServiceSource.ts, packages/eas-cli/src/submit/ios/IosSubmitCommand.ts, packages/eas-cli/src/submit/ios/IosSubmitter.ts, packages/eas-cli/src/submit/ios/__tests__/CredentialsServiceSource-test.ts
Only prompt for Apple Id Username (ie) `quin@expo.io` if we are authenticating via App Specific Password. We don't need this information if we are using ASC Api Keys.
=> [eas-cli] only prompt for appleIdUsername if authenticating via asp

CHANGELOG.md, packages/eas-cli/src/__tests__/api-test.ts, packages/eas-cli/src/api.ts, packages/eas-cli/src/build/utils/url.ts, packages/eas-cli/src/graphql/client.ts
Why
---
Make local development behave more closely to production and use the same API route paths. I made 127.0.0.1 behave the same way as api.expo.test and localhost. Another fix would have been to change 127.0.0.1 to localhost in EAS CLI, but it's a good idea to make the API server treat localhost and 127.0.0.1 similarly (look up PR 8542).
How
---
This reverts commit 5ba3cc66237d8ca8984d1fbd1efff65097f5feaf.
Test Plan
---------
Started the API server locally, then started EAS CLI locally with `EXPO_LOCAL=1 yarn eas login`. Logged in with my staging credentials and saw the API server locally print out that it had made new database connections in the log.
=> Revert "fix working with local api server (#747)"

CHANGELOG.md, packages/eas-cli/src/build/ios/credentials.ts, packages/eas-cli/src/credentials/ios/appstore/entitlements.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts
https://github.com/expo/eas-cli/issues/528#issuecomment-962002509
when entitlements were resolved app.conifg.js did not have env variables set, 
pass env in eas build and eas credentials
throw error in app.config.js when env is not set, set that value in eas.json, make sure it won't throw were running build
=> [eas-cli] pass envs to prebuild config when resolving entitlements

CHANGELOG.md, packages/eas-cli/src/credentials/android/actions/RemoveFcm.ts, packages/eas-cli/src/credentials/android/actions/__tests__/RemoveFcm-test.ts, packages/eas-cli/src/credentials/ios/actions/AscApiKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/AssignAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/CreateAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/RemoveAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/SetUpAscApiKey.ts, packages/eas-cli/src/credentials/ios/actions/SetUpSubmissionCredentials.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/AssignAscApiKey-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/CreateAscApiKey-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/RemoveAscApiKey-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/SetUpAscApiKey-test.ts, packages/eas-cli/src/credentials/ios/appstore/ascApiKey.ts, packages/eas-cli/src/credentials/ios/credentials.ts, packages/eas-cli/src/credentials/ios/utils/__tests__/__snapshots__/printCredentials-test.ts.snap, packages/eas-cli/src/credentials/ios/utils/printCredentials.ts, packages/eas-cli/src/credentials/manager/AndroidActions.ts, packages/eas-cli/src/credentials/manager/IosActions.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/submit/ios/CredentialsServiceSource.ts, packages/eas-cli/src/submit/ios/IosSubmitter.ts, packages/eas-cli/src/submit/ios/__tests__/AscApiKeySource-test.ts, packages/eas-cli/src/submit/ios/__tests__/CredentialsServiceSource-test.ts
GA nits: When shown to the user, we should display `API`. Whereas as part of variable naming, we should use `Api`.
=> [eas-cli] Api -> API

CHANGELOG.md, packages/eas-cli/src/analytics/common.ts, packages/eas-cli/src/analytics/events.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/submit/BaseSubmitter.ts, packages/eas-cli/src/submit/android/AndroidSubmitter.ts, packages/eas-cli/src/submit/ios/IosSubmitter.ts, packages/eas-cli/src/submit/submit.ts
Adding `attempt` events to the build and submit command, based on discussion here: https://github.com/expo/eas-cli/pull/752#discussion_r747120167
=> [eas-cli] add analytic attempt events

CHANGELOG.md, packages/eas-cli/src/credentials/android/utils/keystore.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/KeystoreGenerationUrlMutation.ts
We built a keystore service so ppl don't need to install Java to generate keystores.
Use keystore service if:
- keytool is not installed
- keytool failed to generate keystore
=> use keytool service

.github/workflows/changelog.yml, .github/workflows/release.yml, .github/workflows/size.yml, .github/workflows/test.yml
`v2` release has been published a while ago (https://github.com/actions/setup-node/releases/tag/v2.1.4) and it work flawless in other Expo repositories and it is an officially recommended version to use, so let's update the action also in here.
This PR updates all of the `setup-node` action occurrences in the workflows to the `v2` release.
Run CI?
=> [workflows] update `setup-node` action to `v2`

packages/eas-cli/src/build/ios/UpdatesModule.ts, packages/eas-cli/src/build/ios/__tests__/version-test.ts, packages/eas-cli/src/build/ios/version.ts, packages/eas-cli/src/credentials/ios/appstore/entitlements.ts, packages/eas-cli/src/utils/plist.ts
Fixes https://github.com/expo/eas-cli/issues/519
Add the plist path to the error message when parsing failed.
=> show plist path when parsing failed

CHANGELOG.md, packages/eas-cli/src/build/utils/repository.ts, packages/eas-cli/src/vcs/clients/git.ts, packages/eas-cli/src/vcs/vcs.ts
According to @wkozyra95, `git commit` can fail if `user.name` and/or `user.email` are not set (I couldn't repro this though). 
- Check if Git `user.name` and `user.email` are configured before committing. Prompt for the values if they are not configured.
- Print stdout and stderr when `git commit` fails.
=> interactively configure git user.name and user.email

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/build/metadata.ts, yarn.lock
`eas build` throws a validation error when we use a runtime version policy.
Apply the config plugin to compute the policy.
Upgraded `@expo/config`, `@expo/config-plugins`, and `@expo/prebuild-config` to get the correct typing for the runtime version plugins. Checked there were no breaking changes.
tested in a demo repo with `runtimeVersion: {"policy":"nativeVersion"}`
=> [eas-cli] compute the runtime version for a build's  metadata

packages/eas-cli/package.json, yarn.lock
There was a [bug](https://github.com/expo/rudder-sdk-node/pull/30) where flushing an empty queue would clobber some flush state. This caused subsequent flushes to return an outdated nullResponse.
Bumped the client to the newest version which contains a fix.
Triggered some local builds, confirmed events were being sent.
=> [eas-cli] bump rudder node sdk

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/webhook/create.ts, packages/eas-cli/src/commands/webhook/list.ts, packages/eas-cli/src/commands/webhook/update.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/webhooks/input.ts
Merge after https://github.com/expo/universe/pull/8627 is deployed.
People want to define webhooks that would be called when a submission finishes/fails/cancels.
Add a new type of webhooks.
Tested manually:
- I stated a webhook server.
- I created a submit webhook.
- I ran `eas submit -p android`.
- I observed that the webhook was called after the submission finished.
=> implement submit webhooks

CHANGELOG.md, packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/createContext.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/validate.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/submit/android/AndroidSubmitCommand.ts, packages/eas-cli/src/submit/context.ts, packages/eas-cli/src/submit/ios/IosSubmitCommand.ts
Pass applicationId/bundleIdentifier from build process to submit when aoutosubmit.
- value from build take precedence over values defined in submit profile in eas.json
- extend build context with platform-specific values
Run build with autosubmit (make sure that value passed  from build is used)
=> [eas-cli] pass identifier from build to submit

CHANGELOG.md, packages/eas-cli/src/build/ios/version.ts
Reported by @brentvatne 
Project: https://github.com/brentvatne/runverter-cloud
`evaluateTemplateString` didn't always receive the correct type of the `vars` argument. 
It was sometimes a plain object (it has `.hasOwnProperty`) and sometimes an object with null prototype (without `.hasOwnProperty`).
Solution: convert the argument to plain object.
Tested with https://github.com/brentvatne/runverter-cloud
=> fix evaluating template strings from info.plist

packages/eas-cli/src/commands/branch/publish.ts
Prevent users from publishing without having configured their updates URL. 
This will prevent frustrating foot guns.
Check app.json and throw if incorrectly configured.
Note: the question of how to keep the url in app.json and native config files is already managed here: https://github.com/expo/expo-cli/blob/master/packages/config-plugins/src/android/Updates.ts#L199
Tested in demo repo
=> [eas-cli] check EAS Update URL is correctly configured before publish

packages/eas-cli/package.json, yarn.lock
Fix missing missing `@expo/sdk-runtime-versions` dependency
=> [eas-cli] add missing @expo/sdk-runtime-versions dependency

CHANGELOG.md, packages/eas-cli/src/submit/ios/AppProduce.ts
if submit profile does not have ascAppId specified and  there is multiple bundleIdentifier in the project, submit fails even if bundleIdentifier is specified in submit profile 
TODO
=> [eas-cli] pass bundle identifier when resolving asc app id

CHANGELOG.md, packages/eas-cli/src/commands/update/configure.ts
We should set the runtime version to the sdkVersion policy when configuring EAS Update.
Only update if a runtimeVersion hasn't been set.
tested in demo repo.
=> [eas-cli] set runtime version in eas update:configure

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
`@expo/sdk-runtime-versions` is not used by directly. It should be imported by @expo/config-plugins.
`@expo/sdk-runtime-versions` is necessary to parse the `sdkVersion` runtime policy.
Added @expo/sdk-runtime-versions to @expo/config-plugins here: https://github.com/expo/expo-cli/blob/main/CHANGELOG.md#-bug-fixes-1
bumped @expo/config-plugins and confirmed there are no breaking changes.
Tested publish now works in demo repo with `runtimeVersion: { policy: "sdkVersion"}`
=> [eas-cli] bump config-plugins to 4.0.11

packages/eas-cli/src/commands/build/configure.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/credentials/ios/actions/AscApiKeyUtils.ts, packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts, packages/eas-cli/src/submit/utils/wait.ts
`eas submit -p ios` uploads apps to App Store Connect. It seems it sounds scary to some people when they see that EAS CLI states the app was uploaded to App Store.
Be more explicit about where the app gets uploaded.
None
=> make iOS submission message less scary: App Store -> App Store Connect

CHANGELOG.md, packages/eas-cli/src/project/ios/target.ts
2nd part of the fix for https://github.com/expo/eas-cli/issues/795 (1st part: https://github.com/expo/expo-cli/pull/4048)
When resolving targets, we don't read the dependencies of a target dependency.
Recursively read target dependencies.
Followed the repro steps from the issue - https://github.com/expo/eas-cli/issues/795#issue-1063807227
The app was built fine on EAS Build.
=> fix setting up credentials for projects with Apple Watch companion apps

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, packages/eas-cli/src/commands/diagnostics.ts
When looking into issues, it's helpful to know what's the project workflow.
- Print project workflow in `eas diagnostics`.
- Update issue template to require users to provide project workflow (to catch issues when they think they're using different workflow than they are).
=> print project workflow in `eas diagnostics` + update bug report template - add manged/bare input

packages/eas-cli/src/build/createContext.ts, packages/eas-cli/src/submit/context.ts
We'd like to anonymize analytics events to hit GDPR regulations by removing account names. e.g. https://www.notion.so/expo/PII-Audit-6bde8ab95e2640a7a330441b3677e8ab#34c4e2eafa8446cf8a5e0915311bb9da
I'll follow this PR up with a PR to remove or scrub the `reason` property from `_fail` events.
Removed account_name from tracking_context at each callsite.
Fired a few events locally, confirmed they did not contain account name.
=> [eas-cli] removes account name from analytics events

CHANGELOG.md, packages/eas-cli/src/build/createContext.ts, packages/eas-cli/src/commands/credentials.ts, packages/eas-cli/src/credentials/context.ts, packages/eas-cli/src/credentials/manager/ManageAndroid.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/credentials/manager/SelectBuildProfileFromEasJson.ts, packages/eas-cli/src/credentials/manager/SelectPlatform.ts
Fixes https://github.com/expo/eas-cli/issues/820
Pass the `env` properties defined in an `eas.json` buildProfile into the expo config. In order to do this, I've needed to create the `buildProfile` before the `CredentialsContext`.
=> [eas-cli] pass build profile env to credentials ctx

CHANGELOG.md, packages/eas-json/package.json, packages/eas-json/src/__tests__/reader-build-test.ts, packages/eas-json/src/build/schema.ts
Fixes https://github.com/expo/eas-cli/issues/558#issuecomment-989162199
We use a custom regex for version validation in eas.json. The regex does not allow alpha versions.
Use `semver.valid` for version validation.
Tests
=> [eas-json] use semver for version validation

CHANGELOG.md, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/project/expoSdk.ts
Fixes https://linear.app/expo/issue/ENG-2279/loudly-warn-when-attempting-to-use-eas-cli-on-managed-sdk-41-project
Projects with SDK < 41 are not supported.
Ask the user if they want to proceed if EAS CLI detects the project is using SDK < 41. Print warning and proceed in non-interactive mode.
_Screenshots were made when I had a typo in the message. I changed 42 -> 41_
Unsupported SDK:
Supported SDK:
=> [ENG-2279] warn when attempting to use EAS CLI on managed SDK < 41 project

CHANGELOG.md, packages/eas-cli/src/prompts.ts, packages/eas-cli/src/utils/__tests__/profiles-test.ts, packages/eas-cli/src/utils/profiles.ts, packages/eas-json/src/__tests__/reader-submit-test.ts, packages/eas-json/src/reader.ts, packages/eas-json/src/submit/resolver.ts
Fixes https://linear.app/expo/issue/ENG-2052/prompt-user-to-pick-profile-if-release-doesnt-exist
Ask the user to pick the profile if `release` does not exist.
Tests + tested manually
=> [ENG-2052] ask user to select profile if release does not exist

packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/createContext.ts, packages/eas-cli/src/build/local.ts, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/build/inspect.ts
Provide a way for users to debug their builds locally
- add new `buidl:inspect` command
- `--stage upload` is implemented using vcs client that would be used for a build
- `--stage prepare` runs local build, but aborts it just before gradle/fastlane call
- `--stage postbuild` runs full local build, the only difference to `build --local` is that artifact is not copied into current directory
- `--verbose` option will show the same logs as `build --local`, by default no logs are shown
prepare and post build can fail, but project will still be copied to the output directory
=> [eas-cli] add build inspect command

CHANGELOG.md, packages/eas-cli/src/submit/ios/IosSubmitCommand.ts
When testing my answer https://github.com/expo/eas-cli/issues/824#issuecomment-991584905 I discovered that a prompt is displayed in non-interactive mode, when user passed _some, but not all_ ASC API credentials in `eas.json`
Instead of failing right away, I've decided to skip the `eas.json` resolution with a warning, so the CLI can try to resolve them from EAS servers.
=> [eas-cli] Fix ASC prompt displayed in --non-interactive

packages/eas-cli/src/build/utils/devClient.ts, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/project/publish.ts, packages/eas-cli/src/utils/expoCli.ts
Currently there is too much logging when using `eas update`. We want to supply the user only with information they need.
Added a silent option to `expoCommand` and added an ora spinner.
demo repo
=> [eas-cli] clean up eas update logs

CHANGELOG.md, packages/eas-cli/src/commandUtils/EasCommand.ts, packages/eas-cli/src/commands/account/login.ts, packages/eas-cli/src/commands/account/logout.ts, packages/eas-cli/src/commands/account/view.ts
We want to be able to run commands like `eas whoami` and `eas login` outside of a project.
Currently, this throws an error when running `applyCliConfigAsync`: https://github.com/expo/eas-cli/blame/487316370b5028d0aef78303e68d05a7ce3bdbcc/packages/eas-cli/src/commandUtils/EasCommand.ts#L30
This was added to allow a "commit free" workflow here: 
https://github.com/expo/eas-cli/pull/695
Since a command run outside of a project should not be connected to anything requiring (or opting out of requiring) a git commit, we should only run this when inside of a project.
tested in a demo repo and out side of a project.
=> [eas-cli] allow eas-cli to be run outside of expo projects

.github/workflows/release.yml, package.json, packages/eas-cli/package.json, packages/eas-cli/scripts/pretarball-ci.sh
When working on https://github.com/expo/eas-cli/pull/858 I didn't realize that we forked the old oclif dev cli because there is a problem with installing dependencies from the monorepo workspaces.
This made the release fail - https://github.com/expo/eas-cli/runs/4593517219?check_suite_focus=true
Instead of forking the oclif cli, explicitly run a script that does the same job.
I ran `yarn pretarball-ci` and then `yarn oclif pack:tarballs --no-xz --targets darwin-x64` and it worked fine.
=> fix release process

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
`@oclif/plugin-help` is missing in EAS CLI production dependencies. It worked locally because it's a dependency of a dev dependency (`oclif`).
=> install missing @oclif/plugin-help

packages/eas-cli/src/commands/update/configure.ts
The current output is:
It looks like you are using a dynamic configuration! Learn more: https://docs.expo.dev/workflow/configuration/#dynamic-configuration-with-appconfigjs)
In order to finish configuring your project for EAS Update, you are going to need manually add the following to your app.config.js:
Learn more: https://expo.fyi/eas-update-config.md
```json
{
updates": {
"url": "https://u.expo.dev/"
},
"runtimeVersion": {
"policy": "sdkVersion"
}
}
```
=> [eas-cli] fixed wrong JSON output

CHANGELOG.md, packages/eas-cli/src/build/local.ts, packages/eas-cli/src/commands/build/index.ts
Add `--output` option for local builds
run local build
=> [eas-cli] Add --output flag to build command

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts, yarn.lock
- https://github.com/expo/third-party/pull/70
- Bump apple-utils to 27
- Check for agreements when the error message says 'agree'
New error results:
```
✖ Failed to register bundle identifier com.bacon.yolo76
Messages from App Store Connect:
› Apple Developer Program License Agreement Updated
The updated Apple Developer Program License Agreement needs to be reviewed. In order to update your existing apps and submit new apps to the App Store, the Account Holder must review and accept the updated agreement by signing in to their account
(https://developer.apple.com/account) on the Apple Developer website.
Error: App Store Connect has agreement updates that must be resolved
```
`eas build -p ios` in a new project.
=> Bump @expo/apple-utils@0.0.0-alpha.27

CHANGELOG.md, packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/branch/view.ts, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/commands/update/list.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/UpdateQuery.ts
[We want to be able to list all of the projects updates](https://linear.app/expo/issue/ENG-2700/create-an-eas-updatelist-command)
When run with the `--all` flag show every update group owned by the project.
When run with the `--branch` flag show ever update group owned by the branch.
When run with no flag, ask the user to specify the branch name. If the project is a git repo, suggest the current git branch.
Demo repo
=> [eas-cli] add update:list alias

CHANGELOG.md, packages/eas-cli/src/vcs/local.ts
When there is a symlink on macos to the parent directory that contains .gitingore `fast-glob` is entering in cycle crashing after some time
do not follow symlinks when searching for .gitignore files
created symlink to the root of the repo and run build:inspect -s archive
=> [eas-cli] do not follow symlinks with fast-glob

CHANGELOG.md, packages/eas-cli/src/commands/build/configure.ts
In #888 we refactored the `build:configure` command and as a result of that change we ended up attempting to configure native iOS and Android projects for expo-updates even if they don't exist because the project is managed. It's possible to repro this with:
```
expo init project # blank app
cd project && expo install expo-updates
eas build:configure
``` 
I used the same logic that we use in `syncProjectConfiguration` to detect if we are in a generic project or not, then skip running updates configuration in managed projects:
https://github.com/expo/eas-cli/blob/dd2303dbb2b01dcd941591b5ccba01bbd04b29a7/packages/eas-cli/src/build/ios/syncProjectConfiguration.ts#L26-L29
- Run `easd build:configure` in managed app with `expo-updates` installed, it should just create **eas.json** and nothing …
=> [eas-cli] Only configure updates in generic projects

CHANGELOG.md, packages/eas-cli/src/build/android/graphql.ts, packages/eas-cli/src/build/android/prepareJob.ts, packages/eas-cli/src/build/ios/graphql.ts, packages/eas-cli/src/build/ios/prepareJob.ts, packages/eas-cli/src/build/local.ts, packages/eas-json/src/build/schema.ts, packages/eas-json/src/build/types.ts
Resolves https://github.com/expo/eas-cli/issues/887.
Extend job objects and schemas with the new `eas.json` field.
Ran tests on staging, as well as locally.
In 'draft' because it depends on a pending release of `local-build-plugin` of which the version number is already included.
=> [eas-cli][build] add support for `prebuildCommand` in eas.json

CHANGELOG.md, packages/eas-cli/src/build/runBuildAndSubmit.ts
- Resolves https://github.com/expo/eas-cli/issues/920
Display identical output as for completed builds
Ran locally with and without the json flag.
=> [eas-cli][build] add json output for started builds

CHANGELOG.md, package.json, packages/eas-cli/package.json, packages/eas-json/package.json, yarn.lock
- macOS Catalina images are no longer supported - upgrade `@expo/eas-build-job`.
- It's good practice to keep deps up-to-date.
- Upgrade `@expo/eas-build-job`.
- Upgrade other deps (based on `yarn outdated`).
CI
=> upgrade deps

CHANGELOG.md, packages/eas-cli/src/submit/ArchiveSource.ts
Fixes https://github.com/expo/eas-cli/issues/937
Check platform and print `.ipa` or `.aab`.
- I ran `eas submit -p android` and checked the placeholder.
- I ran `eas submit -p ios` and checked the placeholder.
=> fix url placeholder for iOS submits

packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/commands/channel/edit.ts, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/BranchQuery.ts, packages/eas-cli/src/project/projectUtils.ts
The return type of `getBranchByNameAsync` falsely promises to not be undefined.
This leads to confusing errors such as: https://github.com/expo/eas-cli/issues/926
Refactored `getBranchByNameAsync` to use the generated graphQL types and moved it to the graphQL directory. 
Put in informative errors where appropriate.
Tested affected commands in a demo repo.
=> [eas-cli] fix get branchByNameAsync typing

CHANGELOG.md, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/commands/channel/view.ts, packages/eas-cli/src/graphql/queries/ChannelQuery.ts
giving a non-existent channel to `eas channel:rollout does-not-exist` results in a non-informative error.
Confirm the channel is defined at the call site and throw an informative error if it is not.
Since we know the channel is defined, we can simplify the types passed through the code.
Tested affected rollout routes in a demo repo.
=> [eas-cli] return an informative error if rollout channel dne

packages/eas-cli/src/build/metadata.ts
Reduce code duplication by importing nullable function from config-plugins
for reference the code for the nullable function: https://github.com/expo/expo-cli/blob/main/packages/config-plugins/src/utils/Updates.ts#L86
=> [eas-cli] import getRuntimeVersionNullabe from config-plugins

CHANGELOG.md, packages/eas-cli/src/project/projectUtils.ts
if package.json is outside git repo, eas.json is also created there and `git add` is failing
Potentially root cause of https://github.com/expo/eas-cli/issues/967
check projectDir is outside of vcs dir
reproduced a case described in why section and tun local build
=> [eas-cli] check if package.json is inside git repo

CHANGELOG.md, packages/eas-cli/src/commands/update/configure.ts
Starting in SDK 44, expo-updates can no longer be assumed to be installed.
check and install
Tested in demo repo
=> [eas-cli] install expo-updates when running update:configure

CHANGELOG.md, packages/eas-cli/src/commands/update/index.ts
Minimal runtime version warning on non-managed workflow is confusing end users.
Updated wording.
Run it in a bare workflow with a runtimeversion policy configured.
=> [update] make runtime version warning more descriptive

packages/eas-cli/src/commands/update/index.ts
regression was never published, so I'm not adding anything to changelog
If I run `eas update` on project that was not configured to use eas update I'm getting 
```
Error: Must specify codeSigningMetadata under the "updates" field of your app config file to use EAS code signing
```
move getCodeSigningInfoAsync
steps starting form unconfigured project: 
`eas update` throws     `Error: There is neither a value or a policy set for the runtime version on "android"`
`eas update:configure`
`eas update` - works correctly`
=> [eas-cli] Fix code signing error on unconfigured eas project

CHANGELOG.md, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/utils/code-signing.ts
The logic here was incorrect as it was requiring code signing metadata even if there was not code signing certificate.
Fix logic.
We should really add some tests. Will work on that.
=> [eas-cli] Fix code signing error when not yet configured

CHANGELOG.md, packages/eas-cli/src/graphql/client.ts, packages/eas-cli/src/graphql/mutations/BuildMutation.ts
retrying request might cause multiple builds to be scheduled
add noRetry flag in graphql client context and check for it in 
setup local nginx that return 504 only + attempt to run builds
=> [eas-cli] do not retry build requests

CHANGELOG.md, packages/eas-cli/src/credentials/ios/appstore/capabilityIdentifiers.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfile.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfileAdhoc.ts, packages/eas-cli/src/credentials/ios/appstore/pushKey.ts
Add clarity regarding what methods must be skipped for App Store Connect Token support in `eas build` command.
Tested that these functionalities do not work with Apple cookie authentication.
=> chore: add annotations about functions that do not support App Store Connect API

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/fetch.ts, packages/eas-cli/src/graphql/client.ts, yarn.lock
Fix proxy support
- pass agent to fetch wrapper (currently it was only used by ggraphql)
- use `https_proxy` instead of `http_proxy`
- update @expo/apple-utils
run build with and without proxy
=> [eas-cli] fix proxy support

CHANGELOG.md, packages/eas-cli/src/build/utils/printBuildInfo.ts
Sometimes we are deprecating stuff that is server-side so the message to update cli is misleading, especially if changes are marked as user-facing
remove part of the message, from now on the messages from turtle-api should be more descriptive
=> [eas-cli] make deprecation message more generic

CHANGELOG.md, packages/eas-cli/src/project/ios/target.ts
support generating credentials for iOS ap extension
allow specifying those values via extra field
run build with onesignal config
```
"extra": {
"eas": {
"build": {
"experimental": {
"ios": {
"appExtensions": [
{
"targetName": "OneSignalNotificationServiceExtension",
"bundleIdentifier": "com.wkozyra95.sdk44.OneSignalNotificationServiceExtension"
}
]
}
}
}
}
},
"plugins": [
[
"onesignal-expo-plugin",
{
"mode": "development"
}
]
]
}
```
=> [eas-cli] generate credentilas for iOS app extensions

.github/workflows/stale-issues.yml
Close stale issues automatically (issue becomes stale after 30 days of inactivity and it's close after 7)
Run job once a day
Not tested(copied from expo/expo), workflow will not show up unless before it's merged to main
=> autoclose stale issues

CHANGELOG.md, packages/eas-cli/src/credentials/context.ts, packages/eas-cli/src/credentials/ios/appstore/AppStoreApi.ts, packages/eas-cli/src/credentials/ios/appstore/ascApiKey.ts, packages/eas-cli/src/credentials/ios/appstore/contractMessages.ts, packages/eas-cli/src/credentials/ios/appstore/ensureAppExists.ts, packages/eas-cli/src/submit/ios/AppProduce.ts
Require user/password authentication for methods that don't support api key authentication (jwt). Followup to https://github.com/expo/eas-cli/pull/1051#discussion_r844938222 . Also fixed a couple auth bugs - we weren't using api key authentication where we should've been.
- App.createAsync: tested manually, received error. Seems like only cookies are supported, see https://github.com/expo/third-party/blob/main/packages/app-store/src/connect/models/App.ts#L146
These all fail with this class of error: `Failed to get iTunes contract status: Invalid client request. Missing providerId in request context`
- getContractStatusAsync: tested manually
- getContractMessagesAsync: tested manually
All received this class of error: `UnexpectedAppleResponse: The URL path is not valid - The resource …
=> [eas-cli] require userAuthCtx for methods that don't support jwt

CHANGELOG.md, packages/eas-cli/src/build/build.ts
Closes https://linear.app/expo/issue/ENG-4566/provide-queue-position-and-estimated-wait-time-when-running-builds-for
Follow-up to https://github.com/expo/eas-cli/pull/1049
We want to display queue position + estimated wait time when running multiplatform builds.
Use multiline spinner for reporting status.
=> [ENG-4566] refactor status updates for multi-platform builds

CHANGELOG.md, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/utils/__tests__/code-signing-test.ts, packages/eas-cli/src/utils/code-signing.ts
Corresponding PR for https://github.com/expo/expo/pull/16979. Now that private code signing keys are encouraged to be kept offline or encrypted in a separate directory from the certificate, this argument needs to be required when code signing is configured to know how to locate the private key to use to sign the manifest.
Make argument required when code signing is configured.
Run tests.
```
DEBUG=true ~/expo/eas-cli/packages/eas-cli/bin/run update --branch preview --message "Updating the app 3"
Error: Must specify --private-key-path argument to sign update for code
signing
```
=> [eas-cli] Require private-key-path to be specified for updating when code signing configured

CHANGELOG.md, packages/eas-cli/src/credentials/android/actions/CreateGoogleServiceAccountKey.ts, packages/eas-cli/src/credentials/android/actions/__tests__/CreateGoogleServiceAccountKey-test.ts, packages/eas-cli/src/credentials/android/actions/__tests__/SetUpGoogleServiceAccountKey-test.ts, packages/eas-cli/src/submit/android/ServiceAccountSource.ts
I had to create a Google Service Account key for my new app. I noticed we're missing the URL to the FYI page on how to create the key.
It turns out that we have a similar prompt in two places but it doesn't look the same. 
It'd be best to refactor the code so the function is reused but I didn't want to spend too much time on it.
Instead, I copy-pasted the better implementation.
This can be refactored in a follow-up PR.
=> [ENG-4615] unify google service account prompts

CHANGELOG.md, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/submit/utils/errors.ts
Companion to https://github.com/expo/turtle-v2/pull/922/files
Some of Apple's certificates have expired. This results in app rejections.
Handle the new error code.
None
=> submit - add custom error message for expired apple certs problem

CHANGELOG.md, packages/eas-cli/src/commands/update/index.ts
Currently, we might ask a question about if you want to install expo-updates when running EAS CLI, which can break CI. When CI breaks, there's no indication of what we tried to get input for. Just an error.
We need to throw the log before we throw the error, or we need to add a default choice with a --non-interactive flag.
This PR adds the non-interactive flag to be in alignment with the other commands.
Closes ENG-4590.
Used https://github.com/expo/eas-cli/pull/600/ as inspiration. Added flag, test manually (there's no tests for this command).
```
~/expo/eas-cli/packages/eas-cli/bin/run update --non-interactive
✔ Linked to project @wschurman/eas-update-test
Error: Must supply --branch when in non-interactive mode
~/expo/eas-cli/packages/eas-cli/bin/run update --non-interactive --branch …
```
=> [eas-cli] Add non-interactive flag to eas update command

CHANGELOG.md, packages/eas-cli/src/project/publish.ts
In rare cases, the bundling could fail with heap out of memory errors in Github Actions. Without these logs, it's super hard to find this cause.
Removed the harcoded `silent: true` and replaced it with `silent: !Log.isDebug`.
- Linux/MacOS: `$ EXPO_DEBUG=true; eas update`
- Windows: `$ npx cross-env 'EXPO_DEBUG=true' eas update`
=> [eas-cli] Enable update bundle output when debugging

CHANGELOG.md, packages/eas-cli/src/build/build.ts
https://linear.app/expo/issue/ENG-4968/verify-and-probably-fix-eas-cli-p-all-status-update-behavior
In case when running `eas build -p all`, place the spinner next to "Waiting for builds to complete".
Single build
Multiple builds
=> [ENG-4968] better spinner placement for multiple builds

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
This PR makes EAS CLI a single version of `@oclif/core`.
- `@oclif/plugin-*` libs don't seem to be actively maintained. I decided to fork all of them we're using and upgraded `@oclif/core` to the same version. In the future, I'll make `@oclif/core` a peer dependency of those libs so we don't have to touch them again.
- I upgraded `@oclif/core` to 1.9.0 here.
Smoke test by running `easd build`.
=> use single version of @oclif/core

CHANGELOG.md, packages/eas-cli/src/build/build.ts
See https://linear.app/expo/issue/ENG-5022/add-learn-more-link-during-the-archive-uploading-process
Print learn more link above the spinner(s).
When "Compressing project files" spinner is displayed (when takes longer than 1 second):
Without "Compressing project files":
=> [ENG-5022] print learn more link before uploading archive to S3

packages/eas-cli/src/metadata/context.ts, packages/eas-json/src/submit/schema.ts, packages/eas-json/src/submit/types.ts
Part of PR #1083
This adds a new context around the metadata, based on the submission contexts. It is used to initialize and authenticate the user to interact with the metadata stuff.
- Metadata is configured through `eas.json`'s submission profiles, that's why we read those profiles in the context.
- If it's not configured, we assume the store configuration file.
- When the store configuration file is set in the profile, we use that to read/write the data.
- Add the submission property `meta` with default value whenever users configure it.
I need to add some tests for this, can add them later.
=> [eas-cli] Add metadata context based on submission contexts

packages/eas-cli/package.json, packages/eas-cli/schema/metadata-0.json, packages/eas-cli/src/metadata/apple/config/__tests__/fixtures/appInfoLocalization.ts, packages/eas-cli/src/metadata/config.ts, yarn.lock
- Part of PR #1083
This adds basic JSON validation for the store configuration, using AJV and a custom JSON schema.
- This contains well-known issues/limitations of the stores, to help users inform of configurational errors.
- In cases of errors, it fails before we communicate with the stores to keep the feedback loop as fast as we can.
- If you go to PR #1083, generate a store config, and mess up some configuration, you can see the errors.
- Alternatively, you could add the custom JSON schema to vscode to see live validation as you code. Will probably add this to Expo Tools later as well.
=> [eas-cli] Add metadata config validation using json schema

packages/eas-cli/src/analytics/events.ts, packages/eas-cli/src/metadata/utils/__tests__/telemetry.test.ts, packages/eas-cli/src/metadata/utils/telemetry.ts
- Part of PR #1083 
This adds customized telemetry to the App Store library, and gives us visibility on potential (new) issues or changes from the stores.
- The telemetry can be directly bound to the App Store library and sends events based on the responses.
- In cases of failures, we send a bit more context to understand what is going wrong.
- When we send more context, we also make sure to never send sensitive data by scrubbing/replacing these values with placeholders.
See unit tests
=> [eas-cli] Add metadata telemetry to increase visibility in store errors

packages/eas-cli/src/metadata/apple/data.ts, packages/eas-cli/src/metadata/apple/task.ts, packages/eas-cli/src/metadata/apple/tasks/__mocks__/nock.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/age-rating.test.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/app-info.test.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/app-version.test.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/ageRatingDeclarations/patch-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appInfoLocalizations/patch-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appInfos/get-appInfoLocalizations-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appInfos/patch-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appStoreVersions/get-ageRatingDeclaration-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appStoreVersions/get-ageRatingDeclaration-404.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appStoreVersions/get-appStoreVersionLocalizations-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/apps/get-appInfos-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/apps/get-appInfos-404.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/apps/get-appStoreVersions-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/apps/get-appStoreVersions-count-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/apps/get-appStoreVersions-count-multiple-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/requestContext.ts, packages/eas-cli/src/metadata/apple/tasks/age-rating.ts, packages/eas-cli/src/metadata/apple/tasks/app-info.ts, packages/eas-cli/src/metadata/apple/tasks/app-version.ts, packages/eas-cli/src/metadata/apple/tasks/index.ts, packages/eas-cli/src/metadata/context.ts
- Part of PR #1083
This adds the task-runner based entity actions to perform the download/upload actions, see Notion for more info.
- Every task runner works independently from another task
- Every task can have data-dependencies that have to be asserted
- When a task fails, the other tasks should still be executed to try and send/get as much data as possible
- When the command is finished, the exit status is determined by "encountered any issue or not" and should log helpful context to the user
See tests with fixtures from the ASC
=> [eas-cli] Add metadata app store task runner

packages/eas-cli/src/metadata/download.ts, packages/eas-cli/src/metadata/errors.ts, packages/eas-cli/src/metadata/upload.ts
- Part of PR #1083
These methods are the methods that should be used in the commands, they combine everything from the metadata into simple routines.
If you go to PR #1083, you can test these actions directly from `eas metadata` and `eas metadata:configure`.
=> [eas-cli] Add metadata root actions and error handling

CHANGELOG.md, packages/eas-cli/src/graphql/queries/UpdateQuery.ts
A user has [reported](https://forums.expo.dev/t/eas-update-gateway-timeout/63783) that requests to publish updates started to time out a few weeks ago. 
I inspected the screenshot they provided and saw that they time out after the update has been linked to the project. I then inspected the code in that commands execution path after an update gets linked for any web requests. I found `UpdateQuery.viewBranchAsync` on `.../commands/update/index.ts` ln ~132 and realized that this query times out consistently when i run it for their particular branch. the fix:
* lower page limit from 10_000 to 300 in UpdateQuery.ts
I noticed that the `app.byId.updateBranch*.updates` query started to time out after the branch contained > ~600 updates. I ran queries against production using the website and an …
=> [eas-cli] lower page limit for UpdateQueries

.gitignore, CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/UpdateQuery.ts, packages/eas-cli/src/update/__tests__/update-test.ts
Follow up to #1119. This will help avoid timeouts and network errors related to publishing updates by avoiding querying for large payloads of updates when it is not necessary.
For the execution flow to publish a new update we just need to check the existence of the branch, and if it is not extant, create it. We can limit the updates returned in the GQL query in this case to 0 because we are not using them.
For the execution flow to republish an old update, we need to both check that a branch exists and get updates associated with it. We can limit the updates returned in the GQL query in this case to however many we need. We lowered the number of updates returned from 10k to 300 previously. We will need to add in some new functionality to paginate these results and re-query with an offset …
=> [eas-cli] make viewBranchAsync updates limit configurable

CHANGELOG.md, packages/eas-cli/src/build/utils/url.ts, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/ensureProjectExists.ts, packages/eas-cli/src/project/publish.ts
We'd like to ensure our users have a better experience using `eas-cli`. Contains various UX improvements listed in  https://linear.app/expo/issue/ENG-4589/improve-publish-command
- Updated `uploadAssetsAsync` to now return the # of unique assets uploaded and use that value to inform the user of the CLI run status
- Added a bunch of info to the log output
- Added a 'fallback' behavior for unsupported terminals for the `ensureProjectExistsAsync` console output
I've updated the automated tests for `uploadAssetsAsync` to include the new return value.
You should be able to run the CLI as normal but now:
- in an unsupported terminal by [terminal link](https://www.npmjs.com/package/terminal-link), URLs should not contain `)`
- Console output should capitalize all the outputs (branch => Branch)
- …
=> [eas-cli] improve update terminal output

CHANGELOG.md, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/UpdateQuery.ts, packages/eas-cli/src/update/__tests__/update-test.ts
Follow up to #1119. This allows CLI users to `update --republish` any previously published update, even if it is beyond the initial page limit (n=300).
I added the `getUpdatesToRepublishAsync` method which will recurse when the user asks for a new page updates. The updates are accumulated and presented to the user. Once a branch has been fully loaded, the option to fetch another page (`Next page...`) will disappear.
Run locally (`edl update --republish`) with a low page limit (n=5) on a branch with few updates. Ensure that:
- the option to fetch new pages of updates is present
- updates fetched in both the current network request and previous network requests can be republished
- once all updates are fetched, the option to fetch another page disappears
Also, added some automated tests for …
=> [eas-cli] add fetching additional pages for update --republish

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/project/publish.ts, yarn.lock
Google gets overloaded when too many assets are uploaded at once. 
Closes ENG-5232.
This limits it to 50 at a time. Previously there was no limit but we had another artificial limit of 400 on the server side, so the max concurrent uploads was 400. We could do 400 here, but I figure 50 is probably a bit more reliable.
With eas-cli changes running locally and www changes running locally from https://github.com/expo/universe/pull/9852, with an app with 1600 assets (temporarily set MAX_ASSETS_PER_UPDATE to 2000 on local server)
```
export EXPO_LOCAL=1
EXPO_DEBUG=1 ~/expo/eas-cli/packages/eas-cli/bin/run update --branch preview --message "Updating the app"
```
see it finishes successfully.
=> [eas-cli] Limit concurrent asset uploads

packages/eas-cli/src/commands/metadata/pull.ts, packages/eas-cli/src/commands/metadata/push.ts
When `eas.json` is missing from the project, it fails with `Could not find eas.json`. With this change, we generate the default `eas.json` file.
Reused the `eas build` `ensureProjectConfiguredAsync` after validating the user's local Expo/RN project.
=> [eas-cli] Auto-configure eas.json with metadata when missing

packages/eas-cli/src/commands/metadata/pull.ts, packages/eas-cli/src/commands/metadata/push.ts, packages/eas-cli/src/metadata/apple/tasks/app-info.ts, packages/eas-cli/src/metadata/apple/tasks/app-version.ts, packages/eas-cli/src/metadata/download.ts, packages/eas-cli/src/metadata/errors.ts, packages/eas-cli/src/metadata/upload.ts
This makes the output of the `eas metadata` commands more like `eas build`, showing the user how to use it.
command | terminal UI
--- | ---
`eas metadata:pull` | <img alt="Screenshot 2022-06-14 at 14 55 58" src="https://user-images.githubusercontent.com/1203991/173584292-51efd19e-d48f-4205-81f6-61ca24335d11.png">
`eas metadata:push` | <img alt="Screenshot 2022-06-14 at 15 05 54" src="https://user-images.githubusercontent.com/1203991/173584229-2e3dc176-2691-4664-90a7-96bb5336e39e.png">
- `$ eas metadata:pull`
- `$ eas metadata` or `$ eas metadata:push`
=> [eas-cli] Polish the command output for release

CHANGELOG.md, CODEOWNERS, packages/eas-cli/package.json, packages/eas-cli/src/commands/metadata/configure.ts, packages/eas-cli/src/commands/metadata/index.ts, packages/eas-cli/src/commands/metadata/pull.ts, packages/eas-cli/src/commands/metadata/push.ts, packages/eas-cli/src/metadata/apple/config/reader.ts, packages/eas-cli/src/metadata/apple/config/writer.ts, packages/eas-cli/src/metadata/apple/task.ts, packages/eas-cli/src/metadata/apple/tasks/age-rating.ts, packages/eas-cli/src/metadata/apple/tasks/app-info.ts, packages/eas-cli/src/metadata/apple/tasks/app-version.ts, packages/eas-cli/src/metadata/context.ts, packages/eas-cli/src/metadata/download.ts, packages/eas-cli/src/metadata/errors.ts, packages/eas-cli/src/metadata/upload.ts, packages/eas-cli/src/metadata/utils/__tests__/date.test.ts, packages/eas-cli/src/metadata/utils/array.ts, packages/eas-cli/src/metadata/utils/date.ts, packages/eas-cli/src/utils/expodash/__tests__/uniq-test.ts, packages/eas-cli/src/utils/expodash/uniq.ts
**Part of PR #1083**
**Additional PRs merged**
This adds the EAS CLI commands to let users interact with the metadata features.
Originally we wanted to include it in the submission commands, but that workflow does not work well.
- We have to wait until the binary is shipped and processed, else we might be editing a wrong version
- There is no good way to wait until the binary is processed
- It's not that great to ask the user to wait until that's all done
As a temporary solution, the metadata is split into its own commands.
After all PRs are merged and ready:
- `$ eas metadata`
- `$ eas metadata:pull`
- _Edit the store configuration_
- `$ eas metadata:push`
=> [eas-cli] Add metadata commands

CHANGELOG.md, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/config.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/metadata/context.ts, packages/eas-cli/src/utils/__tests__/profiles-test.ts, packages/eas-cli/src/utils/profiles.ts, packages/eas-json/src/submit/resolver.ts
We keep backward compatibility for some breaking changes in eas.json, this PR removes them:
- change from git workflow that required committing
- change from the default 'release' profile to 'production'
- remove migration process for git workflow changes
- remove fallback to `release` profile
- remove prompt that asked what profile you want to use if default profile did not exist
- move default profile logic(submits only) to `eas-json` package
tests + run build with different profiles
=> remove support for deprecated eas.json formats

CHANGELOG.md, packages/eas-cli/src/metadata/errors.ts
Fixes ENG-5280
We keep track of these errors, but the user should also understand if something is configured wrongly.
- Create an app
- Initialize metadata `eas metadata:pull`
- Change the `apple.info.[locale].title` to `My App`
- Check if the error above is surfaced
=> [eas-cli] Surface metadata cause errors in logging output

CHANGELOG.md, packages/eas-cli/src/commands/metadata/push.ts, packages/eas-cli/src/metadata/upload.ts
Fixes ENG-5282
- Generated a link in **src/metadata/upload.ts**
- Outputted the link in **src/commands/metadata/push.ts**
- Run `eas metadata:push`
=> [eas-cli] Add link to ASC after successful metadata sync

CHANGELOG.md, packages/eas-cli/src/metadata/errors.ts, packages/eas-cli/src/metadata/upload.ts
If we have a potential issue in the metadata validation, we still want users to be able and try it anyways. The user should be "informed" that the current config state might cause issues later on.
> `want ... want` typo is fixed
- Create a `store.config.json`
- Add `apple.info[en-CA]` with only `title`
- `$ eas metadata:push`
=> [eas-cli] Allow users to skip metadata validation

CHANGELOG.md, packages/eas-cli/src/__tests__/uploads-test.ts, packages/eas-cli/src/uploads.ts
I noticed that links to submission archives are broken (but they are still usable).
`https://submission-service-archives.s3.amazonaws.com/production%2Fdc98ca84-1473-4cb3-ae81-8c7b291cb27e%2F4424aa95-b985-4e2f-8755-9507b1037c1c`
See that the path is encoded - `%2F` instead of `/`. This is probably a bug in AWS S3.
Fix links.
Added test case.
=> [ENG-5262] fix URLs returned from AWS S3

CHANGELOG.md, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/update/__tests__/update-test.ts
Closes [5234](https://linear.app/expo/issue/ENG-5234/truncate-eas-update-message-in-eas-cli)
Added a short truncate function and ran the user input through it. The function will warn the user if truncation has occurred.
Added some automated tests to check:
- truncates long messages
- does not truncate short messages
- warns the user that truncation has occurred
https://user-images.githubusercontent.com/15132641/175425347-d8f401d6-b54b-4349-afcf-c4f914ae742c.mov
https://user-images.githubusercontent.com/15132641/175425365-47f88cb3-d295-4349-97c4-536363b9b258.mov
=> [eas-cli] truncates long messages for eas update command

CHANGELOG.md, packages/eas-cli/schema/metadata-0.json, packages/eas-cli/src/metadata/apple/config/__tests__/fixtures/ageRatingDeclaration.ts, packages/eas-cli/src/metadata/apple/config/__tests__/reader.test.ts, packages/eas-cli/src/metadata/apple/config/__tests__/writer.test.ts, packages/eas-cli/src/metadata/apple/config/reader.ts, packages/eas-cli/src/metadata/apple/config/writer.ts
This includes improved schema configuration and default store config values for:
- `apple.info`
- `apple.release`
- `apple.advisory`
- Updated metadata schema
- Updated tests
- See tests
=> [eas-cli] Improve store configuration defaults and schema configuration

CHANGELOG.md, packages/eas-cli/schema/metadata-0.json, packages/eas-cli/src/metadata/apple/config/__tests__/fixtures/appStoreReviewDetail.ts, packages/eas-cli/src/metadata/apple/config/__tests__/writer.test.ts, packages/eas-cli/src/metadata/apple/config/reader.ts, packages/eas-cli/src/metadata/apple/config/writer.ts, packages/eas-cli/src/metadata/apple/data.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/app-review-detail.test.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appStoreReviewDetails/patch-200.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appStoreReviewDetails/post-201.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appStoreVersions/get-appStoreReviewDetail-200-empty.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appStoreVersions/get-appStoreReviewDetail-200.json, packages/eas-cli/src/metadata/apple/tasks/app-review-detail.ts, packages/eas-cli/src/metadata/apple/tasks/app-version.ts, packages/eas-cli/src/metadata/apple/tasks/index.ts, packages/eas-cli/src/metadata/apple/types.ts
Adds the review details to the metadata task runners.
- Tested validation properties through force-feeding ASC API
- Added tests for `AppReviewDetailTask`, with actual ASC API responses
- Tweaked the store configuration scheme
- See tests
- Set the `apple.review` property and run `eas metadata:push`
- Add review detail attachments
=> [eas-cli] Add review details to metadata store configuration

CHANGELOG.md, packages/eas-cli/schema/metadata-0.json, packages/eas-cli/src/metadata/apple/config/__tests__/fixtures/appInfo.ts, packages/eas-cli/src/metadata/apple/config/__tests__/reader.test.ts, packages/eas-cli/src/metadata/apple/config/__tests__/writer.test.ts, packages/eas-cli/src/metadata/apple/config/reader.ts, packages/eas-cli/src/metadata/apple/config/writer.ts, packages/eas-cli/src/metadata/apple/types.ts
This improves/finalizes the `apple.categories` in the EAS metadata store configuration.
> See the `metadata-0.json` schema for examples
- Updated schema documentation and validation
- Updated the schema typescript types
- Updated the store configuration reader and writer
- See added tests
=> [eas-cli] Improve EAS metadata categories configuration

CHANGELOG.md, packages/eas-cli/schema/metadata-0.json
This drops both `apple.idfa` and `apple.priceTier`.
- For IDFA, that's because it has been fully deprecated in ASC in favor of [AppTrackTransparency](https://developer.apple.com/documentation/apptrackingtransparency)
- For price tier, that's because there is a v2 that is completely different and needs to be re-implemented.
Dropped both configuration options from store config schema
Only a change in the store config schema
=> [eas-cli] Drop deprecated idfa and price tier from store config

CHANGELOG.md, packages/eas-cli/src/env.ts, packages/eas-cli/src/project/android/applicationId.ts, packages/eas-cli/src/project/workflow.ts
Expo go build gradle is using more complicated logic that we can handle when parsing to extract applicationId.
- Pass applicationId override via env.
- Change file that detects workflows to app/build.gradl.
=> [eas-cli] allow applicationId override

CHANGELOG.md, packages/eas-cli/src/project/publish.ts, packages/eas-cli/src/submit/__tests__/ArchiveSource-test.ts, packages/eas-cli/src/submit/utils/__tests__/files-test.ts, packages/eas-cli/src/submit/utils/files.ts, packages/eas-cli/src/uploads.ts
https://github.com/expo/eas-cli/commit/3d5b77a2638f91705134846817dcc3053ce6427e looks correct from a type point of view, but due to the weirdness of the method signature and casting to string, it unfortunately is crashing.
What would happen is that the `location` headers is sometimes not present in the response. Therefore it would pass the string `"null"` to `fixArchiveUrl`, which would throw in the `URL` constructor.
The fix here is to stop doing this header extraction and string coercion when not necessary. It seems like maybe all the submission requests have `location` and only the asset ones don't?
```
$ EXPO_DEBUG=1 ~/expo/eas-cli/packages/eas-cli/bin/run update --branch preview --message "Updating the app"
```
(this would have been tough to catch in an integration test since it is …
=> [eas-cli] Fix asset upload crash

CHANGELOG.md, packages/eas-json/src/build/resolver.ts
The current implementation allows only one base profile, but there is a lot of use cases where you might want to have more extends in a chain.
Increase max number of build profiles in an extend chain to 5.
=> [eas-json] Increase max allowed profile extend chain

CHANGELOG.md, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
Now that we are allowing more assets to be uploaded, this timeout no longer makes sense. Instead, this PR shows a spinner (progress) to let people ctrl-c when they deem it to be stalled.
Closes ENG-5706.
Add spinner.
```
$ EXPO_DEBUG=1 ~/expo/eas-cli/packages/eas-cli/bin/run update --branch preview --message "Updating the app"
```
with an app with ~700 assets.
=> [eas-cli] Show spinner instead of silently timing out during asset upload

CHANGELOG.md, packages/eas-cli/src/__tests__/uploads-test.ts, packages/eas-cli/src/submit/__tests__/ArchiveSource-test.ts, packages/eas-cli/src/submit/utils/files.ts, packages/eas-cli/src/uploads.ts
- In https://github.com/expo/eas-cli/pull/1179 I broke uploading assets with `eas update`.
- In https://github.com/expo/eas-cli/pull/1205 Will broke my fix for build archive URLs.
`uploadAsync` is meant for handling AWS S3 uploads (used for EAS Build and Submit). Moved fixing the upload location to the function. 
I made sure three code paths for uploading files work fine:
- `eas build`
- `eas submit`
- `eas update`
=> fix S3 upload URLs

CHANGELOG.md, packages/eas-cli/src/project/android/applicationId.ts, packages/eas-cli/src/project/ios/bundleIdentifier.ts
The warning about package name / bundle identifier also shows up after running `expo prebuild` or `expo run`, in which case it's expected that app.json contains these fields. The warning that it will be ignored once the native code exists is okay, but the deprecation notice should be removed.
Old vs new:
Tested by running `expo prebuild` followed by `eas build`.
=> [cli] Change wording on build warning for bundle id/package name

CHANGELOG.md, packages/eas-cli/src/build/build.ts
https://linear.app/expo/issue/ENG-5017/suggestion-display-queue-type-in-cli-when-waiting
Display queue type when waiting.
=> [ENG-5017] display queue type when waiting

packages/eas-cli/package.json, packages/eas-cli/src/project/ensureProjectExists.ts
I always forget the command to upgrade CLIs. Some requires to run `brew`, other `npm`, some `yarn` or `curl`.
- Add a one-line command on how to upgrade
- I specifically used `npm` to match expo-doc which also use `npm/npx` as default
- I also fixed the `addNewLineIfNone` usage. Looks like the new line added through package.json wasn't recognized by the util function that supposed to detect those. I instead removed it from package.json and added the `addNewLineIfNone` to the command coming after the upgrade message.
~~Install an outdated eas-cli f.x. `npm install -g eas-cli@0.50.0`. Then run a command f.x. `eas build --profile development --platform ios`~~ (yeah well, not really, I had to manually change my global node_modules folder to preview the changes)
You will be prompt with the …
=> chore: add better message on how to self-upgrade eas-cli

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/project/ensureProjectExists.ts
Commit https://github.com/expo/eas-cli/commit/2bbf7f2b6d50db77127fa30e6f993da115f84c38 introduced newline before project is resolved which is adding a new line even if there was no output before it.
Also, leading stars were using different symbol fo `*` which make it look inconsistent in different terminals
=> [eas-cli] Fix newlines in cli deprecation message

CODEOWNERS
Why
---
They have been working on EAS CLI for EAS Update the most. Set them as codeowners.
=> Set Kirby and Will as codeowners for EAS Update CLI

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/credentials/ios/actions/SetUpAdhocProvisioningProfile.ts, packages/eas-cli/src/devices/actions/create/__mocks__/developerPortalMethod.ts, packages/eas-cli/src/devices/actions/create/__tests__/action-test.ts, packages/eas-cli/src/devices/actions/create/action.ts, packages/eas-cli/src/devices/actions/create/developerPortalMethod.ts, packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/utils/expodash/__tests__/chunk-test.ts, packages/eas-cli/src/utils/expodash/chunk.ts, yarn.lock
Adds a new option to `eas device:create`. It allows importing devices from Apple Developer Portal.
Use `@expo/apple-utils` for fetching devices from Apple Developer Portal and display a multi-select for importing them to EAS.
https://user-images.githubusercontent.com/5256730/181497915-9576425a-8f64-4b6f-a35d-216836bfa8b7.mov
https://user-images.githubusercontent.com/5256730/181497948-8cb76504-1d39-45d9-bc7c-b533d0038183.mov
=> [ENG-5622] allow importing devices from Apple Developer Portal

packages/eas-cli/.eslintrc.js, packages/eas-cli/src/utils/__tests__/queries-test.ts
Closes https://linear.app/expo/issue/ENG-5230/add-linter-error-if-only-is-present-on-eas-cli
Updated the eslint config
My first commit on this pr had a `.only` and the tests failed.
=> [eas-cli] disallow .only from being commited

packages/eas-cli/graphql.schema.json, packages/eas-cli/package.json, packages/eas-cli/src/analytics/events.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/createContext.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-json/package.json, yarn.lock
We want to track whether the build was run with the `--no-wait` flag and/or from CI environment.
- Send new metadata to www.
- Send `BUILD_REQUEST_NO_WAIT` / `BUILD_REQUEST_CI` events.
I ran 2 builds:
- `eas build`
- `CI=1 eas build --no-wait`
and checked the metadata was set correctly.
=> [ENG-5893] add runWithNoWaitFlag and runFromCI to build metadata

packages/eas-cli/schema/metadata-0.json, packages/eas-cli/src/metadata/apple/config/__tests__/fixtures/appStoreVersionPhasedRelease.ts, packages/eas-cli/src/metadata/apple/config/__tests__/reader.test.ts, packages/eas-cli/src/metadata/apple/config/__tests__/writer.test.ts, packages/eas-cli/src/metadata/apple/config/reader.ts, packages/eas-cli/src/metadata/apple/config/writer.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/app-version.test.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appStoreVersions/get-appStoreVersionPhasedRelease-200-empty.json, packages/eas-cli/src/metadata/apple/tasks/app-version.ts, packages/eas-cli/src/metadata/apple/types.ts
This cleans up a lot of the deprecated/unused `apple.release` properties. Right now, we support two:
- `automaticRelease`
- `phasedRelease`
- Updated store config schema
- Added phased release config reader/writer
- Updated data handling
- Added and updated tests
See tests
=> [eas-cli] Finalize the store config release properties

packages/eas-json/schema/eas.schema.json
Moving schema to the eas-cli will minimize the maintenance, and potentially in the future, we can use it directly for validation and docs generation.
- copy schema from vscode extension
- Cedric already prepared workflow that will pull this file from our repo https://github.com/expo/vscode-expo/pull/126
=> [eas-json] move eas.json schema to eas-cli repo

packages/eas-cli/schema/metadata-0.json, packages/eas-cli/src/metadata/apple/config/__tests__/reader.test.ts, packages/eas-cli/src/metadata/apple/config/__tests__/writer.test.ts, packages/eas-cli/src/metadata/apple/config/reader.ts, packages/eas-cli/src/metadata/apple/config/writer.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/app-version.test.ts, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/appStoreVersions/post-201.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/apps/get-appStoreVersions-200-empty.json, packages/eas-cli/src/metadata/apple/tasks/__tests__/fixtures/apps/get-appStoreVersions-count-multiple-200.json, packages/eas-cli/src/metadata/apple/tasks/app-version.ts, packages/eas-cli/src/metadata/apple/tasks/index.ts, packages/eas-cli/src/metadata/apple/types.ts, packages/eas-cli/src/metadata/upload.ts
Fixes ENG-5286
This allows users to create or select an editable app version through the store config.
- Added `apple.version` to store config schema
- Added find and update existing editable app version
- Added create new editable app version
- See added tests
=> [eas-cli] Add version selector to store config for metadata

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/PublishMutation.ts, packages/eas-cli/src/graphql/queries/PublishQuery.ts, packages/eas-cli/src/project/__tests__/publish-test.ts, packages/eas-cli/src/project/publish.ts
Closes https://linear.app/expo/issue/ENG-5245/show-a-warning-when-publishing-updates-with-too-many-assets
Uploading assets during a publish now returns the `assetLimitPerUpdateGroup` field. We use it to determine if we should render a warning message. 
Ran locally with a hardcoded value to see the warning message.
=> [eas-cli] add asset limit warning on publish flow

CHANGELOG.md, packages/eas-cli/src/vcs/clients/gitNoCommit.ts
A developer encountered an exception when running a build in Git no commit workflow:
```
All credentials are ready to build @x/y (com.x.y.staging)
✔ Push Notifications setup for x: com.x.y.staging
Error: git exited with non-zero code: 1
at ChildProcess.completionListener (/usr/local/lib/node_modules/eas-cli/node_modules/@expo/spawn-async/build/spawnAsync.js:43:23)
at Object.onceWrapper (node:events:642:26)
at ChildProcess.emit (node:events:527:28)
at maybeClose (node:internal/child_process:1092:16)
at Socket.<anonymous> (node:internal/child_process:451:11)
at Socket.emit (node:events:527:28)
at Pipe.<anonymous> (node:net:709:12)
...
at spawnAsync (/usr/local/lib/node_modules/eas-cli/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
at GitNoCommitClient.trackFileAsync …
```
=> [eas-cli] Swallow error when unable to track file in no commit workflow

packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/local.ts
I want to unify the env vars that are set when running builds in cloud and with local plugin. For that, I need to pass the build's metadata to the local plugin.
Pass metadata to local plugin.
None, I'll test it with local plugin.
=> [ENG-3865] pass build metadata to local plugin

CHANGELOG.md, packages/eas-cli/src/build/runBuildAndSubmit.ts
nativeVersion should only be disable when remoteVersionSource is set to remote
Set nativeVersion policy and try run build.
=> [eas-cli] Validate only if using remote version source

CHANGELOG.md, packages/eas-json/schema/eas.schema.json
This was missing from the JSON Schema, used in the vscode plugin.
- Added `metadataPath` to the iOS submit profiles, [as documented here](https://docs.expo.dev/submit/eas-json/#metadatapath).
JSON schema change only.
=> [eas-json] Add metadata path to ios submit profile

CHANGELOG.md, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/project/projectUtils.ts
Current validation is using config-plugins from eas-cli to validate the config, but if the project is using old expo-updates package prebuild will use older config plugins that silently ignores appVersion policy.
Check the version of the expo-updates package, and warn if the version is too old and appVersion policy is enabled.
run build locally
=> [eas-cli] Add warning about unsupported policy.

packages/eas-cli/package.json
During the work on the Windows DX PR I have spotted that `oclif` uses old Node for generating tars.
Update Node used by `oclif` to the same version as specified for Volta. 
`build-for-size-check` command works as expected after the bump.
=> [workspace] bump Node used by oclif

CHANGELOG.md, packages/eas-cli/src/ora.ts
- simple bug, `console.info` was being bound to `console.log` after an ora spinner stopped.
=> fix: log binding was incorrect after ora instance

CHANGELOG.md, packages/eas-cli/src/commands/metadata/pull.ts, packages/eas-cli/src/metadata/__tests__/config.test.ts, packages/eas-cli/src/metadata/__tests__/fixtures/invalid-type.async.js, packages/eas-cli/src/metadata/__tests__/fixtures/invalid-type.config.js, packages/eas-cli/src/metadata/__tests__/fixtures/invalid-type.config.json, packages/eas-cli/src/metadata/__tests__/fixtures/invalid-type.function.js, packages/eas-cli/src/metadata/__tests__/fixtures/invalid.async.js, packages/eas-cli/src/metadata/__tests__/fixtures/invalid.config.js, packages/eas-cli/src/metadata/__tests__/fixtures/invalid.config.json, packages/eas-cli/src/metadata/__tests__/fixtures/invalid.function.js, packages/eas-cli/src/metadata/__tests__/fixtures/store.async.js, packages/eas-cli/src/metadata/__tests__/fixtures/store.config.js, packages/eas-cli/src/metadata/__tests__/fixtures/store.config.json, packages/eas-cli/src/metadata/__tests__/fixtures/store.function.js, packages/eas-cli/src/metadata/config.ts, packages/eas-cli/src/metadata/download.ts, packages/eas-cli/src/metadata/upload.ts
This adds support for `store.config.js` files support, for `eas metadata:push`. It supports returned `object`, `function` or `async function`.
Added `loadConfigAsync` and `saveConfigAsync` that handles language specific things, like reading/writing JSON or JavaScript content.
See added tests
=> [eas-cli] Add js metadata config file support

packages/eas-cli/src/credentials/__tests__/fixtures-constants.ts, packages/eas-cli/src/project/__tests__/projectUtils-test.ts, packages/eas-cli/src/project/projectUtils.ts
Some background:
- We used to choose which type of manifest to serve in development based on the `extra.eas.projectId` field.
- At one point, code was added to configure the `extra.eas.projectId` field upon running commands that needed the project ID. https://github.com/expo/eas-cli/pull/402
- This caused those commands to change the manifest type used, and the new manifest type wasn't yet ready for prime time.
- https://github.com/expo/eas-cli/pull/412 was added to gate the auto-configuration-write temporarily.
- At some point shortly later, we changed the mechanism used to determine the type of manifest to use to either a flag or looking at the `updates.url` property of the config.
- We forgot to revert https://github.com/expo/eas-cli/pull/412
This PR reverts …
=> [eas-cli] Configure EAS project ID in app config in all cases

CHANGELOG.md, packages/eas-cli/src/project/publish.ts
Generating a ton of these at once on the server creates 1) requests that are huge and that have huge responses, and 2) a lot of load to google to generate the specs. Both of these issues were fixed on the server in https://github.com/expo/universe/pull/10394, but we still need to do batching on the client in order to not get timeouts. 
I think doing 100 at a time is fine. For 3k assets, this took ~10 seconds or so to get all the specifications when I tested locally.
For an app with 3k assets:
```
export EXPO_STAGING=1
~/expo/eas-cli/packages/eas-cli/bin/run update --branch preview --message "Updating the app"
```
See that it works!!
=> [eas-cli] Limit the number of SignedAssetUploadSpecifications fetched at a time

CHANGELOG.md, packages/eas-cli/src/commands/project/init.ts, packages/eas-cli/src/project/__tests__/projectUtils-test.ts, packages/eas-cli/src/project/projectUtils.ts
Blame: https://github.com/expo/eas-cli/pull/1282
- This PR made it so that whenever the project ID is created/fetched from the server, it is put in the app config (app.json). Automatically adding this to a dynamic app config (app.config.js) doesn't work, so an error was thrown.
- While some commands require an explicit project ID (the reason for the blame PR), most do not; instead, most commands just call this method to get the project ID and don't need it to be configured in the manifest for later in their process.
- This caused CI breakage for projects that use dynamic app config and don't synchronize their project ID locally.
In the future, we may require explicitly setting up the project ID before any command can be run, or may make all commands run the setup and throw if they can't …
=> [eas-cli] Prevent throwing dynamic app config write error when configuring project id

CHANGELOG.md, packages/eas-cli/src/vcs/__tests__/local-test.ts, packages/eas-cli/src/vcs/local.ts
Adding trailing backslash in gitignore, is causing a syntax error when packaging a build archive.
Remove all trailing backslashes from gitignore before passing them to the ignore library.
add test + tested manually
=> [eas-cli] Handle trailing backslash in gitignore

CHANGELOG.md, packages/eas-cli/src/analytics/events.ts, packages/eas-cli/src/credentials/ios/appstore/__tests__/ascApiKey-test.ts, packages/eas-cli/src/credentials/ios/appstore/ascApiKey.ts
There is a [bug in Apple's infrastructure](https://developer.apple.com/forums/thread/684314) that does not propagate newly created objects for a long time (up to 14 seconds in my experiments!). This behaviour is non-deterministic, but the general chain of events is as follows:
1. cli creates Api Key through Apple API
2. cli receives response that key is created
3. cli attempts to download Api Key
4. Apple responds saying that resource does not exist 😿 
Fixes https://github.com/expo/expo-cli/issues/4521
Retry, using exponential backoff. We will retry for up to 6 times, waiting 2, 4, 8, 16, 32 and 64 seconds between each retry. I tried creating an Api Key many times and when the bug occurred, the maximum time I ended up waiting was around 14 seconds. It is possible people might experience …
=> [ENG-6057][cli] api key creation: exponential backoff for slow apple propagation

CHANGELOG.md, packages/eas-cli/src/credentials/manager/ManageAndroid.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/project/__tests__/projectUtils-test.ts, packages/eas-cli/src/project/projectUtils.ts
This is inconsistent with the rest of the CLI commands which just create the project automatically.
Remove code and replace with equivalent code. All cases here used to throw if the user declined. Now they throw only if the user is not logged-in or on the internet.
In a project that is not yet linked, run `~/expo/eas-cli/packages/eas-cli/bin/run credentials`, generate android keystore and see that it is created on the server and linked.
=> [eas-cli] Replace promptToCreateProjectIfNotExistsAsync with getProjectIdAsync

CHANGELOG.md, packages/eas-cli/README.md, packages/eas-cli/src/commandUtils/EasCommand.ts
https://linear.app/expo/issue/ENG-6125/verify-that-eas-cli-isnt-installed-locally-to-the-project-dependencies
Detect if eas-cli is installed as a dependency and print a warning.
Installed in project:
Installed in monorepo root:
Installed in project + monorepo root:
=> [ENG-6125] print warning when eas-cli is installed as dependency

CHANGELOG.md, packages/eas-cli/src/submit/android/AndroidSubmitter.ts, packages/eas-cli/src/submit/submit.ts
Fixes ENG-6163 and ENG-6164
- Consistency with our usage of the word "email"
- After uploading the iOS app, developers will typically want to go to the TestFlight page
=> Copy changes to EAS Submit output

CHANGELOG.md, packages/eas-cli/src/build/createContext.ts, packages/eas-cli/src/credentials/context.ts, packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-json/schema/eas.schema.json, packages/eas-json/src/schema.ts, packages/eas-json/src/types.ts
When building a project that doesn't use push notifications, it's really annoying that EAS CLI keeps asking if you want to set up push notifications credentials for your project.
This PR introduces an option to permanently skip the question.
Give the user an option to skip the push notifications credentials setup forever when we detect they don't have them set up. Persist this choice to eas.json - `"cli.setUpPushNotifications": false`.
The prompt looks like this:
=> add eas.json option to skip push notifications setup

CHANGELOG.md, packages/eas-cli/src/commands/update/configure.ts
The output message for this call to `modifyConfigAsync` contains all the existing keys. This PR manually curates that message just for added/removed keys.
Fixes ENG-6174.
Manually curate object to include in message.
```
$ ~/expo/eas-cli/packages/eas-cli/bin/run update:configure
💡 The following process will configure your project to run EAS Update. These changes only apply to your local project files and you can safely revert them at any time.
It looks like you are using a dynamic configuration! Learn more
In order to finish configuring your project for EAS Update, you are going to need manually add the following to your app.config.js:
Learn more
{
"runtimeVersion": {
"policy": "sdkVersion"
},
"updates": {
"url": "https://staging-u.expo.dev/a26c0832-1d8e-4154-8ed0-9ec11cc66986"
}
}
Error: …
```
=> [eas-cli] Fix dynamic config update warning for update:configure

packages/eas-cli/src/credentials/ios/IosCredentialsProvider.ts, packages/eas-json/schema/eas.schema.json, packages/eas-json/src/schema.ts, packages/eas-json/src/types.ts
Fixes typo in `promptToConfigurePushNotifications`.
- I don't think many people started using this.
- Let's release this as soon as possible.
- I think that adding code that fixes the typo in eas.json is a bit of overkill. 
=> fix typo in promptToConfigurePushNotifications

CHANGELOG.md, packages/eas-cli/src/commands/device/delete.ts, packages/eas-cli/src/credentials/__tests__/fixtures-context.ts, packages/eas-cli/src/credentials/__tests__/fixtures-ios.ts, packages/eas-cli/src/credentials/context.ts, packages/eas-cli/src/credentials/ios/__tests__/IosCredentialsProvider-test.ts, packages/eas-cli/src/credentials/ios/actions/ConfigureProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/CreateProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/ProvisioningProfileUtils.ts, packages/eas-cli/src/credentials/ios/actions/SetUpAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/SetUpBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/SetUpInternalProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/SetUpProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/SetUpTargetBuildCredentials.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/ConfigureProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/CreateProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/SetUpInternalProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/actions/__tests__/SetUpProvisioningProfile-test.ts, packages/eas-cli/src/credentials/ios/appstore/AppStoreApi.ts, packages/eas-cli/src/credentials/ios/appstore/Credentials.types.ts, packages/eas-cli/src/credentials/ios/appstore/constants.ts, packages/eas-cli/src/credentials/ios/appstore/distributionCertificate.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfile.ts, packages/eas-cli/src/credentials/ios/appstore/provisioningProfileAdhoc.ts, packages/eas-cli/src/credentials/ios/validators/validateProvisioningProfile.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/devices/actions/create/developerPortalMethod.ts, packages/eas-cli/src/project/ios/__tests__/target-test.ts, packages/eas-cli/src/project/ios/target.ts
- Ensure tvOS projects play nice for adhoc, enterprise and app store builds. 
- Generate the proper credentials for tvOS in the case where the user wants Expo to manage them
Since this PR touches many files
=> [ENG-6070][cli] generate tvOS credentials for adhoc and prod

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/commands/open.ts, ts-declarations/better-opn/index.d.ts, yarn.lock
https://linear.app/expo/issue/ENG-6186/add-eas-open-command-to-open-the-project-on-the-website
Adds `eas open` command that opens the project page in a web browser.
I tested 3 scenarios:
1. Already existing project.
2. Freshly generated project (create-expo-app).
3. Outside project directory.
=> [ENG-6186] add "eas open" command

CHANGELOG.md, packages/eas-cli/package.json, yarn.lock
Refs ENG-6204
This PR bumps our fork of the oclif help plugin, which includes corrected description for the `help` command in the help prompt
The change has been tested locally by running `yarn eas`.
=> [eas-cli] bump oclif help plugin

packages/eas-cli/src/devices/manager.ts
Small language updates that I noticed while running the `eas device:create` command to add some iOS devices to our provisioning profile.
=> Small updates to the language of the Device Create command

CHANGELOG.md, packages/eas-cli/README.md, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/commands/build/inspect.ts, packages/eas-cli/src/commands/build/version/set.ts, packages/eas-cli/src/commands/build/version/sync.ts, packages/eas-cli/src/commands/config.ts, packages/eas-cli/src/commands/metadata/pull.ts, packages/eas-cli/src/commands/metadata/push.ts, packages/eas-cli/src/commands/submit.ts
Adds `-e` as a shortcut for the `--profile` flag.
Add the `-e` shortcut to all places where we use `--profile` flag.
Run commands locally and see if the new flag is available in help and if it works.
=> [eas-cli][ENG-6229] add `-e` as a shortcut for `--profile` flag

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/channel/list.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/queries/ChannelQuery.ts, packages/eas-cli/src/graphql/queries/UpdateQuery.ts, packages/eas-cli/src/graphql/types/Update.ts, packages/eas-cli/src/graphql/types/UpdateBranch.ts, packages/eas-cli/src/update/queries.ts, packages/eas-cli/src/update/utils.ts
There are a lot of different queries that fetch `Updates`. When we then use that data elsewhere in the code-base we need to match sure that the typing in those functions matches the query type. This gets complicated and unnecessarily difficult to handle. We should simplify the typing so that every schema has the same format and we just use that one format when referring to updates in our typing.
Most of the standardizing was already done in previous PRs. This PR introduces a standardized fragment and replaces in-line schemas with a spread of the fragment.
Ran commands locally to confirm the GQL changes didn't break our fetches.
=> [eas-cli] Standardize GQL Update type schema using Fragment 

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/secret/create.ts, packages/eas-cli/src/commands/secret/list.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/mutations/EnvironmentSecretMutation.ts, packages/eas-cli/src/graphql/types/EnvironmentSecret.ts
We want to allow users to upload files to EAS Secrets. The file will be recreated on EAS Build and the env var set to the ephemeral file path.
- `secret:create`
- add new option - `--type` that can be either `string` or `file`
- If `--type` is not specified, assume the value is a file path and try to find it. If the file exists, ask the user if they want to upload the file contents. Otherwise, fall back to `string`.
- `secret:list`
- add column with `type`
=> [ENG-4730] support uploading files to EAS Secret

packages/eas-cli/src/build/utils/repository.ts, packages/eas-cli/src/credentials/context.ts, packages/eas-cli/src/credentials/manager/ManageAndroid.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/project/ios/__tests__/scheme-test.ts, packages/eas-cli/src/project/ios/scheme.ts, packages/eas-cli/src/vcs/clients/git.ts, packages/eas-cli/src/vcs/vcs.ts
Noticed while writing https://github.com/expo/eas-cli/pull/1356 that there were a few other methods that had `nonInteractive` as an optional arg. It's better to be explicit to avoid unintentionally missing cases where the flag is passed in by the user.
Make these need to be specified explicitly.
`yarn start` (typecheck) and run tests.
=> [eas-cli] Make optional nonInteractive arguments non-optional in utility functions

packages/eas-cli/src/build/__tests__/cancel-test.ts, packages/eas-cli/src/commands/build/cancel.ts
When running `build:cancel` for a single build, the results of the confirm prompt are ignored.
I changed the behavior slightly, to always have the user select from a list of builds (even if there is just one) and to always ask for confirmation that 'yes, we should delete the build'. Happy to change this back to how it was with just the bugfix, but this seemed better behavior to me because:
- it's more consistent across use-cases 
- it always asks for confirmation
Ran the command locally
=> [eas-cli] Use confirmation when canceling builds

packages/eas-cli/src/commands/device/delete.ts, packages/eas-cli/src/commands/device/list.ts, packages/eas-cli/src/commands/device/view.ts, packages/eas-cli/src/devices/__tests__/manager-test.ts, packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/project/__tests__/projectUtils-test.ts, packages/eas-cli/src/project/projectUtils.ts
Part 2 of https://github.com/expo/eas-cli/pull/1368.
This removes the rest of the callsites.
Get account from GraphQL by using project ID.
Run tests.
```
$ ~/expo/eas-cli/packages/eas-cli/bin/run device:create
This command lets you register your Apple devices (iPhones and iPads) for internal distribution of your app.
Internal distribution means that you won't need to upload your app archive to App Store / Testflight.
Your app archive (.ipa) will be installable on your equipment as long as you sign your application with an adhoc provisiong profile.
The provisioning profile needs to contain the UDIDs (unique identifiers) of your iPhones and iPads.
First of all, choose the Expo account under which you want to register your devices.
Later, authenticate with Apple and choose your desired Apple …
```
=> [2/n][eas-cli] Remove rest of getProjectAccountNameAsync callsites

packages/eas-cli/src/build/queries.ts, packages/eas-cli/src/commands/branch/create.ts, packages/eas-cli/src/commands/branch/delete.ts, packages/eas-cli/src/commands/branch/rename.ts, packages/eas-cli/src/commands/build/cancel.ts, packages/eas-cli/src/commands/build/list.ts, packages/eas-cli/src/commands/build/version/set.ts, packages/eas-cli/src/commands/build/view.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/commands/channel/rollout.ts, packages/eas-cli/src/commands/secret/create.ts, packages/eas-cli/src/commands/webhook/list.ts, packages/eas-cli/src/project/projectUtils.ts
Part 5 of https://github.com/expo/eas-cli/pull/1368.
Remove function, replace with function that gets the display name (the only thing this function was used for) from GraphQL.
`yarn start` (typecheck) and run tests.
=> [5/n][eas-cli] Remove getProjectFullNameAsync

CHANGELOG.md, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/update/utils.ts
Forgetting to migrate `releaseChannel` to `channel` is one of the most common issues with EAS Update. This PR addresses this by warning/erroring when the project is configured for EAS Update, but the build profile still uses `releaseChannel`. This is split off of my earlier PR, that tried to address this in 3 different places at once.
For each build, check the buildProfile and project configuration. On non-interactive builds, display a warning. On interactive builds, throw an error. 
Tested locally with a variety of build profile configurations (more specifically, global vs per-platform configuration).
=> [eas-cli] warn about channel configuration before build

packages/eas-cli/src/commandUtils/EasCommand.ts, packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts, packages/eas-cli/src/commands/account/login.ts, packages/eas-cli/src/commands/account/logout.ts, packages/eas-cli/src/commands/account/view.ts, packages/eas-cli/src/commands/analytics.ts, packages/eas-cli/src/commands/branch/delete.ts, packages/eas-cli/src/commands/branch/list.ts, packages/eas-cli/src/commands/config.ts, packages/eas-cli/src/commands/diagnostics.ts
The main idea is that we need a better way to declaratively specify dependencies/requirements for commands in a type-safe way. This PR creates a new concept similar in typesystem pattern to flags/parse, but for things like projectId, authenticated actor, project directory, etc.
It is the evolution of https://github.com/expo/eas-cli/pull/1360 but allows commands to be more fine-grained in what they specify/require.
Create new Context concept following the patten used by flags/parse (pass the class constructor to the `getContextAsync` method to infer types).
This allows classes to specify what they need. The idea is that we'll remove `getProjectIdAsync` (in the next PR) and make it so that all commands that need the `projectId` must get it through this new context concept. This will work …
=> [10/n][eas-cli] Add new on-demand context concept for commands

packages/eas-cli/src/build/android/build.ts, packages/eas-cli/src/build/android/syncProjectConfiguration.ts, packages/eas-cli/src/build/createContext.ts, packages/eas-cli/src/build/ios/build.ts, packages/eas-cli/src/build/ios/syncProjectConfiguration.ts, packages/eas-cli/src/commandUtils/EasCommand.ts, packages/eas-cli/src/commands/build/configure.ts, packages/eas-cli/src/commands/credentials.ts, packages/eas-cli/src/commands/device/create.ts, packages/eas-cli/src/commands/metadata/pull.ts, packages/eas-cli/src/commands/metadata/push.ts, packages/eas-cli/src/commands/update/configure.ts, packages/eas-cli/src/credentials/android/actions/BuildCredentialsUtils.ts, packages/eas-cli/src/credentials/android/actions/CreateKeystore.ts, packages/eas-cli/src/credentials/context.ts, packages/eas-cli/src/credentials/ios/actions/BuildCredentialsUtils.ts, packages/eas-cli/src/credentials/manager/HelperActions.ts, packages/eas-cli/src/credentials/manager/ManageAndroid.ts, packages/eas-cli/src/credentials/manager/ManageIos.ts, packages/eas-cli/src/credentials/manager/SelectPlatform.ts, packages/eas-cli/src/devices/__tests__/manager-test.ts, packages/eas-cli/src/devices/context.ts, packages/eas-cli/src/devices/manager.ts, packages/eas-cli/src/submit/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submit/context.ts, packages/eas-cli/src/submit/ios/__tests__/IosSubmitCommand-test.ts, packages/eas-cli/src/update/android/UpdatesModule.ts, packages/eas-cli/src/update/ios/UpdatesModule.ts
Same as https://github.com/expo/eas-cli/pull/1387 but for the remaining commands.
Note that it seems that there's actually no need for `EASCommandProjectIdIfProjectDirContext` (both commands that use it require being run in a project directory) so it will be removed in the next PR.
Add context arg where necessary, pipe through secondary derived contexts.
`yarn test`, run all changed commands.
=> [13/n][eas-cli] Use projectId context in remaining commands

packages/eas-cli/src/commandUtils/EasCommand.ts, packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts, packages/eas-cli/src/commands/account/login.ts, packages/eas-cli/src/commands/account/logout.ts, packages/eas-cli/src/commands/account/view.ts, packages/eas-cli/src/commands/analytics.ts, packages/eas-cli/src/commands/config.ts, packages/eas-cli/src/commands/diagnostics.ts
The `allowUnauthenticated` option is now automatically derived from the context. Put another way, if the command needs the projectId and doesn't have one, they will need to be authenticated. Also if the command requires the actor, they will need to be authenticated. Otherwise, the command can run in an unauthenticated manner.
Remove the flag.
Run tests. Run all commands that used to have this flag and ensure they still can be run while logged-out.
=> [15/n][eas-cli] Remove allowUnauthenticated command configuration

packages/eas-cli/src/commandUtils/context/ProjectConfigContextField.ts, packages/eas-cli/src/commands/build/configure.ts, packages/eas-cli/src/commands/metadata/pull.ts, packages/eas-cli/src/commands/metadata/push.ts, packages/eas-cli/src/commands/update/configure.ts
By also exporting projectDir from the config context, we can deduplicate extra calls to findProjectRoot.
`yarn start` (tsc)
=> [19/n][eas-cli] Reduce code duplication in project config context commands

packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/commands/submit.ts, packages/eas-cli/src/submit/android/__tests__/AndroidSubmitCommand-test.ts, packages/eas-cli/src/submit/android/__tests__/ServiceAccountSource-test.ts, packages/eas-cli/src/submit/context.ts, packages/eas-cli/src/submit/ios/__tests__/AscApiKeySource-test.ts, packages/eas-cli/src/submit/ios/__tests__/CredentialsServiceSource-test.ts, packages/eas-cli/src/submit/ios/__tests__/IosSubmitCommand-test.ts
Closes ENG-6471 (discussion: https://github.com/expo/eas-cli/pull/1387#discussion_r979799325)
Replace dynamic config param with exp and project ID params, pass in from above (this context is only created with a single env per call).
`yarn start` (tsc), run tests.
=> [20/n][eas-cli] Simplify submit context creation

packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commandUtils/context/ProjectConfigContextField.ts, packages/eas-cli/src/commandUtils/context/__tests__/ProjectConfigContextField-test.ts, packages/eas-cli/src/graphql/generated.ts, packages/eas-cli/src/graphql/types/App.ts
This PR is the final PR in the stack and is part of what drove this new pattern. It becomes very easy to validate that the slug, owner, and projectId fields are all correct.
Closes ENG-6193.
Add validation to the context field that is used in all commands that use this context.
Run the test.
=> [21/21][eas-cli] Validate that owner and projectId and slug all are in alignment

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/commands/device/delete.ts, packages/eas-cli/src/commands/device/list.ts, packages/eas-cli/src/credentials/ios/actions/AppleTeamFormatting.ts, packages/eas-cli/src/credentials/ios/actions/AppleTeamUtils.ts, packages/eas-cli/src/credentials/ios/actions/AscApiKeyUtils.ts, packages/eas-cli/src/credentials/ios/actions/DeviceUtils.ts, packages/eas-cli/src/credentials/ios/actions/DistributionCertificateUtils.ts, packages/eas-cli/src/credentials/ios/actions/PushKeyUtils.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleDeviceQuery.ts, packages/eas-cli/src/credentials/ios/api/graphql/queries/AppleTeamQuery.ts, packages/eas-cli/src/devices/queries.ts, packages/eas-cli/src/devices/utils/errors.ts, packages/eas-cli/src/devices/utils/formatDevice.ts, packages/eas-cli/src/graphql/generated.ts
This PR finishes adding support for paginated queries to the EAS CLI.
Following in the steps of previous PRs I 
- introduced helper methods to query for items
- updated the gql schema for relevant queries
- did some light rewriting/refactoring
As a part of this PR, I removed support for deleting multiple devices from an Apple team in a single `delete` command. That requires multi-select pagination and we are choosing to hold off an adding that functionality due to UX concerns.
Ran the affected commands (using Brent's account 🙏 ). Confirmed each combination of flags and command was working properly.
https://user-images.githubusercontent.com/15132641/192421718-948410c7-bd39-4c17-ae46-e89ca1763a88.mov
https://user-images.githubusercontent.com/15132641/192421879-4a12f915-62fa-417d-ba2e-681f0a4 …
=> [eas-cli] Add pagination to device:* commands

CHANGELOG.md, packages/eas-cli/src/commands/build/index.ts
Code that is handling deprecated eas.json does not handle a case where eas.json does not exists and fails before automatic configuration has a chance to trigger.
`eas build` on a project without eas.json
=> [ENG-6505][eas-cli] Fix automatic configuration if eas.json does not exist.

CHANGELOG.md, packages/eas-cli/src/build/build.ts
https://linear.app/expo/issue/ENG-4932/dealing-with-platform-specific-issues-on-eas
Companion to https://github.com/expo/universe/pull/10576.
Handle errors from new platform-specific kill switches to stop accepting builds for a given platform, so users see an accurate message for which platform we are not accepting builds vs just seeing generic information that the whole free tier is disabled.
Tested locally
=> [ENG-4932][eas-cli] handle errors form new platform-specific kill switches

CHANGELOG.md, packages/eas-cli/src/commandUtils/context/OptionalProjectConfigContextField.ts
I had an invalid eas.json and I was having trouble figuring out why the project context wasn't set. Would be better if invalid eas.json errors were surfaced since it indicates the user intends to be in a project context
=> [cli] surface context error with invalid eas.json

CHANGELOG.md, packages/eas-cli/src/commandUtils/context/contextUtils/__tests__/getProjectIdAsync-test.ts, packages/eas-cli/src/commandUtils/context/contextUtils/getProjectIdAsync.ts
Error messages are frustrating, and by providing a link to an FYI page we can easily provide more context on what is happening, why, and suggestions for how to adapt your workflow.
I created a simple placeholder FYI page and then linked to it from here. I also changed the formatting of the message slightly to inline the mismatched values in parens.
I changed the slug and owner in an existing project and tried running commands.
=> [eas-cli] Add learn more link to project ID mismatch errors

CHANGELOG.md, packages/eas-cli/src/credentials/ios/actions/ConfigureProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/ProvisioningProfileUtils.ts, packages/eas-cli/src/credentials/ios/actions/SetUpAdhocProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/actions/SetUpProvisioningProfile.ts, packages/eas-cli/src/credentials/ios/validators/validateProvisioningProfile.ts, packages/eas-cli/src/project/ios/__tests__/target-test.ts, packages/eas-cli/src/project/ios/target.ts
We don't have any docs on how our users should build their project for tvOS yet (assuming it will be released after we complete https://linear.app/expo/issue/ENG-5930/research-requirements-to-make-apple-tv-targets-buildable). I'm not really sure what users are doing to build for tvOS but having a more robust check seems like a good improvement and will probably help https://github.com/expo/eas-cli/issues/1349  .
After talking to @douglowder , we should be looking at the following Xcode build settings to determine which Apple Platform we should be building for:
- SDK_ROOT
- TARGETED_DEVICE_FAMILY
new tests pass
=> [cli] more robust platform check

CHANGELOG.md, packages/eas-cli/graphql.schema.json, packages/eas-cli/src/build/runBuildAndSubmit.ts, packages/eas-cli/src/build/types.ts, packages/eas-cli/src/commands/build/index.ts, packages/eas-cli/src/graphql/generated.ts
https://linear.app/expo/issue/ENG-6571/add-m1-resource-class-for-eas-cli-use
Add new `m1-experimental` option for `--resource-class` flag
Test locally, run builds on staging
=> [ENG-6571][eas-cli] use resource class flag to select M1 resource class

CONTRIBUTING.md, package.json, scripts/bin/run, scripts/package.json, scripts/src/nextVersion.ts, scripts/src/release.sh
https://exponent-internal.slack.com/archives/C017N0N99RA/p1664960139821809
We want to use strict semver when releasing EAS CLI. This PR should let us avoid mistakes when choosing the next version for a release.
Use the following algorithm for bumping the version:
- If there are some entries under "Breaking changes", bump the major version.
- Otherwise, if there are some entries under "New features", bump the minor version.
- In all other cases bump the patch.
=> [ENG-6652] automatically choose next version when releasing

packages/eas-cli/src/commandUtils/EasCommand.ts, packages/eas-cli/src/commandUtils/__tests__/EasCommand-test.ts, packages/eas-cli/src/commands/project/__tests__/init.test.ts, packages/eas-cli/src/user/SessionManager.ts
https://github.com/expo/eas-cli/pull/1390 changed the semantics around this initial log call.
Before that PR, it would require login before logging the action. This meant that users that had not already logged-in would be prompted to do so before the command was logged, so there would be non-anonymous identification for the event.
That PR changed it to just use the user that is already logged-in to log the event, and if they hadn't logged in before log anonymously.
This changed our metrics a bit, and this PR reverts that change (in the new context-based world).
Change EasCommand to pre-require logging in (ahead of context evaluation) if context will require it in the future anyways. Note that this still isn't perfect in the same way as before: the user can ctrl-c out of signing in.
This …
=> [eas-cli] Fix command statistic analytics

CHANGELOG.md, packages/eas-cli/src/submit/utils/errors.ts
Companion to https://github.com/expo/turtle-v2/pull/1109
Maintaining two lists of errors is annoying.
- I moved the error messages to the server side - https://github.com/expo/turtle-v2/pull/1109
- I removed the error messages from CLI
Known error:
Unknown error:
=> [ENG-6721][submit] move error messages from CLI

.github/workflows/test.yml, CHANGELOG.md, package.json, scripts/package.json, scripts/src/changelog/consts.ts, scripts/src/changelog/entry.ts, scripts/src/changelogEntry.ts, scripts/src/lintChangelog.ts, scripts/src/nextVersion.ts, scripts/yarn.lock
Fixes https://linear.app/expo/issue/ENG-5269/add-ci-job-for-validating-eas-cli-changelog-format
- Implement simple linter (it does not check whether the entry was added to the right section yet, but it's not trivial)
- Fix invalid changelog entries.
CI + tested locally:
=> [ENG-5269] add changelog linter

packages/eas-cli/src/analytics/AnalyticsManager.ts, packages/eas-cli/src/analytics/common.ts, packages/eas-cli/src/build/build.ts, packages/eas-cli/src/build/context.ts, packages/eas-cli/src/build/createContext.ts, packages/eas-cli/src/build/metadata.ts, packages/eas-cli/src/submit/BaseSubmitter.ts, packages/eas-cli/src/submit/context.ts, packages/eas-cli/src/submit/submit.ts
https://github.com/expo/eas-cli/pull/1444#discussion_r996812052
This PR cleans this up.
- Rename trackingCtx to analyticsEventProperties and make the type consistent across the entire analytics system.
- Fix bug from https://github.com/expo/eas-cli/pull/757 where the attempt event was never logged.
I opted to keep this in its own file since I couldn't think of a good method name that would be callable of the form `analytics.<do_with_try_catch_logging_analytics>(fn, properties)` if this were on the analytics object. Open to suggestions.
Inspect.
=> [eas-cli] Clean up withAnalyticsAsync

CHANGELOG.md, packages/eas-cli/src/vcs/clients/git.ts
@ccheever encountered the following error when running `eas build:configure` on a fresh-ish Mac:
He tried running git to see why, and was greeted with this beauty:
So, I think it is useful for us to handle every case where `git --help` exits with an error that doesn't match `ENOENT` as some unknown error that points to a problem with the git installation. I let the developer know in the message specifically that `git --help` failed so that they can run it themselves and verify and debug from there.  
Handle all unknown error types as an indication that git isn't configured correctly and provide a message explaining what is happening.
I didn't know how to get back to the state that @ccheever was in, so I changed the command that we use to check the git installation from `git --help` to …
=> [eas-cli] Handle case where git is installed but not working properly

CHANGELOG.md, packages/eas-cli/src/project/publish.ts, packages/eas-cli/src/utils/expoCli.ts
Fix ENG-6079
- Hide warning:
```
--non-interactive is not supported, use $CI=1 instead
```
- Check if `@expo/cli` is available in the project. Users can disable this behavior with `EXPO_USE_LOCAL_CLI=false`.
- Ideally, we'd have something like this for changing the default script:
```json
{
"scripts": {
"build": "expo export"
}
}
```
- This seems most aligned with [how web frameworks work](https://vercel.com/docs/concepts/deployments/configure-a-build#build-command).
- `eas update` in a project with the latest CLI, there will be no warning.
=> feat: use versioned cli for export

packages/eas-cli/package.json, packages/eas-cli/src/commands/secret/create.ts, packages/eas-cli/src/commands/secret/push.ts, packages/eas-cli/src/commands/secret/sync.ts, packages/eas-cli/src/utils/expodash/__tests__/intersection-test.ts, packages/eas-cli/src/utils/expodash/intersection.ts, yarn.lock
We want to add support for Doppler (secret storage/sync service).
This PR adds the `eas secret:push` command that allows importing secrets from a dot env-like file to EAS secret.
It looks sth like this:
`eas secret:push --scope project --env-file ./eas/.env --force`
This allows using Doppler:
`doppler run --mount ./eas/.env -- eas secret:push --scope project --env-file ./eas/.env --force`
The dot env file should look sth like this:
```
ABC=123
DEF=456
```
- The command is mostly a copy-paste of `secret:create`.
- It checks whether any of the secrets defined in the file is already present on the server.
- If there is, and `--force` is passed. Those secrets are deleted from the server.
- If `--force` is not passed, the command exits.
- If `--env-file` is not passed,  the command display a …
=> [ENG-6183] add secret:push command

CHANGELOG.md, packages/eas-cli/src/project/publish.ts, packages/eas-cli/src/utils/expoCli.ts
Revert https://github.com/expo/eas-cli/pull/1460 as this doesn't work with projects with older SDKs.
See https://exponent-internal.slack.com/archives/C017N0N99RA/p1666603376919699
=> revert #1460

CHANGELOG.md, packages/eas-cli/src/commands/secret/list.ts
Follow up on #1463, to get rid of tables in general.
Reused the same formatting as `eas device:list` ([here](https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/devices/queries.ts#L163-L165)).
Just a visual output change.
=> [eas-cli] Replace secret:list table with format fields

CHANGELOG.md, packages/eas-cli/src/devices/actions/create/inputMethod.ts, packages/eas-cli/src/devices/utils/formatDevice.ts, packages/eas-cli/src/utils/formatFields.ts
Replaces the CLI table for `eas device:create` with formatted fields, similarly to how `eas device:list` works.
- Created new `formatNewDevice` method, as some fields don't exist yet.
- Moved device class formatting over
- Resort the fields to match `formatDevice`
- Run `eas device:create`
- Pick `input` mode
- Fill in details
- See device summary being formatted fields instead of a table
=> [eas-cli] Replace device:create input summary table with format fields

CHANGELOG.md, packages/eas-cli/package.json, packages/eas-cli/src/channel/queries.ts, packages/eas-cli/src/channel/utils.ts, packages/eas-cli/src/update/queries.ts, packages/eas-cli/src/update/utils.ts, yarn.lock
Converts all remaining CLI tables to formatted fields.
Went through all commands:
<details><summary><code>eas update:list</code></summary>
```log
╭╴~/Projects/bycedric/dogfood test*
╰╴$ easd update:list
✔ Which branch would you like to view? › main
Branch:
Name  main
ID    7072afed-8681-4dd2-855a-cf02f224b73e
┌──────────────────────────────────────────────────────────────────────────┬────────────────────────┬──────────────────────────────────────┬──────────────────┐
│ Update message                                                           │ Update runtime version │ Update group ID                      │ Update platforms │
├──────────────────────────────────────────────────────────────────────────┼────────────────────────┼──────────────────────────────────────┼──────────────────┤
│ …
```
=> [eas-cli] Drop remaining cli tables

CHANGELOG.md, packages/eas-cli/src/commands/update/configure.ts
Some users can get confused about why EAS Update doesn't work after adding it to an existing app without rebuilding it.
I added a warning to rebuild and resubmit your app after running `eas update:configure`.
=> [eas-cli] Warn about outdated build deployment when configuring EAS Update

packages/eas-cli/src/commands/update/configure.ts, packages/eas-cli/src/commands/update/index.ts, packages/eas-cli/src/log.ts, packages/eas-cli/src/project/__tests__/workflow-test.ts, packages/eas-cli/src/project/workflow.ts
Fixes ENG-6013
Fixes ENG-6014
This changeset adds the prompt for the user when there is no runtime version specified, which asks if setup the updates automatically for them (via `eas update:configure`).
If user do not want this the CLI exits as before.
If user selects "Yes", we are programmatically running `eas update:configure`, and then re-reading the modified config, so the process can continue without the interruption or command exit.
As always, the copy/messages content probably can be written better. 😉 
The changes have been tested locally in few project by running `dev` bin of EAS CLI.
=> [eas-cli] Update: improve DX on first run, correct error message

packages/eas-cli/src/commands/update/index.ts
This starts ENG-5926 and is the first of a couple of stacked PRs to clean this command up.
- Added `RawUpdateFlags` and `UpdateFlags`
- Added basic validation for incorrect combinations of flags
- Renamed a few variables in `runAsync` to emphasize entity relation
- `group` → `groupId`
- `message` → `updateMessage`
`eas update` (with all flag-variations should work)
=> [eas-cli] Add flag sanitization in updates command

packages/eas-cli/src/branch/queries.ts, packages/eas-cli/src/channel/queries.ts, packages/eas-cli/src/commands/branch/create.ts, packages/eas-cli/src/commands/channel/create.ts, packages/eas-cli/src/commands/update/index.ts
Continuation of PR #1473 and ENG-5926.
- Moved ensure methods from `UpdatePublish` to `src/branch|channel/queries.ts`.
- Copied other methods from commands `BranchCreate` and `ChannelCreate`, to keep queries contained in `src/branch|channel/queries.ts` files.
- Validated the logging is similar (still slightly different)
- _branch logging_
- removed: `Created branch: <branchName>`
- why: The branch is both listed in the formatted fields (first field), and the "Channel is pointing to branch" logging, seems not worth it to determine if the branch was created or already existed. (_but if people disagree, I'd be happy to change it_)
- _channel logging_  
- from: `Created a channel: <channelName> pointed at branch: <branchName>` (_only logged when created_)
- to: `Channel: <channelName> pointed …
=> [eas-cli] Extract entity utilities from update command class
